hengband/hengband

src/player-attack/player-attack.c
- Change "a" to "an" to match "elastic".
=> 3.0.0.0: minor English edits for src/player-attack

src/racial/racial-switcher.c
- Use "poisoned" rather than "of poison" to be a bit terser.
=> 3.0.0.0: minor English edits for src/racial

src/specific-object/toragoroshi.c
In message for toragoroshi activation, add "the" and replace "enchanted" with "fascinated".
=> 3.0.0.0: minor English edits for src/specific-object

lib/file/rumors.txt
https://github.com/hengband/hengband/issues/39　これへの対応用。まだなんかミスってないか不安ではある。
=> [Fix] 英語版 rumor.txt に有用な噂追加. / Add useful rumors to English version.

src/mspell/mspell-checker.c
=> [Fix] spell_is_inate() の未定義動作を修正

lib/file/rumors_j.txt
=> [Fix] rumors_j.txt 内の改行忘れを修正

src/store/museum.c, src/store/purchase-order.c, src/store/sell-order.c, src/store/store.c
- To be more idiomatic, replace "don't have any item" with "don't have any items".
- Fill out message for rejecting purchases from the museum.
- To be more idiomatic, preface "Museum" with "the".
=> 3.0.0.0: minor English edits for src/store

src/melee/melee-util.h, src/melee/monster-attack-monster.c, src/monster-attack/monster-attack-player.c, src/monster-attack/monster-attack-util.h, src/system/monster-race-definition.h
Fixes #63.
Hourier 氏のコード #88 を取り込みました。
=> [Refactor] mon_type、monap_type の ap_cnt メンバを除去

lib/file/rumors_j.txt
=> [Fix] rumors_j.txt の typo を修正。クイスルグス -> クイルスルグ

src/wizard/artifact-bias-table.c, src/wizard/spoiler-table.c
- Fix typo.
- Fix spoiler label for TR_AGGRAVATE.
=> 3.0.0.0: minor English edits for src/wizard

src/system/angband-version.h
取り敢えずgit flowに則ってreleaseブランチを作成し、バージョン番号のみ変更しました
しかしながらここからパッケージング及びmasterへのマージ手順が不明ですので、お手数ですがこのプルリクの正式なクローズ方法についてご存じの方、コメントお願いします
(多分管理権限を持つdeskullさんかHabuさんしかできないかと思いますが、習熟度の観点からHabuさんに備忘録の作成も含めて実施頂けると助かります)
=> [Version] 3.0.0Alpha6

src/flavor/flavor-describer.c
describe_bowの射撃回数の計算部がおかしく、スポイラー生成時にクラッシュしていた。
射撃回数増加なしのクラスの射撃回数を計算し、OD_DEBUG時に使用する。
=> [Fix] Artifact Spoiler出力の射撃回数計算がおかしい

lib/edit/a_info.txt
- Change last part of the description for "of Jack of Shadows" to be more idiomatic and fix a  spelling mistake.
- Fix two spelling mistakes in the description for "of Jing Ke" and add a phrase to tie the second sentence to the first.
- Fix spelling mistake in the description for the whip 'Rose'.  For clarity, change "whipping" to "to use".
=> 3.0.0: minor English edits for a_info.txt

src/mind/monk-attack.c
Fixes a regression introduced in 3.0.0Alpha5 (my fault).
=> English: drop capitalization of argument in monk's MA_SLOW attack message

lib/edit/r_info.txt
Reword the first sentence to be an interpolation between the current translation and the content at https://chargeman-ken.fandom.com/wiki/Yuichi .
=> English: description for Yu'uichi the Arsonist

lib/edit/r_info.txt
Use singular nouns for the forms compared to the shape of the elemental.  Rephrase the second sentences for the air, magma, and fire elder elementals - taking some liberties with the translation in the case of the air and fire elder elementals.
=> English: try to improve the descriptions of the elder elementals

src/floor/floor-generator.c
Fixes #52.
現状のダンジョン生成アルゴリズムは、山およびオークの洞窟で非連結な(永久壁に囲まれた孤立部屋のある)フロアを生成することが確認されている。
このようなフロアが生成されると狂戦士でのプレイに支障をきたしうるため、生成後に連結性をチェックし、一定回数の上限を設けて再生成を試みる。
地上/荒野マップ/クエストでは連結性判定は不要と判断し、行わない。現在の連結性判定をこれらに対して適用すると正しく動かないという実装上の理由も若干ある。
連結性判定は単純な再帰DFSで行うとスタック消費量が不安なので、ヒープ上に確保したスタックを用いて非再帰DFSを行う。
このために簡単な動的可変長配列を作成した。一応競プロサイトの簡単なDFS問題で動作チェック済み。
再生成の試行回数上限はとりあえず 1000 回とした。手元では最適化オフでも 1000 回試すのに 10 秒かからないので許容範囲かと思う。
=> [Feature] ダンジョンフロアが連結でないとき再生成を試みる

src/wizard/monster-info-spoiler.c, src/wizard/monster-info-spoiler.h, src/wizard/wizard-spoiler.c
スポイラー一覧出力を拡張し、WILD_*フラグを保持するモンスターの一覧を出力するように変更した。
=> [Implement] 荒野に出現するモンスター一覧のスポイラー出力

src/system/angband-version.h
=> [Version] 3.0.0Alpha7

lib/edit/a_info.txt, lib/edit/misc.txt, src/artifact/fixed-art-types.h, src/player/player-status.c
Discussionのスレッド( https://github.com/hengband/hengband/discussions/196 )から、
★ロングボウ『天鹿児弓』、★シミター『アイシングデス』、★シミター『トゥインクル』を実装。
=> Add: 3 artifacts from XAngband. #225

src/system/angband-version.h
=> [Version] 3.0.0Alpha8

src/core/show-file.c
我が家のアイテムやヘルプの検索で、ヒットした行とヒットしなかった行を色分けして目立たせる。
[Feature] Draw line with different colors between keyword matched line or not in show_file(). #211
=> [Feature] Draw line with different colors in show_file()'s keyword finding. #211

src/knowledge/knowledge-monsters.c, src/lore/lore-calculator.c, src/lore/lore-calculator.h, src/lore/magic-types-setter.c, src/view/display-lore-status.c, src/view/display-lore.c
=> [Fix] 自動生成スポイラーに魔法・ブレスの威力を表示

src/window/main-window-stat-poster.c
ものまねの表示状態が反転しているのを修正。
直下のif文も三項演算子に変更。
=> Fix: display reverse imitation status. #289

lib/edit/r_info.txt
These are an attempt to improve the English descriptions for some monsters introduced after 2.2.1.
=> English: edits for post 2.2.1 monster additions

src/grid/grid.c
`place_bold()` と `place_grid()` の動作が異なっていたのが原因。
v2.2.1 のコードを見る限り、これらは本来引数の形式が違うだけで同じことをするはずだった。
同じ動作にして問題ないと確認がとれたのでそのようにする。
=> ﻿[Fix] アリーナ外周の上辺と左辺が永久壁でなく花崗岩になる #294

src/mind/mind-samurai.c
=> [Fix] 剣術の技のダイス倍率増加が適用されない #313

src/birth/birth-explanations-table.c
全ての下級魔法を使用できるように変更したので、職業説明をそれに合わせて修正する。
=> [Fix] 赤魔道師の説明を修正

src/monster-floor/monster-summon.c, src/mspell/mspell-special.c
1) 特別な行動でショートテレポートしたときに増殖する不具合
2) 荒野での召喚レベルが弱くて低レベルな護衛しか呼べない不具合
=> [Fix] 大鷲系モンスターの挙動がおかしい

lib/edit/t0000001.txt, lib/edit/t_lite.txt
一応入手テストは剣術家、魔法戦士、赤魔導師一通り、済ませました。
=> [Feature] 赤魔導師の古い城報酬をサンブレードに変更．

readme.md
とりあえず注意点を追加しました。英語版との内容齟齬などは後々どうにか調整したいので、このままマージさせて解決とさせてもらいたいと思います。
=> #120の注意喚起を追記

lib/edit/r_info.txt
This is an attempt to make those descriptions a bit more fluent.
=> English: edit descriptions for elementary, high, and acting master mystic

src/mutation/mutation-investor-remover.c
=> [Refactor] BIT演算マクロへの置換を進める。mutation-investor-remover.c

lib/edit/r_info.txt
These changes are an attempt to improve the English for those descriptions.  I'm not so sure that I've correctly matched what was intended for the description of Odahviing.
=> English: edit descriptions for the uniques from Skyrim

lib/edit/a_info.txt
=> [Feature]α10に向けたアーティファクトの調整

src/view/display-player-stat-info.c
=> [Refactor] BIT演算マクロへの置換を進める。display-player-stat-info.c

src/wizard/monster-info-spoiler.c
=> [Refactor] BIT演算マクロへの置換を進める。monster-info-spoiler.c

src/birth/inventory-initializer.c, src/core/game-play.c
ゲーム開始時に武器がトライデントになる(セクシー除く)
トライデントと三叉槍の熟練度が達人になる
上記はスペルマスターを除く
=> [Feature] マーフォークの初期武器及び武器熟練度

lib/edit/r_info.txt
The intent is to improve those descriptions.  The affected monsters are:  dragon insect, dragon worm, dragon centipede, "The Pair of Soft Leather ...", King Boo, raven (from Nintendo's Mario games), Raphael the Raven, spirit horse, and spirit cow.
=> English: edit descriptions for some of the new 3.0.0 monsters

lib/edit/r_info.txt
=> [Fix] ジェノサイバーの思い出表現がおかしかったのを修正

src/main-win.c
=> [Fix] 同じBGMタイプのエリアに移動するとBGMが鳴りなおす #264

src/player-info/mutation-info.c
=> [Refactor] BIT演算マクロへの置換を進める。mutation-info.c

src/racial/racial-switcher.c
=> [Refactor] BIT演算マクロへの置換を進める。racial-switcher.c

lib/help/attack.txt
Make some other changes for readability.
=> English help: align the contents of attack.txt with jattack.txt

src/room/door-definition.h
些細な内容ですが馬鹿馬鹿いじっている間に気づいたのでお願いします。
=> [Fix] DUN_ROOMS_MAX のコメント修正． / Fix comment of DUN_ROOMS_MAX.

.editorconfig
=> [Fix] .editorconfigにcppを追加

src/wizard/cmd-wizard.cpp, src/wizard/wizard-special-process.cpp, src/wizard/wizard-special-process.h
あわせて、職業変更で名称やステータスの変更が起きないのを修正。
=> ウィザードコマンドに種族変更を追加。

src/player-info/race-ability-info.cpp
shimiteiさんからご報告いただいたもの以外にもあったので調べて修正。
=> 【バグ】 自己分析の種族特殊能力メッセージの誤り

src/system/angband-version.h
=> [Version]3.0.0Alpha10

src/effect/effect-monster-switcher.cpp, src/realm/realm-hissatsu.cpp
=> 剣術家の技「幻惑」の説明と実際の効果が異なる

src/effect/effect-monster-resist-hurt.cpp
=> [Fix] GF_HOLY_FIREが善良なモンスターに有効 #446

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/wizard/cmd-wizard.cpp, src/wizard/wizard-game-modifier.cpp, src/wizard/wizard-game-modifier.h, src/wizard/wizard-player-modifier.cpp, src/wizard/wizard-player-modifier.h
- 一部のデバグコマンドをまとめてサブコマンド化
- デバグコマンド入力時に一覧を出す
- コマンドを追加する
=> [Feature] デバグコマンドの整理と拡張

doxygen/Hengband.doxyfile
Doxygenの有効活用も考えていきたいのでとりあえず変愚のバージョン表記とdoxyfileのバージョン更新しました。よろしくお願いします。
=> [Feature] doxyfileを1.9.1で更新してバージョン表記も3.0.0Alpha10に変更．

src/core/scores.cpp
=> [Fix] ローカルスコアの種族と性格がおかしい

src/realm/realm-hex.cpp
=> [Fix] 呪術の呪力吸収の説明文 #453

src/flavor/flavor-describer.cpp
=> [Feature] 騎乗時にランス、ヘヴィ・ランスのダイス追加を明示する。

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/player-status/player-speed.cpp, src/player-status/player-status-base.cpp, src/player-status/player-status-base.h, src/player-status/player-stealth.cpp, src/player-status/player-stealth.h, src/player/player-status-flags.cpp, src/player/player-status.cpp
隠密処理を担当するクラスを実装し、処理を整理した。
この実装に際してPlayerStatusBaseを修正して例外処理関数を導入している。
=> [Refactor] PlayerStealthクラスの導入

lib/edit/k_info.txt, src/object-enchant/apply-magic-accessory.cpp
ベースアイテムの出現階、レア度等の調整をします。
Discussion #300 参照。
=> [Feature] ベースアイテムの調整(α10→α11) #300

lib/help/defend.txt
Make some minor changes for readability.
=> [English documentation] align the contents of defend.txt with jdefend.txt

src/action/action-limited.cpp, src/cmd-action/cmd-move.cpp, src/cmd-building/cmd-store.cpp, src/cmd-io/cmd-dump.cpp, src/core/hp-mp-processor.cpp, src/core/player-processor.cpp, src/floor/floor-leaver.cpp, src/grid/grid.cpp, src/io/write-diary.cpp, src/load/player-info-loader.cpp, src/monster-race/monster-race-hook.cpp, src/mutation/mutation-processor.cpp, src/player/player-damage.cpp, src/player/player-status.cpp, src/player/player-status.h, src/spell-kind/spells-world.cpp, src/wizard/wizard-special-process.cpp
馬鹿馬鹿でいじる分にも分かりやすくしたかったので地味にリファクタリング進めてみました。
=> [Refactor] プレイヤーがダンジョンに居るかの判定をis_in_dungeon()関数に置換．

src/effect/effect-monster-psi.cpp
=> [Fix] GF_PSI及びGF_PSI_DRAINの反射判定の不具合を修正 #472

src/effect/effect-monster.cpp
=> [Fix] モンスター自爆効果が無限連鎖する #505

src/cmd-item/cmd-eat.cpp
returnしていなかったが、そもそもコードがわかりにくかった。
=> [Fix/Refactor] 吸血鬼が普通に食事していた/食事の処理の整理 #526

src/wizard/monster-info-spoiler.cpp, src/wizard/monster-info-spoiler.h, src/wizard/wizard-spoiler.cpp
=> [Feature] 自動スポイラー作成に騎乗可能モンスター一覧を追加

src/lore/lore-util.cpp, src/lore/lore-util.h, src/lore/monster-lore.cpp, src/view/display-lore-attacks.cpp, src/view/display-lore-drops.cpp, src/view/display-lore-magics.cpp, src/view/display-lore-status.cpp, src/view/display-lore.cpp
ユニークの場合、「この仇敵はまだ生きている」
ナズグル系の場合、「xxxらはまだ xx 体生きている」
=> [Feature] 思い出にユニーク/ナズグル系の生存情報を表示する

src/main-win.cpp
This reverts commit 3d2ba515e29c5083d21490a443cc7d66697d91f9.
描画にゴミが出たりするためいったん戻します。
=> Revert "[Feature] Windowsの高DPI環境での表示改善"

src/birth/inventory-initializer.cpp, src/io/read-pref-file.cpp, src/io/report.cpp, src/knowledge/knowledge-experiences.cpp, src/knowledge/knowledge-self.cpp, src/mind/mind-elementalist.cpp, src/object-hook/hook-magic.cpp
=> [Feature] 元素使いの調整

src/object-enchant/apply-magic-armor.cpp
ひとまず論理的に無限ループにならないよう修正の上、チートメッセージで選択がなかった時にメッセージを出す機能を追加しました。よろしければApproveお願いします。
=> [Fix] apply-magic-armor.cppの無限ループになる可能性のある場所を解消．

src/room/pit-nest-kinds-table.cpp, src/room/pit-nest-kinds-table.h, src/room/rooms-pit-nest.cpp
=> [Fix]  #574のリファクタリングでファイルが消えていなかった

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, Hengband/Hengband/stdafx.cpp, Hengband/Hengband/stdafx.h
=> [Fix/Feature] VisualStudioでプリコンパイルヘッダ導入

src/mind/mind-elementalist.cpp
=> [Fix] 元素使いのレベルによる耐性のチェックで職業を加味していない

src/player/permanent-resistances.cpp, src/player/race-resistances.cpp
=> [Fix] 元素使いのダンプで免疫の表示がおかしい(+になる)

doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Version] 3.0.0Alpha13

src/cmd-item/cmd-eat.cpp
=> [Fix] 吸血鬼が食料やキノコを食べても数が減らない #614

src/floor/floor-generator.cpp, src/floor/floor-util.cpp, src/grid/grid.cpp, src/grid/grid.h, src/monster-floor/monster-safety-hiding.cpp, src/monster-floor/monster-sweep-grid.cpp, src/target/target-describer.cpp
魔法が使えないモンスターが穴を挟んで見えている場合の挙動もほんのり変更。
=> [Fix/Feature] 飛行モンスターが深い穴を超えられない現象を解消 #177

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/main-win.cpp, src/main-win/main-win-music.cpp, src/main-win/main-win-music.h, src/main/scene-table.cpp, src/main/scene-table.h, src/main/sound-of-music.cpp, src/term/z-term.h
term_xtra関数用のアクション定義TERM_XTRA_SCENE（場面更新時のイベント）を追加し、場面に応じたBGMの再生をこのアクションで行う。
=> [Refactor] BGM選曲のリファクタリング

src/artifact/fixed-art-generator.cpp, src/artifact/fixed-art-generator.h, src/object-enchant/apply-magic.cpp
=> [Fix] 天然生成のアーティファクトでXTRA_DICEが無効になる

src/game-option/map-screen-options.cpp, src/game-option/map-screen-options.h, src/game-option/option-types-table.cpp, src/game-option/option-types-table.h, src/spell-kind/spells-floor.cpp, src/view/display-map.cpp, src/window/display-sub-windows.cpp, src/window/main-window-util.cpp
=> [Feature] 啓蒙/周辺感知で壁の中の壁も感知する / 壁に囲まれた壁を表示するオプション #643

src/core/hp-mp-processor.cpp
=> [Refactor] 地形によるダメージの耐性計算をcalc_*_damage_rate()で行う #664

src/spell/spells-object.cpp
=> [Fix/refactor] MPがある職にもかかわらず知識の石の発動でMPを消費しない #685

src/melee/melee-spell.cpp, src/mspell/mspell-attack-util.cpp, src/mspell/mspell-attack.cpp, src/mspell/mspell-ball.cpp, src/mspell/mspell-bolt.cpp, src/mspell/mspell-breath.cpp, src/mspell/mspell-curse.cpp, src/mspell/mspell-particularity.cpp, src/mspell/mspell-status.cpp, src/mspell/mspell.h
=> [Fix] ものまね師が攻撃魔法のダメージを記憶できなかったので修正 #548 #673

src/wizard/cmd-wizard.cpp
=> [Add] ウィザードモードのyコマンド解説を追記 / Add description wizard 'y' command.

src/effect/effect-monster-charm.cpp, src/specific-object/monster-ball.cpp
=> [Fix] ペットを捕まえた直後にペット維持が更新されない #699

src/game-option/birth-options.cpp, src/game-option/option-types-table.cpp, src/game-option/text-display-options.cpp, src/player-info/avatar.cpp, src/player/player-status.cpp
=> [Feature] 技能値の実値表示オプションで徳の善悪属性の実値も表示する #720

src/game-option/map-screen-options.cpp, src/game-option/map-screen-options.h, src/game-option/option-types-table.cpp, src/game-option/option-types-table.h, src/view/display-map.cpp
=> [Feature] 罠未感知エリアの壁の中に囲まれた壁を表示するオプション  #643

src/io-dump/character-dump.cpp, src/knowledge/knowledge-self.cpp, src/player-info/avatar.cpp, src/player/player-status.cpp, src/player/player-status.h, src/view/display-player.cpp, src/view/display-self-info.cpp
=> [Fix] Linx/Mac版で徳の実値表示がおかしい

src/artifact/fixed-art-generator.cpp
天然産(apply_magic)とデバグ産(create_named_art)で能力を付ける処理に違いがあって齟齬がある場合があった
=> [Refactor] 固定アーティファクト生成ルーチンの統一 #694

autopick.txt, autopick_eng.txt
=> [MISC] autopick.txtの変数説明に新種族と新職業を追加

src/util/string-processor.cpp, src/util/string-processor.h
- str_trim: 文字列の両端の空白を削除する
- str_split: 文字列を指定文字で分割する
欲しいらしいので作ってみました。
=> [Feature] 文字列操作ユーティリティ関数

src/io/input-key-acceptor.cpp
#754のエンバグ
再描画後にカーソル位置を戻すようにした。
=> [Fix] ターゲッティング等の入力待ちでカーソル位置がおかしい #760

src/main-win.cpp
起動時の初期化中を除き、以下のオプションを切り替え可能にした。
- グラフィックス
- BGM
- 効果音
- 壁紙を使う
また、「壁紙を選択」も同様に行えるようにした。
=> [Feature] Win版メニューのオプションをタイトル画面やキャラメイク中も切り替え可能にする

src/birth/birth-select-realm.cpp, src/load/player-info-loader.cpp
PullRequest#779による#750のエンバグの顕在化。
=> [Fix] Linux/MacOSX版で元素使いで新規開始及びクイックスタートができなくなっていた

src/main-win.cpp
負の位置の座標が考慮されていないためウインドウ位置を復元できない場合があった。
座標がいずれかのモニタ領域に含まれる場合にウインドウ位置を復元するように修正した。
=> [Fix] Win版ウインドウ位置の復元チェック修正

src/main-win.cpp, src/main-win/main-win-music.cpp
既存の未参照パラメーター抑制をUNREFERENCED_PARAMETERマクロからmaybe_unused属性へ変更した。
=> [MISC] 不要なincludeの削除、未参照パラメーター警告の抑制、参照型の代入修正

src/dungeon/quest.cpp, src/dungeon/quest.h, src/market/building-quest.cpp
=> [Fix] ワーグタイプ以外のクエストが放棄できるのを修正 / 放棄時間が記録されないのを修正

src/player/player-status-flags.cpp
=> [Fix] 攻撃に対する毒耐性に種族ゾンビが抜けている

src/object-activation/activation-switcher.cpp
=> [Fix] マジックベーンの発動呼び出しが抜けている

src/cmd-visual/cmd-draw.cpp, src/io-dump/player-status-dump.cpp, src/view/display-characteristic.cpp, src/view/display-characteristic.h, src/view/display-player.cpp
=> [Feature] キャラクタダンプの出力ページを拡張

lib/xtra/music/music.cfg, src/birth/character-builder.cpp, src/main-win.cpp, src/main/music-definitions-table.cpp, src/main/music-definitions-table.h
=> [Feature] キャラメイク時BGM対応

lib/pref/pref-opt.prf, src/game-option/option-types-table.cpp
=> [Feature] オプションのデフォルト値を変更

src/birth/character-builder.cpp
=> [Fix] プレイ記録で元素の系統とカオスパトロンを出力 #825

src/view/display-inventory.cpp, src/window/display-sub-windows.cpp
=> [Feature] サブウィンドウの装備/持ち物一覧でシンボルを表示する #829

src/birth/auto-roller.cpp
オートローラの初期値が3,3,3,3,3,3だと初心者殺しなので修正。
=> [Feature] オートローラの初期設定を職業に合わせて設定する

src/angband.rc
バージョン情報の値はangband-version.hの定義を使用する。
=> [MISC] Win版のリソースにバージョン情報を追加

src/main-win.cpp
4ビットカラー対応処理を削除した。
起動時に画面の色深度をチェックし、8ビット(256色)以下の画面ではエラーを表示して終了する。
=> [Refactor] 16色画面用の処理を削除し、256色以下の画面では起動しないようにする

src/cmd-action/cmd-racial.cpp, src/mind/mind-elementalist.cpp, src/racial/class-racial-switcher.cpp, src/racial/mutation-racial-selector.cpp, src/racial/race-racial-command-setter.cpp, src/racial/racial-util.cpp, src/racial/racial-util.h
=> [Refactor] #625 レイシャルパワーの説明文のコードをわかりやすく整理

src/main-win.cpp
=> [Refactor] 256色画面用の処理を削除する

src/knowledge/knowledge-monsters.cpp
馬鹿馬鹿でバグ起こしている回りなのでちょっと確認して追記しました。
=> [Add] collect_monsters() のDoxygenコメント整理.

src/Makefile.am, src/main-win/graphics-win.cpp, src/main-win/graphics-win.h
Makefile.amに抜けがあったのと、リネームしたためコメントが合わなくなっている部分を修正した。
=> [Fix] Makefile.am、Doxygenコメント修正

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/player-status/player-infravision.cpp, src/player-status/player-infravision.h, src/player/player-status-flags.cpp, src/player/player-status.cpp
PlayerStatusBaseの派生クラスの実装を進める。
赤外線視力の処理を分離。
=> [Refactor] 赤外線視力管理クラス PlayerInfravisionの導入

src/birth/auto-roller.cpp
=> [Fix] オートローラーで最大値が出ない #949

src/mind/mind-archer.cpp
アーチャーのレイシャルパワーである矢弾の生成で、矢弾の
種類を選択部分を繰り返しコマンドに対応させる。
これにより矢弾の生成を繰り返しコマンドで実行した時の
配列外アクセスの可能性などのおかしな挙動が修正される。
=> [Feature] 矢弾生成のレイシャルパワーを繰り返しコマンドに対応

src/realm/realm-song.cpp
[Disccusion](https://github.com/hengband/hengband/discussions/321#discussioncomment-469491)の話題より。
分解音波が分解の遠距離攻撃だと思ってたという誤解の報告もあったので、合わせて対応。
=> [Refactor] 吟遊詩人の一部の歌名を実情に合わせて改名

src/main-win.cpp, src/main-win/graphics-win.cpp, src/main-win/graphics-win.h
タイル初期化処理をgraphics-win.cppへ移動しました。
=> [Refactor] main-win.cpp分割（タイル初期化処理をgraphics-win.cppへ移動）

src/main-win.cpp, src/main.cpp, src/view/display-lore-drops.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/items-spoiler.cpp, src/wizard/monster-info-spoiler.cpp, src/wizard/spoiler-util.h, src/wizard/wizard-spoiler.cpp
詳細はLinked issuesをご参照下さい
また、修正範囲について、VSが出してきたサジェストも解消しました
=> モンスター情報の詳細化/修正

src/effect/effect-item.cpp
affect_item()の処理で魔力復活の薬が破壊された時に、再帰的な
affect_item()の呼び出しによりリストの次のアイテムが破壊され、
次のアイテムを指すイテレータが無効になってしまっているのが
原因。
破壊されなかった次のアイテムを得る妥当な方法が無いため、
リストの最初から処理をやり直すようにする。
処理が重複しなよう、一度処理したアイテムは登録しておき
処理をスキップするようにする。
=> [Fix] 轟音のブレスにより魔力復活の薬が割れた際にクラッシュ #1041

src/cmd-action/cmd-attack.cpp, src/cmd-action/cmd-pet.cpp, src/combat/shoot.cpp, src/core/player-processor.cpp, src/knowledge/knowledge-experiences.cpp, src/load/load-zangband.cpp, src/mind/mind-cavalry.cpp, src/monster-attack/monster-attack-player.cpp, src/monster/monster-processor.cpp, src/pet/pet-fall-off.cpp, src/player-attack/player-attack.cpp, src/player-status/player-speed.cpp, src/player/player-skill.h, src/player/player-status.cpp, src/spell/spell-info.cpp
こちらもプルリクのみで。またテストビルドで怒られた場合は対処療法で。
=> [Refactor] GINOU_* を改名して enum 化．

src/window/display-sub-windows.cpp
=> [Fix] 床上のアイテム一覧サブウィンドウでモンスターを感知できる #1030

src/player/player-damage.cpp
日本語版のみに限定する処理ではないため、英語版でも同様に処理が行われるようにしました。
=> [Fix] 英語版もプレイヤー死亡時に強制セーブする

src/main-win.cpp
コマンドライン引数でセーブファイルを指定した場合にも、効果音とBGMの初期化を行うように修正した。
=> [Fix] セーブファイル指定起動時も効果音/BGMを初期化する

src/cmd-io/cmd-macro.cpp
メッセージが自動で送られるとマクロの確認等を行えなかった。
画面クリアのタイミングをマクロ設定画面コマンド選択後に移動することで、確認を行えるようにする。
=> [Fix] キー待ちしないオプション有効時もマクロ設定画面を扱いやすくする

lib/xtra/music/music.cfg
Town, Dungeon, Questの個別項目のコメントを追加しました。
=> [MISC] music.cfgに個別BGMのコメント追加

src/main-win.cpp
消す機会がなかなか来ないので、削除するだけプルリクエストです。
=> [Refactor] term_data構造体の未使用メンバ変数削除

src/grid/trap.cpp, src/grid/trap.h
=> [Refactor] トラップの種別をenum化.

src/cmd-action/cmd-mind.cpp, src/mind/mind-power-getter.cpp, src/mind/mind-power-getter.h
掲題の通りです
クラス化してメソッド分割を行いました
処理 (特にif文の反転)やメソッドの内容と命名の一致等問題ありましたらご連絡下さい
=> mind-power-getter.cpp の分割

lib/edit/a_info.txt, lib/edit/misc.txt, src/action/racial-execution.cpp, src/artifact/fixed-art-types.h, src/cmd-action/cmd-mane.cpp, src/cmd-item/cmd-usestaff.cpp, src/player/player-status.cpp
★の追加や効果等の調整を行いました
モンスター調整の方でも★を追加することになったので、コンフリクト解消のためにどなたかお早めにチェックして頂けますと助かります
=> v3.0.0 α25 アイテム調整

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/main-win.cpp, src/main-win/main-win-sound.cpp, src/main-win/main-win-sound.h, src/main-win/wav-reader.cpp, src/main-win/wav-reader.h
効果音の複数同時再生に対応する。
対応形式は変わらずPCMのWAVファイルのみです。
=> [Feature] Windows版の効果音再生をwaveOut APIへ移行

src/main-win/main-win-sound.cpp
waveOutPrepareHeader、waveOutWriteがエラーの場合、再生完了することがないためキューにデータが無限に溜まってしまう。
これらのAPIの戻り値をチェックするようにした。
また、キューに上限を設けてデータが溜まり続けることがないようにした。
=> [Fix] Windows版の効果音再生のエラーチェック追加

lib/edit/a_info.txt
- Add tentative English translations for Merlin's mirror, the two-handed sword, 'Dragon slayer', and the trifurcate spear, 'Trishula'.  Change the English name for the mirror from 'of Wizard Marlin' to 'of the Wizard, Merlin'.
- Make minor changes to the English descriptions of 'Magicbane', 'Talaria', and 'Morthanc' for readability.
=> English:  edits for recent artifacts

lib/edit/r_info.txt
- Add tentative English translations for piranha plants, Diavolo, and Cioccolata.
- For clarity, make some significant changes to the descriptions of Professor Ootsuki, passing sparrow, tiger in folding screen, spawn of Yog-Sothoth, half-giant, and half-ogre.
- Make some minor changes (single words, punctuation, whitespace) to some other descriptions.
=> English: edits for monster descriptions

src/object-hook/hook-enchant.cpp, src/sv-definition/sv-protector-types.h
特に大きな副作用にはならないと思うのでどなたか追認お願いします。
=> [Add] 魔法を防ぐクローク、ミスリル及びアダマン製の防具をRARE対象に。

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/main-win.cpp
=> コンパイル警告/エラーの解消

src/main-win/main-win-sound.cpp, src/main-win/wav-reader.h
=> [Refactor] Windowsの音再生に関わるコンパイル警告の除去

src/monster-floor/one-monster-placer.cpp, src/wizard/wizard-spells.cpp
#1305 のコミットがこっちのミスでめちゃくちゃになってしまったので一旦まとめます。
>#1302
>
>こっちの方がデバッグ上の「モンスター生成」とも合ってるし、使い勝手もこっちが良さそうなのでこちらから
=> 【再プルリク】デバッグのモンスター生成についてコメント側を合わせる

src/monster-floor/one-monster-placer.cpp, src/wizard/wizard-spells.cpp
#1307
one-monster-placer.cppのフラグ管理を全部マクロにしました
#1306 
ついでに前回のコメント修正のミスも修正しました（小声）
=> フラグ管理のリファクタリング(one-monster-placer.cpp)

lib/edit/a_info.txt
題名の通りです。+隠密が抜けていたので追加いたしました
追記: 性能調整も同時にいたします
=> 鼠小僧の黒装束の性能調整

src/monster/monster-damage.cpp
Resolves https://github.com/hengband/hengband/issues/1348 .
=> Fix some verbs in English death messages

src/autopick/autopick-command-menu.cpp, src/autopick/autopick-describer.cpp, src/autopick/autopick-destroyer.cpp, src/autopick/autopick-drawer.cpp, src/autopick/autopick-editor-command.cpp, src/autopick/autopick-editor-util.cpp, src/autopick/autopick-entry.cpp, src/autopick/autopick-finder.cpp, src/autopick/autopick-initializer.cpp, src/autopick/autopick-inserter-killer.cpp, src/autopick/autopick-matcher.cpp, src/autopick/autopick-pref-processor.cpp, src/autopick/autopick-reader-writer.cpp, src/autopick/autopick-registry.cpp, src/autopick/autopick-util.cpp, src/autopick/autopick.cpp
=> [Refactor] autopick内の関数コメントをDoxygen向けに整形．

src/floor/floor-mode-changer.h
=> [Add] cfm_type をDoxygenコメントに置換し、確認調整．

src/cmd-action/cmd-mind.cpp, src/mind/mind-explanations-table.cpp, src/mind/mind-explanations-table.h, src/mind/mind-info.cpp, src/mind/mind-info.h, src/mind/mind-power-getter.cpp, src/mind/mind-power-getter.h, src/mind/mind-types.h, src/window/display-sub-window-spells.cpp
mind-explanations-table周りは元素使いの説明文表示が独特なのを含めてややこしいことになっているので別Issue化して整理する。
=> mind_kind_type を enum class 化して各型を矯正.

src/mind/mind-sniper.cpp
エゴ矢を参考に倍率を上げていますので、もしかしたらバランス面で問題があるかもしれません
フラグ関連のリファクタリングはこれのマージ後に別のプルリクでします
=> [Feature]スナイパーの火炎/冷気の矢が弱点の敵に対して更に高倍率に

src/load/lore-loader.cpp, src/lore/lore-store.cpp, src/monster/monster-status.cpp, src/save/monster-writer.cpp, src/system/angband-version.h, src/system/monster-race-definition.h, src/view/display-lore-status.cpp
掲題の通りです
セーブデータ形式v5からv6にアップしました
v5のデータ読み込みも問題ありません
ご確認下さい
=> monster_race からr_xtra2 を削除し、r_xtra1 をr_can_evolve に改名した

src/core/scores.cpp, src/io/report.cpp, src/io/report.h
ごく小さいリファクタリングなのでチケットはなし
掲題の関数はerrr型を返していましたが、0 or 1だったのでboolにしました
また、失敗時にfalseとなるよう処理を反転させました
ご確認下さい
=> report_score() の型リファクタリング

src/system/h-config.h
掲題の通りです
何箇所かtodoがありますので併せてご確認下さい
間違って消したものはないと思われますが、OS XやLinuxでは必要なプリプロがありましたらコメントお願いします
=> Windowsとそれ以外で使用するプリプロを分ける

src/artifact/random-art-resistance.cpp, src/object-enchant/object-boost.cpp
付与する条件・確率などについてはコミットログを参照してもらい、こんなものでよいかご意見を頂きたく。
=> 上位耐性のランダム付与とランダムアーティファクトに 3.0.0Alpha で新しく追加された耐性が付与されるようにする

src/system/object-type-definition.cpp
=> object_type::is_offerable() のコンパイル警告修正

src/floor/floor-leaver.cpp, src/system/h-define.h
掲題の通りです
1箇所からしか使われていないマクロ関数なので分かりやすくなるよう削除しました
ご確認下さい
=> SGN() の削除 他 jump_floors() の微修正

src/io-dump/dump-util.cpp
=> [Refactor] io-dump ディレクトリ内のコメントを Doxygen 向けに整理．

src/avatar/avatar-changer.cpp
=> [Refactor] avatar ディレクトリ以下のコメントをDoxygen向けに追加、整理．

src/main-x11.cpp
Memory Sanitizer のノイズとなるので見つけうる限りのリソース漏れ
コードを修正する。
XIMとXftに関するリソース漏れだけはどうしても修正できなかった。
ライブラリの仕様としてどうしても完全にリソース漏れ無しにできない
可能性がある。
以前作業しててそのまま放置してたのを思い出したので。
X11版をレビューできるアクティブなメンバーが居ないかもしれませんが、参考として修正前後のLeakSanitizerの出力を記載しておきます。
修正前：
```
=================================================================
==11744==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 768 byte(s) in 1 object(s) allocated from:
#0 0x7f59cd8fd8e0 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
#1 0x7f59cd0413a0  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x213a0)
Direct leak of 408 byte(s) in 1 object(s) allocated from:
#0 0x7f59cd8fd6f7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7f59cd70bbdf in _XimOpenIM …
```
=> [Fix] X11版インターフェースのリソースリーク

src/autopick/autopick-methods-table.h, src/dungeon/dungeon-flag-mask.h, src/market/building-initializer.h, src/monster-floor/monster-dist-offsets.h, src/player-info/self-info-util.h
=> [Fix] すべてのソースファイルにBOMを付与する

src/monster-attack/monster-attack-player.cpp, src/spell-realm/spells-hex.cpp, src/spell-realm/spells-hex.h
掲題の通りです
後ほどmonster-attack/ を大規模にクラス化する予定があるので、前段作業として変数宣言をautoにするなど諸々整えました
ご確認下さい
=> monster-attack-player.cpp に定義されていた呪術関係の処理をspells-hex.cpp/h へ移した

src/grid/feature.h, src/store/service-checker.cpp, src/system/h-type.h, src/system/object-type-definition.h
掲題の通りです
他の作業が立て込んできたので、消したエイリアスは2個しかないですがレビューに回して脳内スタックを減らします
ご確認下さい
=> 型エイリアスの削除 Alpha38

src/game-option/runtime-arguments.cpp, src/game-option/runtime-arguments.h, src/load/info-loader.cpp, src/load/item-loader.cpp, src/load/load.cpp, src/load/lore-loader.cpp, src/main.cpp
=> arg_fiddleを常時真として削除した

src/core/game-play.cpp, src/game-option/runtime-arguments.cpp, src/game-option/runtime-arguments.h, src/io/input-key-processor.cpp, src/load/load.cpp, src/main.cpp
掲題の通りです
ご確認下さい
これがマージされたら、本体であるウィザードモード本体の削除に取り掛かります
=> arg_wizardを常時偽として削除した

src/monster-attack/monster-attack-player.cpp
掲題の通りです
適当なモンスターをデバッグ召喚してご確認下さい
=> モンスターが直接攻撃をしない事象を修正した

src/main-win/main-win-utils.h
C_MAKE の使用を避けるため、 to_wchar と to_multibyte クラスで使用されて
いる内部バッファ用のメンバ変数を std::vector にする。
実際その使い方がされているかわからないがNULLポインタを返す仕様を維持する
ために std::optional で NULL ポインタかどうかをエミュレートする。
=> [Refactor] to_wchar と to_multibyte の内部バッファを std::vector にする

src/autopick/autopick-drawer.cpp
string_make で確保した文字列領域に対して C_KILL を呼んで解放している。
結果的には同じことになっているが、string_make に対しては string_free を
呼ぶべきなのでそのようにする。
また断りなく const 修飾子を外しているので、理由をコメントに記載し
const_cast を使用するようにする。
=> [Fix] string_make で確保した領域に C_KILL している

src/util/quarks.cpp
掲題の通りです
ごく小さい修正なのでチケット化はしていません
ご確認下さい
=> quark_add() においてコンパイル警告が出るのを修正した

src/object-enchant/smith-tables.cpp, src/object-enchant/smith-types.h
=> [Feature] 鍛冶：階のユニークモンスターを表示する発動

lib/xtra/sound/sound.cfg, src/cmd-action/cmd-move.cpp, src/main/sound-definitions-table.cpp, src/main/sound-definitions-table.h
=> [Implement] 階段の昇降時効果音を追加

src/autopick/autopick-destroyer.cpp, src/birth/game-play-initializer.cpp, src/birth/quick-start.cpp, src/blue-magic/learnt-power-getter.cpp, src/core/scores.cpp, src/floor/floor-changer.cpp, src/floor/floor-leaver.cpp, src/knowledge/knowledge-features.cpp, src/load/load.cpp, src/main-win.cpp, src/main-x11.cpp, src/monster-floor/monster-remover.cpp, src/monster/monster-compaction.cpp, src/monster/monster-damage.cpp, src/room/rooms-city.cpp, src/system/object-type-definition.cpp, src/term/z-virt.h, src/wizard/wizard-item-modifier.cpp
=> WIPE/C_WIPE/COPY マクロを削除する

src/main/angband-initializer.cpp, src/main/game-data-initializer.cpp, src/main/game-data-initializer.h
掲題の通りです
常に「return 0;」 (成功)で呼び出し側のif (...)が無意味になっていました
削除しましたのでご確認下さい
=> game-data-initializer.cpph/h に定義されているメソッドの無意味な返り値をvoidに変更した

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/blue-magic/blue-magic-checker.cpp, src/blue-magic/blue-magic-checker.h, src/blue-magic/learnt-power-getter.cpp, src/io-dump/special-class-dump.cpp, src/load/player-class-specific-data-loader.cpp, src/load/player-class-specific-data-loader.h, src/mind/mind-blue-mage.h, src/mspell/assign-monster-spell.cpp, src/player-base/player-class.cpp, src/player-info/class-specific-data.h, src/save/player-class-specific-data-writer.cpp, src/save/player-class-specific-data-writer.h, src/wizard/wizard-spells.cpp
職業固有データ分離の続き。
青魔道士のデータを bluemage_data_type に移動する。
=> [Refactor] 青魔道士の固有データを magic_num から分離

src/Makefile.am
Resolves https://github.com/hengband/hengband/issues/1646 .
=> Include player-info/bard-data-type.h in the output of "make dist"

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/object-activation/activation-switcher.cpp, src/specific-object/stone-of-lore.cpp, src/specific-object/stone-of-lore.h, src/spell/spells-object.cpp, src/spell/spells-object.h
=> perilous_secrets() をspells-object.cpp/h からspecific-object/stone-of-lore.cpp/h へ移動させた

src/birth/character-builder.cpp, src/monster-floor/monster-death.cpp, src/player-ability/player-ability-types.h, src/player/patron.cpp, src/player/patron.h, src/player/player-status.cpp, src/view/display-player.cpp, src/wizard/cmd-wizard.cpp
最近変愚からのマージにようやく追いついてきたので、カオスパトロンの処理をクラス化したものを馬鹿馬鹿から単純移植しました。レビューお願いします。
=> [Refactor] 馬鹿馬鹿よりカオスパトロンのクラス化移行を移植．

lib/xtra/sound/Makefile.am
Resolves https://github.com/hengband/hengband/issues/1662 .
=> Remove readme.txt from output of "make dist" in lib/xtra/sound

src/knowledge/knowledge-experiences.cpp, src/view/display-util.cpp
小さな置換なのでチケットはなしで
掲題の件、久しぶりに起動して解析したら2ファイルでエラーが出ました
それを修正しただけのコミットです
ご確認下さい
\# concptrではなくconst char\* を使ったのは今後の型エイリアス削減のため
=> SourceTrailの解析 (clangベース)でエラーが出た箇所を修正した

.clang-format
=> [Style] clang-format の整形ルールの調整

src/effect/effect-player.cpp
たまたま見つけただけなのでチケットはなし
以下の作業を行いました
ご確認下さい
- 使われていないテーブル定義の削除
- 意味的に重複定義されていたenumの削除
- その他整形 (ブレースを付ける、長すぎるif文を分割する)
=> effect-player.cpp の整形

src/cmd-io/cmd-gameoption.cpp, src/combat/shoot.cpp, src/effect/effect-processor.cpp, src/game-option/special-options.cpp, src/game-option/special-options.h, src/load/option-loader.cpp, src/mind/mind-mirror-master.cpp, src/object-use/throw-execution.cpp, src/save/info-writer.cpp, src/spell-kind/spells-genocide.cpp
とりあえず1描写に1秒以上設定したがることはないと思うのでこの辺に留めました。delay_factorがbyteだったのでint32_tへ移行してセーブデータバージョンも繰り上げています。
=> [Feature] #83 ウェイト値をmsecで0から1000へ選択可能に。

src/action/activation-execution.cpp, src/artifact/artifact-info.cpp, src/artifact/artifact-info.h, src/artifact/random-art-effects.h, src/object-enchant/activation-info-table.cpp, src/object-enchant/activation-info-table.h, src/object/object-info.cpp, src/object/object-value-calc.cpp
表題の通りです
単純な差し替えにつきチケットはありません
本作業に伴って不要なdefine定数も廃止しました
ご確認下さい
=> activation_info を配列からvectorに差し替えた

src/Makefile.am
Resolves https://github.com/hengband/hengband/issues/1719 .
=> Include player-info/monk-data-type.h in the result of "make dist"

src/cmd-action/cmd-move.cpp
=> 塔のクエストがクリア状態にならない不具合を解消した

src/dungeon/quest-completion-checker.cpp, src/dungeon/quest-completion-checker.h
=> QuestCompletionCheckerクラスの分割

doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.0Alpha40

src/dungeon/quest-completion-checker.cpp, src/floor/floor-object.cpp, src/floor/floor-object.h, src/grid/object-placer.cpp, src/monster-floor/monster-death.cpp, src/monster-floor/special-death-switcher.cpp, src/specific-object/chest.cpp, src/spell/spells-object.cpp, src/wizard/wizard-item-modifier.cpp
掲題の通りです
詳細はチケットをご参照下さい
確認お願いします
=> make_object() の引数rq_level をデフォルト引数にし、型もintからstd::optional<int>に変更した

src/artifact/fixed-art-generator.cpp, src/info-reader/fixed-map-parser.cpp, src/load/item-loader.cpp, src/load/option-loader.cpp, src/lore/lore-calculator.cpp, src/main-win.cpp, src/mspell/mspell-damage-calculator.cpp, src/pet/pet-util.cpp, src/player/player-damage.cpp, src/player/player-move.cpp, src/player/player-status.cpp, src/realm/realm-arcane.cpp, src/realm/realm-chaos.cpp, src/realm/realm-craft.cpp, src/realm/realm-crusade.cpp, src/realm/realm-death.cpp, src/realm/realm-demon.cpp, src/realm/realm-hissatsu.cpp, src/realm/realm-names-table.h, src/realm/realm-nature.cpp, src/realm/realm-song.cpp, src/realm/realm-sorcery.cpp, src/realm/realm-trump.cpp, src/spell-kind/spells-polymorph.cpp, src/store/cmd-store.cpp, src/wizard/wizard-item-modifier.cpp
=> '? true : false' 形式の判定を適切に差し替えた

src/market/arena-info-table.cpp, src/market/arena-info-table.h, src/system/building-type-definition.h
たまたま目についた単純なリファクタリングです
チケットはありません
ご確認下さい
=> arena-type構造体をbuilding-type-definition.h から arena-info-table.h に移した

lib/edit/r_info.txt
=> [Fix] おじゃまぷよの英文フレーバーが余計だった（爆発は別にしない）ので修正。

lib/edit/k_info.txt
下記、Discussionのコメントより。
- https://github.com/hengband/hengband/discussions/300#discussioncomment-1295979
レア度に見合ったちょっとうれしい能力かつフレーバー的にマッチしていると思うので採用で良いのではないかと。
=> [Feature] 天上のクロークに浮遊能力を追加

lib/edit/r_info.txt
モンティ・パイソン・アンド・ホーリー・グレイルより、カルバノグの殺人兎を追加した。
バランス等問題あれば修正をお願いします。
=> [Add] 『カルバノグの殺人兎』/ The Killer Rabbit of Caerbannog

src/effect/effect-monster-oldies.cpp, src/load/old/load-v1-5-0.cpp, src/monster-floor/one-monster-placer.cpp, src/monster/monster-list.cpp, src/monster/monster-status.cpp, src/mspell/mspell-damage-calculator.cpp, src/system/monster-type-definition.h, src/view/display-lore-status.cpp
馬鹿馬鹿では#defineにしていたが、こちらはconst intで。
=> [Refactor] モンスターの限界最大HP(30000)がマジックナンバーになっていたのを const int に変更

src/player-ability/player-charisma.cpp, src/player-ability/player-charisma.h, src/player-ability/player-constitution.cpp, src/player-ability/player-constitution.h, src/player-ability/player-dexterity.cpp, src/player-ability/player-dexterity.h, src/player-ability/player-intelligence.cpp, src/player-ability/player-intelligence.h, src/player-ability/player-strength.cpp, src/player-ability/player-strength.h, src/player-ability/player-wisdom.cpp, src/player-ability/player-wisdom.h, src/player-base/player-class.cpp, src/player-base/player-class.h, src/player-status/player-speed.cpp, src/player-status/player-speed.h, src/player-status/player-status-base.cpp, src/player-status/player-status-base.h, src/player/player-status-flags.cpp, src/player/player-status-flags.h, src/player/temporary-resistances.cpp
=> [Refactor] ソースコード内BattleForm表記をStance表記に統一

src/artifact/random-art-effects.h, src/object-activation/activation-switcher.cpp, src/object-enchant/activation-info-table.cpp, src/object-enchant/object-boost.cpp
=> [Add] ランダム発動に加速(50+d50)を追加。

lib/edit/r_info.txt, lib/file/mondeath.txt, lib/file/monfear.txt, lib/file/monspeak.txt, src/action/weapon-shield.cpp, src/cmd-item/cmd-eat.cpp, src/effect/effect-monster-resist-hurt.cpp, src/effect/effect-player-resist-hurt.cpp, src/flavor/flavor-describer.cpp, src/io/interpret-pref-file.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-priest.cpp, src/mspell/mspell-particularity.cpp, src/object-use/quaff-execution.cpp, src/object-use/read-execution.cpp, src/object-use/use-execution.cpp, src/object-use/zaprod-execution.cpp, src/object-use/zapwand-execution.cpp, src/player-attack/attack-chaos-effect.cpp, src/player-info/body-improvement-info.cpp, src/racial/class-racial-switcher.cpp, src/racial/mutation-racial-selector.cpp, src/realm/realm-trump.cpp, src/spell/spells-summon.cpp, src/wizard/wizard-item-modifier.cpp
Many of these are for messages that were changed or added since the transition to the 3.0.0 alpha versions.    Others are for messages that predate those changes.
=> Slightly edit English messages

lib/edit/a_info.txt
・Nethackでは所持時にテレパシー能力がついていたので追加。
・英名のバグ修正
・価格が低すぎるのを底上げ
=> ★ダイアナの長弓の調整

src/birth/birth-wizard.cpp, src/birth/history-editor.cpp, src/cmd-visual/cmd-draw.cpp, src/core/game-closer.cpp, src/core/game-play.cpp, src/core/scores.cpp, src/core/scores.h, src/io-dump/character-dump.cpp, src/io-dump/character-dump.h, src/io-dump/player-status-dump.cpp, src/io-dump/player-status-dump.h, src/io/files-util.cpp, src/io/files-util.h, src/io/report.cpp, src/io/report.h, src/player/process-death.cpp, src/player/process-death.h, src/view/display-player.cpp, src/view/display-player.h, src/window/display-sub-windows.cpp
掲題の通りです
少しコードが雑ですが、理屈的には解決していると思われます
但し画面描画周りに全く手を付けていないため、最終的には解決していません
どなたか画面周りに原因がないか確認お願いします
=> [Fix] #1965 長い名前のモンスターに殺されるとダンプが見切れる事象を解決した

src/core/scores.cpp
=> Fix compilation error if WORLD_SCORE not set.

src/floor/floor-base-definitions.h
気まぐれなことだが馬鹿馬鹿でいじったのでついでに提案。Issueなし。
=> [Refactor] floor-base-definitions.h 内定数の constexpr int 化。

lib/edit/r_info.txt
=> [Fix] ドワーフ『ナル』のフレーバーが多方面にひどすぎるので直してみた。

src/wizard/wizard-special-process.cpp
=> (Refactor)　ウィザードモードの任意地形変更におけるID指定処理をget_valueに置換。

lib/edit/r_info.txt
=> [Fix] アングマールの魔王のテキスト送り仮名ミス修正。

src/io/uid-checker.cpp
掲題の通りです
setuid() 等の関数の戻り値が0 (正常値)以外であれば、具体的にいくつだったのかをコンソールへ表示する機能も追加しておきました
ご確認下さい
=> uid-checker.cpp のコンパイルエラーを解消した＋ログ出力を追加した

src/main-gcu.cpp
Standard fix for playing older 'bands in a 256 colour terminal.
=> Colour patch for 88 and 256 colour terminals

src/blue-magic/blue-magic-ball-bolt.cpp, src/blue-magic/blue-magic-breath.cpp, src/cmd-action/cmd-mane.cpp, src/effect/effect-feature.cpp, src/effect/effect-monster-resist-hurt.cpp, src/mspell/high-resistance-checker.cpp, src/mspell/mspell-ball.cpp, src/mspell/mspell-selector.cpp, src/object/warning.cpp
#2027 に沿って、#2080 で編集したファイルを一括修正。
=> #2080 で編集したファイルのif文における｛｝の位置をまとめて修正

src/object-enchant/apply-magic.cpp
=> 薬や魔導書にも上質補正がかかる事象を修正した

src/artifact/random-art-characteristics.cpp, src/inventory/inventory-curse.cpp
掲題の通りです
random-art-characteristics.cpp の方はやや釈然としませんが、ひとまず今あるコードで警告は消えました
ご確認下さい
=> MSVC環境で出るコンパイル警告を2件解消した

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/core/player-processor.cpp, src/dungeon/dungeon.h, src/info-reader/dungeon-reader.cpp, src/info-reader/race-info-tokens-table.cpp, src/info-reader/race-info-tokens-table.h, src/info-reader/race-reader.cpp, src/lore/lore-util.h, src/monster-race/race-visual-flags.h, src/system/monster-race-definition.h, src/view/display-map.cpp, src/wizard/monster-info-spoiler.cpp
=> モンスターのフラグをまとめる（見た目）

src/load/info-loader.cpp, src/player/race-resistances.cpp, src/player/temporary-resistances.cpp, src/system/angband-version.h
Alpha52で無理に実施するほどでもなかった雑多な作業をまとめました
1つ1つは大したこともしていないためチケットはありません
ご確認下さい
=> 不要コメントの削除・必要コメントの追加・変数のコンパイル時定数への変更

src/main-gcu.cpp, src/main-win.cpp
Resolves https://github.com/hengband/hengband/issues/2116 .
=> English: avoid "angband" in startup failure messages

src/object-enchant/others/apply-magic-amulet.cpp, src/object-enchant/others/apply-magic-others.cpp, src/object-enchant/others/apply-magic-ring.cpp, src/object-enchant/protector/apply-magic-armor.cpp, src/object-enchant/protector/apply-magic-boots.cpp, src/object-enchant/protector/apply-magic-cloak.cpp, src/object-enchant/protector/apply-magic-crown.cpp, src/object-enchant/protector/apply-magic-gloves.cpp, src/object-enchant/protector/apply-magic-helm.cpp, src/object-enchant/protector/apply-magic-shield.cpp, src/object-enchant/weapon/apply-magic-weapon.cpp
=> デバッグ用の装備品強化ルーチンは最初に判定するように修正した

src/effect/effect-monster-resist-hurt.cpp
Fixed #1960 
Fixed #2172 
複数のバグ修正なので注意してご確認お願いいたします
=> 重力属性のバグを修正

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/object-enchant/apply-magic.cpp, src/object-enchant/enchanter-base.h, src/object-enchant/others/apply-magic-amulet.cpp, src/object-enchant/others/apply-magic-amulet.h, src/object-enchant/others/apply-magic-lite.cpp, src/object-enchant/others/apply-magic-lite.h, src/object-enchant/others/apply-magic-others.cpp, src/object-enchant/others/apply-magic-others.h, src/object-enchant/others/apply-magic-ring.cpp, src/object-enchant/others/apply-magic-ring.h, src/object-enchant/protector/abstract-protector-enchanter.h, src/object-enchant/protector/apply-magic-armor.h, src/object-enchant/protector/apply-magic-boots.h, src/object-enchant/protector/apply-magic-cloak.h, src/object-enchant/protector/apply-magic-crown.h, src/object-enchant/protector/apply-magic-gloves.h, src/object-enchant/protector/apply-magic-helm.h, src/object-enchant/protector/apply-magic-shield.h, src/object-enchant/weapon/abstract-weapon-enchanter.h, src/object-enchant/weapon/apply-magic-weapon.h
apply-magic-others.cpp をクラス化する前に、他より処理の多かった光源強化ルーチンを別クラスに切り出しました
ご確認下さい
=> LiteEnchanterクラスを定義した

src/player-info/alignment.cpp
1メソッドだけ付いてなかったのを付けただけの単純置換です
チケットはありません
ご確認下さい
=> Alignment::update_alignment() のplayer_ptrにthisを付けた

src/load/old/item-loader-savefile50.cpp, src/load/savedata-old-flag-types.h
=> ディスコードでの議論に基づき、XTRA1が再利用できない潜在不具合を解消した

src/wizard/wizard-spells.cpp, src/wizard/wizard-spells.h
他にもツッコミどころは多いがとりあえず単独の目的はこれなので。
=> [Refactor] debug_spell_commands_listをvector化。

src/wizard/wizard-spells.cpp
属性一覧表示はともかく、まともに動作するように修正はしてみました。
=> [Fix] wiz_kill_enemy()の数値入力をget_value()で実装しなおし。

src/effect/effect-monster-charm.cpp, src/effect/spells-effect-util.cpp, src/effect/spells-effect-util.h, src/hpmp/hp-mp-regenerator.cpp, src/load/old/item-loader-savefile50.cpp, src/load/old/load-v1-5-0.cpp, src/save/item-writer.cpp, src/specific-object/monster-ball.cpp, src/spell-realm/spells-arcane.cpp, src/system/h-type.h, src/system/object-type-definition.h, src/wizard/wizard-item-modifier.cpp
掲題の通りです
xtra5は、調べた限りではモンボの最大HP以外では使われていませんでした
なので単純置換＋αでPR出します
ご確認下さい
=> ObjectType::xtra5 をcaptured_monster_max_hp に変更した 他微修正

src/effect/spells-effect-util.h, src/system/h-type.h, src/system/monster-type-definition.h, src/util/quarks.cpp, src/util/quarks.h
=> STR_OFFSETの型エイリアスを廃止し、ushortに統一した

src/cmd-action/cmd-pet.cpp, src/cmd-io/cmd-gameoption.cpp, src/cmd-visual/cmd-draw.cpp, src/io/input-key-acceptor.cpp, src/io/record-play-movie.cpp, src/main-cap.cpp, src/main-gcu.cpp, src/main-win.cpp, src/main-x11.cpp, src/main/x11-type-string.cpp, src/player/player-damage.cpp, src/spell-kind/spells-sight.cpp, src/term/screen-processor.cpp, src/term/z-term.cpp, src/term/z-term.h, src/view/display-lore.cpp, src/view/object-describer.cpp, src/window/display-sub-window-spells.cpp, src/window/display-sub-windows.cpp
=> 命名がスネークケースでないものをスネークケースに改名した

src/core/player-processor.cpp, src/io/input-key-requester.cpp, src/io/input-key-requester.h, src/store/cmd-store.cpp, src/system/h-type.h
掲題の通りです
#2221 のバグは別途対応します (誰かが)
ご確認下さい
=> input-key-requestor.cpp/h をクラス化した

src/effect/effect-processor.cpp
Resolve #2262
こちらで影響がないことは確認したが、どこまで影響しているかわかりにくいグローバル変数のような状態のものなため注意してご確認いただきたい
=> project()関数内のy, xを一部ローカル化した①+グローバルなy, xをtemp_*に変えた

src/wizard/wizard-game-modifier.cpp
=> [Fix] wiz_restore_monster_max_num()の範囲指定を修正しつつn/Nコマンドと同等の仕様にリファクタリング。

src/object-enchant/apply-magic.cpp, src/object-enchant/weapon/abstract-weapon-enchanter.cpp, src/object-enchant/weapon/abstract-weapon-enchanter.h, src/object-enchant/weapon/apply-magic-weapon.cpp
今まではコンストラクタを呼ぶかどうかを上流のif文で判定していましたが、あまりオブジェクト指向設計っぽくない感じがしたのでコンストラクタ以下にまとめました
デバッグ生成でダイヤモンド・エッジ等作って確認済です
ご確認下さい
=> AbstractWeaponEnchanter のコンストラクタで武器類の強化/弱化を判定させることにした

src/object-enchant/apply-magic.cpp, src/object-enchant/others/apply-magic-others.cpp, src/object-enchant/others/apply-magic-others.h
掲題の通りです
いよいよ全体のクラス化も見えてきましてもう一息といったところです
ここはothersというだけあって雑多なコードなので敢えてこれ以上細分化せずswitch文で処理しました
ご確認下さい
=> apply-magic-others.cpp/h をクラス化した

src/action/movement-execution.cpp
掲題の件、修正しました
長いif文を変数で受けた時に2回否定していたようです
ご確認下さい
=> ペットを押し退けようとすると攻撃動作に入ってしまう事象を修正した

src/system/angband-exceptions.h
MSVC様がお怒りになるので
多分 Resolve #2318
=> [Fix] デフォルトコンストラクタを明示的に削除する

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/blue-magic/blue-magic-checker.cpp, src/core/magic-effects-timeout-reducer.cpp, src/core/player-processor.cpp, src/load/player-info-loader.cpp, src/mind/mind-ninja.cpp, src/monster-attack/monster-attack-status.cpp, src/monster-attack/monster-eating.cpp, src/player/digestion-processor.cpp, src/player/player-damage.cpp, src/racial/racial-switcher.cpp, src/save/player-writer.cpp, src/status/bad-status-setter.cpp, src/status/buff-setter.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h, src/timed-effect/player-paralysis.cpp, src/timed-effect/player-paralysis.h, src/timed-effect/timed-effects.cpp, src/timed-effect/timed-effects.h, src/window/main-window-stat-poster.cpp
掲題の通りです
幻覚に続いて一部の文字列操作を修正しました
併せてご確認下さい
=> プレイヤーの麻痺に関するパラメータをクラス化した

src/cmd-action/cmd-others.cpp, src/cmd-io/cmd-save.cpp, src/core/game-closer.cpp, src/core/scores.cpp, src/io/exit-panic.cpp, src/io/report.cpp, src/io/signal-handlers.cpp, src/load/load-util.cpp, src/load/load-util.h, src/load/player-info-loader.cpp, src/player/player-damage.cpp, src/player/process-death.cpp, src/save/save-util.cpp, src/save/save-util.h, src/system/player-type-definition.h, src/view/display-player.cpp, src/wizard/wizard-special-process.cpp
Resolve #2320 
修正内容についてはコミットログをご確認ください。
=> [Refactor] PlayerType::died_from を std::string 型にする

src/main-win.cpp
=> Windowsでコンパイルエラーが出る事象を修正した

src/effect/effect-processor.cpp
Resolve #2253 
準グローバル変数状態だったものなため、引き続き注意してご確認お願いいたします
=> projectの temp_x, y を一意にし、 const化

src/effect/effect-processor.cpp
=> project() の dist 変数のスコープを切り分けた

src/player/process-death.cpp
=> English: fix "cannot pass object of non-trivial type" error with clang

doxygen/Hengband.doxyfile, src/spell-kind/spells-launcher.cpp, src/system/angband-version.h
=> プレイヤーのブレスが発動しないバグを修正(master)

src/floor/floor-generator.cpp, src/load/world-loader.cpp, src/market/arena.cpp, src/monster-race/monster-race.cpp, src/monster-race/monster-race.h, src/save/player-writer.cpp, src/system/building-type-definition.cpp, src/system/building-type-definition.h
役割からして MonsterRace クラスのメンバ関数であるべき。
また、これを使用しているモンスター闘技場からの呼び出し部分を STL を使って書き直し、
battle_mon 配列を複数なので battle_mon_list に改名する。
=> [Refactor] calc_monrace_power() を MonsterRace のメンバ関数にする

doxygen/Hengband.doxyfile, src/birth/game-play-initializer.cpp, src/system/angband-version.h
Resolved #2385 
50FRQ (40番目のクエスト) が読み込まれてなかったので修正
=> ランダムクエストの50Fが存在しないバグを修正

src/monster/monster-list.cpp
Fixed #2395 
OR であるはずの部分が AND になってたので修正
=> 変身していないカメレオンが生成されるバグを修正

src/melee/melee-switcher.cpp, src/melee/melee-switcher.h, src/melee/melee-util.cpp, src/melee/melee-util.h, src/melee/monster-attack-monster.cpp
=> [Refactor] be_type を enum class BlowEffectType 化。

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/dungeon/dungeon.h, src/info-reader/dungeon-reader.cpp, src/info-reader/race-info-tokens-table.cpp, src/info-reader/race-info-tokens-table.h, src/info-reader/race-reader.cpp, src/load/lore-loader.cpp, src/load/savedata-old-flag-types.h, src/lore/lore-calculator.cpp, src/lore/lore-store.cpp, src/lore/lore-util.cpp, src/lore/lore-util.h, src/market/bounty.cpp, src/monster-floor/monster-death-util.cpp, src/monster-floor/monster-death.cpp, src/monster-race/race-drop-flags.h, src/monster/monster-processor-util.cpp, src/monster/monster-processor-util.h, src/monster/monster-update.cpp, src/monster/monster-util.cpp, src/object-enchant/others/apply-magic-others.cpp, src/save/monster-writer.cpp, src/system/angband-version.h, src/system/monster-race-definition.h, src/view/display-lore-drops.cpp
Resolved #2258 
こちらである程度確認はしたが、これの作業の間に何百ものコミットがあったためエンバグに注意してご確認いただきたい
=> モンスターのフラグをまとめる（ドロップ）

src/load/item/item-loader-factory.cpp, src/load/item/item-loader-factory.h, src/load/monster/monster-loader-factory.cpp, src/load/monster/monster-loader-factory.h, src/object-use/read/read-executor-factory.cpp, src/object-use/read/read-executor-factory.h
=> ファクトリクラスにおいてshared_ptr を返している箇所をunique_ptr に差し替えた

src/monster/monster-util.cpp
Resolved #2420 
1、2を修正いたしました。3、4については議論の余地があるため現状は保留としておきます
=> ダンジョンで指定された条件とは違うモンスターが生成されることのあるバグを修正

src/lore/lore-store.cpp, src/monster/monster-util.cpp
=> 思い出補完のカウントとダンジョンのモンスターフラグフィルターのコピペを低減

src/combat/shoot.cpp, src/effect/effect-characteristics.h, src/effect/effect-processor.cpp, src/io/cursor.cpp, src/mind/mind-ninja.cpp, src/mspell/mspell-checker.cpp, src/mspell/mspell-judgement.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-fetcher.cpp, src/spell/range-calc.cpp, src/spell/range-calc.h, src/target/projection-path-calculator.cpp, src/target/projection-path-calculator.h
Resolve #2413 
一応動作が問題ないことを確認したが、特にシーカーレイ、スーパーレイの変更が大きいため注意
=> projection_path をクラス化した

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/action/movement-execution.cpp, src/dungeon/dungeon.h, src/dungeon/quest.cpp, src/info-reader/dungeon-reader.cpp, src/info-reader/race-info-tokens-table.cpp, src/info-reader/race-info-tokens-table.h, src/info-reader/race-reader.cpp, src/monster-floor/monster-move.cpp, src/monster-race/monster-race-hook.cpp, src/monster-race/race-wilderness-flags.h, src/monster/monster-damage.cpp, src/monster/monster-info.cpp, src/monster/monster-util.cpp, src/mspell/summon-checker.cpp, src/system/monster-race-definition.h, src/wizard/wizard-spoiler.cpp
Resolve #2186 
これらには思い出フラグがなく、セーブデータの互換性は特に必要ないので更新しておりません
=> モンスターのフラグをまとめる（荒野）

src/cmd-action/cmd-mind.cpp, src/mind/mind-berserker.cpp, src/mind/mind-berserker.h, src/mind/mind-force-trainer.cpp, src/mind/mind-force-trainer.h, src/mind/mind-mindcrafter.cpp, src/mind/mind-mindcrafter.h, src/mind/mind-mirror-master.cpp, src/mind/mind-mirror-master.h, src/mind/mind-ninja.cpp, src/mind/mind-ninja.h, src/mind/mind-numbers.h
=> mind-numbers.h をenum class 化

doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.0Alpha57

src/monster-attack/monster-eating.cpp
掲題の通りです
2行修正のみなのでチケットはありません
ご確認下さい
=> monster-eating.cpp で出ていたナローキャスティング警告を解消した

src/spell-class/spells-mirror-master.cpp
=> シーカーレイが鏡で反射しないことのあるバグを修正

src/load/load.cpp, src/load/quest-loader.cpp, src/load/quest-loader.h
見かけたので軽く設計変更しました
チケットはありません
ご確認下さい
=> load_quest_info() を、「2つのポインタ引数戻り値なし」から「引数なしタプルの戻り値あり」に変更した

src/mind/mind-blue-mage.h, src/mind/mind-elementalist.cpp, src/object-enchant/tr-types.h, src/player/player-skill.cpp, src/util/rng-xoshiro.cpp, src/wizard/wizard-spoiler.cpp
起動確認だけは行いました (解消と呼ぶには数百行以上出てきたのでFix扱いにしてあります)
詳細はチケットをご参照下さい
=> VS2022環境でstd::array<T, N> 型の変数宣言でコンパイル警告が出ていたのを解消した

src/main-win.cpp, src/main.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/items-spoiler.cpp, src/wizard/monster-info-spoiler.cpp, src/wizard/spoiler-util.h, src/wizard/wizard-spoiler.cpp, src/wizard/wizard-spoiler.h
Discordでの議論に基づき、wiz\_spell\_stat をコンパイル時定数に変更しました
またこれに伴って、wizard-spoiler.cpp/h 及びspoiler-util.h も微調整しました
ご確認下さい
=> wizard-spoiler.cpp の調整

src/flavor/named-item-describer.cpp
=> Eric氏の修正でBitFlagsCalculatorが使われていなかったので差し替えた

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/cmd-building/cmd-inn.cpp, src/cmd-item/cmd-eat.cpp, src/core/magic-effects-timeout-reducer.cpp, src/hpmp/hp-mp-processor.cpp, src/load/player-info-loader.cpp, src/object-activation/activation-switcher.cpp, src/object-use/quaff/quaff-effects.cpp, src/player-info/self-info.cpp, src/realm/realm-arcane.cpp, src/realm/realm-crusade.cpp, src/realm/realm-life.cpp, src/realm/realm-nature.cpp, src/save/player-writer.cpp, src/spell/spells-staff-only.cpp, src/spell/spells-status.cpp, src/status/bad-status-setter.cpp, src/status/bad-status-setter.h, src/status/buff-setter.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h, src/timed-effect/player-poison.cpp, src/timed-effect/player-poison.h, src/timed-effect/timed-effects.cpp, src/timed-effect/timed-effects.h, src/window/main-window-stat-poster.cpp
掲題の通りです
形容詞だとクラス名として扱いにくかったので名詞化しました
設計は、今までに実装してきたTimedEffect 系統と同じです
以下のことを確認しました
- 毒打撃で毒になる
- 毒ブレスで毒になる
- 毒耐性がある状態で毒打撃を受けても毒にならない
- 毒耐性がある状態で毒ブレスを受けても毒にならない
=> PlayerType::poisoned フィールド変数をPlayerPoison クラスでカプセル化した

src/artifact/fixed-art-generator.cpp, src/birth/game-play-initializer.cpp, src/combat/shoot.cpp, src/floor/fixed-map-generator.cpp, src/floor/floor-changer.cpp, src/floor/floor-object.cpp, src/floor/floor-streams.cpp, src/floor/floor-util.cpp, src/grid/object-placer.cpp, src/knowledge/knowledge-items.cpp, src/load/item/item-loader-base.cpp, src/monster-floor/monster-death.cpp, src/monster-floor/special-death-switcher.cpp, src/object-enchant/item-magic-applier.cpp, src/save/save.cpp, src/spell-kind/spells-floor.cpp, src/spell/spells-object.cpp, src/system/artifact-type-definition.h, src/wizard/wizard-item-modifier.cpp
=> artifact_type のmax_num を廃止し、cur_num をbool型にしてis_generated に改名した

src/artifact/fixed-art-generator.cpp, src/floor/fixed-map-generator.cpp, src/monster-floor/monster-death.cpp, src/monster-floor/special-death-switcher.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp
掲題の通りです
但し疑義があるので一旦ドラフトにします
次のコメントを基に方針決めを行いたいです
よろしくお願いします
=> create_named_art() の中でArtifactType::is_generated をtrueにするよう設計を変えた

src/knowledge/knowledge-items.cpp
std::map<T, bool> は std::set<T> で必要十分。
ちょっとしたリファクタリングシリーズ。先日のレビュー中に見かけたやつ。
そもそも自分が過去にC_MAKE/C_KILLをなくすリファクタリングの際に思考停止でstd::vector<bool>にしてたのだが、その時点でstd::setにするべきだった。
=> [Refactor] 既知のアーティファクト抽出処理

src/combat/shoot.cpp, src/object-use/throw-execution.cpp, src/object/object-info.cpp, src/object/object-info.h, src/object/object-kind.cpp, src/object/object-kind.h, src/system/object-type-definition.cpp, src/system/object-type-definition.h, src/view/display-inventory.cpp, src/view/display-map.cpp, src/view/display-player.cpp, src/view/display-store.cpp, src/window/display-sub-windows.cpp, src/window/main-window-equipments.cpp
=> object_char() をObjectType::get_symbol() に、object_attr() をObjectType::get_color() に変えた

src/monster-floor/monster-death.cpp
#2635 を肯定的に解決しました
詳細はコミットログをご参照下さい
=> 固定アーティファクトドロップ処理の改善

src/flavor/flavor-describer.cpp, src/flavor/flavor-util.cpp, src/flavor/tval-description-switcher.cpp, src/floor/floor-events.cpp, src/inventory/recharge-processor.cpp, src/load/old/item-loader-savefile50.cpp, src/object-enchant/others/apply-magic-others.cpp, src/object-hook/hook-expendable.cpp, src/object/object-broken.cpp, src/object/object-kind.h, src/object/object-stack.cpp, src/object/object-value.cpp, src/racial/racial-android.cpp, src/store/store-util.cpp, src/system/object-type-definition.cpp
掲題の通りです
変更が小さいのでチケットはありません
ご確認下さい
=> object_kind 構造体をクラス化するための準備として、まずはヘッダ依存性を減らした

src/cmd-visual/cmd-visuals.cpp, src/flavor/object-flavor.cpp, src/flavor/object-flavor.h, src/knowledge/knowledge-experiences.cpp, src/knowledge/knowledge-items.cpp, src/wizard/wizard-special-process.cpp
一箇所describe\_flavor() のせいでstringを直接使えず切り替えている箇所がありますが、 #2604 で対応します
ご確認下さい
=> strip_name() のシグネチャを変えた

lib/edit/d_info.txt
些細な表記ミスなのでIssueはなし。むしろ今までなぜ気づかなかった。
=> [Fix] d_info.txtのWブロック表記解説がおかしかったので修正。

src/io-dump/character-dump.cpp, src/knowledge/knowledge-quests.cpp, src/knowledge/knowledge-uniques.cpp, src/util/string-processor.cpp, src/util/string-processor.h, src/wizard/monster-info-spoiler.cpp
=> [Feature] キャラクタダンプなどで長いモンスター名を折り返し表示する

src/mind/monk-attack.cpp, src/monster-race/monster-race.cpp, src/monster/monster-processor-util.cpp, src/monster/monster-processor-util.h, src/monster/monster-processor.cpp, src/mspell/mspell-judgement.cpp, src/player-status/player-speed.cpp, src/spell-kind/spells-sight.cpp, src/system/gamevalue.h, src/system/monster-type-definition.cpp, src/system/monster-type-definition.h, src/view/display-lore.cpp, src/view/display-player-middle.cpp, src/window/main-window-stat-poster.cpp, src/wizard/monster-info-spoiler.cpp
掲題の通りです
#2647 の漏れ作業みたいなものなので個別チケットはありません
ご確認下さい
=> decide_mosnter_speed() をオブジェクトメソッド「monster_type::get_riding_speed()」にした

lib/edit/k_info.txt, src/info-reader/kind-reader.cpp, src/system/baseitem-info-definition.h
掲題の通りです
起動時の処理も問題なく通りました
ご確認下さい
=> k_info.txt から使われていないフィールドを除外した

src/wizard/wizard-game-modifier.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp
ひとまず見て思いついたものを。Issueは閉じず継続し続ける。
=> ウィザードモード一部の数値入力にget_value()適用

src/core/asking-player.cpp, src/core/asking-player.h
=> 現askfor() を廃止し、askfor_aux() に統合した

src/birth/history-generator.cpp
=> decide_social_class() のシグネチャを、std::stringを返すように書き換えた

src/wizard/wizard-special-process.cpp
=> ウィザードモードの全回復で減速と恐怖にも対応した

src/blue-magic/blue-magic-caster.cpp, src/cmd-action/cmd-mane.cpp, src/cmd-item/cmd-eat.cpp, src/inventory/inventory-curse.cpp, src/mind/mind-mindcrafter.cpp, src/monster-attack/monster-attack-status.cpp, src/mutation/mutation-processor.cpp, src/object-activation/activation-others.cpp, src/object-activation/activation-resistance.cpp, src/object-activation/activation-switcher.cpp, src/object-use/quaff/quaff-effects.cpp, src/racial/racial-switcher.cpp, src/realm/realm-crusade.cpp, src/realm/realm-demon.cpp, src/realm/realm-hissatsu.cpp, src/realm/realm-nature.cpp, src/realm/realm-song.cpp, src/specific-object/blade-turner.cpp, src/spell/spells-staff-only.cpp, src/spell/spells-status.cpp, src/status/bad-status-setter.cpp, src/status/bad-status-setter.h, src/status/shape-changer.cpp, src/wizard/wizard-special-process.cpp
掲題の通りで、hoge() をset\_hoge() に変えました
ご確認下さい
=> BadStatusSetter のメソッド名を調整した

src/floor/floor-leaver.cpp, src/floor/floor-leaver.h, src/wizard/wizard-special-process.cpp
掲題の通りです
たまたま見かけた「1箇所からしか参照されていないグローバル関数」をファイルスコープにしたものです
ご確認下さい
=> jump_floor() 関数を floor_leaver.cpp/h からwizard-special-process.cpp/h に移した

lib/file/news.txt, lib/file/news_j.txt, lib/help/faq.txt, lib/help/general.txt, lib/help/jgeneral.txt, readme.md
=> ヘルプやニュース類の古すぎる情報を変更、削除

src/artifact/fixed-art-generator.cpp, src/info-reader/artifact-reader.cpp, src/info-reader/general-parser.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-quests.cpp, src/object-hook/hook-quest.cpp, src/spell/spells-object.cpp, src/store/rumor.cpp, src/system/artifact-type-definition.cpp, src/system/artifact-type-definition.h, src/util/sort.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp
掲題の通りです、ご確認下さい
(ObjectType::tval/sval との比較が不格好ですが、これは別チケットで直します)
=> ArtifactType のtval/sval をBaseitemKey に差し替えた

src/artifact/random-art-generator.cpp, src/flavor/flavor-util.h, src/flavor/object-flavor.cpp, src/info-reader/baseitem-reader.cpp, src/io/interpret-pref-file.cpp, src/knowledge/knowledge-experiences.cpp, src/knowledge/knowledge-items.cpp, src/load/item/item-loader-base.cpp, src/load/old/item-loader-savefile50.cpp, src/market/building-craft-fix.cpp, src/market/building-recharger.cpp, src/mind/mind-mage.cpp, src/monster-attack/monster-eating.cpp, src/object-enchant/protector/apply-magic-armor.cpp, src/object-enchant/protector/apply-magic-soft-armor.cpp, src/object/object-broken.cpp, src/object/object-kind-hook.cpp, src/object/object-kind-hook.h, src/spell-kind/magic-item-recharger.cpp, src/spell/spells-object.cpp, src/system/baseitem-info-definition.cpp, src/system/baseitem-info-definition.h, src/system/object-type-definition.cpp, src/wizard/items-spoiler.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp, src/world/world-object.cpp
掲題の通りです
本体作業後、関連する一部処理のリファクタリングもついでに行いました
ご確認下さい
=> BaseitemInfo::tval/sval をBaseitemKey に差し替えた

src/window/display-sub-windows.cpp
[【QoL向上】視界内のモンスター一覧表示に起きているモンスターの数を追加する](https://github.com/hengband/hengband/issues/2796)
↑issueで挙げた対応のpull reqになります。
- 今回の修正でリストアップに必要なデータの構築と描画を別々のforループで行うようにしました。その影響で変更量が多くなったので、差支えありそうなら従来の処理ベースの実装に戻します
- `print_monster_line` 関数内で `MonsterEntity` が `MonsterConstantFlagType::KAGE` を持っているかどうかをチェックしているが、この手のフラグは `MonsterRaceInfo` が持った方が良いのではと思った（状況によって一時的にこのフラグを持つことがあり得るから `MonsterEntity` が持つ作りになっている？）
=> [Feature]モンスター一覧に起きているモンスター数を表示するようにした

src/flavor/flavor-describer.cpp, src/system/baseitem-info.cpp
掲題の通りです
スリングとショートボウで正しく修正されていることを確認しました
ご確認下さい
=> 矢弾のダメージが表記されない不具合を修正した

src/floor/wild.cpp
掲題の通りです
たまたま目についたものなのでチケットはありません
ご確認下さい
=> wild.cpp において、使われていない型エイリアスを削除し、ファイルの中途半端な行で宣言されている構造体やファイルスコープグローバル変数の定義を上に寄せた

src/core/stuff-handler.cpp, src/system/player-type-definition.h, src/view/object-describer.cpp, src/view/object-describer.h, src/window/display-sub-windows.cpp
=> displey_koff() が呼ばれる前と関数本体の両方でベースアイテムIDの有無チェックをしていたので後者に統一した

src/flavor/flavor-describer.cpp, src/flavor/flavor-util.h, src/object-hook/hook-quest.cpp, src/object-hook/hook-quest.h, src/player/player-status.cpp, src/player/player-status.h
箱の状態、武器のダイス目、弓の倍率、命中/ダメージ修正の記述関数までリファクタリング。
#2865 の続き。
呼び出している関数の引数で適切に const が付いていないものがあったので合わせて修正しています。
=> [Refactor] describe_flavor (1/n)

src/view/display-player-middle.cpp
=> 弓を装備せずにキャラクタ情報を表示するとクラッシュする不具合を修正した

src/combat/shoot.cpp, src/system/baseitem-info.cpp, src/system/baseitem-info.h, src/system/item-entity.cpp, src/system/item-entity.h, src/view/display-player-middle.cpp
掲題の通りです
#2898 と併せてコードを一部共通化しました (bow\_magnification とかも含めて統合したいですがこのPRでは見送り)
ご確認下さい
=> 弓を装備していない状態でアイテムを投げるとクラッシュする不具合を修正した

src/flavor/flavor-describer.cpp
矢弾および鉄くさびのダメージ詳細表示、アーマークラスの表示までリファクタリング。
#2865 の続き。
なお、クリティカル率の表示での計算で弓の命中ボーナスを足す時に弓の鑑定状態ではなく矢弾の鑑定状態を見ているというバグらしきコードがあったので弓の鑑定状態を見るようにしています。
=> [Refactor] describe_flavor (2/n)

src/flavor/flavor-describer.cpp
杖/魔法棒/ロッドの充填状態、pval、光源の残りターン数、発動アイテムの充填中表示をリファクタリング。
#2865 の続き。
=> [Refactor] describe_flavor (3/n)

src/info-reader/baseitem-reader.cpp, src/knowledge/knowledge-items.cpp, src/main/game-data-initializer.cpp, src/system/baseitem-info.h, src/wizard/items-spoiler.cpp
掲題の通りです
ついでに配列なのに単数形だったのと、変数の意味が通りにくかったので変えました
ご確認下さい
=> BasitemInfo::locale/chance の取り扱いを改善した

src/artifact/random-art-characteristics.cpp, src/artifact/random-art-characteristics.h, src/artifact/random-art-generator.cpp
掲題の通りです
ついでにItemEntity の引数もポインタからconst参照に変えました
ご確認下さい
=> get_random_name() の戻り値をvoidからstd::string に変え、char * の引数を削除した

src/io/record-play-movie.cpp
掲題のコードはGitHub Actions だとシフトJISが扱えず、そのプリプロ内でエラーになっていました
修正したのでご確認下さい
=> record-play-movie.cpp のコンパイルエラーを修正した

src/locale/japanese.cpp, src/locale/japanese.h, src/term/screen-processor.cpp, src/util/buffer-shaper.cpp
=> shape_buffer で使用している is_kinsoku 関数を c_roff の折り返し表示にも適用する

src/action/mutation-execution.cpp, src/cmd-action/cmd-pet.cpp, src/effect/effect-monster.cpp, src/effect/spells-effect-util.h, src/floor/floor-changer.cpp, src/floor/floor-leaver.cpp, src/io-dump/character-dump.cpp, src/load/old/load-v1-5-0.cpp, src/load/old/monster-loader-savefile50.cpp, src/monster-floor/monster-death.cpp, src/monster-floor/one-monster-placer.cpp, src/monster/monster-compaction.cpp, src/monster/monster-describer.cpp, src/monster/monster-processor.cpp, src/save/monster-writer.cpp, src/specific-object/monster-ball.cpp, src/spell-kind/earthquake.cpp, src/spell-kind/spells-floor.cpp, src/spell-kind/spells-genocide.cpp, src/spell-kind/spells-pet.cpp, src/spell-kind/spells-world.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h, src/util/sort.cpp, src/wizard/wizard-special-process.cpp
=> [Refactor] MonsterEntity::nickname をquarkインデックスから std::string に変える

src/action/activation-execution.cpp, src/specific-object/monster-ball.cpp, src/specific-object/monster-ball.h
#3002 をやっていて気になったので関連してやっておきました。
- 特に必要なさそうだったので ae_type から切り離す
- ポインタを使用したコードをC++風に書き換え
- 関数名と引数をそれらしく調整
=> [Refactor] モンスターボール発動のソースコード

src/blue-magic/blue-magic-caster.cpp, src/cmd-action/cmd-pet.cpp, src/monster/monster-damage.cpp, src/monster/monster-damage.h, src/player/eldritch-horror.cpp
Tries to address the changes (except for those in monster/monster-describer.cpp) requested in the comments on https://github.com/hengband/hengband/pull/2981 .
=> Cleanup the monster_desc() refactoring.

src/monster/monster-describer.cpp
… resolves https://gith…ub.com/hengband/hengband/issues/3019
=> English: fix compiler errors in monster_desc(); 

src/monster/monster-describer.cpp
掲題の通りです
#2651 の後段として先行作業していた関係上、rebase 祭りになって齟齬が出ているかもしれません
時間も時間なので一旦ドラフトにしておきます
ご確認下さい
=> monster_desc() の整形

src/term/screen-processor.cpp
現状の c_roff 関数のコードがかなり読みづらいのでリファクタリングを行う。
主な変更内容は以下の通り。
- #ifdef JP による分岐の削除
- ラップ処理部分が長いので関数化
- ループをポインタではなくイテレータで行う
C++移行プロジェクトに伴うリファクタリングにつき、Issue無し。
=> [Refactor] c_roff 関数を読みやすくする

src/main-win.cpp, src/main.cpp
#3040 の作業の一部です。
基本的に、画面（機能）ごとに PR を作る予定です。
=> [Feature] タイトル画面をウィンドウの中央に表示する

src/birth/character-builder.cpp
=> [Feature] キャラメイク画面をウィンドウの中央に表示する

src/view/display-scores.cpp
=> [Feature] スコアランキング画面をウィンドウの中央に表示する

Hengband/Hengband/Hengband.vcxproj.filters, src/autopick/autopick-finder.cpp, src/cmd-item/cmd-equipment.cpp, src/combat/shoot.cpp, src/combat/shoot.h, src/flavor/flavor-describer.cpp, src/flavor/flavor-describer.h, src/market/bounty.cpp, src/market/building-craft-fix.cpp, src/mind/mind-priest.cpp, src/monster/monster-describer.cpp, src/window/main-window-equipments.cpp, src/window/main-window-util.cpp
表題の件について、周辺コードの整備を行いました
後々面倒になりそうな箇所の関数切り出しをしたり、char[] をstringに置換する処理等です
ご確認下さい
=> describe_flavor() のシグネチャを変更する準備 その1

lib/edit/MonsterRaceDefinitions.txt
適当に英文までつけて強化してみました。 #1368 案からEVIL抜いています。
=> [Modify] 航海士『ナミ』を原作中盤ほどまでを意識して強化。

src/knowledge/knowledge-inventory.cpp, src/knowledge/knowledge-self.cpp, src/market/building-craft-fix.cpp, src/monster-floor/monster-object.cpp, src/util/string-processor.cpp, src/util/string-processor.h, src/wizard/wizard-spoiler.cpp
表題の件について、周辺コードの整備を行いました
後々面倒になりそうな箇所の関数切り出しをしたり、char[] をstringに置換する処理等です
ご確認下さい
=> describe_flavor() のシグネチャを変更する準備 その2

src/util/buffer-shaper.cpp
Resolves #3110 
日本語と英語がスペースを開けずに繋がった文章で英語部分で折り返しが発生す
ると分割位置がおかしくなる。
例えば「日本語english」のenglishの途中で折り返すと「日本」「語english」
と分割されてしまう。「日本語」「english」と分割されるように修正する。
=> [Fix] shape_buffer関数の文字列分割位置がおかしい

src/object/object-stack.cpp
掲題の通りです
軽いコード整形も一緒に実施しました
ご確認下さい
=> 未鑑定のフェアノールのランプが重なる事象を修正した

src/main-win/main-win-utils.h, src/system/angband.h, src/system/h-basic.h, src/term/z-form.h, src/term/z-term.h, src/term/z-util.h, src/term/z-virt.cpp, src/term/z-virt.h
=> インクルードガードを#pragma once に統一した

src/flavor/named-item-describer.cpp
Resolves https://github.com/hengband/hengband/issues/3153 .
=> English: expand tildes in the base item name

lib/edit/misc.txt, src/birth/character-builder.cpp, src/cmd-io/cmd-dump.cpp, src/core/turn-compensator.cpp, src/floor/fixed-map-generator.cpp, src/floor/floor-town.cpp, src/floor/floor-town.h, src/floor/floor-util.cpp, src/floor/wild.cpp, src/io-dump/character-dump.cpp, src/io-dump/random-art-info-dumper.cpp, src/knowledge/knowledge-inventory.cpp, src/knowledge/knowledge-self.cpp, src/load/quest-loader.cpp, src/load/store-loader.cpp, src/main-win/main-win-music.cpp, src/market/building-initializer.cpp, src/player/process-death.cpp, src/save/save.cpp, src/spell-kind/spells-world.cpp, src/store/black-market.cpp, src/store/cmd-store.cpp, src/store/home.cpp, src/store/rumor.cpp, src/store/store.cpp, src/target/target-describer.cpp
=> misc.txt から町の最大数を削除した

src/cmd-io/cmd-diary.cpp, src/cmd-io/diary-subtitle-table.cpp, src/cmd-io/diary-subtitle-table.h
=> 日記のサブタイトルをconcptr[] からstd::vector<std::string> に変えた

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/monster/horror-descriptions.cpp, src/monster/horror-descriptions.h, src/player/eldritch-horror.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
掲題の通りです
ついでに関連処理を調整しました
ご確認下さい
=> エルドリッチホラーの形容詞テーブルをconcptr[] からvector<string> に変えた

src/io/gf-descriptions.h, src/io/interpret-pref-file.cpp, src/wizard/wizard-spells.cpp
=> named_num::name をconcptr からstd::string に変えた

lib/edit/quests/027_TheOldCatsle.txt, src/knowledge/knowledge-quests.cpp
表題の通りです
ついでにいくつか関連箇所を調整・修正しました
ご確認下さい
=> ダミークエストが表示される不具合を解消した

src/autopick/autopick-describer.cpp, src/autopick/autopick-describer.h, src/autopick/autopick-drawer.cpp, src/autopick/autopick-editor-command.cpp, src/autopick/autopick-editor-util.cpp, src/autopick/autopick-entry.cpp, src/autopick/autopick-entry.h, src/autopick/autopick-finder.cpp, src/autopick/autopick-key-flag-process.h, src/autopick/autopick-matcher.cpp, src/autopick/autopick-matcher.h, src/autopick/autopick-pref-processor.cpp, src/autopick/autopick-registry.cpp, src/autopick/autopick-util.cpp, src/autopick/autopick-util.h, src/cmd-io/cmd-autopick.cpp, src/knowledge/knowledge-autopick.cpp
ちょうどよくautopick\_type のオブジェクトメソッドに繰り込めたので実施しました
ご確認下さい
=> 関数マクロIS_FLG() を削除した

src/term/z-form.cpp, src/term/z-form.h
コメント以外は小規模なりファクタリングのみです
ご確認下さい
=> z-form.cpp/h のコメント等を調整した

src/action/activation-execution.cpp, src/artifact/artifact-info.cpp, src/autopick/autopick-entry.cpp, src/flavor/flavor-util.cpp, src/flavor/named-item-describer.cpp, src/floor/floor-events.cpp, src/info-reader/ego-reader.cpp, src/load/old/load-v1-5-0.cpp, src/object-enchant/object-ego.cpp, src/object-enchant/object-ego.h, src/object-enchant/weapon/apply-magic-sword.cpp, src/object/object-flags.cpp, src/object/object-value-calc.cpp, src/object/object-value.cpp, src/racial/racial-android.cpp, src/system/item-entity.cpp, src/system/item-entity.h, src/wizard/wizard-item-modifier.cpp
掲題の通りです
egos\_info への直接アクセスがほぼなくなりました
ご確認下さい
=> ItemEntity クラスにget_ego() メソッドを追加した

src/io/files-util.cpp, src/io/files-util.h, src/main-win.cpp, src/main-win/main-win-file-utils.cpp, src/main-win/main-win-file-utils.h, src/main-win/main-win-utils.cpp, src/main-win/main-win-utils.h, src/main.cpp, src/main/angband-initializer.cpp, src/main/angband-initializer.h, src/system/h-config.h
掲題の通りです
Linux側のコードも一部変更しましたのでご注意下さい
α79に入るのが理想ですが、入らなくても構いません
=> path_build() に関連する関数の入出力をpath に変えた

src/main-win.cpp
=> main-win.cpp で、prefファイルの読み書きが正常に行われない事象を修正した

src/main/angband-initializer.cpp
STLのstd::filesystemを使用し、古いデバッグ用セーブファイルの削除のコードをシステムに依存しないようにする。
せっかくstd::filesystemを使用する潮流が来ているので、システム依存コードを除去してみました。
=> [Refactor] 古いデバッグ用セーブファイルの削除

src/autopick/autopick-matcher.cpp
Discord でのデータ提供・調査ありがとうございました
修正しましたのでご確認下さい
=> picktypeで保護されるはずのアイテムが破壊される事象を修正した

src/main/info-initializer.cpp
=> str_split() の戻り値をコピーで受け取っていたので参照に受け変えた

src/main/angband-initializer.cpp
デバッグセーブ用のディレクトリが存在しない場合、std::directory_iteratorのコンストラクタが例外を送出するためクラッシュする。
後のstd::removeと同様に、例外を送出せずエラーコードを引数で返すコンストラクタのオーバーロードを使用するよう修正する。
=> [Fix] デバッグセーブ用ディレクトリが存在しない場合にクラッシュする

src/autopick/autopick-matcher.cpp
=> 自動拾いで兜を拾えない問題を修正した

src/flavor/flavor-describer.cpp, src/flavor/flavor-describer.h, src/knowledge/knowledge-inventory.cpp, src/view/display-store.cpp
=> 特定パターンの文字列を持ったアイテムを店で売るとクラッシュする不具合を解消した

src/wizard/items-spoiler.cpp
Resolves #3273
Resolves #2929
describe_flavorのリファクタリングの際に、アイテム名称用のバッファにアイテム名が書き込まれなくなったのが原因であるが、この際なので色々な事をやりすぎている関数describe_baseitem_info()を分割して対応する。
=> [Fix] スポイラーのオブジェクト一覧(obj-desc.txt)の内容がおかしい

src/main-win.cpp, src/main-win/graphics-win.cpp, src/main-win/graphics-win.h, src/main-win/main-win-bg.cpp, src/main-win/main-win-bg.h, src/main-win/main-win-utils.cpp, src/main-win/main-win-utils.h
#3245 の後続PRです
本件の修正はWindows 環境のみに影響を与えます
=> path_build() のシグネチャを変える準備 その4

src/main-win.cpp
こちらでコメント頂いた通りです
ご確認下さい
https://github.com/hengband/hengband/pull/3246#discussion_r1186765137
=> 背景画像設定をiniファイルへ書き込む際の判定が反転していた事象を修正した

src/cmd-io/cmd-diary.cpp, src/cmd-io/cmd-knowledge.cpp, src/io/record-play-movie.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp
=> [Feature] 現在の知識の確認画面および記録の設定画面をウィンドウ中央に表示する

src/floor/floor-events.cpp, src/mind/mind-sniper.cpp, src/mind/mind-weaponsmith.cpp, src/status/action-setter.cpp, src/status/sight-setter.cpp
=> 画面再描画フラグの更新準備 コピペコードの低減

src/cmd-io/cmd-diary.cpp, src/core/game-closer.cpp, src/core/game-play.cpp, src/core/scores.cpp, src/floor/floor-save.cpp, src/io/files-util.cpp, src/io/record-play-movie.cpp, src/io/record-play-movie.h, src/load/floor-loader.cpp, src/load/load.cpp, src/main-win.cpp, src/main-x11.cpp, src/main/angband-initializer.cpp, src/save/floor-writer.cpp, src/save/save.cpp, src/util/angband-files.cpp, src/util/angband-files.h
=> fd_hoge() の引数をstring_view からpath に変えた

src/cmd-building/cmd-building.cpp, src/cmd-io/cmd-dump.cpp, src/core/game-play.cpp, src/core/turn-compensator.cpp, src/core/window-redrawer.cpp, src/floor/floor-town.h, src/floor/floor-util.cpp, src/floor/floor-util.h, src/floor/wild.cpp, src/info-reader/general-parser.cpp, src/io-dump/character-dump.cpp, src/io-dump/random-art-info-dumper.cpp, src/knowledge/knowledge-inventory.cpp, src/knowledge/knowledge-self.cpp, src/load/store-loader.cpp, src/market/building-initializer.cpp, src/player/process-death.cpp, src/save/save.cpp, src/spell-kind/spells-world.cpp, src/store/black-market.cpp, src/store/cmd-store.cpp, src/store/home.cpp, src/store/rumor.cpp, src/store/store.cpp, src/system/building-type-definition.cpp, src/system/building-type-definition.h, src/target/target-describer.cpp, src/view/display-player.cpp
詳細はチケットをご参照下さい
起動処理及びセーブデータ読み込みには成功しています
=> town_type の調整

src/main/angband-initializer.cpp, src/main/game-data-initializer.cpp, src/main/game-data-initializer.h
=> init_alloc() をinit_monsters_alloc() とinit_items_alloc() に分割した

src/action/racial-execution.cpp, src/birth/birth-stat.cpp, src/birth/quick-start.h, src/spell/spells-status.cpp, src/status/base-status.cpp, src/system/h-type.h, src/system/player-type-definition.h, src/wizard/wizard-special-process.cpp
掲題の通りです
特に型での見分けが必須と思われる箇所は見つかりませんでした
ご確認下さい
=> BASE_STATUS 型エイリアスを削除した

src/cmd-action/cmd-spell.cpp, src/cmd-item/cmd-magiceat.cpp, src/cmd-item/cmd-usestaff.cpp, src/cmd-item/cmd-usestaff.h, src/cmd-item/cmd-zaprod.cpp, src/cmd-item/cmd-zaprod.h, src/cmd-item/cmd-zapwand.cpp, src/cmd-item/cmd-zapwand.h, src/mind/mind-archer.cpp, src/mind/mind-chaos-warrior.cpp, src/monster-floor/monster-death-util.cpp, src/object-enchant/others/apply-magic-others.cpp, src/system/h-type.h, src/system/system-variables.cpp, src/system/system-variables.h
=> OBJECT_SUBTYPE_VALUE 型エイリアスを削除した

src/cmd-io/cmd-diary.cpp
Resolves #3310 
記録の表示でランダムなサブタイトルを決める時にrandint0を呼んでいるため、ゲームの進行に使用する乱数シードを消費してしまっている。
ゲームの進行に関係ない乱数生成には独立した乱数シードのRand_externalを使用すべきなので、そのように修正する。
=> [Fix] 記録の表示でゲームの乱数シードを消費してしまう

configure.ac, lib/edit/BaseitemDefinitions.txt, lib/file/Makefile.am, lib/file/books/Makefile.am
=> macOS 環境で正しくlib/file/books/ を含むリポジトリをコンパイルできるようにした

src/artifact/random-art-misc.cpp, src/avatar/avatar.cpp, src/cmd-item/cmd-zapwand.cpp, src/effect/effect-player-resist-hurt.cpp, src/mind/mind-chaos-warrior.cpp, src/monster-attack/monster-attack-describer.cpp, src/object-enchant/object-boost.cpp, src/realm/realm-arcane.cpp, src/spell-kind/earthquake.cpp, src/spell-kind/spells-equipment.cpp, src/term/gameterm.cpp, src/view/display-map.cpp
#3296 の追加修正。
get_random_virtue()の処理に関しては等確率ではないので ProbabilityTable クラスを使用して書き換え。
=> [Refactor] switch (randint1(x)) のパターンを rand_choice で書き換え

src/effect/effect-player-resist-hurt.cpp, src/effect/effect-player-resist-hurt.h, src/player/player-damage.cpp, src/player/player-damage.h
掲題の通りです
ほぼシグネチャだけの変更なのでチケットはありません
ご確認下さい
=> take_hit_mon() 及び関連する関数群の引数をconcptr からstring_view に変えた

src/cmd-io/cmd-diary.cpp, src/mspell/summon-checker.cpp, src/player-base/player-class.cpp, src/player-base/player-class.h, src/player-base/player-race.cpp, src/player-base/player-race.h, src/player-info/race-info.cpp, src/player-info/race-info.h
掲題の通りです
#3318 でコメントした件です
ご確認下さい
=> PlayerRace/PlayerClass にだけ依存する処理をそれぞれのオブジェクトメソッドに繰り込んだ

src/effect/effect-player-resist-hurt.cpp, src/monster-attack/monster-attack-status.cpp, src/monster-attack/monster-attack-status.h, src/monster-attack/monster-attack-switcher.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h
=> アビリティスコア減少処理をdecrease_ability_*() にまとめた

src/birth/auto-roller.cpp, src/birth/birth-select-realm.cpp, src/cmd-action/cmd-pet.cpp, src/cmd-io/cmd-autopick.cpp, src/core/visuals-reseter.cpp, src/hpmp/hp-mp-processor.cpp, src/inventory/inventory-curse.cpp, src/io/input-key-requester.cpp, src/io/read-pref-file.cpp, src/main/angband-initializer.cpp, src/market/building-craft-weapon.cpp, src/mspell/mspell-special.cpp, src/player/patron.cpp, src/spell-kind/earthquake.cpp, src/spell-kind/spells-genocide.cpp, src/spell-kind/spells-sight.cpp, src/view/display-characteristic.cpp, src/view/display-lore.cpp, src/view/display-store.cpp, src/window/display-sub-windows.cpp, src/window/main-window-stat-poster.cpp, src/wizard/cmd-wizard.cpp, src/wizard/wizard-game-modifier.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-player-modifier.cpp, src/wizard/wizard-special-process.cpp
あちこちの引数をstring\_view へ変えていますが、その時にconcptr を引数として入れていた頃の名残コードを見つけて削除しました
これが全部ではないですがある程度削れたと思います
ご確認下さい
=> 呼ぶ必要のない.data() を削除した

src/cmd-action/cmd-shoot.cpp, src/combat/shoot.cpp, src/core/player-processor.cpp, src/io/input-key-processor.cpp, src/load/player-class-specific-data-loader.cpp, src/load/player-class-specific-data-loader.h, src/load/player-info-loader.cpp, src/mind/mind-sniper.cpp, src/monster/monster-update.cpp, src/player-base/player-class.cpp, src/player-info/class-specific-data.h, src/player-info/sniper-data-type.h, src/player/player-status.cpp, src/save/player-class-specific-data-writer.cpp, src/save/player-class-specific-data-writer.h, src/window/main-window-stat-poster.cpp
掲題の通りです
#3315 の関連で掲題の構造体だけを引数に取る関数が出てきたので、別チケットにて調整したものです
ご確認下さい
=> sniper_data_type を構造体からクラスへ変更し、メソッドを追加した

src/io/input-key-requester.cpp, src/io/input-key-requester.h
誰も使わないようなヘンテコ機能なので廃止しました
詳細はチケットをご覧下さい
=> ペットの名前に依存して全コマンドに確認を求められる仕様を削除した

src/autopick/autopick-describer.cpp, src/autopick/autopick-reader-writer.cpp, src/birth/history-editor.cpp, src/birth/history-generator.cpp, src/cmd-action/cmd-pet.cpp, src/cmd-item/cmd-item.cpp, src/core/scores.cpp, src/effect/effect-monster-psi.cpp, src/effect/effect-monster-spirit.cpp, src/effect/effect-monster.cpp, src/effect/effect-player.cpp, src/inventory/player-inventory.cpp, src/io/read-pref-file.cpp, src/melee/melee-postprocess.cpp, src/melee/melee-spell.cpp, src/melee/monster-attack-monster.cpp, src/monster-attack/monster-attack-player.cpp, src/mspell/mspell-attack.cpp, src/player-attack/attack-chaos-effect.cpp, src/player-attack/player-attack.cpp, src/player/player-damage.cpp, src/player/process-death.cpp, src/spell-kind/spells-perception.cpp, src/store/purchase-order.cpp, src/util/string-processor.cpp, src/util/string-processor.h, src/view/display-self-info.cpp, src/window/main-window-left-frame.cpp, src/wizard/artifact-analyzer.cpp
angband\_strcpy() に含まれていたmemcpy() を削除しました
これに伴い、(ついでにstrcatも含めて)引数をstring\_view へ変え、更に関数を呼んでいるところを調べてstring::data() を呼んでいる箇所を削除しました
ご確認下さい
(肝心のEnglish-Debug がVSのバグで動かないためCIに任せます)
=> memcpy() を1箇所削除した

src/game-option/option-flags.cpp, src/game-option/option-flags.h, src/load/option-loader.cpp, src/main/game-data-initializer.cpp, src/save/info-writer.cpp
g_window_flags だけ FlagGroup なのは片手落ちなので、g_window_masks も同じ型としました。
単体のIssueは立てず、 #3287 の一部とします。
=> [Refactor] g_window_masks の型を g_window_flags に合わせる

src/floor/floor-generator.cpp, src/floor/floor-util.cpp, src/grid/grid.cpp, src/main-win.cpp, src/main-win/main-win-utils.cpp, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h
掲題の通りです
grid\_type の配列とWinAPI 関係の構造体の2つでした
ご確認下さい
=> memset() を削除した

src/grid/grid.cpp
VS2022のサジェストに従うとクラッシュするという切ない目に遭うことが分かりました
修正したのでご確認下さい
=> ダングリング参照に陥る不具合を修正した

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, Hengband/Hengband/packages.config, src/autopick/autopick-util.h, src/birth/auto-roller.cpp, src/cmd-item/cmd-destroy.cpp, src/spell-realm/spells-craft.cpp, src/target/target-describer.cpp, src/term/z-term.cpp
MS Code Quality Analyzers を使って出てきた警告を潰しました
特に一箇所 (最新コミット)潜在的なクラッシュの危険性があったので効果はあったと思います
ご確認下さい
=> 静的解析警告の解消 その1

src/autopick/autopick-editor-command.cpp, src/birth/birth-util.cpp, src/cmd-building/cmd-building.cpp, src/cmd-io/cmd-diary.cpp, src/cmd-io/cmd-gameoption.cpp, src/cmd-io/cmd-help.cpp, src/core/show-file.cpp, src/core/show-file.h, src/knowledge/knowledge-autopick.cpp, src/knowledge/knowledge-experiences.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-inventory.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp, src/knowledge/knowledge-mutations.cpp, src/knowledge/knowledge-quests.cpp, src/knowledge/knowledge-self.cpp, src/knowledge/knowledge-uniques.cpp, src/market/arena.cpp, src/market/play-gamble.cpp, src/object-use/read/parchment-read-executor.cpp
掲題の通りです
静的解析との兼ね合いで先にやっておいた方が良さそうだと判断し実施しました
更に、what 引数はnullptr になっている箇所が相当数見受けられたのでオプション引数にしました
ご確認下さい
=> show_file() の引数をchar* からstring_view に変えた

src/birth/game-play-initializer.cpp, src/cmd-action/cmd-others.cpp, src/effect/spells-effect-util.cpp, src/effect/spells-effect-util.h, src/inventory/inventory-util.cpp, src/io-dump/character-dump.cpp, src/knowledge/knowledge-uniques.cpp, src/load/player-info-loader.cpp, src/lore/lore-util.cpp, src/lore/lore-util.h, src/lore/monster-lore.cpp, src/market/building-initializer.cpp, src/melee/melee-postprocess.cpp, src/monster-floor/monster-generator.cpp, src/object/item-tester-hooker.h, src/player/player-damage.cpp, src/room/rooms-city.cpp, src/save/player-writer.cpp, src/system/building-type-definition.cpp, src/system/building-type-definition.h, src/system/player-type-definition.h, src/target/grid-selector.cpp
主な作業：C言語時代に構造体の初期化関数としてinitialize\_hoge() を作っていましたが、C++ への変換に伴ってコンストラクタに書き換えました
ご確認下さい
=> 静的解析警告の解消 その3

src/autopick/autopick-editor-util.cpp, src/birth/birth-select-personality.cpp, src/cmd-action/cmd-hissatsu.cpp, src/dungeon/quest-completion-checker.cpp, src/io/record-play-movie.cpp, src/main-win.cpp, src/market/building-craft-armor.cpp, src/market/building-craft-armor.h, src/mind/mind-elementalist.cpp, src/mind/mind-power-getter.cpp, src/mind/mind-power-getter.h, src/mind/mind-samurai.cpp, src/monster/monster-processor-util.cpp, src/monster/monster-processor-util.h, src/room/space-finder.cpp, src/status/bad-status-setter.cpp, src/target/target-preparation.cpp, src/timed-effect/player-cut.cpp, src/timed-effect/player-cut.h, src/wizard/spoiler-util.h
構造体初期化、ぬるぽ回避等です
これで小型の警告は全て解消しました
ご確認下さい
=> 静的解析警告の解消 その5

doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.0.85

src/mspell/mspell-util.cpp, src/view/display-messages.cpp, src/view/display-messages.h
=> msg_format(string_view,...) のオーバーロードを削除した

src/io/report.cpp
Cの時代に独自実装した伸長バッファをstd::vectorに置き換えることでmallocを
使用しないようにする。
#3419 の一環
[テスト用スコアサーバ](https://mars.kmc.gr.jp/~dis/heng_score_test/score_ranking.php?&sort=newcome)にてスコア送信できることを確認済みです。（Test1は失敗）
=> [Refactor] report.cpp

src/io/record-play-movie.cpp
プレイムービー再生機能で使用するリングバッファの領域をstd::vectorに変更することでmallocを使用しないようにする。
#3419 の一環
=> [Refactor] record-play-movie.cpp

src/io/record-play-movie.cpp
https://github.com/hengband/hengband/pull/3426#pullrequestreview-1476955323 で指摘のあった件の修正です。
小さなtypo修正なのでIssue無し。
=> [Fix] ムービーファイルの上書き確認メッセージにゴミが入っている

src/main-x11.cpp
Resolves #3439 
以前よりXftを有効にしたX11版でカーソルやドラッグした選択範囲の矩形領域が塗りつぶされてしまい下の文字がわからなくなるという問題がある。
非常に悪いユーザ体験なので、カーソルは下の文字が反転表示されるように、選択範囲は中の領域を塗りつぶさず枠だけの表示をするように修正する。
macOSでの動作を確認していただきたいので、@tanguband 氏をレビューアに割り当てさせていただきます。
劇的ビフォーアフター
半角カーソル
全角カーソル
領域選択
=> [Feature] Xft/X11版でカーソルおよび選択領域の下の文字をわかるようにする

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/util/finalizer.h, src/wizard/wizard-special-process.cpp
Resolves #3462 
Resolves #3463 
詳しくは上記の Issue をご参照ください。
=> [Fix] デバッグコマンドのステータス変更が反映されない

hengband.spec
- バージョンを3.0.0.86に更新しました。
- Coprでの配布を開始しました。 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/build/6113362/
=> Update the version in hengband.spec

src/wizard/wizard-special-process.cpp
Resolves #3458
ステータス変更のデバッグコマンド '^a e' で最初に全ステータスをMAXにするかどうか訪ね、yを押した場合は一発で全ステータスをMAXにする。
nを押した場合はこれまで通り1つ1つステータスを入力する。
入力範囲が制限されたことで1個1個個別に最大値を入力するのが面倒になった問題も一応これで回避できるはず。
ちなみにゴールドはMAXという概念がないようなので、999999999ゴールドにします。（INT_MAXを超えると普通にオーバーフローする模様。通常プレイでそこまで稼ぐのは不可能だとは思われますが。）
=> [Feature] デバッグコマンドで一発で全ステータスをMAXにする機能

src/player/process-name.cpp, src/wizard/wizard-item-modifier.cpp
=> #3469 に混入した不具合修正

src/blue-magic/learnt-power-getter.cpp, src/cmd-action/cmd-hissatsu.cpp, src/cmd-action/cmd-mane.cpp, src/cmd-action/cmd-pet.cpp, src/cmd-action/cmd-racial.cpp, src/cmd-action/cmd-spell.cpp, src/cmd-io/cmd-floor.cpp, src/cmd-io/cmd-lore.cpp, src/cmd-item/cmd-magiceat.cpp, src/core/asking-player.cpp, src/core/asking-player.h, src/io/input-key-requester.cpp, src/market/building-monster.cpp, src/mind/mind-archer.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-power-getter.cpp, src/mind/mind-sniper.cpp, src/mind/mind-weaponsmith.cpp, src/mutation/mutation-processor.cpp, src/racial/racial-util.h, src/spell-kind/spells-genocide.cpp, src/spell-realm/spells-hex.cpp, src/store/store.cpp, src/target/target-getter.cpp, src/wizard/cmd-wizard.cpp, src/wizard/wizard-game-modifier.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-player-modifier.cpp, src/wizard/wizard-special-process.cpp
掲題の通りです
数が多くて全部は確認できていませんが、デバッグコマンドやアイテムで色々聞かれる箇所は確認しました
ご確認下さい
なおoptional の扱いについてはDiscord での議論前にコミットしたので今までのやり方を踏襲しています
(後でまとめて実施予定)
=> input_command() のシグネチャを変更した

src/realm/realm-hex.cpp
=> [Fix] #3479 での修正漏れ

src/floor/wild.cpp
=> 乱数ジェネレータのコピーで静的解析警告が出ていたので対処した

src/io-dump/random-art-info-dumper.cpp, src/wizard/artifact-analyzer.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/fixed-artifacts-spoiler.h, src/wizard/spoiler-table.cpp, src/wizard/spoiler-table.h, src/wizard/spoiler-util.cpp, src/wizard/spoiler-util.h
#3228 の後続作業です
アーティファクトのスポイラーが正常に出力できたのを確認済です
ご確認下さい
=> stat_flags_desc とpval_flags1_desc を生配列からvector に変えた

src/store/museum.cpp, src/store/purchase-order.cpp, src/store/store.cpp, src/store/store.h
asking-player.cpp/h に定義されていなかった、ユーザ入力関数の引数/戻り値差し替えです
買う時・調べる時・展示する時 確認済です
ご確認下さい
=> get_stock() をinput_stock() に変え、シグネチャを差し替えた

src/cmd-action/cmd-others.cpp
=> 勝利メッセージ確定のyes/no が反転していた不具合を修正した

src/io-dump/random-art-info-dumper.cpp, src/object/object-info.cpp, src/object/object-info.h, src/perception/identification.cpp, src/wizard/artifact-analyzer.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/fixed-artifacts-spoiler.h, src/wizard/spoiler-table.cpp, src/wizard/spoiler-table.h, src/wizard/spoiler-util.h
掲題の通りです
かなり見通しが立ちやすくなったと思います
作業前と同じスポイラーが出力されるのを確認済です
ご確認下さい
=> obj_desc_list を構成していた生配列を全てvector とstring に変えた

src/autopick/autopick-finder.cpp, src/birth/history-editor.cpp, src/cmd-action/cmd-mind.cpp, src/cmd-action/cmd-racial.cpp, src/cmd-action/cmd-spell.cpp, src/cmd-item/cmd-magiceat.cpp, src/cmd-visual/cmd-draw.cpp, src/core/show-file.cpp, src/io/signal-handlers.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp, src/main/angband-initializer.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-sniper.cpp, src/mind/mind-weaponsmith.cpp, src/spell-kind/spells-sight.cpp, src/spell-realm/spells-hex.cpp, src/term/screen-processor.cpp, src/term/z-term.cpp, src/term/z-term.h, src/view/display-inventory.cpp, src/view/display-lore.cpp, src/view/display-messages.cpp, src/view/display-player-misc-info.cpp, src/view/object-describer.cpp, src/window/display-sub-windows.cpp, src/wizard/wizard-special-process.cpp
Resolves #3555
もともと横幅256マス以上のウィンドウは想定されていないようですね。
とりあえず term_erase(x, y, 255); で右端まで消去している箇所をすべて対応しておきました。
=> [Fix] 消去時に画面右端までの消去されないことがある 

src/io-dump/random-art-info-dumper.cpp, src/io-dump/random-art-info-dumper.h, src/io/input-key-processor.cpp, src/util/angband-files.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/fixed-artifacts-spoiler.h, src/wizard/items-spoiler.cpp, src/wizard/items-spoiler.h, src/wizard/spoiler-util.cpp, src/wizard/spoiler-util.h, src/wizard/wizard-spoiler.cpp
FILE\* もofstream に切り替えました
修正前後で同じファイルが出力されるのを確認済です
ご確認下さい
=> spoiler_file グローバル変数の使用箇所削減

doxygen/Hengband.doxyfile, hengband.spec, src/system/angband-version.h
* 今回からhengband.specも更新、ログの名義はビルドしていただくwhiteharaさんのまま、日付はリリース当日とておく。
=> [Release] 3.0.0.88-Alpha

lib/edit/MonsterRaceDefinitions.txt
=> サルーインのExpを0→66666に修正

src/player/player-damage.cpp
Resolves https://github.com/hengband/hengband/issues/3583 .
=> English: add colon and space after prompt for last words

lib/edit/MonsterRaceDefinitions.txt
closes #3575
特別ドロップ持ちなのも相俟ってバランスに関しては要チェック
=> 赤チォコヴォLv99を実装

src/view/display-lore.cpp
Resolves https://github.com/hengband/hengband/issues/3599 .
=> English: fix formatting of escorts list in monster lore

src/cmd-action/cmd-mane.cpp
resolves #2079
影響範囲が広いため注意
これで全部網羅しているはず
=> ものまねの範囲指定を全部マスクに移した

src/dungeon/quest.h, src/object/item-tester-hooker.h, src/player/patron.h, src/player/player-status.cpp
VS2022 v17.7.3 で新しく出た警告に対応しました
ご確認下さい
=> コンパイル警告の解消 (特殊コンストラクタ周り)

src/cmd-io/cmd-process-screen.cpp, src/cmd-item/cmd-equipment.cpp, src/cmd-item/cmd-item.cpp, src/cmd-visual/cmd-draw.cpp, src/cmd-visual/cmd-map.cpp, src/core/show-file.cpp, src/core/window-redrawer.cpp, src/floor/object-scanner.cpp, src/io-dump/dump-util.cpp, src/io/record-play-movie.cpp, src/io/report.cpp, src/io/signal-handlers.cpp, src/io/write-diary.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp, src/perception/identification.cpp, src/store/cmd-store.cpp, src/term/screen-processor.cpp, src/util/candidate-selector.cpp, src/view/display-inventory.cpp, src/view/display-player-misc-info.cpp, src/window/display-sub-windows.cpp, src/window/main-window-equipments.cpp, src/window/main-window-left-frame.cpp, src/window/main-window-stat-poster.cpp, src/wizard/cmd-wizard.cpp, src/world/world-turn-processor.cpp
=> コンパイル警告の解消 α90 その2

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/packages.config, src/cmd-io/cmd-floor.cpp, src/grid/grid.cpp, src/io/cursor.cpp, src/mspell/mspell-checker.cpp, src/room/cave-filler.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-realm/spells-hex.cpp, src/spell/range-calc.cpp, src/target/projection-path-calculator.cpp, src/target/target-checker.cpp, src/target/target-setter.cpp, src/util/string-processor.cpp, src/window/display-sub-windows.cpp, src/wizard/items-spoiler.cpp
#3635 とやっていることは同じです
ついでにNuGet の静的解析パッケージを更新しました
ご確認下さい
=> コンパイル警告の解消 (変数キャプチャ)

src/locale/english.cpp
Resolves https://github.com/hengband/hengband/issues/3604 .
=> English: use Homonculi as the plural for Homonculous

src/action/movement-execution.cpp, src/cmd-visual/cmd-visuals.cpp, src/core/visuals-reseter.cpp, src/floor/floor-streams.cpp, src/floor/object-allocator.cpp, src/grid/feature.cpp, src/grid/feature.h, src/grid/grid.cpp, src/grid/trap.cpp, src/info-reader/feature-reader.cpp, src/io/interpret-pref-file.cpp, src/knowledge/knowledge-features.cpp, src/monster/monster-info.cpp, src/player/player-move.cpp, src/room/rooms-builder.cpp, src/room/rooms-city.cpp, src/room/rooms-trap.cpp, src/spell-kind/spells-floor.cpp, src/spell-realm/spells-chaos.cpp, src/store/purchase-order.cpp, src/store/store.cpp, src/store/store.h, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h, src/view/display-map.cpp, src/view/display-store.cpp, src/window/display-sub-windows.cpp, src/wizard/wizard-special-process.cpp, src/world/world-turn-processor.cpp
QuestList と同じくグローバル変数のカプセル化です
ご確認下さい
=> TerrainList クラスを作った

configure.ac, doxygen/Hengband.doxyfile, hengband.spec, src/system/angband-version.h
=> [Release] 3.0.0.90-Alpha (develop)

src/effect/effect-feature.cpp, src/floor/fixed-map-generator.cpp, src/floor/object-allocator.cpp, src/grid/trap.cpp, src/grid/trap.h, src/load/old/load-v1-5-0.cpp, src/room/rooms-normal.cpp, src/room/rooms-vault.cpp, src/room/treasure-deployment.cpp, src/room/vault-builder.cpp, src/room/vault-builder.h
過去のリファクタリングで一部PlayerType への依存性がなくなったので掲題の通り設計変更しました
ご確認下さい
=> choose_random_trap() の引数をPlayerType からFloorType に差し替えた

configure.ac, doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.0.91-Alpha

src/effect/effect-monster-charm.cpp, src/effect/effect-monster-evil.cpp, src/effect/effect-monster-oldies.cpp, src/effect/effect-monster-psi.cpp, src/effect/effect-monster-resist-hurt.cpp, src/effect/effect-monster-spirit.cpp, src/effect/effect-monster-switcher.cpp, src/effect/effect-monster.cpp, src/info-reader/dungeon-reader.cpp, src/info-reader/race-info-tokens-table.cpp, src/info-reader/race-info-tokens-table.h, src/info-reader/race-reader.cpp, src/load/lore-loader.cpp, src/load/old/load-v1-5-0.cpp, src/load/savedata-old-flag-types.h, src/melee/melee-postprocess.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-samurai.cpp, src/mind/monk-attack.cpp, src/monster-race/race-flags-resistance.h, src/monster-race/race-flags3.h, src/monster/monster-damage.cpp, src/mspell/mspell-status.cpp, src/player-attack/attack-chaos-effect.cpp, src/spell/spells-diceroll.cpp, src/view/display-lore-status.cpp
=> 状態異常無効化フラグをEnum Class化

src/dungeon/quest.h, src/info-reader/fixed-map-parser.h, src/knowledge/knowledge-quests.h, src/main-win.cpp, src/main-win/graphics-win.cpp, src/util/flag-group.h
未初期化警告を潰し、今となっては不要になった抑制を消しました
ご確認下さい
=> コンパイル警告の解消 β (予定)

src/info-reader/info-reader-util.h, src/util/flag-group.h
=> テキストデータから定数を読み込めるようにした

src/action/open-close-execution.cpp, src/dungeon/quest-monster-placer.cpp, src/effect/effect-feature.cpp, src/floor/cave-generator.cpp, src/floor/floor-leaver.cpp, src/floor/floor-streams.cpp, src/grid/grid.cpp
=> グリッドから地形へのアクセスをカプセル化する準備 その4

src/grid/grid.cpp, src/info-reader/feature-reader.cpp, src/player/player-move.cpp, src/target/target-describer.cpp
=> グリッドから地形へのアクセスをカプセル化する準備 その5

src/floor/pattern-walk.cpp, src/hpmp/hp-mp-processor.cpp, src/mind/mind-archer.cpp, src/mind/mind-ninja.cpp, src/monster-attack/monster-attack-processor.cpp, src/monster-attack/monster-attack-processor.h, src/monster-floor/monster-move.cpp, src/monster-floor/monster-move.h, src/monster/monster-processor.cpp, src/monster/monster-util.cpp, src/mspell/mspell-lite.cpp, src/mutation/mutation-techniques.cpp, src/player-base/player-race.cpp, src/room/rooms-builder.cpp, src/spell-kind/spells-lite.cpp
=> グリッドから地形へのアクセスをカプセル化する準備 その6

src/action/movement-execution.cpp, src/action/run-execution.cpp, src/floor/cave.cpp, src/floor/floor-streams.cpp, src/floor/pattern-walk.cpp, src/monster/monster-util.cpp, src/player/player-status.cpp, src/spell-kind/spells-floor.cpp
=> グリッドから地形へのアクセスをカプセル化する準備 その7

src/info-reader/feature-reader.cpp, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h
=> グリッドから地形へのアクセスをカプセル化する準備 その8

src/info-reader/artifact-reader.cpp, src/info-reader/baseitem-reader.cpp, src/info-reader/dungeon-reader.cpp, src/info-reader/race-reader.cpp, src/info-reader/vault-reader.cpp
Resolves https://github.com/hengband/hengband/issues/3763 .
=> Tolerate info lines starting with "D::"

src/action/movement-execution.cpp, src/action/open-close-execution.cpp, src/action/open-util.cpp, src/action/open-util.h, src/autopick/autopick.cpp, src/cmd-action/cmd-open-close.cpp, src/cmd-action/cmd-pet.cpp, src/combat/shoot.cpp, src/core/window-redrawer.cpp, src/floor/geometry.cpp, src/floor/geometry.h, src/floor/pattern-walk.cpp, src/floor/pattern-walk.h, src/grid/grid.cpp, src/grid/grid.h, src/object-use/throw-execution.cpp, src/room/space-finder.cpp, src/specific-object/chest.cpp, src/specific-object/chest.h, src/spell-realm/spells-crusade.cpp, src/target/target-describer.cpp, src/target/target-setter.cpp, src/window/display-sub-windows.cpp, src/window/display-sub-windows.h
掲題の通りです
手元で軽く動作確認しましたが特に重大な問題は発生しませんでした
ご確認下さい
=> POSITION y, POSITION x の引数を持つ関数をPos2D に差し替えた その1

Makefile.am
Resolves https://github.com/hengband/hengband/issues/3768 .
=> Include THIRD-PARTY-NOTICES.txt in archive from 'make dist'

src/room/rooms-normal.cpp
掲題の通りです
流石に全ての条件分岐を確認できていませんが、全ての部屋タイプが生成されることは確認しました：
http://sikabane-works.net/monzetsu_diary/?date=20130111
=> rooms-normal.cpp を整形した

configure.ac, doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.1.3-Beta

src/effect/effect-processor.cpp
=> project()のgm_radのスコープを狭めた

lib/edit/MonsterRaceDefinitions.txt
=> MonsterRaceDefinitions.txtのWパラメータ説明文を現行仕様に修正

src/melee/melee-switcher.cpp, src/monster-attack/monster-attack-switcher.cpp
=> カオス効果の打撃の地震に関する不自然なメッセージを修正

lib/edit/MonsterRaceDefinitions.txt
=> ユニークモンスター「カフモ」を追加

Hengband/Hengband/Hengband.vcxproj, src/Makefile.am, src/info-reader/dungeon-reader.cpp, src/info-reader/race-info-tokens-table.cpp, src/info-reader/race-info-tokens-table.h, src/info-reader/race-reader.cpp, src/load/lore-loader.cpp, src/lore/lore-calculator.cpp, src/lore/lore-store.cpp, src/lore/lore-util.cpp, src/lore/lore-util.h, src/lore/monster-lore.cpp, src/monster-race/race-special-flags.h, src/monster/monster-processor-util.cpp, src/monster/monster-processor-util.h, src/monster/monster-status.cpp, src/monster/monster-update.cpp, src/monster/monster-util.cpp, src/save/monster-writer.cpp, src/system/angband-version.h, src/system/dungeon-info.h, src/system/monster-race-info.h
=> ダメージキャップを先行実装

Makefile.am
Resolves https://github.com/hengband/hengband/issues/3878 .
=> Include hengband-en.spec in the archive generated by 'make dist'

src/core/game-play.cpp, src/dungeon/dungeon-processor.cpp, src/floor/floor-generator.cpp, src/floor/wild.cpp, src/info-reader/fixed-map-parser.cpp, src/item-info/flavor-initializer.cpp, src/load/angband-version-comparer.cpp, src/load/angband-version-comparer.h, src/load/floor-loader.cpp, src/load/info-loader.cpp, src/load/load.cpp, src/load/old/load-v1-5-0.cpp, src/load/world-loader.cpp, src/main-win.cpp, src/main/game-data-initializer.cpp, src/monster/monster-list.cpp, src/monster/monster-status.cpp, src/save/info-writer.cpp, src/save/player-writer.cpp, src/system/angband-system.cpp, src/system/angband-system.h, src/system/angband-version.cpp, src/system/angband-version.h, src/system/gamevalue.h, src/term/z-rand.cpp, src/world/world-object.cpp, src/world/world.h
掲題の通りです
単に移動させただけでなく、乱数周りのフィールド変数はメソッド経由でのアクセスにカプセル化しました
過去にこの辺りのコードを @habu1010 氏が担当されていましたので、勝手ながらレビュアーに割り当てます
お手数ですがご確認下さい
=> AngbandWorld のフィールド変数をAngbandSystem へ移した その1

src/action/movement-execution.cpp, src/action/mutation-execution.cpp, src/cmd-action/cmd-pet.cpp, src/floor/geometry.cpp, src/floor/geometry.h, src/mind/mind-berserker.cpp, src/mind/mind-warrior.cpp, src/mutation/mutation-techniques.cpp, src/racial/racial-vampire.cpp, src/realm/realm-hissatsu.cpp, src/spell/spells-status.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h
get\_direction() が呼ばれている周辺のコードを整備しました
主に座標をYとXで個別に評価していたものをPos2D に変えました
ご確認下さい (特に、y/x へ再代入している箇所がリファクタリング前と同じ処理を維持しているかどうか)
=> get_direction() のシグネチャを変える準備 その1

src/action/run-execution.cpp, src/action/travel-execution.cpp, src/cmd-action/cmd-open-close.cpp, src/cmd-action/cmd-others.cpp, src/cmd-action/cmd-tunnel.cpp, src/core/player-processor.cpp, src/mind/mind-archer.cpp, src/mind/mind-force-trainer.cpp, src/mind/monk-attack.cpp, src/realm/realm-hissatsu.cpp, src/specific-object/monster-ball.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-class/spells-mirror-master.h, src/spell-kind/spells-launcher.cpp, src/spell-kind/spells-teleport.cpp
その1 で実装したget\_neighbor() をコード全体に拡大しました
ご確認下さい
=> get_direction() のシグネチャ変更準備 その2

src/system/monster-entity.cpp, src/system/monster-race-info.cpp
馬鹿馬鹿で移植作業再開した折にちょっと気づいてつけただけの作業です。お茶濁すようなことですが確認の上取り込んでいただければ。
=> 各 is_explodable() メソッドにMonsterEntity::get_died_message() にDoxygenコメント付加。

src/action/mutation-execution.cpp, src/cmd-action/cmd-pet.cpp, src/mind/mind-berserker.cpp, src/mind/mind-warrior.cpp, src/mutation/mutation-techniques.cpp, src/racial/racial-vampire.cpp, src/realm/realm-hissatsu.cpp, src/specific-object/monster-ball.cpp, src/spell/spells-status.cpp, src/target/target-getter.cpp, src/target/target-getter.h
#3904、#3915 の本番PRです
引数と戻り値の関係が明確化されて使いやすくなったかと思います
ご確認下さい
=> get_direction() のシグネチャからポインタの引数を除去し、optionalの戻り値を返すようにした

src/io-dump/special-class-dump.cpp, src/io/interpret-pref-file.cpp, src/save/save.cpp
掲題の通りです
少量なのでチケットはありません
ご確認下さい
=> VS2022 で出ているコンパイル警告を解消した (v3.0.0 β12)

src/combat/shoot.cpp, src/effect/effect-monster.cpp, src/monster/monster-pain-describer.cpp, src/monster/monster-pain-describer.h, src/object-use/throw-execution.cpp
=> describe() の "" で返す部分を nullopt にした

src/room/rooms-normal.cpp, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h
#3953 の前段作業です
全てのif文は網羅できていませんが、大雑把にdevelopと同一のフロアが生成されることを確認済です
ご確認下さい
=> rooms-normal.cpp の整形作業

src/cmd-visual/cmd-visuals.cpp, src/io/interpret-pref-file.cpp, src/item-info/flavor-initializer.cpp, src/object/object-kind-hook.cpp, src/system/baseitem-info.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp
#3932 に入り切らないと判断して別PRに分けたコミットです
ご確認下さい
=> 正常なベースアイテムかどうかの判定にis_valid() を使うよう差し替えた

src/room/rooms-special.cpp, src/system/dungeon-info.h, src/wizard/wizard-special-process.cpp
最後のコミットに書いた通り、デバッグコマンドにバグがあったので修正しました
このファイルはガラスの部屋を生成するルーチンですが、あまりにも生成確率が低いので目視確認だけにしてあります
ご確認下さい
(一度だけ、内部がガラスで埋め尽くされた部屋が生成されたことがあります。それで正しいのかは不明です)
=> rooms-special.cpp の整形作業

src/room/rooms-fractal.cpp
他のrooms系リファクタリングよりは軽いです (変数の型推論とポインタ→参照 の切り替えくらい)
乱数の全パターンは追っていませんが、develop と同じ部屋が生成されることを確認済です
ご確認下さい
=> rooms-fractal.cpp の整形作業

src/room/rooms-city.cpp, src/room/rooms-city.h
長すぎて何をやっているか意味不明だったので、ugbldg\_type を育ててロジックを分散させました
現在のdevelop と同じ地下街が生成されることを確認済です
ご確認下さい
=> rooms-city.cpp の整形作業

src/object-enchant/object-ego.cpp, src/term/z-rand.cpp, src/term/z-rand.h
エラーレポートへいくつか掲題の例外が飛んでいることを確認し、どんな数値が入ってきても正常動作するように修正しました
ご確認下さい
=> randint0/1 が例外を吐く事象を修正した

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/view/colored-char.h, src/view/display-map.cpp, src/window/main-window-util.cpp, src/window/main-window-util.h
#3955 の後続チケットです、これがApproveされるまではドラフトにしておきます
以下のようなエイリアスの変数組が頻出しているのに気づいたのでまとめました
軽くポインタ引数から戻り値への変換も行っています
ご確認下さい
```cpp
TERM_COLOR a;
char c;
```
=> ColoredChar クラスを作成した

src/info-reader/feature-reader.cpp, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h
今までend() を使っていた箇所を可読性のために差し替えました
ご確認下さい
=> TerrainList にrbegin()/rend() を実装した

src/avatar/avatar.cpp, src/birth/game-play-initializer.cpp, src/window/display-sub-windows.cpp
=> `strcpy()` 使用部位の修正 その1

lib/edit/MonsterRaceDefinitions.txt
=> [Add] おたずねものムシシリーズを実装

src/artifact/random-art-misc.cpp, src/autopick/autopick-command-menu.cpp, src/autopick/autopick-describer.cpp, src/autopick/autopick-editor-util.cpp, src/autopick/autopick-editor-util.h, src/autopick/autopick-entry.cpp, src/mind/mind-elementalist.cpp, src/room/cave-filler.cpp
主に配列の未初期化警告を解消しました
autopick-command-menu.cpp、次いでautopick-entry.cpp の差分が多いですが事情により動作確認できておりません
一応ドラフトにしておきますが確認頂けると助かります
=> コンパイル警告の解消 (β13)

src/info-reader/info-reader-util.h, src/player/process-death.cpp
Resolves #3994 
#3931 で指摘されている、GCCの警告はこれで対処できたことになります。
=> [Fix] GCC 13 で出力される警告の対策

src/room/rooms-pit-nest.cpp, src/room/rooms-pit-nest.h, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h
#3953 の前段作業です
Nest/Pit/開門トラップの全てにおいてdevelop と同じ部屋が生成されることを確認済です
ご確認下さい
=> rooms-pit-nest.cpp/h の整形作業 その1

src/room/rooms-pit-nest.cpp, src/room/rooms-pit-nest.h, src/util/point-2d.h
ベクトルの反転処理が欲しかったのでついでに追加しました
developと同一のnestが生成されることを確認済です
ご確認下さい
=> rooms-pit-nest.cpp の整形 その2

src/floor/wild.cpp, src/room/rooms-city.cpp, src/room/rooms-city.h, src/room/rooms-fractal.cpp, src/room/rooms-normal.cpp, src/room/rooms-pit-nest.cpp, src/room/rooms-special.cpp, src/util/point-2d.h
point-2d.h 以外の箇所はほぼ変数名変更＆取りまとめです
ご確認下さい
=> Rectangle2D クラスを作り、左上/右下座標のペアをまとめた

src/room/rooms-city.cpp, src/room/rooms-pit-nest.cpp, src/util/point-2d.h
[#4024](https://github.com/hengband/hengband/issues/4024#issuecomment-2105632069) で書いた内容を実装してみました。
また、追加したメソッドをRect2Dクラスとともに適用できる箇所はたくさんありそうですが、とりあえず今Rect2Dクラスを使用している箇所の周辺に適用したコミットを入れています。
=> [Feature] Rectangle2Dクラスにメソッドを追加

src/room/pit-nest-util.cpp, src/room/pit-nest-util.h, src/room/rooms-nest.cpp, src/room/rooms-pit.cpp
煩雑なif文であったり基本型で扱いにくかった箇所をenum classとmapで分かりやすくなるよう書き直しました
ご確認下さい
=> pit用の処理とnest用の処理を分離した

src/util/candidate-selector.h, src/wizard/tval-descriptions-table.cpp, src/wizard/tval-descriptions-table.h, src/wizard/wizard-special-process.cpp
Resolves #2779 
長らく放置されていましたが実装しました。
これでアイテム種類数の限界の問題とともに、通常の画面サイズだと右側に見切れてしまう問題も解決します。
=> [Feature] デバッグコマンドでアイテム生成するときに候補の表示にCandidateSelectorを使用する

src/room/pit-nest-util.cpp, src/room/pit-nest-util.h, src/room/rooms-nest.cpp, src/room/rooms-pit.cpp
#4027 の準備のため、あまり細かい関数分割はしていません (単にコミットが膨れたのも一因)
developと同一のpitが生成されることをチェック済です
ご確認下さい
=> rooms-pit.cpp の整形作業 その4

src/birth/inventory-initializer.cpp, src/cmd-visual/cmd-visuals.cpp, src/core/visuals-reseter.cpp, src/flavor/object-flavor.cpp, src/flavor/object-flavor.h, src/info-reader/baseitem-reader.cpp, src/io/interpret-pref-file.cpp, src/item-info/flavor-initializer.cpp, src/knowledge/knowledge-experiences.cpp, src/knowledge/knowledge-items.cpp, src/perception/object-perception.cpp, src/system/baseitem-info.cpp, src/system/baseitem-info.h, src/system/item-entity.cpp, src/system/terrain-type-definition.h, src/view/display-map.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp
BaseitemList を定義した他、ベースアイテムシンボルをColoredChar に差し替えるなどカプセル化を進展させました
ご確認下さい
=> baseitems_info をBaseitemList に差し替える準備

src/io-dump/dump-util.cpp, src/io-dump/dump-util.h, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h, src/view/colored-char.h
今後TerrainType に諸々のメソッドを繰り込んでいく準備は概ねこれで整ったかと思います
マップ描画 (セーブファイル読み込み＋フロア再生成)はチェック済です
ご確認下さい
=> TERM_COLORとchar の組み合わせで表現していたグローバル変数をシングルトンクラスに差し替えた

src/autopick/autopick-editor-command.cpp, src/birth/birth-util.cpp, src/cmd-building/cmd-building.cpp, src/cmd-io/cmd-diary.cpp, src/cmd-io/cmd-gameoption.cpp, src/cmd-io/cmd-help.cpp, src/core/show-file.cpp, src/core/show-file.h, src/knowledge/knowledge-autopick.cpp, src/knowledge/knowledge-experiences.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-inventory.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp, src/knowledge/knowledge-mutations.cpp, src/knowledge/knowledge-quests.cpp, src/knowledge/knowledge-self.cpp, src/knowledge/knowledge-uniques.cpp, src/market/arena.cpp, src/market/play-gamble.cpp, src/object-use/read/parchment-read-executor.cpp
(void)show\_file() が気持ち悪すぎたので戻り値のチェックは別メソッドで行うようにしました
元関数の中身はコンパイルが通る程度にしか変えていません
ご確認下さい
=> show-file.cpp をクラス化した

src/cmd-action/cmd-pet.cpp, src/floor/floor-changer.cpp, src/floor/floor-streams.cpp, src/grid/grid.cpp, src/hpmp/hp-mp-processor.cpp, src/mind/mind-elementalist.cpp, src/monster-floor/monster-generator.cpp, src/monster-floor/monster-sweep-grid.cpp, src/monster/monster-list.cpp, src/monster/monster-status.cpp, src/player/player-skill.cpp, src/player/player-status-flags.cpp, src/player/player-status.cpp, src/spell/spell-info.cpp, src/system/monster-entity.cpp, src/target/target-preparation.cpp, src/util/sort.cpp
=> [Refactor] MonsterEntity 外のMonsterEntity.r_idx 系への依存をなくした

src/game-option/game-play-options.h, src/game-option/option-types-table.cpp, src/io/input-key-requester.cpp, src/save/info-writer.cpp, src/save/info-writer.h, src/save/save.cpp, src/save/save.h
Close #4064
現状あまり有効でないauto_debug_saveオプションを廃止する。
=> [Feature] auto_debug_saveオプションの廃止

src/birth/game-play-initializer.cpp, src/birth/inventory-initializer.cpp, src/core/visuals-reseter.cpp, src/item-info/flavor-initializer.cpp, src/system/baseitem-info.cpp, src/system/baseitem-info.h
グローバル関数の繰り込みだけで細かい設計変更は行っていません
ご確認下さい
=> BaseitemList へメソッドをいくつか繰り込んだ

lib/edit/MonraceDefinitions.jsonc
=> (3.0.1.13-Beta)ドラウナーの経験値を調整した

lib/edit/MonraceDefinitions.jsonc
=> [Add] ユニーク・モンスター「メガ・フレイム・ドラゴン」を実装した

src/cmd-item/cmd-eat.cpp, src/cmd-item/cmd-magiceat.cpp, src/io-dump/character-dump.cpp, src/io-dump/special-class-dump.cpp, src/knowledge/knowledge-quests.cpp, src/mind/mind-archer.cpp, src/spell/spells-object.cpp, src/spell/spells-status.cpp, src/system/baseitem-info.cpp, src/system/baseitem-info.h
掲題の通りです
これで長らく滞留させていた#2805 の実施準備が整いました
ご確認下さい
=> BaseitemList にlookup_baseitem() を実装し、bi_id が不要な箇所を差し替えた

src/autopick/autopick-reader-writer.cpp, src/cmd-io/cmd-diary.cpp, src/cmd-io/cmd-dump.cpp, src/cmd-io/cmd-macro.cpp, src/cmd-io/cmd-process-screen.cpp, src/cmd-visual/cmd-visuals.cpp, src/core/game-closer.cpp, src/core/game-play.cpp, src/core/scores.cpp, src/core/show-file.cpp, src/info-reader/fixed-map-parser.cpp, src/io-dump/random-art-info-dumper.cpp, src/io/files-util.cpp, src/io/read-pref-file.cpp, src/io/record-play-movie.cpp, src/io/write-diary.cpp, src/main-win.cpp, src/main-win/graphics-win.cpp, src/main-win/main-win-cfg-reader.cpp, src/main-win/main-win-file-utils.cpp, src/main/angband-initializer.cpp, src/main/info-initializer.cpp, src/market/building-initializer.cpp, src/view/display-scores.cpp, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/items-spoiler.cpp, src/wizard/monster-info-spoiler.cpp, src/wizard/wizard-special-process.cpp, src/wizard/wizard-spoiler.cpp
掲題の関数は戻り値が値なので左辺も値に変えました
ご確認下さい
=> path_build() の戻り値を参照ではなく値で受けるようにした

src/external-lib/json.hpp, src/io/interpret-pref-file.cpp, src/io/interpret-pref-file.h, src/io/read-pref-file.cpp, src/main-win/main-win-sound.cpp
ItemEntity 関連のリファクタリングをしていた最中、周辺コードでVSが検出したコンパイル警告を解消しました
雑多なmisc作業のためチケットはありません
ご確認下さい
=> コンパイル警告の解消＋周辺コード整備

src/combat/shoot.cpp, src/effect/effect-processor.cpp, src/io/cursor.cpp, src/mind/mind-ninja.cpp, src/mspell/mspell-checker.cpp, src/mspell/mspell-judgement.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-fetcher.cpp, src/spell/range-calc.cpp, src/spell/range-calc.h, src/target/projection-path-calculator.cpp, src/target/projection-path-calculator.h, src/util/point-2d.h
元からぐちゃぐちゃですが、今回の作業範囲ではまだ人類にも理解できる程度の差分に押さえたつもりです
単純置換ばかりのはずですが置換ミスがありましたらコメントお願いします
=> projection_path とprojection_path_type のpair<int, int> をPos2D に変えた

src/artifact/fixed-art-generator.cpp, src/artifact/random-art-generator.cpp, src/combat/shoot.cpp, src/dungeon/quest.cpp, src/dungeon/quest.h, src/flavor/named-item-describer.cpp, src/floor/fixed-map-generator.cpp, src/info-reader/artifact-reader.cpp, src/info-reader/general-parser.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-quests.cpp, src/load/old/item-loader-savefile50.cpp, src/load/old/load-v1-5-0.cpp, src/load/quest-loader.cpp, src/main/info-initializer.cpp, src/monster-floor/special-death-switcher.cpp, src/save/item-writer.cpp, src/save/save.cpp, src/spell/spells-object.cpp, src/store/rumor.cpp, src/system/artifact-type-definition.cpp, src/system/artifact-type-definition.h, src/system/item-entity.cpp, src/system/item-entity.h, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/wizard-item-modifier.cpp, src/wizard/wizard-special-process.cpp
初期化時を除き (これはBaseitemList/TerrainListも同様)、必ずArtifactListを経由してmapにアクセスする方式を実現できました
ご確認下さい
=> artifacts_info をArtifactList に繰り込んだ

src/perception/identification.cpp
Resolves https://github.com/hengband/hengband/issues/4120 .
=> English: add space after "by" for negative light radius

src/cmd-visual/cmd-visuals.cpp, src/core/visuals-reseter.cpp, src/io/interpret-pref-file.cpp, src/knowledge/knowledge-monsters.cpp, src/perception/identification.cpp, src/system/item-entity.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h, src/view/display-lore.cpp, src/view/display-map.cpp, src/window/display-sub-windows.cpp, src/window/main-window-left-frame.cpp, src/window/main-window-util.cpp
フロアのデバッグ生成で見た感じ、特にモンスターの表示は変わっていないように見えます
ご確認下さい
=> MonsterRaceInfo::x_attr/x_char をColoredChar に差し替えた

src/combat/shoot.cpp, src/effect/effect-monster.cpp, src/monster/monster-pain-describer.cpp, src/monster/monster-pain-describer.h, src/object-use/throw-execution.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h
=> [Refactor] MonsterPainDescriber を MonsterEntity の関連クラスにした

src/cmd-visual/cmd-visuals.cpp, src/grid/grid.cpp, src/io-dump/dump-util.cpp, src/io/cursor.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-items.cpp, src/knowledge/knowledge-monsters.cpp, src/perception/identification.cpp, src/term/z-term.cpp, src/term/z-term.h, src/view/colored-char.h, src/view/display-inventory.cpp, src/view/display-map.cpp, src/view/display-map.h, src/view/display-store.cpp, src/window/display-sub-windows.cpp, src/window/main-window-equipments.cpp, src/window/main-window-util.cpp
ASCII表示用のColoredChar と、タイル表示用のColoredChar を合わせたColoredCharPair を作りました
かなり引数がスッキリしたかと思います
これに関連する画面表示関数も一部差し替えました
ご確認下さい
(キャラクタなどほとんどのコードはY, Xの順番ですが画面表示だけ逆だったので逆転させました：画面表示上の座標もキャラクタ表示用の座標も同じ位置を表すのでPos2D に変えました)
=> map_info() の引数を表すクラスを作って差し替えた

src/room/pit-nest-util.h, src/room/rooms-nest.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
詳細には確認していませんが、ID順ではなくレベル順にソートされているように見えます
ご確認下さい
=> nest_mon_info_type のソート関数の自身のオブジェクトメソッドに繰り込んだ

src/cmd-io/cmd-diary.cpp, src/io/files-util.cpp, src/io/files-util.h, src/io/write-diary.cpp, src/player/process-name.cpp
#4160 の後続作業
調査した結果、path に変えても問題なさそうだと判断したので型を差し替えました
ご確認下さい
=> savefile_base をstring からpath に変えた

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/load/floor-loader.cpp, src/load/info-loader.cpp, src/load/load-util.cpp, src/load/load-util.h, src/locale/character-encoding.h, src/locale/japanese.cpp, src/locale/japanese.h, src/save/save.cpp
Resolves #4203 
当該作業中にあきらかにおかしなコードを見つけたので調べたところ、リファクタリングのミスによりエンバグしたものだったようなので合わせて修正しておきました。
=> [Refactor] セーブファイルの文字コードをenum class化 

configure.ac, doxygen/Hengband.doxyfile, src/monster/monster-damage.cpp, src/monster/monster-damage.h, src/system/angband-version.h
=> モンスター撃破時に経験値が入らない不具合を修正した to master

src/action/open-close-execution.cpp, src/cmd-visual/cmd-visuals.cpp, src/floor/cave.cpp, src/floor/floor-streams.cpp, src/floor/object-allocator.cpp, src/grid/feature.cpp, src/grid/grid.cpp, src/grid/trap.cpp, src/info-reader/feature-reader.cpp, src/io/interpret-pref-file.cpp, src/knowledge/knowledge-features.cpp, src/monster/monster-info.cpp, src/player/player-move.cpp, src/room/rooms-trap.cpp, src/spell-kind/spells-floor.cpp, src/store/purchase-order.cpp, src/system/artifact-type-definition.cpp, src/system/grid-type-definition.cpp, src/system/monster-race-info.cpp, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h, src/target/target-describer.cpp, src/view/display-map.cpp, src/view/display-store.cpp, src/window/display-sub-windows.cpp
=> TerrainList::[] をget_terrain() に差し替えた

src/dungeon/quest.cpp, src/io-dump/character-dump.cpp, src/market/bounty.cpp, src/mspell/mspell-special.cpp, src/object-enchant/others/apply-magic-others.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
=> MonraceList::[] をMonraceList::get_monrace() に変えた

src/floor/floor-generator.cpp, src/grid/trap.cpp, src/info-reader/dungeon-reader.cpp, src/info-reader/feature-reader.cpp, src/info-reader/feature-reader.h, src/info-reader/general-parser.cpp, src/info-reader/magic-reader.cpp, src/info-reader/skill-reader.cpp, src/main/angband-headers.h, src/main/angband-initializer.cpp, src/main/info-initializer.cpp, src/system/artifact-type-definition.cpp, src/system/artifact-type-definition.h, src/system/baseitem-info.cpp, src/system/baseitem-info.h, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h
Resolves #3732 
合わせて周辺コードの整理も行いました。コミットをご参照ください。
=> [Refactor] *Listクラスの内部コンテナの参照を得るメンバ関数を削除 

src/info-reader/dungeon-reader.cpp, src/info-reader/dungeon-reader.h, src/main/angband-initializer.cpp, src/main/info-initializer.cpp, src/main/info-initializer.h
Resolves #4220 
合わせて、init_angband() 内でのコードが一定のパターンにおさまるよう、2つ修正コミットを追加しています。
=> [Refactor] init_info/init_jsonの戻り値をvoidにする 

src/knowledge/knowledge-monsters.cpp, src/load/load-zangband.cpp, src/load/player-info-loader.cpp, src/market/bounty.cpp, src/object-hook/hook-quest.cpp, src/save/player-writer.cpp, src/system/baseitem-info.cpp, src/util/object-sort.cpp, src/world/world.cpp, src/world/world.h
=> monraces_info をMonraceList に繰り込む作業 その2

src/cmd-visual/cmd-visuals.cpp
=> MonraceList::size() が呼ばれている周辺のmonraces_info をMonraceList に変えた

src/player/eldritch-horror.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
=> monraces_info をMonraceList に繰り込む作業 その4

src/birth/game-play-initializer.cpp, src/dungeon/dungeon-processor.cpp, src/dungeon/quest-monster-placer.cpp, src/dungeon/quest.cpp, src/dungeon/quest.h, src/floor/fixed-map-generator.cpp, src/floor/object-allocator.cpp, src/io/write-diary.cpp, src/knowledge/knowledge-quests.cpp, src/load/dungeon-loader.cpp, src/load/quest-loader.cpp, src/world/world-movement-processor.cpp
=> monraces_info をMonraceList に繰り込む作業 その5

src/system/monster-entity.cpp
馬鹿馬鹿でこの辺いじっている間に気づいたのでとりあえず修正かけました。
=> [Fix] コメントのTypo修正。

Hengband/Hengband/Hengband.vcxproj, Hengband/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/cmd-action/cmd-spell.cpp, src/core/stuff-handler.cpp, src/core/stuff-handler.h, src/knowledge/knowledge-items.cpp, src/system/item-entity.cpp, src/system/item-entity.h, src/system/player-type-definition.h, src/tracking/baseitem-tracker.cpp, src/tracking/baseitem-tracker.h, src/view/object-describer.cpp
#4223 の後続チケットです (マージまではドラフト)
ついでに行いました
=> PlayerType::tracking_bi_id をBaseitemTracker に移した

src/monster/monster-processor-util.cpp, src/monster/monster-processor-util.h, src/monster/monster-processor.cpp
=> old_race_flags 構造体をOldRaceFlags クラスに変えた

src/monster/monster-util.cpp
=> [Fix] ダンジョンによる出現モンスター制限が機能していない 

src/external-lib/json.hpp, src/flavor/flavor-describer.cpp, src/game-option/option-flags.h, src/io/input-key-requester.cpp, src/load/angband-version-comparer.h, src/load/info-loader.cpp, src/load/item/item-loader-factory.cpp, src/load/load.cpp, src/load/monster/monster-loader-factory.cpp, src/load/store-loader.cpp, src/object-use/read/read-executor-factory.cpp, src/room/rooms-vault.h, src/status/action-setter.h, src/system/angband-system.h, src/system/angband-version.h, src/system/h-system.h, src/system/h-type.h, src/target/target-setter.h, src/target/target-types.h, src/util/flag-group.h
以下の2点を実施しました
チケットはありません
ご確認下さい
- C言語のヘッダはC++では「hoge.h」ではなく「choge」と呼ぶことになっているので差し替え (stdint.h とh-system.h に定義されたもののみ)
- 例外クラスを指定せずスローしていた箇所を型を指定するように修正
=> Miscコード最適化 β15

src/monster-floor/one-monster-placer.cpp, src/monster/monster-list.cpp, src/monster/monster-list.h, src/monster/monster-status.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h
=> [Refactor] get_mspeed() をMonsterEntity のメソッドに繰り込んだ

src/cmd-building/cmd-inn.cpp, src/view/display-player-middle.cpp, src/world/world.cpp, src/world/world.h
=> AngbandWorld をシングルトンに変える準備 その1

src/cmd-io/cmd-dump.cpp, src/core/show-file.cpp, src/io-dump/character-dump.cpp, src/io/report.cpp, src/load/angband-version-comparer.cpp, src/load/floor-loader.cpp, src/load/info-loader.cpp, src/load/load.cpp, src/main/angband-initializer.cpp, src/net/report-error.cpp, src/system/angband-system.cpp, src/system/angband-system.h, src/system/angband-version.cpp, src/system/angband-version.h, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/items-spoiler.cpp, src/wizard/monster-info-spoiler.cpp, src/wizard/wizard-special-process.cpp, src/wizard/wizard-spoiler.cpp
AngbandVersion クラスを作って扱いやすくしました
起動時のトップ画面やダンプなど問題なさそうです
ご確認下さい
=> AngbandWorld をシングルトンに変える準備 その2

src/market/arena-entry.h
Resolves https://github.com/hengband/hengband/issues/4279 .
=> Prevent compiler error when not using precompiled headers

src/wizard/wizard-game-modifier.cpp, src/wizard/wizard-special-process.cpp, src/wizard/wizard-special-process.h, src/world/world.cpp, src/world/world.h
=> set_gametime() をAngbandWorld のオブジェクトメソッドに繰り込んだ

src/birth/birth-stat.cpp, src/io-dump/character-dump.cpp, src/knowledge/knowledge-self.cpp, src/load/load-zangband.cpp, src/load/player-info-loader.cpp, src/player/player-status.cpp, src/save/player-writer.cpp, src/spell/spells-status.cpp, src/status/shape-changer.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h, src/view/display-self-info.cpp
=> [Refactor] プレイヤーのHDにDiceクラスを使用する

src/info-reader/fixed-map-parser.cpp
静的領域か文字列リテラルを指す const char* が戻り値でかつ再帰呼び出しを行っているという非常に追いづらいものとなっているので、戻り値をstd::string オブジェクトで戻すように変更する。
#4282 をやるにあたり、parse_fix_map_expression が const char* が邪魔になるので前作業です。
とりあえず各街、クエスト、広域マップを適当に回ってみましたが特に問題はなさそうでした。
=> [Refactor] parse_fix_map_expression

src/room/rooms-vault.cpp
ひとまずプロジェクトの目的が達成できる程度の変更に留めました
全てのVaultを引くのは現実的ではないので何回か試してみましたが特に生成されるモンスター種族や配置はdevelopと変わりませんでした
ご確認下さい
=> rooms-vault.cpp の整形

src/autopick/autopick-drawer.cpp, src/io/pref-file-expressor.cpp, src/io/pref-file-expressor.h, src/io/read-pref-file.cpp
=> [Refactor] process_pref_file_expr

src/effect/effect-monster-charm.cpp, src/monster-floor/monster-death.cpp, src/monster-floor/one-monster-placer.cpp, src/monster/monster-list.cpp, src/monster/monster-list.h, src/monster/monster-processor.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h
=> choose_new_monster() 関数を分割した

src/inventory/inventory-object.cpp, src/util/enum-converter.h
=> [Refactor] enum-converter.hの各関数群にコンセプトを使用する

Makefile.am
Resolves https://github.com/hengband/hengband/issues/4316 .
=> Include all schema files in the archive generated by 'make dist'

src/birth/game-play-initializer.cpp, src/dungeon/quest.h, src/load/dungeon-loader.cpp, src/object/tval-types.h, src/player/player-skill.h, src/room/room-types.h, src/store/store-util.h, src/system/floor-type-definition.cpp, src/system/redrawing-flags-updater.cpp, src/util/enum-range.h, src/util/flag-group.h, src/wizard/artifact-analyzer.cpp, src/wizard/spoiler-util.cpp, src/world/world-movement-processor.cpp
=> [Feature/Refactor] EnumRangeクラスの改良

lib/edit/ClassMagicDefinitions.jsonc, src/realm/realm-demon.cpp
=> [Feature] 悪魔領域の魔法強化案 #4331

src/monster-floor/monster-move.cpp, src/monster-floor/monster-move.h, src/monster-floor/one-monster-placer.cpp
Close #4327 
若干処理の変更があるが、挙動に影響はなし
=> [Refactor] 爆発のルーンの作動処理をモジュールとして分割した

lib/edit/ClassMagicDefinitions.jsonc, src/realm/realm-demon.cpp
=> [Feature] 悪魔領域魔法 士気高揚を1冊目に追加する

src/monster-floor/monster-generator.cpp
=> [Refactor] place_monster_idx, place_monster_m_idx を削除する

src/effect/effect-monster-resist-hurt.cpp
Resolves https://github.com/hengband/hengband/issues/4351 .
=> English: add space after monster's name for some death/pain messages

lib/edit/Makefile.am
Resolves https://github.com/hengband/hengband/issues/4355 .
=> configure: install lib/edit/SpellDefinitions.jsonc

src/mind/mind-elementalist.cpp, src/mind/mind-elementalist.h, src/mind/mind-types.h, src/window/display-sub-windows.cpp
=> [Fix] 元素使いの呪文一覧をサブウィンドウに表示するとクラッシュ

src/monster-floor/one-monster-placer.cpp, src/monster/monster-flag-types.h, src/monster/monster-processor.cpp, src/monster/monster-status-setter.cpp, src/monster/monster-status-setter.h, src/monster/monster-util.cpp, src/monster/monster-util.h, src/mspell/mspell-floor.cpp
=> グローバル変数 hack_m_idx を削除する

src/autopick/autopick-entry.cpp, src/autopick/autopick-matcher.cpp, src/cmd-action/cmd-spell.cpp, src/object-hook/hook-magic.cpp, src/object/object-info.cpp, src/player/player-realm.cpp, src/player/player-realm.h, src/util/object-sort.cpp
=> get_realm*_book をPlayerRealmクラスのメンバ関数にする

src/birth/birth-select-realm.cpp
#4357 の一環
PlayerTypeクラスのrealm1とrealm2に対する直接アクセスを減らすため、キャラメイク時の領域選択処理をリファクタリングする。
=> [Refactor] キャラメイク時の領域選択処理

lib/edit/MonraceDefinitions.jsonc, lib/file/mondeath.txt, lib/file/monspeak.txt
May resolve https://github.com/hengband/hengband/issues/4385 .
These changes are coming from someone who does not know Japanese and is not familiar with the source material, so it would be helpful if a reviewer checked that the changes are still consistent with the Japanese text.
=> English: clarify text for Mika Misono

src/monster-floor/one-monster-placer.cpp, src/monster/monster-list.cpp, src/monster/monster-list.h, src/monster/monster-processor.cpp
=> [Refactor] カメレオンの種族選択処理のモンスターの位置情報への依存をなくした

src/wizard/wizard-special-process.cpp
デバッグコマンドで種族・職業・領域を変更する時に、既存のID番号を入力する方法は該当の番号をいちいち調べなくてはならず面倒なので、リストから選択できるようにする。
=> [Feature] デバッグコマンドの種族・職業・領域変更をリストから選択

configure.ac, doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.1.17-Beta

src/monster-floor/one-monster-placer.cpp
=> [Refactor] カメレオンの変身処理を種族番号の代入処理に統合した

src/combat/shoot.cpp, src/effect/effect-monster.cpp, src/floor/floor-generator.cpp, src/load/old/load-v1-5-0.cpp, src/melee/melee-postprocess.cpp, src/melee/melee-spell-flags-checker.cpp, src/monster-floor/monster-move.cpp, src/monster-floor/monster-move.h, src/monster-floor/one-monster-placer.cpp, src/monster/monster-info.cpp, src/monster/monster-processor.cpp, src/monster/monster-status-setter.cpp, src/monster/monster-status-setter.h, src/mspell/mspell-attack.cpp, src/spell-kind/spells-teleport.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h
=> set_target()（及びreset_target()）、set_friendly() をMonsterEntity に組み込んだ

configure.ac, doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.1.18-Beta

src/cmd-action/cmd-pet.cpp, src/core/game-play.cpp, src/floor/floor-leaver.cpp, src/load/extra-loader.cpp, src/mind/mind-cavalry.cpp, src/monster-floor/monster-remover.cpp, src/monster/monster-flag-types.h, src/pet/pet-fall-off.cpp, src/pet/pet-util.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h
=> [Refactor] MonsterConstantFlagType に騎乗フラグを追加した

src/core/player-processor.cpp, src/effect/effect-monster-oldies.cpp, src/effect/effect-monster-spirit.cpp, src/effect/effect-monster-util.cpp, src/effect/effect-monster-util.h, src/effect/effect-monster.cpp, src/effect/effect-player-spirit.cpp, src/effect/effect-player.cpp, src/effect/effect-player.h, src/floor/floor-leaver.cpp, src/hpmp/hp-mp-regenerator.cpp, src/melee/melee-postprocess.cpp, src/melee/monster-attack-monster.cpp, src/monster-attack/monster-attack-switcher.cpp, src/monster-attack/monster-eating.cpp, src/monster-attack/monster-eating.h, src/monster-floor/monster-remover.cpp, src/monster/monster-compaction.cpp, src/monster/monster-damage.cpp, src/monster/monster-processor.cpp, src/monster/monster-status-setter.cpp, src/monster/monster-update.cpp, src/mspell/mspell-special.cpp, src/mspell/mspell-status.cpp, src/pet/pet-util.cpp, src/spell-kind/spells-polymorph.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h, src/target/target-preparation.cpp
=> [Refactor] モンスターの騎乗判定をモンスター自身の騎乗フラグでするようにした

src/effect/effect-monster-spirit.cpp, src/effect/effect-monster-util.cpp, src/effect/effect-monster-util.h, src/effect/effect-player-spirit.cpp, src/effect/effect-player.cpp, src/effect/effect-player.h
Fix #4466 
src_idx が-1 になるケースは検索したところデバッグコマンドによるものしかなかったが、やや重大なエンバグと思われるため優先度はHIGHとしておく
=> [Fix] src_ptr がsrc_idx のチェックをしておらず、-1 などが入ると範囲外アクセスエラーを起こしてしまうバグを修正

lib/edit/MonraceDefinitions.jsonc
=> [Feature] レアおたずねものムシの英名の誤りを訂正

src/lore/combat-types-setter.cpp
Close #4476 
詳細は紐付けしてあるIssue 参照
=> 攻撃方法"CRUSH" の誤訳を修正

src/birth/game-play-initializer.cpp, src/dungeon/dungeon-processor.cpp, src/floor/floor-generator.cpp, src/load/player-info-loader.cpp, src/load/world-loader.cpp, src/market/melee-arena.cpp, src/market/melee-arena.h, src/save/player-writer.cpp, src/system/building-type-definition.cpp, src/system/building-type-definition.h, src/wizard/wizard-game-modifier.cpp, src/world/world-turn-processor.cpp
動作は問題なさそうです
monraces\_info への依存がこれで減らせました
ご確認下さい
=> モンスター闘技場のエントリーとそのオッズをMeleeArena/MeleeGladiator に繰り込んだ

src/market/melee-arena.cpp, src/system/building-type-definition.cpp, src/system/building-type-definition.h, src/world/world-turn-processor.cpp
developと動作が変わらないことを確認済です (引き分けだけは再現が極めて困難なので放置)
getter/setter もできればカプセル化したいところですが現時点ではここまでで妥協しました
ご確認下さい
=> モンスター闘技場に関するグローバル変数をMeleeArena クラスへ繰り込んだ

lib/edit/MonraceDefinitions.jsonc
https://github.com/hengband/hengband/issues/4500
こちらの実装になります。
=> [Add]モンスター「這いずる粘体」、「タイタン・ゾンビ」を追加

src/info-reader/race-reader.cpp, src/lore/lore-util.cpp, src/lore/lore-util.h, src/lore/monster-lore.cpp, src/monster-floor/monster-generator.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h, src/view/display-lore.cpp
リテラル型のtupleより表現力が上がったと思います
一応思い出表示はdevelopと同じであることをチェックしました (年経たエレメンタル)
ご確認下さい
=> モンスターの指定護衛をクラス化した

src/Makefile.am, src/term/z-rand.cpp, src/term/z-rand.h, src/test/test-probability-table.cpp, src/util/probability-table.h
Resolves #4462 
今回追加したテストコードで想定通りの確率で抽選される事を確認済みです。
=> ProbabilityTableクラスの確率分布生成に std::discrete_distribution を使用する 

src/wizard/wizard-special-process.cpp
=> [Refactor] `NUM_O_SET` / `NUM_O_BIT` をローカルconstに更新。

lib/edit/MonraceDefinitions.jsonc
https://github.com/hengband/hengband/issues/4511
上記issueの実装となります。
=> [Add]モンスター「虹色の宝箱」、「金色の宝箱」、「石の宝箱」を追加

lib/edit/MonraceDefinitions.jsonc
=> [Feature] #4546 虹色の宝箱にテレポート耐性を追加

lib/edit/MonraceDefinitions.jsonc
ゲーム性に大きな変化をもたらす性能ではないと思われるためIssueはなし
=> モンスター「デカアゴムシ」と「スネッコ」を追加

lib/edit/ArtifactDefinitions.jsonc
Adds some missing artifact flavours for English.
=> English: additional artifact flavours

src/core/game-play.cpp, src/floor/fixed-map-generator.cpp, src/io/interpret-pref-file.cpp, src/knowledge/knowledge-monsters.cpp, src/knowledge/knowledge-uniques.cpp, src/object-enchant/others/apply-magic-others.cpp, src/system/dungeon-info.cpp, src/view/display-lore.cpp, src/view/display-lore.h, src/window/display-sub-windows.cpp
全部は差し替えていないです
(差分がえげつなくなるのと、個別にモデル化が必要な箇所が多いため)
#4516 を前提にしているので、マージまではドラフトにしておきます
=> monraces_info へ直接アクセスしている箇所を削減した

lib/edit/ArtifactDefinitions.jsonc
Those parsing errors are a regression from https://github.com/hengband/hengband/pull/4469 .  Resolves https://github.com/hengband/hengband/issues/4548 .
=> Add commas to artifact definitions to avoid JSON parsing errors

src/birth/game-play-initializer.cpp, src/floor/fixed-map-generator.cpp, src/floor/floor-changer.cpp, src/floor/floor-generator.cpp, src/floor/floor-save.cpp, src/load/floor-loader.cpp, src/load/old/load-v1-5-0.cpp, src/monster-floor/monster-remover.cpp, src/monster-floor/one-monster-placer.cpp, src/monster/monster-list.cpp, src/monster/monster-status.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
#4531 の後続PRなのでこれがマージされるまではドラフトにしておきます
大枠の目的は目的はProjects の通りなので完全なカプセル化まではやっていません
後ほど別PRで実施します
ご確認下さい
=> MonsterRaceInfo::cur_num を部分的にカプセル化した

src/monster/monster-damage.cpp, src/monster/monster-damage.h, src/system/monster-race-info.cpp, src/system/monster-race-info.h, src/wizard/monster-info-spoiler.cpp
=> monraces_info への直接アクセスをメソッドに書き換えた その15

src/lore/lore-util.cpp
Discordでいくらか議論はあるようですが明確な反対意見ではなさそうなのでPRとして提出します
ご確認下さい
=> モンスターの加速表記を細分化した

src/dungeon/quest.cpp, src/monster-race/monster-race-hook.cpp, src/monster/monster-info.cpp, src/monster/monster-info.h, src/monster/monster-list.cpp, src/mspell/mspell-summon.cpp, src/system/monster-entity.cpp, src/system/monster-entity.h, src/system/monster-race-info.cpp, src/system/monster-race-info.h
掲題の通りです
#4550 の後続チケットなので、マージされるまではドラフトにしておきます
=> monraces_info へ直接アクセスしている箇所を削減した その16

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/dungeon/dungeon-processor.cpp, src/floor/floor-generator.cpp, src/io/screen-util.cpp, src/monster-floor/monster-remover.cpp, src/monster-floor/one-monster-placer.cpp, src/monster/monster-compaction.cpp, src/monster/monster-status-setter.cpp, src/monster/monster-status.cpp, src/monster/monster-status.h, src/monster/monster-timed-effect-types.h, src/monster/monster-timed-effects.cpp, src/monster/monster-timed-effects.h, src/save/monster-entity-writer.cpp, src/save/save.cpp, src/spell-kind/spells-polymorph.cpp, src/system/floor-type-definition.cpp, src/system/floor-type-definition.h, src/system/monster-entity.cpp, src/system/monster-entity.h, src/window/main-window-row-column.cpp, src/window/main-window-row-column.h, src/world/world-turn-processor.cpp
掲題の通りです
併せて、mproc に関連する一部FloorType を引数とするグローバル関数をオブジェクトメソッドへ繰り込みました
ご確認下さい
=> FloorType::mproc_list/mproc_max とMonsterEntity::mproc をmap に変えた

src/lore/lore-util.cpp
=> モンスターの加速表記に亜光速、光速を追加した

src/birth/auto-roller.cpp, src/birth/birth-util.cpp, src/birth/birth-util.h, src/birth/birth-wizard.cpp, src/birth/character-builder.cpp, src/cmd-io/cmd-gameoption.cpp, src/cmd-io/cmd-gameoption.h, src/game-option/option-types-table.cpp, src/game-option/option-types-table.h, src/io/interpret-pref-file.cpp, src/io/report.cpp, src/main/game-data-initializer.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-elementalist.h, src/racial/racial-draconian.cpp, src/save/info-writer.cpp, src/system/enums/game-option-page.h, src/wizard/wizard-special-process.cpp
掲題の通りです
先行チケット#4557 がマージされるまでドラフトにしておきます
=> enum game_option_page をenum class GameOpenPage に変えた

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/grid/grid.cpp, src/monster-floor/monster-safety-hiding.cpp, src/monster-floor/monster-sweep-grid.cpp, src/system/enums/grid-flow.h, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h, src/system/monster-race-info.cpp, src/system/monster-race-info.h, src/target/target-describer.cpp
掲題の通りです
周辺コードも整備しました (配列のmap 化やconcptr のstring 化など)
先行チケット#4561 がマージされるまではドラフトにしておきます
=> enum flow_type をenum class GridFlow に変えた

src/info-reader/race-reader.cpp
デッドコードが残っているのを見つけました
削除しましたのでご確認下さい
=> 「モンスター希少度範囲外」のエラーはリファクタリングの過程で不要になったはずが残ってしまっていたのを修正

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/core/magic-effects-timeout-reducer.cpp, src/load/player-info-loader.cpp, src/monster-attack/monster-attack-player.cpp, src/mspell/mspell-dispel.cpp, src/object-activation/activation-switcher.cpp, src/object-use/read/scroll-read-executor.cpp, src/player-info/body-improvement-info.cpp, src/player-info/self-info.cpp, src/realm/realm-craft.cpp, src/realm/realm-crusade.cpp, src/save/player-writer.cpp, src/spell/spells-staff-only.cpp, src/status/body-improvement.cpp, src/status/body-improvement.h, src/status/buff-setter.cpp, src/system/player-type-definition.h, src/timed-effect/player-protection.cpp, src/timed-effect/player-protection.h, src/timed-effect/timed-effects.cpp, src/timed-effect/timed-effects.h, src/window/main-window-stat-poster.cpp
対邪悪結界をクラス化しました
巻物でターン数が更新されること (重ねがけ無制限)、切れたらメッセージが表示されることをチェック済です
ご確認下さい
=> PlayerProtection クラスを作った

src/action/open-close-execution.cpp, src/cmd-action/cmd-open-close.cpp, src/floor/cave-generator.cpp, src/floor/fixed-map-generator.cpp, src/floor/floor-changer.cpp, src/floor/object-allocator.cpp, src/grid/feature.cpp, src/grid/feature.h, src/grid/grid.cpp, src/grid/grid.h, src/monster-floor/monster-move.cpp, src/spell-kind/spells-grid.cpp, src/spell-realm/spells-chaos.cpp, src/system/dungeon-info.cpp, src/system/dungeon-info.h
掲題の通りですが、準備コミットがいくつかあります
関数ポインタがなくなったことによりPlayerType への依存性が低下しましたが、これに関しては次のチケットで対応します
併せてご確認下さい
=> count_dt() の引数から関数ポインタを除去した

src/floor/fixed-map-generator.cpp, src/floor/floor-object.cpp, src/floor/floor-object.h, src/grid/object-placer.cpp, src/monster-floor/monster-death.cpp, src/object/object-info.h, src/specific-object/chest.cpp, src/system/floor-type-definition.cpp, src/system/floor-type-definition.h
自然配置、通常の財宝ドロップ、クリーピングコインいずれも正常動作しています
ご確認下さい
=> make_gold() をFloorType のオブジェクトメソッドへ繰り込んだ

src/action/weapon-shield.cpp, src/autopick/autopick.cpp
※ その15まで続きます
src/ 以下のフォルダの頭文字で順次対応しました
詳細はコミットコメントをご確認下さい
先行チケット#4582 がマージされるまではドラフトにしておきます
=> describe_flavor() を呼び出している箇所のコード整形 その1

src/autopick/autopick-destroyer.cpp, src/autopick/autopick-matcher.cpp, src/cmd-item/cmd-destroy.cpp, src/inventory/inventory-object.cpp, src/load/store-loader.cpp, src/spell-realm/spells-sorcery.cpp, src/store/home.cpp, src/store/pricing.cpp, src/store/sell-order.cpp, src/store/service-checker.cpp, src/store/store-util.cpp, src/store/store.cpp, src/system/item-entity.cpp, src/system/item-entity.h, src/util/object-sort.cpp, src/util/object-sort.h, src/window/display-sub-windows.cpp, src/wizard/items-spoiler.cpp
=> [Refactor] object_sort_comp 関数のシグネチャ調整

src/load/store-loader.cpp, src/store/home.cpp, src/store/store-util.cpp
=> [Refactor] 店舗のアイテム一覧の挿入/削除/並び替え処理 

src/cmd-item/cmd-equipment.cpp, src/effect/effect-item.cpp
※ その15まで続きます
src/ 以下のフォルダの頭文字で順次対応しました
詳細はコミットコメントをご確認下さい
=> describe_flavor() を呼び出している箇所のコード整形 その2

src/floor/floor-object.cpp, src/floor/floor-streams.cpp, src/floor/object-scanner.cpp
=> describe_flavor() を呼び出している箇所のコード整形 その3

src/hpmp/hp-mp-processor.cpp
=> describe_flavor() を呼び出している箇所のコード整形 その4

src/inventory/inventory-curse.cpp, src/inventory/inventory-damage.cpp, src/inventory/inventory-object.cpp, src/inventory/inventory-util.cpp, src/inventory/pack-overflow.cpp, src/inventory/player-inventory.cpp, src/inventory/recharge-processor.cpp
=> describe_flavor() を呼び出している箇所のコード整形 その5

src/artifact/fixed-art-generator.cpp, src/artifact/fixed-art-generator.h, src/floor/floor-object.cpp, src/system/floor-type-definition.cpp, src/system/floor-type-definition.h
このPRではメソッドを丸ごと移しただけです
個別のオブジェクトへ移していく作業は別途行います
ご確認下さい
=> make_artifact_special() をFloorType のオブジェクトメソッドへ繰り込んだ

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/cmd-action/cmd-open-close.cpp, src/grid/grid.cpp, src/grid/grid.h, src/system/dungeon-info.cpp, src/system/dungeon-info.h, src/system/enums/grid-count-kind.h, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h
(後続チケットが後2つあります)
#3729 の続きです
証人クエでのドア開け閉め、箱を開ける操作に問題はありませんでした
ご確認下さい
=> count_dt() をFloorType へ繰り込むための準備

src/knowledge/knowledge-inventory.cpp, src/market/building-craft-fix.cpp, src/market/building-craft-weapon.cpp, src/monster-floor/monster-object.cpp
一部、ファイルスコープstatic関数の引数も調整しています
それも含めて単純置換です
ご確認下さい
=> describe_flavor() を呼び出している箇所のコード整形 その6

src/grid/grid.cpp, src/system/dungeon-info.cpp, src/system/floor-type-definition.cpp, src/system/floor-type-definition.h
掲題の通りです
FloorType もモデルクラスとして少しずつ育ってきました
ご確認下さい
=> FloorType::check_terrain() を実装してcount_dt() を軽量化した

src/room/rooms-trap.cpp
=> rooms-trap.cpp を整形した

src/knowledge/knowledge-monsters.cpp, src/knowledge/knowledge-uniques.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
unique\_list\_type を中心に設計を改善しました
ご確認下さい
=> monraces_info へのアクセスをMonraceList に差し替えた その18

src/room/rooms-vault.cpp
掲題の通りです
#4626 がマージされるまではドラフトにしておきます
=> rooms-vault.cpp を整形した

src/spell-kind/spells-enchant.cpp, src/spell-kind/spells-equipment.cpp, src/spell-kind/spells-fetcher.cpp, src/spell-kind/spells-perception.cpp, src/spell-realm/spells-sorcery.cpp, src/spell/spells-object.cpp, src/spell/spells-status.cpp
単純置換です (1箇所、moveしている箇所でコピー警告が出ていたので右辺値参照へ切り替え)
#4612 がマージされるまでドラフトにしておきます
=> describe_flavor() を呼び出している箇所のコード整形 その8

src/lore/lore-calculator.cpp, src/lore/lore-calculator.h, src/lore/lore-util.cpp, src/lore/lore-util.h, src/system/monster-race-info.cpp, src/system/monster-race-info.h, src/view/display-lore-attacks.cpp, src/view/display-lore-status.cpp, src/view/display-lore.cpp
思い出関連の調整です
#4631 がマージされるまではドラフトにしておきます
=> monraces_info へのアクセスをMonraceList に差し替えた その19

src/store/cmd-store.cpp, src/store/store-util.cpp, src/store/store-util.h, src/store/store.cpp, src/store/store.h
forge 変数を廃止しました
https://github.com/hengband/hengband/pull/4613 がマージされるまでドラフトにしておきます
=> describe_flavor() を呼び出している箇所のコード整形 その9

src/action/movement-execution.cpp, src/action/open-close-execution.cpp, src/action/travel-execution.cpp, src/cmd-action/cmd-open-close.cpp, src/cmd-action/cmd-travel.cpp, src/effect/effect-feature.cpp, src/floor/floor-streams.cpp, src/floor/floor-util.cpp, src/grid/feature.cpp, src/grid/feature.h, src/grid/grid.cpp, src/grid/grid.h, src/grid/trap.cpp, src/mind/mind-berserker.cpp, src/monster-floor/monster-move.cpp, src/monster-floor/monster-sweep-grid.cpp, src/object/warning.cpp, src/player/player-move.cpp, src/realm/realm-hissatsu.cpp, src/room/rooms-special.cpp, src/room/rooms-vault.cpp, src/system/floor-type-definition.cpp, src/system/floor-type-definition.h
#4605 の後続チケットです
マージされるまではドラフトにしておきます
=> グローバル関数is_open()、is_closed_door()、is_trap() を廃止した

src/floor/floor-leaver.cpp, src/floor/geometry.cpp, src/monster-floor/monster-direction.cpp, src/monster/monster-update.cpp, src/mspell/mspell-lite.cpp
#4595 で、get\_position() を2回呼んだりして非効率なところを効率化しました
ご確認下さい
※ 不具合ではないです、get\_position() は内部の状態が変わらない限り冪等性があります
=> projectable() の変換漏れを微調整した

src/system/artifact-type-definition.cpp, src/system/artifact-type-definition.h, src/system/floor-type-definition.cpp
メソッド全体をprivate化するのは次のPRで行います
ご確認下さい
=> try_make_instant_artifact() でArtifactType に依存する箇所をオブジェクトメソッドへ繰り込んだ

src/target/target-describer.cpp, src/view/display-inventory.cpp, src/view/object-describer.cpp
単純置換です
https://github.com/hengband/hengband/pull/4614 がマージされるまでドラフトにしておきます
=> describe_flavor() を呼び出している箇所のコード整形 その10

src/system/artifact-type-definition.cpp, src/system/artifact-type-definition.h, src/system/floor-type-definition.cpp
public メソッドをprivate メソッドに変えるなどしました
#4601 がマージされるまでドラフトにしておきます
=> ArtifactType とArtifactList のカプセル化を向上させた

src/main-win.cpp, src/main-win/main-win-cfg-reader.cpp, src/main-win/main-win-cfg-reader.h, src/main-win/main-win-music.cpp, src/main-win/main-win-music.h, src/main-win/main-win-sound.cpp, src/main-win/main-win-utils.h
BGM/効果音周りを調整しました
鳴ることは確認済です
#4632 がマージされるまではドラフトにしておきます
=> monraces_info へのアクセスをMonraceList に差し替えた その20

src/window/display-sub-windows.cpp, src/window/main-window-equipments.cpp, src/window/main-window-util.cpp, src/wizard/artifact-analyzer.cpp
単純置換です
https://github.com/hengband/hengband/pull/4615 がマージされるまでドラフトにしておきます
=> describe_flavor() を呼び出している箇所のコード整形 その11

src/floor/cave-generator.cpp, src/floor/floor-streams.cpp, src/floor/floor-streams.h, src/floor/tunnel-generator.cpp, src/floor/tunnel-generator.h, src/grid/feature-generator.cpp, src/grid/feature-generator.h, src/room/room-generator.cpp, src/room/room-generator.h, src/room/rooms-city.cpp, src/room/rooms-city.h, src/room/rooms-fractal.cpp, src/room/rooms-fractal.h, src/room/rooms-nest.cpp, src/room/rooms-nest.h, src/room/rooms-normal.cpp, src/room/rooms-normal.h, src/room/rooms-pit.cpp, src/room/rooms-pit.h, src/room/rooms-special.cpp, src/room/rooms-special.h, src/room/rooms-trap.cpp, src/room/rooms-trap.h, src/room/rooms-vault.cpp, src/room/rooms-vault.h, src/room/space-finder.cpp, src/room/space-finder.h, src/system/dungeon-data-definition.h
掲題の関数を整形するのが中心です
#4627 がマージされるまではドラフトにしておきます
=> find_space() の引数を差し替える準備 その1

src/monster/monster-list.cpp, src/monster/monster-status.cpp
モンスター経験値周りを調整しました
#4633 がマージされるまではドラフトにしておきます
=> monraces_info へのアクセスをMonraceList に差し替えた その21

src/effect/effect-monster-curse.cpp, src/effect/effect-monster-oldies.cpp, src/effect/effect-monster-spirit.cpp, src/effect/effect-monster-switcher.cpp, src/effect/effect-monster-util.cpp, src/effect/effect-monster-util.h, src/effect/effect-monster.cpp, src/effect/effect-player-spirit.cpp, src/effect/effect-player.cpp, src/effect/effect-player.h, src/mind/mind-elementalist.cpp
monraces\_info とは直接関係ないですが準備の一環です
#4634 がマージされるまではドラフトにしておきます
=> EffectPlayer/EffectMonster のカプセル化を推し進めた

src/monster/monster-util.cpp, src/system/dungeon-info.h
dungeon\_type 周りを調整しました
#4635 がマージされるまではドラフトにしておきます
=> monraces_info へのアクセスをMonraceList に差し替えた その23

src/system/item-entity.cpp, src/system/item-entity.h, src/system/monster-race-info.cpp, src/system/monster-race-info.h
掲題の通りです
https://github.com/hengband/hengband/pull/4618 がマージされるまでドラフトにしておきます
=> ItemEntity からMonraceId が陽に見えないようにした

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/floor/cave-generator.cpp, src/floor/cave-generator.h, src/floor/floor-generator.cpp, src/floor/floor-streams.cpp, src/floor/tunnel-generator.cpp, src/room/space-finder.cpp, src/system/dungeon-data-definition.cpp, src/system/dungeon-data-definition.h
コンストラクタ整備、define 定数の廃止などです
#4628 がマージされるまではドラフトにしておきます
=> DungeonData のクラス化とカプセル化を推し進めた

src/floor/cave-generator.cpp, src/floor/tunnel-generator.cpp, src/floor/tunnel-generator.h
build\_tunnel() とbuild\_tunnel2() の引数をPos2D に変えました
#4629 がマージされるまではドラフトにしておきます
=> find_space() の引数を差し替える準備 その2

src/cmd-item/cmd-eat.cpp, src/core/object-compressor.cpp, src/flavor/flavor-describer.cpp, src/floor/floor-events.cpp, src/inventory/recharge-processor.cpp, src/item-info/flavor-initializer.cpp, src/market/building-recharger.cpp, src/mind/mind-mage.cpp, src/monster-attack/monster-eating.cpp, src/object-activation/activation-util.cpp, src/object-enchant/item-magic-applier.cpp, src/object-enchant/others/apply-magic-others.cpp, src/object-use/quaff/quaff-execution.cpp, src/object-use/read/read-execution.cpp, src/object-use/use-execution.cpp, src/object-use/zaprod-execution.cpp, src/object-use/zapwand-execution.cpp, src/object/object-stack.cpp, src/object/object-value.cpp, src/perception/object-perception.cpp, src/racial/racial-android.cpp, src/spell-kind/magic-item-recharger.cpp, src/store/store-util.cpp, src/system/baseitem/baseitem-definition.cpp, src/system/baseitem/baseitem-definition.h, src/system/baseitem/baseitem-list.cpp, src/system/item-entity.cpp, src/system/item-entity.h, src/wizard/items-spoiler.cpp, src/wizard/wizard-item-modifier.cpp
level, pval, cost の3つです
ご確認下さい
#4623 がマージされるまではドラフトにしておきます
=> ベースアイテムに直接アクセスしている箇所をItemEntity でカプセル化した

src/artifact/random-art-generator.cpp, src/birth/inventory-initializer.cpp, src/cmd-item/cmd-eat.cpp, src/floor/floor-object.cpp, src/io-dump/random-art-info-dumper.cpp, src/market/bounty.cpp, src/mind/mind-archer.cpp, src/object-enchant/others/apply-magic-others.cpp, src/object-use/quaff/quaff-execution.cpp, src/object-use/read/read-execution.cpp, src/object-use/use-execution.cpp, src/object-use/zaprod-execution.cpp, src/object-use/zapwand-execution.cpp, src/perception/object-perception.cpp, src/perception/object-perception.h, src/player/process-death.cpp, src/smith/object-smith.cpp, src/spell-kind/spells-perception.cpp, src/spell/spells-object.cpp, src/store/purchase-order.cpp, src/wizard/artifact-analyzer.cpp, src/wizard/artifact-analyzer.h, src/wizard/fixed-artifacts-spoiler.cpp, src/wizard/wizard-special-process.cpp
掲題の通りです
コンパイルが通る程度の差し替えのみなのでほぼ機械的置換です
ご確認下さい
=> 店のアイテムに関するunique_ptr.get() を参照に変えた その3

src/monster-floor/monster-generator.cpp, src/mspell/summon-checker.cpp
=> monraces_info へのアクセスをMonraceList に差し替えた その25

src/monster-floor/monster-summon.cpp, src/mspell/mspell-damage-calculator.cpp, src/mspell/mspell-damage-calculator.h, src/mspell/specified-summon.cpp, src/save/save.cpp, src/spell-kind/spells-polymorph.cpp, src/store/rumor.cpp
=> monraces_info へのアクセスをMonraceList に差し替えた その26

src/market/bounty.cpp, src/monster-floor/one-monster-placer.cpp, src/system/item-entity.cpp, src/system/item-entity.h, src/system/monster-entity.cpp, src/window/main-window-util.cpp, src/wizard/wizard-game-modifier.cpp
これで粗方片付きました
ご確認下さい
(ここからは大量差分の複雑なリファクタリングになっていく予定です)
=> monraces_info へのアクセスをMonraceList に差し替えた その27

src/artifact/random-art-generator.cpp, src/cmd-item/cmd-item.cpp, src/knowledge/knowledge-items.cpp, src/perception/identification.cpp, src/perception/identification.h, src/spell-kind/spells-perception.cpp, src/store/black-market.cpp, src/store/black-market.h, src/store/home.cpp, src/store/pricing.cpp, src/store/pricing.h, src/store/purchase-order.cpp, src/store/sell-order.cpp, src/store/store.cpp, src/view/display-store.cpp
一部引数の調整も行っていますが概ね単純置換です
ご確認下さい
この次のPRで```ItemEntity &item = *store_type::stock[i]``` への転換を行います
=> store_type::stock.get() を消滅させた

src/info-reader/race-reader.cpp, src/main/info-initializer.cpp, src/monster-floor/monster-generator.cpp, src/room/rooms-nest.cpp, src/room/rooms-pit.cpp, src/system/monster-race-info.cpp, src/system/monster-race-info.h
=> monraces_info へのアクセスをMonraceList に差し替えた その28

src/load/store-loader.cpp, src/market/building-initializer.cpp, src/save/info-writer.cpp, src/save/info-writer.h, src/store/store-util.cpp, src/store/store-util.h, src/system/floor/town-info.cpp, src/system/floor/town-info.h, src/system/floor/town-list.cpp, src/system/floor/town-list.h
#4688 の後続チケットです
単純置換 (ファイル名変更＋移動)だけです
ご確認下さい
=> townとstore を構造体からクラスへ変えた

src/floor/cave-generator.cpp, src/room/rooms-city.cpp, src/room/rooms-fractal.cpp, src/room/rooms-maze-vault.cpp, src/room/rooms-maze-vault.h, src/room/rooms-nest.cpp, src/room/rooms-normal.cpp, src/room/rooms-pit.cpp, src/room/rooms-special.cpp, src/room/rooms-trap.cpp, src/room/rooms-vault.cpp, src/room/space-finder.cpp, src/room/space-finder.h
本体作業です
変更範囲のシグネチャもいくつか修正しています
ご確認下さい
=> find_space() の引数からポインタを削除し、戻り値をoptional に変えた

src/artifact/random-art-generator.cpp, src/artifact/random-art-misc.cpp, src/birth/birth-wizard.cpp, src/birth/inventory-initializer.cpp, src/floor/wild.cpp, src/grid/grid.cpp, src/mind/mind-archer.cpp, src/monster-attack/monster-attack-switcher.cpp, src/monster-attack/monster-eating.cpp, src/monster-floor/one-monster-placer.cpp, src/monster/monster-status.cpp, src/mutation/mutation-processor.cpp, src/object-enchant/object-boost.cpp, src/save/floor-writer.cpp, src/save/save.cpp, src/spell-kind/spells-teleport.cpp, src/status/shape-changer.cpp, src/store/store.cpp, src/term/z-rand.h
```)rand``` で検索した結果を全部置換しました
enum へのキャストはi2enum にしましたが、これは別途修正します
ご確認下さい
=> randint0 の不適切なキャストをrandnum0<T> に置き換えた

src/store/black-market.cpp, src/store/black-market.h, src/store/museum.cpp, src/store/purchase-order.cpp, src/store/sell-order.cpp, src/store/store-util.cpp, src/store/store-util.h, src/store/store.cpp
#4695 の後続チケットです
developと同じ品揃えになることをチェック済です
GitHub Actions環境でビルドエラーが出ていることも含め、マージされるまでドラフトにしておきます
=> 店に関するグローバル関数をStore クラスのメソッドへ繰り込んだ その1

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/grid/feature.cpp, src/grid/feature.h, src/info-reader/feature-info-tokens-table.cpp, src/info-reader/feature-info-tokens-table.h, src/info-reader/feature-reader.cpp, src/info-reader/feature-reader.h, src/io/cursor.cpp, src/main/info-initializer.cpp, src/system/enums/terrain/terrain-tag.h, src/system/terrain-type-definition.cpp, src/system/terrain-type-definition.h, src/view/display-symbol.h
(このPRはまだレビュー対象ではありません。かなりドラスティックに弄ったのでGCC/Clang環境で正常にコンパイルできるか確かめるものです。後で3つくらいに分割して正式に提出します)
=> 地形IDを動的に引く仕組みの構築 その1

.github/workflows/publish-spoiler-page.yml
upload-artifactと同様にdownload-artifactのバージョンも更新する必要があったので更新する。
=> [Chore] download-artifactのバージョンをv4に更新

src/floor/floor-generator.cpp, src/floor/wild.cpp, src/grid/feature.cpp, src/grid/feature.h, src/info-reader/feature-info-tokens-table.cpp, src/info-reader/feature-reader.cpp, src/load/old/load-v1-5-0.cpp, src/system/enums/terrain/terrain-tag.h, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h, src/target/target-describer.cpp
先行チケットがマージされるまでドラフトにしておきます
feat\_none と同様の手順でfeat\_floor も廃止しました
ご確認下さい
=> 地形IDを動的に引く仕組みの構築 その4

src/effect/effect-feature.cpp, src/grid/feature.cpp, src/grid/feature.h, src/info-reader/feature-info-tokens-table.cpp, src/info-reader/feature-reader.cpp, src/load/old/load-v1-5-0.cpp, src/mind/mind-mirror-master.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-class/spells-mirror-master.h, src/spell-kind/spells-grid.cpp, src/system/enums/terrain/terrain-tag.h
今回は小規模だったので3件実施しました
ご確認下さい
先行チケットがマージされるまでドラフトにしておきます
=> 地形IDを動的に引く仕組みの構築 その5

src/dungeon/quest-completion-checker.cpp, src/floor/cave-generator.cpp, src/floor/floor-changer.cpp, src/floor/floor-streams.cpp, src/floor/floor-streams.h, src/grid/feature.cpp, src/grid/feature.h, src/grid/stair.cpp, src/grid/stair.h, src/info-reader/feature-info-tokens-table.cpp, src/info-reader/feature-reader.cpp, src/load/floor-loader.cpp, src/load/old/load-v1-5-0.cpp, src/room/rooms-normal.cpp, src/spell-kind/spells-grid.cpp, src/system/enums/terrain/terrain-tag.h, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h
階段×2 を繰り込みました
これに伴いstair.cpp/h をfloor-info.cpp/h へ吸収合併しています
ご確認下さい
=> 地形IDを動的に引く仕組みの構築 その6

src/birth/game-play-initializer.cpp, src/cmd-action/cmd-move.cpp, src/core/score-util.cpp, src/dungeon/dungeon-processor.cpp, src/io-dump/character-dump.cpp, src/io/report.cpp, src/io/write-diary.cpp, src/knowledge/knowledge-features.cpp, src/knowledge/knowledge-quests.cpp, src/load/load-zangband.cpp, src/load/world-loader.cpp, src/main/game-data-initializer.cpp, src/market/bounty.cpp, src/player/player-status.cpp, src/save/player-writer.cpp, src/spell-kind/spells-world.cpp, src/store/rumor.cpp, src/system/building-type-definition.cpp, src/system/dungeon/dungeon-record.cpp, src/system/dungeon/dungeon-record.h, src/world/world-movement-processor.cpp
max\_dlv[] のラッパーです
まだ単純な差し替えで、クラスのモデル化は別途実施中です
ご確認下さい
=> ダンジョンの最深階層を保持するクラスDungeonRecord 及びその集合論的クラスDungeonRecords クラスを作った

configure.ac, doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Version] 3.0.1.22-Beta

lib/edit/MonraceDefinitions.jsonc
Resolves https://github.com/hengband/hengband/issues/4732 .
=> Correct English name and description for monster 1372

src/floor/cave-generator.cpp, src/floor/tunnel-generator.cpp, src/main-win.cpp, src/room/rooms-vault.cpp, src/view/display-map.cpp
Discord で議論した通りです、ご確認下さい
またWIN\_DEBUG のプリプロを定義したことで少しだけデバッグしやすくしました (わざとキャッチしないことでVSからトレースに移れる)
ご確認下さい
=> 階段昇降でクラッシュする場合がある事象を修正した

configure.ac, doxygen/Hengband.doxyfile, src/system/angband-version.h
=> [Release] 3.0.1.23-Beta

src/cmd-action/cmd-move.cpp, src/cmd-building/cmd-inn.cpp, src/core/game-play.cpp, src/info-reader/dungeon-reader.cpp, src/info-reader/dungeon-reader.h, src/io-dump/character-dump.cpp, src/load/world-loader.cpp, src/main/info-initializer.cpp, src/market/bounty.cpp, src/market/bounty.h, src/player/player-status.cpp, src/system/building-type-definition.cpp, src/system/dungeon/dungeon-definition.cpp, src/system/dungeon/dungeon-definition.h, src/system/dungeon/dungeon-list.cpp, src/system/dungeon/dungeon-list.h, src/system/dungeon/dungeon-record.cpp, src/system/dungeon/dungeon-record.h, src/world/world-turn-processor.cpp
=> 帰還先情報をDungeonRecords のメソッドへ繰り込んだ

src/knowledge/knowledge-features.cpp, src/spell-kind/spells-world.cpp, src/store/rumor.cpp, src/system/dungeon/dungeon-record.cpp, src/system/dungeon/dungeon-record.h
=> DungeonRecords::collect_entered_dungeons() を実装してダンジョン表記を統一化した

src/birth/birth-select-realm.cpp, src/mind/mind-weaponsmith.cpp
本質的なリファクタリング (無効値をoptional に変える、他)は別PRで実施します
ご確認下さい
=> 静的解析警告を除去した (3.0.1.23-Beta)

src/cmd-action/cmd-move.cpp, src/floor/wild.cpp, src/info-reader/dungeon-reader.cpp, src/load/world-loader.cpp, src/save/player-writer.cpp, src/spell-kind/spells-world.cpp, src/system/dungeon/dungeon-definition.cpp, src/system/dungeon/dungeon-definition.h, src/system/dungeon/dungeon-list.cpp, src/system/dungeon/dungeon-list.h, src/system/dungeon/dungeon-record.cpp, src/system/dungeon/dungeon-record.h, src/target/target-describer.cpp
現時点で全部shared\_ptr\<DungeonRecord\>で、const であるべき箇所にconst\_pointer\_cast を施していません
外から変更できてしまいますが、#4715 との兼ね合いもあるので別途対応します
=> DungeonList とDungeonRecords の要素をshared_ptr に変えた

src/cmd-action/cmd-mane.cpp, src/system/baseitem/baseitem-list.cpp, src/system/baseitem/baseitem-list.h, src/system/terrain/terrain-list.h
Fix #4758 
clang-15によるビルドチェックもCIにいれるべきか…
=> [Fix] clang-15でビルドエラー

src/core/game-play.cpp, src/core/score-util.cpp, src/dungeon/dungeon-processor.cpp, src/dungeon/quest-monster-placer.cpp, src/floor/cave-generator.cpp, src/floor/floor-generator.cpp, src/floor/floor-leaver.cpp, src/floor/pattern-walk.cpp, src/floor/wild.cpp, src/info-reader/dungeon-reader.cpp, src/io/write-diary.cpp, src/load/dungeon-loader.cpp, src/main/scene-table-floor.cpp, src/room/rooms-pit.cpp, src/save/floor-writer.cpp, src/spell-kind/spells-world.cpp, src/system/building-type-definition.cpp, src/system/building-type-definition.h, src/system/dungeon/dungeon-definition.cpp, src/system/dungeon/dungeon-definition.h, src/system/dungeon/dungeon-record.cpp, src/system/dungeon/dungeon-record.h, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/window/main-window-left-frame.cpp, src/wizard/wizard-special-process.cpp, src/world/world-movement-processor.cpp, src/world/world-turn-processor.cpp
全体の調整を行いました
ご確認下さい
(#4715 と同じなのでこちらはクローズします)
=> DungeonDefinition 周りのラップアップ

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/birth/inventory-initializer.cpp, src/core/player-processor.cpp, src/dungeon/quest.cpp, src/floor/cave-generator.cpp, src/floor/floor-generator.cpp, src/floor/wild.cpp, src/monster-floor/one-monster-placer.cpp, src/monster-race/monster-race-hook.cpp, src/monster/monster-util.cpp, src/monster/monster-util.h, src/object-enchant/others/apply-magic-others.cpp, src/player/eldritch-horror.cpp, src/room/rooms-nest.cpp, src/room/rooms-pit.cpp, src/room/rooms-special.cpp, src/system/building-type-definition.cpp, src/system/enums/monrace/monrace-hook-types.h, src/wizard/monrace-filter-debug-info.cpp, src/wizard/monrace-filter-debug-info.h
関数ポインタの塊を多少解しました (本体のhook1はまだ)
ご確認下さい
=> モンスター生成フィルタの2つ目を関数ポインタからenum class に差し替えた

src/autopick/autopick-entry.cpp, src/autopick/autopick-finder.cpp, src/core/show-file.cpp, src/core/show-file.h, src/util/string-processor.cpp, src/util/string-processor.h, src/wizard/wizard-item-modifier.cpp
=> [Refactor] str_tolower()のシグネチャの変更

src/floor/floor-generator.cpp
=> [Fix] 闘技場の地形が正しく生成されない

src/floor/cave-generator.cpp, src/floor/floor-generator.cpp, src/floor/wild.cpp, src/monster-floor/monster-generator.cpp, src/monster-floor/monster-summon.cpp, src/monster-race/monster-race-hook.cpp, src/monster-race/monster-race-hook.h, src/monster/monster-util.cpp, src/monster/monster-util.h, src/player/eldritch-horror.cpp
フィルタ本体の処理が強力発動コピペの嵐ですが、後で低減します (完全統合は無理)
ご確認下さい
=> 特殊なモンスター生成フィルタを個別のフィルタ関数に分割した

src/effect/effect-processor.cpp, src/mspell/mspell-judgement.cpp, src/spell/range-calc.cpp, src/spell/range-calc.h
激長関数の変数をまとめた影響もあり、恐らく合っているだろう……というレベルです
#4785 と同様の問題もあるかもしれません
ご確認下さい
=> breath_shape() の引数を調整し、FloorType::has_terrain_characteristics() 周りの整形を行う準備をした

src/cmd-action/cmd-move.cpp, src/cmd-building/cmd-building.cpp, src/grid/feature-generator.cpp, src/grid/feature.cpp, src/market/building-service.cpp, src/market/building-service.h, src/mind/mind-elementalist.cpp, src/room/cave-filler.cpp, src/spell-kind/earthquake.cpp
=> FloorType::has_terrain_characteristics() を呼び出している関数を整形した その2

src/monster-floor/monster-lite-util.cpp, src/monster-floor/monster-lite-util.h, src/monster-floor/monster-lite.cpp
本来はMonsterLite などといったクラスを作るべきかもしれませんが一旦見送りました
後ほどクラス化します
ご確認下さい
(せっかくなのでここもspanにしたいですが差分が多いのでやっぱり見送り)
=> update_mon_lite() を整形した

src/action/run-execution.cpp, src/combat/shoot.cpp, src/melee/melee-spell-flags-checker.cpp, src/melee/melee-spell-util.cpp, src/melee/melee-spell-util.h, src/mspell/mspell-judgement.cpp, src/mspell/mspell-judgement.h, src/mspell/mspell-lite.cpp, src/player-attack/player-attack.cpp, src/spell-realm/spells-chaos.cpp, src/target/projection-path-calculator.cpp, src/target/projection-path-calculator.h
=> FloorType::has_terrain_characteristics() を呼び出している関数を整形した その3

src/grid/feature-generator.cpp, src/melee/melee-spell-flags-checker.cpp, src/mspell/mspell-judgement.cpp, src/mspell/mspell-judgement.h, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-fetcher.cpp, src/spell-realm/spells-crusade.cpp, src/system/dungeon/dungeon-definition.cpp, src/system/dungeon/dungeon-definition.h, src/system/item-entity.cpp, src/system/item-entity.h
概ねy/x をPos2D へ差し替える作業です
ご確認下さい
=> FloorType::has_terrain_characteristics() を呼び出している関数を整形した その4

src/player/player-damage.cpp
Resolves https://github.com/hengband/hengband/issues/4813 .
=> English: skip article in tombstone explanation when hallucinating

src/monster-race/monster-race-hook.cpp, src/monster-race/monster-race-hook.h, src/monster/monster-util.cpp, src/system/monrace/monrace-definition.cpp, src/system/monrace/monrace-definition.h
filter\_monrace\_hook2() が大分スッキリしました
この次はこれをFloorType へ繰り込んでいく予定です
ご確認下さい
=> モンスター生成フィルタ用のグローバル関数解体 その2

src/monster-race/monster-race-hook.cpp, src/monster-race/monster-race-hook.h, src/monster/monster-util.cpp, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/system/monrace/monrace-definition.cpp, src/system/monrace/monrace-definition.h
恐らく一番バグりそうなネプト竜 (荒野の深い水にしか出現しない)が問題なかったので他も大丈夫と思われます
ご確認下さい
=> filter_monrace_hook2() を解体した

src/object-use/throw-execution.cpp, src/room/rooms-maze-vault.cpp, src/room/rooms-vault.cpp, src/room/treasure-deployment.cpp, src/room/treasure-deployment.h, src/util/point-2d.h
これにて完了です
今回の範囲でリファクタリングしなかった箇所は別PR群で順次やっていこうと思います
ざっくりですがDevelopとフロア生成結果は一致していました
ご確認下さい
=> FloorType::has_terrain_characteristics() を呼び出している関数を整形した その5

src/monster-race/monster-race-hook.cpp, src/monster-race/monster-race-hook.h, src/monster/monster-util.cpp, src/system/monrace/monrace-definition.cpp, src/system/monrace/monrace-definition.h
=> モンスター生成フィルタ用のグローバル関数解体 その4

src/floor/object-allocator.cpp, src/floor/wild.cpp, src/grid/door.cpp, src/grid/feature.cpp, src/grid/feature.h, src/info-reader/feature-info-tokens-table.cpp, src/info-reader/feature-reader.cpp, src/room/rooms-vault.cpp, src/system/enums/terrain/terrain-tag.h, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h
has\_closed\_door\_at() と同じ流れでset\_terrain\_id() にも\_at を付けました
ご確認下さい
=> 地形IDを動的に引く仕組みの構築 その9

src/autopick/autopick-destroyer.cpp, src/autopick/autopick-entry.cpp, src/autopick/autopick-matcher.cpp, src/cmd-item/cmd-eat.cpp, src/monster-race/monster-race-hook.cpp, src/monster-race/monster-race-hook.h, src/monster/monster-util.cpp, src/object-hook/hook-expendable.cpp, src/system/item-entity.cpp, src/system/monrace/monrace-definition.cpp, src/system/monrace/monrace-definition.h
PlayerType::lev が中途半端に引数として残っていますが、後でもっと上流から流し込むように変えようと思います
ご確認下さい
(もっと言えばPlayerLevel のようなクラスに変えてしまいたい……が今ではない)
=> モンスター生成フィルタ用のグローバル関数解体 その6

src/target/target-preparation.cpp, src/target/target-preparation.h, src/target/target-setter.cpp
Resolves #4850
関連して ts_type をクラス化したいところですが、ひとまずこのPRでは target_set_prepare() のシグネチャ変更とそれに伴う部分の変更のみ。
=> [Refactor] target_set_prepare()のシグネチャ変更

src/target/target-setter.cpp
=> [Refactor] ty_type を TargetSetter クラスにする

src/effect/effect-monster-psi.cpp, src/effect/effect-processor.cpp, src/floor/floor-leaver.cpp, src/floor/floor-util.cpp, src/floor/line-of-sight.cpp, src/floor/line-of-sight.h, src/melee/melee-spell-flags-checker.cpp, src/monster-floor/monster-sweep-grid.cpp, src/monster-floor/quantum-effect.cpp, src/mspell/mspell-checker.cpp, src/mspell/mspell-judgement.cpp, src/mspell/mspell-lite.cpp, src/player/player-view.cpp, src/spell-kind/spells-teleport.cpp, src/spell/range-calc.cpp, src/spell/range-calc.h, src/spell/spells-summon.cpp, src/target/target-setter.cpp
los()のシグネチャを座標をバラバラに渡す形からPos2D型で渡すように変更し、それに伴い呼び出し箇所を修正する。
Resolves #4864
=> [Refactor] los()のシグネチャを変更

src/effect/effect-processor.cpp, src/mspell/mspell-judgement.cpp, src/spell/range-calc.cpp, src/spell/range-calc.h
=> project()内での軌道保持方法のリファクタリング

src/autopick/autopick-editor-command.cpp, src/autopick/autopick-finder.cpp, src/core/asking-player.cpp, src/util/string-processor.cpp, src/util/string-processor.h
https://github.com/hengband/hengband/pull/4831#issuecomment-2605526211 で言及した怪しい挙動の修正ついでに軽くリファクタリング。
=> [Refactor/Fix] 文字入力処理

src/effect/effect-feature.cpp, src/grid/door.cpp, src/grid/feature.cpp, src/grid/feature.h, src/info-reader/feature-reader.cpp, src/room/door-definition.cpp, src/room/door-definition.h, src/room/room-generator.cpp, src/room/rooms-normal.cpp, src/system/grid-type-definition.cpp
鉄獄とガラスの城で動作チェックしてみましたが特に問題なさそうです
ご確認下さい
=> Doors クラスを作ってシングルトン化した

src/effect/effect-processor.cpp, src/spell/range-calc.cpp, src/spell/range-calc.h
dist_to_line()のシグネチャをPos2D型で書き替える。
Resolves #4882
=> [Refactor] dist_to_line()のシグネチャ

src/action/run-execution.cpp, src/spell-kind/spells-floor.cpp, src/system/floor/floor-info.cpp, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h, src/target/target-describer.cpp
他との兼ね合いで残っていた掲題のメソッドを統一しました
これで地形IDのgetter/setter は見通しよく統一できたかと思います
ご確認下さい
=> Grid::get_feat_mimic() をget_terrain_id() に吸収合併した

src/core/player-processor.cpp, src/floor/floor-leaver.cpp, src/floor/floor-object.cpp, src/floor/floor-object.h, src/floor/floor-streams.cpp, src/floor/floor-util.cpp, src/floor/floor-util.h, src/mind/mind-elementalist.cpp, src/spell-kind/earthquake.cpp, src/spell-kind/spells-floor.cpp, src/spell-kind/spells-grid.cpp, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h, src/target/grid-selector.cpp
約60箇所から呼ばれているので周辺コードの整備だけで何個かPRを投げる予定です
まずは1つご確認下さい
=> in_bounds() の周辺コードを整備した その1

src/main-win.cpp, src/main-win/graphics-win.cpp, src/main-win/graphics-win.h, src/main-win/main-win-bg.cpp, src/main-win/main-win-exception.cpp, src/main-win/main-win-music.cpp, src/main-win/main-win-utils.h, src/util/angband-files.cpp
CPU判定周りでついでに実施していた作業を独立させました
ご確認下さい
=> マルチバイト文字の入出力をchar\* からstring_view に変えた

src/room/rooms-vault.cpp
=> [Fix] build_bubble_value() でクラッシュ

src/main-win.cpp
=> 表示が崩れる不具合の修正

src/effect/effect-feature.cpp, src/floor/cave-generator.cpp, src/floor/floor-changer.cpp, src/grid/grid.cpp, src/grid/grid.h, src/mind/mind-elementalist.cpp, src/mind/mind-ninja.cpp, src/monster/monster-list.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-lite.cpp, src/system/player-type-definition.cpp, src/system/player-type-definition.h
ほぼ整形コミットですが、PlayerType::set\_position() を定義してプレイヤー座標を扱いやすくしました
ご確認下さい
=> in_bounds() の周辺コードを整備した その2

src/target/target-setter.cpp
d77e13ab でのエンバグ。
上記のコミットでターゲットまでの距離の計算を Grid::calc_distance に置き換えたが、隣接マスは上下左右も斜めも同じ距離1と判定してしまうためカーソルの動く方向が不自然になってしまっていた。
元の距離計算を復活させて正しい挙動になるよう修正する。
上記コミットからリリース前の修正となるので単体Issueはなし。
=> [Fix] ターゲット選択時の挙動がおかしい

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/floor/wild.cpp, src/floor/wild.h, src/monster/monster-util.cpp, src/system/enums/terrain/wilderness-terrain.h
掲題の作業に伴って、生配列をmap に変えた箇所があります
併せてご確認下さい
=> wt_type をenum class に変えた

src/floor/fixed-map-generator.cpp, src/floor/floor-streams.cpp, src/floor/object-scanner.cpp, src/floor/object-scanner.h, src/grid/door.cpp, src/grid/grid.h, src/monster-floor/monster-remover.cpp, src/monster-floor/monster-remover.h, src/spell-kind/earthquake.cpp, src/spell-kind/spells-fetcher.cpp, src/spell-kind/spells-floor.cpp, src/spell-kind/spells-lite.cpp, src/spell-kind/spells-teleport.cpp
あちこち弄っていますが今回は関数単位なので1コミット当たりの差分はあまり多くないです
ご確認下さい
=> in_bounds() の周辺コードを整備した その3

src/birth/game-play-initializer.cpp, src/cmd-action/cmd-move.cpp, src/core/game-closer.cpp, src/core/game-play.cpp, src/dungeon/dungeon-processor.cpp, src/floor/cave-generator.cpp, src/floor/floor-generator.cpp, src/floor/floor-leaver.cpp, src/floor/wild.cpp, src/io/exit-panic.cpp, src/io/signal-handlers.cpp, src/load/load.cpp, src/load/world-loader.cpp, src/main-win.cpp, src/save/player-writer.cpp, src/save/save.cpp, src/system/angband-system.cpp, src/system/angband-system.h, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/system/player-type-definition.h, src/world/world-movement-processor.cpp
例によって「プレイヤーが管理すべきでないフラグ」のいくつかを移設しました
ご確認下さい
=> AngbandSystem/FloorType へPlayerType に属していたフィールド変数を移した

src/floor/fixed-map-generator.cpp, src/floor/wild.cpp, src/floor/wild.h, src/main/info-initializer.cpp
developと同じ地上マップが生成されたのをチェック済です
この後vector のwilderness をシングルトン化していきます
ご確認下さい
=> wild.cpp/h の構造体と関数の整理

.github/workflows/build-with-autotools.yml, .github/workflows/create-cache-for-ccache.yml, .github/workflows/pull-request-status-check.yml, src/info-reader/dungeon-reader.cpp, src/mind/mind-chaos-warrior.cpp, src/monster-floor/monster-safety-hiding.cpp, src/monster-floor/monster-sweep-grid.cpp, src/player-base/player-class.cpp, src/system/baseitem/baseitem-list.cpp, src/system/baseitem/baseitem-list.h, src/term/gameterm.cpp, src/term/z-form.cpp, src/util/abstract-map-wrapper.h, src/util/abstract-vector-wrapper.h, src/util/sha256.cpp, src/view/display-map.cpp
=> std::span のコンストラクタ呼び出しに関する調整

src/floor/tunnel-generator.cpp, src/floor/tunnel-generator.h, src/grid/trap.cpp, src/room/vault-builder.cpp
これで完了です、次のPRでごそっとin\_bounds() をFloorType のメソッドへ繰り込みます
なお、座標かベクタか1箇所型がおかしい気もしますが、動作自体は問題なさそうです (developと同じトンネルやトラップが生成されている)
ご確認下さい
```cpp
pos_tmp.y = std::abs(pos_start.y - pos_start_initial.y);
pos_tmp.x = std::abs(pos_start.x - pos_start_initial.x);
```
=> in_bounds() が呼ばれている箇所の周辺コードを整備した その4

src/action/movement-execution.cpp, src/action/run-execution.cpp, src/cmd-action/cmd-travel.cpp, src/cmd-io/cmd-floor.cpp, src/cmd-io/cmd-gameoption.cpp, src/combat/shoot.cpp, src/floor/floor-streams.cpp, src/floor/geometry.h, src/grid/grid.cpp, src/io-dump/dump-util.cpp, src/mind/mind-berserker.cpp, src/mind/mind-force-trainer.cpp, src/mind/mind-ninja.cpp, src/monster-floor/monster-move.cpp, src/object-use/throw-execution.cpp, src/realm/realm-hissatsu.cpp, src/specific-object/death-crimson.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-fetcher.cpp, src/spell-kind/spells-launcher.cpp, src/spell-kind/spells-lite.cpp, src/spell-realm/spells-crusade.cpp, src/system/player-type-definition.cpp, src/target/grid-selector.cpp, src/target/target-getter.cpp, src/target/target-setter.cpp, src/view/display-map.cpp, src/window/main-window-util.cpp
=> [Refactor] ddx / ddy / CCW_DD を廃止し、Directionクラスで置き換える

src/monster-floor/monster-safety-hiding.cpp, src/monster-floor/monster-safety-hiding.h, src/monster-floor/monster-sweep-grid.cpp, src/monster-floor/monster-sweep-grid.h
Resolves #4901 
#4904 に続く作業。これで一旦モンスター移動処理のリファクタリングは完了。
=> [Refactor] モンスターの逃亡処理

src/room/rooms-city.cpp, src/room/rooms-nest.cpp, src/room/rooms-normal.cpp, src/room/rooms-vault.cpp, src/room/treasure-deployment.cpp, src/util/point-2d.h
#4024 に機能を追加。
each_area() メソッドによる処理より自然な感じで使える。rangesライブラリの range adaptor にも対応可能となる。
Wildernessクラスでも使えるはず。
=> [Feature] Rectangle2Dにイテレータを実装 

src/core/game-play.cpp, src/external-lib/include/fmt/format.h, src/floor/wild.cpp, src/knowledge/knowledge-self.cpp, src/load/world-loader.cpp, src/save/save.cpp, src/spell-kind/spells-world.cpp, src/system/floor/wilderness-grid.cpp, src/system/floor/wilderness-grid.h
=> WildernessGrids::bottom_right/positions を廃止してRect2D に差し替えた

src/action/run-execution.cpp, src/action/run-execution.h, src/cmd-action/cmd-move.cpp, src/core/player-processor.cpp, src/floor/floor-streams.cpp, src/floor/geometry.h, src/realm/realm-hissatsu.cpp, src/target/target-getter.cpp, src/target/target-getter.h
#4962 関連。
- Direction::cdir()
- Direction::id_diagonal()
- Direction::has_direction()
- Direction::rotated_45degree()
- 等値比較
- run_step()とそれに付随する処理
- 五月雨斬りの方向処理
- build_streamer()の方向処理
=> Directionクラスの機能追加とリファクタリング

src/action/movement-execution.cpp, src/action/movement-execution.h, src/action/mutation-execution.cpp, src/cmd-action/cmd-pet.cpp, src/mind/mind-berserker.cpp, src/mind/mind-warrior.cpp, src/mutation/mutation-techniques.cpp, src/racial/racial-vampire.cpp, src/realm/realm-hissatsu.cpp, src/specific-object/monster-ball.cpp, src/spell-kind/spells-launcher.cpp, src/spell-kind/spells-launcher.h, src/spell-kind/spells-specific-bolt.cpp, src/spell-kind/spells-specific-bolt.h, src/spell/spells-status.cpp, src/target/target-getter.cpp, src/target/target-getter.h
=> [Refactor] get_direction()の戻り値をDirectionにする

src/action/movement-execution.cpp, src/action/movement-execution.h, src/action/open-close-execution.cpp, src/action/open-close-execution.h, src/action/run-execution.cpp, src/action/travel-execution.cpp, src/cmd-action/cmd-move.cpp, src/cmd-action/cmd-open-close.cpp, src/cmd-action/cmd-others.cpp, src/cmd-action/cmd-tunnel.cpp, src/mind/mind-archer.cpp, src/mind/monk-attack.cpp, src/realm/realm-hissatsu.cpp, src/target/target-getter.cpp, src/target/target-getter.h
#4962 の続き。
get_rep_dir() での方向取得を int 型の出力引数で得る形からDirection型の戻り値で得る形に変更します。
=> [Refactor] get_rep_dir() のシグネチャ変更

src/cmd-building/cmd-building.cpp, src/market/building-recharger.cpp, src/market/building-util.cpp, src/market/building-util.h, src/mind/mind-info.cpp, src/monster-attack/monster-eating.cpp, src/player/process-death.cpp, src/store/purchase-order.cpp, src/store/sell-order.cpp, src/view/display-scores.cpp, src/view/display-store.cpp, src/view/display-store.h
=> フォーマット指定子がlong になっている箇所をintまたはfmt::format() に差し替えた その2

src/window/main-window-left-frame.cpp, src/wizard/monster-info-spoiler.cpp
その2の続きですが変更範囲は直交しているどちらが先でもOKです
ご確認下さい
=> フォーマット指定子がlong になっている箇所をintまたはfmt::format() に差し替えた その3

src/cmd-action/cmd-move.cpp, src/core/player-processor.cpp, src/floor/floor-leaver.cpp, src/floor/wild.cpp, src/info-reader/dungeon-reader.cpp, src/load/world-loader.cpp, src/monster/monster-list.cpp, src/save/save.cpp, src/spell-kind/spells-world.cpp, src/system/dungeon/dungeon-definition.cpp, src/system/dungeon/dungeon-definition.h, src/system/floor/floor-info.cpp, src/system/floor/wilderness-grid.cpp, src/system/floor/wilderness-grid.h
この次でwilderness\_grids を廃止してラップアップします
develop と同じ地上マップが生成されました
ご確認下さい
=> WildernessGrid をカプセル化した

src/floor/wild.cpp, src/system/floor/wilderness-grid.cpp, src/system/floor/wilderness-grid.h
グローバル変数の繰り込みや最終調整を行いました
これにて地上マップ周りのリファクタリングは完了です
ご確認下さい
(まだwild.cpp/h にborderなど残っていますがこれは別件で対応します)
=> WildernessGrid クラスのラップアップ

src/monster-floor/monster-direction.cpp, src/monster-floor/monster-direction.h, src/monster-floor/monster-move.cpp, src/monster-floor/monster-move.h, src/monster-floor/monster-sweep-grid.cpp, src/monster-floor/monster-sweep-grid.h, src/monster/monster-processor-util.cpp, src/monster/monster-processor-util.h, src/monster/monster-processor.cpp
#4962 の関連作業。
DIRECTION(int)型の配列で保持しているモンスターの移動方向の候補の型をDirection型の配列にする。
=> [Refactor] モンスターの移動方向の候補をDirection型にする

src/cmd-io/cmd-floor.cpp, src/cmd-io/cmd-gameoption.cpp, src/game-option/keymap-directory-getter.cpp, src/game-option/keymap-directory-getter.h, src/io-dump/dump-util.cpp, src/mind/mind-force-trainer.cpp, src/mind/mind-ninja.cpp, src/target/grid-selector.cpp, src/target/target-getter.cpp, src/target/target-setter.cpp
=> [Refactor] get_keymap_dir()の戻り値をDirectionにする

src/action/travel-execution.cpp, src/action/travel-execution.h, src/cmd-action/cmd-travel.cpp, src/core/disturbance.cpp, src/core/player-processor.cpp, src/floor/floor-changer.cpp, src/spell-kind/spells-floor.cpp, src/target/target-describer.cpp
#4986 の作業。
実際の作業はもっと進んでいますが、一気に全部出すとレビューの負担が大きくなるのでとりあえず切りのよいコミットまでを提出します。
=> travel_typeをTravelクラスにする その1

src/action/travel-execution.cpp, src/action/travel-execution.h, src/cmd-action/cmd-travel.cpp, src/player/player-move.cpp, src/player/player-move.h
#4986 の作業続き。
いくつかの地形で確認した限りでは、修正前後で `Travel::costs` の内容は等しくなっているようです。
=> travel_flow() をstd::priority_queueを用いたダイクストラ法で書き直し、Travel::update_flow()へ移設

src/effect/effect-feature.cpp, src/floor/cave-generator.cpp, src/floor/fixed-map-generator.cpp, src/floor/floor-streams.cpp, src/floor/object-allocator.cpp, src/grid/feature-generator.cpp, src/grid/feature-generator.h, src/grid/grid.cpp, src/grid/object-placer.cpp, src/grid/object-placer.h, src/grid/trap.cpp, src/grid/trap.h, src/io-dump/character-dump.cpp, src/player/player-move.cpp, src/room/rooms-normal.cpp, src/room/rooms-special.cpp, src/room/rooms-vault.cpp, src/room/treasure-deployment.cpp, src/room/vault-builder.cpp, src/room/vault-builder.h, src/spell-kind/spells-detection.cpp
=> in_bounds() の周辺コードを整備した その5

src/action/run-execution.cpp, src/action/run-execution.h, src/action/travel-execution.cpp, src/action/travel-execution.h, src/cmd-action/cmd-travel.cpp, src/core/disturbance.cpp, src/core/player-processor.cpp, src/floor/floor-changer.cpp, src/spell-kind/spells-floor.cpp, src/target/target-describer.cpp
=> Travelクラスのメンバのさらなる隠蔽とシングルトン化

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/blue-magic/blue-magic-caster.cpp, src/cmd-action/cmd-mane.cpp, src/cmd-action/cmd-pet.cpp, src/cmd-io/cmd-floor.cpp, src/mind/mind-force-trainer.cpp, src/object-activation/activation-others.cpp, src/realm/realm-trump.cpp, src/spell-kind/spells-fetcher.cpp, src/spell-kind/spells-world.cpp, src/target/target-setter.cpp, src/target/target-setter.h, src/target/target.cpp, src/target/target.h
=> Targetクラスを実装し、グローバル変数 target_who/target_row/target_col を廃止して代わりにTargetクラスを使用する その1

src/io/interpret-pref-file.cpp, src/util/string-processor.cpp, src/util/string-processor.h
定義そのものはまだ手を付けていません
マクロコマンドをざっくり調べましたがひとまず動作しているようです
また、string-processor にいるのは違和感があるので後ほど他のクラスへ分離させます
ご確認下さい
=> マクロ定義周りのconcptr をstring に置き換えた

src/spell-kind/earthquake.cpp
earthquake()関数が300行を超えており見通しが悪いのでまとまった処理ごとに関数化する。
Resolves #5019
=> [Refactor] earthquake()

src/knowledge/knowledge-monsters.cpp, src/target/target-describer.cpp
=> 友好的/ペット の表記が、表示されていて欲しい場合と欲しくない場合で逆転していた不具合を修正した

src/action/run-execution.cpp, src/combat/shoot.cpp, src/effect/effect-feature.cpp, src/floor/cave.cpp, src/floor/cave.h, src/floor/floor-events.cpp, src/floor/floor-streams.cpp, src/grid/grid.cpp, src/monster-floor/monster-move.cpp, src/monster-floor/monster-sweep-grid.cpp, src/monster/monster-processor.cpp, src/spell-kind/earthquake.cpp, src/spell-kind/spells-floor.cpp, src/spell-kind/spells-lite.cpp, src/spell/range-calc.cpp, src/window/display-sub-windows.cpp
過去にcontainsを実装した時のenumに差し替えました
ご確認下さい
=> in_bounds2() をFloorType::contains() に置き換えた

src/combat/shoot.cpp, src/effect/effect-monster.cpp, src/melee/melee-postprocess.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-force-trainer.cpp, src/monster-floor/monster-generator.cpp, src/realm/realm-hex.cpp, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/system/monster-entity.cpp, src/system/monster-entity.h
先にメソッドだけ作成しました
以前Discord で相談しましたが、プレイヤーの座標が引数に入っているので、これはメソッドの外で判定しようと思います
ご確認下さい
```cpp
floor.is_empty_at(p_pos, p_pos); // これは呼び出し方としてあまり良くなさそう
```
=> is_cave_empty_bold() をFloorTypeに繰り込む準備

src/cmd-action/cmd-travel.cpp, src/mind/mind-elementalist.cpp, src/realm/realm-hex.cpp, src/realm/realm-hissatsu.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-teleport.cpp, src/spell-kind/spells-teleport.h, src/target/grid-selector.cpp, src/target/grid-selector.h, src/wizard/wizard-special-process.cpp, src/wizard/wizard-spells.cpp
関数名も省略しすぎだったので分かりやすくしました
ご確認下さい
=> tgt_pt() のシグネチャ改善

src/combat/shoot.cpp, src/floor/cave.cpp, src/floor/cave.h, src/floor/floor-leaver.cpp, src/mind/mind-elementalist.cpp, src/mind/mind-force-trainer.cpp, src/mind/mind-ninja.cpp, src/monster-floor/monster-generator.cpp, src/mspell/mspell-checker.cpp, src/mspell/specified-summon.cpp, src/realm/realm-hex.cpp, src/realm/realm-hissatsu.cpp, src/specific-object/chest.cpp, src/spell-kind/earthquake.cpp, src/spell-kind/spells-fetcher.cpp, src/wizard/wizard-spells.cpp
一部変数名も調整しました
コンパイルは通りましたがif文の逆転を重点的にご確認下さい
=> is_cave_empty_bold() をFloorType のオブジェクトメソッドへ繰り込んだ

src/target/grid-selector.cpp
Resolves #5040
トラベルコマンドで '+' を押すと、施設の一覧を表示し、選択した施設の入口にカーソルを移動する機能を追加する。
使用例：
https://github.com/user-attachments/assets/622d766b-6f39-470a-89fe-08d4c7db3f93
=> [Feature] トラベルコマンドで施設を一覧から選択する機能

.github/workflows/create-cache-for-ccache.yml, .github/workflows/pull-request-status-check.yml
=> [Chore] ビルドテストのGCCのバージョンを14にする

src/effect/effect-processor.cpp, src/floor/cave.cpp, src/floor/cave.h, src/mspell/mspell-judgement.cpp, src/spell-realm/spells-crusade.cpp, src/spell/range-calc.cpp, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/target/projection-path-calculator.cpp
range-calc.cpp をPos2D に差し替えるのは別途実施しようと思います
ご確認下さい
=> cave_stop_disintegration() をFloorType::can_block_disintegration_at() に差し替えた

src/core/object-compressor.cpp
#5046 の作業中気になったので可読性を上げるリファクタリングをしました。
単体Issueはなし。
=> [Refactor] compact_objects()

VisualStudio/Hengband/Hengband.vcxproj, VisualStudio/Hengband/Hengband.vcxproj.filters, src/Makefile.am, src/effect/effect-processor.cpp, src/floor/floor-leaver.cpp, src/melee/melee-spell-util.cpp, src/mind/mind-mirror-master.cpp, src/monster-floor/monster-move.cpp, src/monster-floor/monster-object.cpp, src/monster-floor/monster-runaway.cpp, src/monster/monster-processor.cpp, src/monster/monster-status-setter.cpp, src/monster/monster-status.cpp, src/monster/monster-update.cpp, src/mspell/mspell-attack.cpp, src/mspell/mspell-learn-checker.cpp, src/mspell/mspell-lite.cpp, src/mspell/mspell-lite.h, src/object-activation/activation-others.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-fetcher.cpp, src/spell-kind/spells-lite.cpp, src/spell-kind/spells-sight.cpp, src/system/enums/terrain/path-checker.h, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h
実際の繰り込み作業が意外と膨れ上がったので準備部分だけでPRを出します
ご確認下さい
=> cave_los_bold() をFloorType のメソッドへ繰り込む準備

src/effect/effect-processor.cpp, src/floor/cave.cpp, src/floor/cave.h, src/floor/line-of-sight.cpp, src/monster-floor/monster-lite.cpp, src/mspell/mspell-attack-util.cpp, src/mspell/mspell-attack-util.h, src/mspell/mspell-judgement.cpp, src/mspell/mspell-lite.cpp, src/mspell/mspell-lite.h, src/specific-object/torch.cpp, src/spell-kind/spells-lite.cpp, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/target/projection-path-calculator.cpp
=> cave_los_bold() をFloorType::has_los_terrrain_at() に繰り込んだ

src/combat/shoot.cpp, src/effect/effect-processor.cpp, src/io/cursor.cpp, src/melee/melee-spell-flags-checker.cpp, src/mind/mind-ninja.cpp, src/mspell/mspell-checker.cpp, src/mspell/mspell-judgement.cpp, src/mspell/mspell-judgement.h, src/mspell/mspell-lite.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-fetcher.cpp, src/target/projection-path-calculator.cpp, src/target/projection-path-calculator.h
そろそろPlayerPosition クラスを作りたくなってきましたが別途検討します
ご確認下さい
=> ProjectionPath のコンストラクタとget_project_point() の引数からPlayerType を除去した

src/spell-kind/earthquake.cpp
過去のリファクタリングでnullptr が混じり込んでしまったようです
ご確認下さい
=> 地震で埋まるとクラッシュする不具合を解消した

src/autopick/autopick-describer.cpp, src/effect/effect-feature.cpp, src/external-lib/include/fmt/base.h, src/external-lib/include/fmt/format.h, src/external-lib/include/range/v3/utility/optional.hpp, src/monster-floor/monster-death.cpp, src/spell-class/spells-mirror-master.cpp, src/spell-kind/spells-grid.cpp, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/system/grid-type-definition.cpp, src/system/grid-type-definition.h, src/target/projection-path-calculator.cpp, src/util/angband-files.cpp
コードを眺めていて見つけたものをいくつか調整しました
ご確認下さい
=> Beta27に向けたその他のリファクタリング

src/inventory/floor-item-getter.cpp, src/inventory/item-getter.cpp, src/inventory/item-selection-util.cpp, src/inventory/item-selection-util.h
choose_object() の引数を辿った果ての関数がぐちゃぐちゃだったので先に整理しました
ご確認下さい
=> fis_type とitem_selection をクラス化した

src/inventory/player-inventory.cpp
=> player-inventory.cpp のリファクタリング その2

src/inventory/player-inventory.cpp
=> player-inventory.cpp のリファクタリング その2 

src/room/vault-builder.cpp
Resolves https://github.com/hengband/hengband/issues/4922
=> Honor limit on number of monsters to add in vault_monsters()

src/core/player-processor.cpp, src/effect/effect-monster.cpp, src/monster/monster-flag-types.h, src/monster/monster-processor.cpp, src/monster/monster-util.cpp, src/monster/monster-util.h
Resolves https://github.com/hengband/hengband/issues/3598 .
=> For a projection, do not affect monsters summoed during the projection

src/store/rumor.cpp, src/util/string-processor.cpp, src/util/string-processor.h
display_rumor()をVisitorパターンによってリファクタリングする。
やや大きめのリファクタリングで gemini-code-assist がどのように見るかのテストを兼ねる。
=> [Refactor] display_rumor()

Makefile.am, lib/edit/Makefile.am
Resolves https://github.com/hengband/hengband/issues/5138 .
=> Include MonsterMessages files in the archive generated by "make dist"

Makefile.am
Resolves https://github.com/issues/created?issue=hengband%7Chengband%7C4109 .
=> Include libcurl's files in archives generated by 'make dist'

src/monster/monster-describer.cpp
=> [Fix] カメレオンの王が化けているユニークモンスターの名称表記

src/floor/floor-object.cpp
アイテム消失処理を handle_item_disappearance() 関数に共通化する。
アーティファクトの場合の生成フラグに関する処理は共通化前でまちまちであるが、この際「保存モード有効」かつ「未知」の場合にのみ未生成状態へ戻す仕様に統一する。
Write all summary comments in Japanese.
Write all review comments in Japanese.
=> [Refactor] アイテム消失処理の共通化

lib/edit/MonraceDefinitions.jsonc, lib/edit/MonsterMessages.jsonc, src/monster-attack/monster-attack-describer.cpp, src/mspell/mspell-summon.cpp, src/mspell/specified-summon.cpp, src/mspell/specified-summon.h, src/system/enums/monrace/monrace-id.h
https://github.com/hengband/hengband/issues/5179#issue-3199583434 より
亡霊『はらへりじじい』とまわるポリゴンを実装しました。
=> [Add] ユニーク・モンスター「はらへりじじい」とモンスター「まわるポリゴン」を追加

src/system/monrace/monrace-definition.cpp
Resolves https://github.com/hengband/hengband/issues/5202 .
=> English: do not make a unique's name plural in probing message

src/autopick/autopick-entry.cpp, src/floor/object-scanner.cpp, src/floor/object-scanner.h, src/inventory/floor-item-getter.cpp, src/inventory/inventory-util.cpp, src/inventory/inventory-util.h, src/inventory/item-selection-util.h, src/inventory/player-inventory.cpp, src/io/input-key-requester.cpp, src/target/grid-selector.cpp, src/target/target-describer.cpp, src/util/string-processor.cpp, src/util/string-processor.h
全てのパターンは網羅できていませんが、床置きアイテムへの繰り返しコマンドを中心に動作チェックOKでした
ご確認下さい
=> get_tag_floor() のサブルーチンをboolではなくoptional<short>を返すようにした

src/store/rumor.cpp
掲題の関数を共通化してキャストを簡略化しました
ご確認下さい
=> get_rumor_num() をテンプレート化した

src/combat/shoot.cpp, src/effect/effect-processor.cpp, src/floor/geometry.cpp, src/grid/grid.cpp, src/grid/grid.h, src/io/cursor.cpp, src/io/screen-util.cpp, src/io/screen-util.h, src/mind/mind-mirror-master.cpp, src/object-use/throw-execution.cpp, src/spell-class/spells-mirror-master.cpp, src/system/floor/floor-info.cpp, src/system/floor/floor-info.h, src/term/gameterm.cpp, src/term/gameterm.h, src/view/display-map.cpp
=> bolt_pict()の引数をPos2Dに変えた
