hengband/hengband

src/mind/mind-mage.cpp

1本だけのスタックしていないアイテムから魔力食いをして失敗してアイテムが破壊された時、
「○○が何本壊れた！」と実態に合っていないメッセージが表示される事がある。
「○○が壊れた！」と正しいメッセージに修正する。

[Fix] #2416 魔力食いを失敗した時のメッセージがおかしい

---

src/info-reader/race-reader.cpp
src/lore/monster-lore.cpp
src/monster-floor/monster-generator.cpp
src/system/monster-race-definition.h
src/view/display-lore.cpp

Resolves #1440 
指定護衛のデータを std::vector で持つようにし、1体につき6種までの制限を撤廃する。
ほとんどのモンスターは指定護衛を持たないので無駄なメモリ消費の削減にもなる。

[Fix] 指定護衛のデータ数の制限をなくす

---

src/effect/effect-player.cpp
src/io/write-diary.cpp
src/main/game-data-initializer.cpp
src/object-use/item-use-checker.cpp
src/room/rooms-pit-nest.cpp
src/status/bad-status-setter.cpp
src/view/display-messages.cpp
src/view/display-messages.h
src/wizard/wizard-game-modifier.cpp

Resolves #2417 
表題の通り、msg_print 等の引数を concptr から std::string_view に変更し、呼び出し側は concptr、std::string、std::string_view のどれでも渡せるようにしました。
また現状のコードで c_str() や data() などの呼び出しが不要になるものについて、メンバ関数の呼び出しを削除しました。
ついでに既存の msg_print がかなり見通しの悪いコードなので、多少読みやすくなるように改善しました。

[Refactor] メッセージ表示関連関数の引数の型を std::string_view にする 

---

lib/edit/r_info.txt
src/info-reader/race-reader.cpp
src/monster-floor/monster-death.cpp
src/system/monster-race-definition.h

特定アーティファクトドロップのデータを std::vector で持つようにし、1体につき4種まで
の制限をなくす。
ほとんどのモンスターは特定アーティファクトドロップを持たないので、無駄なメモリ消費の削
減にもなる。
また、r_info.txt 上の特定アーティファクトドロップの定義が
A:artifact_idx:rarity:chance
となっているが、rarity はゲーム内で使用されておらず、紛らわしいので削除する。

[Fix] 特定アーティファクトドロップのデータ数の制限をなくす

---

src/load/old/item-loader-savefile50.cpp
src/save/item-writer.cpp
src/system/object-type-definition.h

モンスターの攻撃により光源の残ターン数が一時的に負の値になる事があるが、変数が符号なし
のため負のオーバーフローを起こす。
符号付きに修正する。

[Fix] #2430 光源の残ターン数が負のオーバーフローを起こす

---

src/effect/effect-processor.cpp
src/grid/grid.cpp
src/grid/grid.h
src/mind/mind-mirror-master.cpp
src/spell-class/spells-mirror-master.cpp
src/term/gameterm.cpp
src/term/gameterm.h

bolt_pict() で色と文字を選んで print_rel() で描画するという一連の処理を
print_bolt_pict() 関数にまとめる。
bolt_pict() は色と文字を uint16_t で返してマクロで分解するのをやめ、
std::pair<TERM_COLOR, char> を返すようにする。
先程レビューしていて目についたので。ちょっとしたリファクタリングなので Issue は無しです。

[Refactor] ボルトの軌道の描画を関数化する

---

src/monster-floor/monster-object.cpp

Resolved #2440 
トロルの王で焼棄の剣を拾わず、魔法書などを拾うようになったことをこちらで確認いたしました

モンスターのアイテムを拾う挙動のバグを修正

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/object-enchant/apply-magic.cpp
src/object-enchant/weapon/abstract-weapon-enchanter.cpp
src/object-enchant/weapon/abstract-weapon-enchanter.h
src/object-enchant/weapon/apply-magic-hafted.cpp
src/object-enchant/weapon/apply-magic-hafted.h
src/object-enchant/weapon/apply-magic-polearm.cpp
src/object-enchant/weapon/apply-magic-polearm.h
src/object-enchant/weapon/apply-magic-sword.cpp
src/object-enchant/weapon/apply-magic-sword.h
src/object-enchant/weapon/melee-weapon-enchanter.cpp
src/object-enchant/weapon/melee-weapon-enchanter.h

SwordEnchanter は名ばかりで、実態は鈍器と戦斧への強化/弱化処理も含まれていました
これを各武器に分離しました
剣・鈍器・戦斧の全てで狙った種類のエゴが生成されることは確認済です
なお基底メソッドを呼んでいてちょっと設計が悪い部分もありますが、これは長期的な課題として後日対応するかもしれません
ご確認下さい

SwordEnchanter を分離してPolearmEnchanter とHaftedEnchanter を定義した

---

src/flavor/object-flavor.cpp
src/market/poker.cpp
src/term/z-rand.h

Resolves #2439
詳細はコミットログをご参照ください。

イテレータ範囲の要素をシャッフルする関数 rand_shuffle を実装

---

src/main-x11.cpp

Resolves #2435 
X11版は入力したキーが Modifier キーで修飾されている場合は自動的にその組み合わせを
マクロに登録するという処理がなされている（そのような実装になっている詳細な理由は不明）。
Modifier キーとは Mod1 が Altキー、 Mod2 が NumLock キーにあたる。
したがって、NumLockがオンの状態では普通にキーを押しただけでマクロが自動的に登録される。
一方、起動直後はまだマクロ情報の配列変数(std::vector)の領域確保が完了しておらず、
マクロを登録しようとすると配列外アクセスを起こす。
結果として、起動直後の初期化中に NumLock がオンになった状態でなんらかのキーを入力する
とクラッシュを引き起こす。
該当のマクロ登録部でマクロの配列の領域が確保済みかどうかをチェックし、確保されていない
場合はマクロの登録をスキップするようにする。

[Fix] X11版で起動直後の初期化中にキーを押すとクラッシュする

---

src/monster-attack/monster-eating.cpp

Issue #2454の原因。has_magic_mastery()がtrueのケースで吸収量が対象魔法道具の現在値を越えることがある。
現在値を越えないように修正。
ついでに魔法道具を空にされたとき「あなたの魔法を操る力がその一部を取り返した」メッセージが出るのは不自然なので修正。

[Fix] 充填魔力吸収打撃でpvalが負値になる

---

src/spell-class/spells-mirror-master.cpp
src/target/projection-path-calculator.h

- 8方向同時にビームの描画を行う
- ビームの効果の発動は描画完了後にまとめて行う
- 中央から外に向かって8方向同時に順番に効果を及ぼすようにする
- 中央の同距離からのマスに効果を及ぼす順序はランダムにする
- 同マスで効果を及ぼす順序は、地形→床上アイテム→モンスターの順序にする
詳細：Issue #2452

fix: スーパーレイの不自然な挙動を自然な感じにする

---

src/birth/history.cpp
src/cmd-action/cmd-racial.cpp
src/mind/mind-elementalist.cpp

- Align labels to the columns in the racial and elementalist power menus.
- Reword some entries for a merfolk's background - avoids a subject-verb disagreement.
- Change failure message when invoking an elementalist's power.
- Use "power" rather than "magic" in the elementalist's power menu.

English:  change some messages, mostly related to the elementalists

---

src/load/old/item-loader-savefile50.cpp

Resolves #2468 
#2431 で負のオーバーフローにより残りターン数が異常になった光源をセーブファイルからロ
ードした時に強制的に残りターン数0にするようにしたが、ObjectType::is_fuel() のみを
見ているため油つぼも対象になっており、油つぼの補給ターン数も0になってしまっている。
ObjectType::is_fuel() に加えて ItemKindType::LITE であるかどうかもチェックする
ようにする。

[Fix] 油つぼからランタンの燃料補給ができなくなる

---

src/object-enchant/weapon/abstract-weapon-enchanter.cpp
src/object-enchant/weapon/abstract-weapon-enchanter.h
src/object-enchant/weapon/apply-magic-arrow.cpp
src/object-enchant/weapon/apply-magic-bow.cpp
src/object-enchant/weapon/apply-magic-digging.cpp
src/object-enchant/weapon/apply-magic-hafted.cpp
src/object-enchant/weapon/apply-magic-hafted.h
src/object-enchant/weapon/apply-magic-polearm.cpp
src/object-enchant/weapon/apply-magic-polearm.h
src/object-enchant/weapon/apply-magic-sword.cpp
src/object-enchant/weapon/apply-magic-sword.h
src/object-enchant/weapon/melee-weapon-enchanter.cpp
src/object-enchant/weapon/melee-weapon-enchanter.h

掲題の通りです
詳細は以下の通りです
ご確認下さい
* C++では派生クラスのコンストラクタで初期化する最中に基底クラスのメソッドを呼ばれた場合、基底クラスのメソッドが呼ばれるが、派生クラスのオーバーライドメソッドが呼ばれると勘違いしていた
* 上記を解消するため、以下の対策を行った
* AbstractWeaponEnchanterのコンストラクタではフィールド変数への代入以外は何もしないようにした
* AbstractWeaponEnchanter::apply\_magic() を新たに定義し、必ずdecide\_skip() より後に呼ぶことにした
* decide\_skip() を基底クラス、派生クラス双方で正しく協調動作するように設計を見直した

強化も弱化もしない装備品 (毒針・ダイヤモンドエッジ・死の大鎌)が判定をすり抜けて強化/弱化する不具合を解消した

---

src/effect/effect-processor.cpp

Fix #2491 
path_g のリファクタリング時に参照をミスったことで挙動が変わってしまっていた模様

ブレスの壁貫通バグを修正した

---

src/wizard/wizard-game-modifier.cpp

[Fix] モンスターの復元数変数が初期化されていなかった不具合を修正。

---

.github/workflows/build-with-autotools.yml

libcurl4のインストールに失敗し、GitHub Actionsが正常に動作しない事象を修正した

---

src/object-enchant/weapon/apply-magic-hafted.cpp
src/object-enchant/weapon/apply-magic-polearm.cpp

掲題の通りです
過去に議論があった通り、暫定でgive\_killing\_bonus() を長柄/斧と鈍器の強化/弱化処理に追加しました
手元の環境では問題なく殺戮修正が付いているように見えます
ご確認下さい
注意：最終的には設計の見直しが必要
#2490 を参照のこと

#2497 長柄/斧と鈍器に殺戮修正が付与されない事象を暫定的に修正した

---

src/wizard/wizard-item-modifier.cpp

タイトル通り行が狂っているだけなので、すぐ修正つきました。確認お願いします。

[Fix] デバッグモードoコマンドの表示が崩れていたので行指定変数を正しく修正。

---

lib/edit/t0000002.txt

[Fix] クエスト、モンサルヴァト城への侵攻にて町への帰還後の位置が永久岩の壁になっていたので修正。

---

src/player/player-status-flags.cpp

これで、他に不具合がないかチェックする必要はあると思うが基本大丈夫だとは思う。少なくともデバッグで、これの修正後、暗黒の100万ダメージを＠さんに与えても0であることは確認した。

[Fix]暗黒耐性判定フラグに暗黒免疫の論理和を付加し、暗闇の巻物で吸血鬼が盲目になるエンバグを修正。

---

src/action/open-util.cpp
src/player/player-move.cpp

Resolves #2538 
箱にしかけられたトラップの種類は chest_traps 配列に定義されており、どのトラップが仕
掛けられているかは ObjectType::pval にこの配列の要素番号を格納することで決定している。
しかし、トラップを解除した時解除済みのマークとしてこの pval の符号を逆転して負にする
仕様となっている。
これを考慮せずそのまま配列にアクセスしてしまい、結果として負の値の要素にアクセスして
しまっている。
chest_traps 配列にアクセスする時は pval が確実に正の値であることをチェックするように
修正する。

[Fix] chest_traps 配列外アクセス

---

src/mspell/mspell-data.cpp

Resolves #2543 
言語仕様により std::initializer_list はコピーした時にリストの値自体のコピーはしない
いわゆるシャローコピーである事が規定されている。
そのため、MSpellDrsDataのコンストラクタが終了した時に引数drsに構築されたリストの値を
保持する領域は解放されており、コンストラクタで生成したラムダ式にコピーキャプチャした
std::initializer_list が指しているリストの値の領域は不正な領域となる。
結果として update_smart_learn の引数が想定していないものとなり、 smart_learn が
正常に機能しない。
ラムダ式にキャプチャする時に std::vector オブジェクトに初期化キャプチャすることで
この問題を回避するように修正する。

[Fix] 一部の魔法で smart_learn が正常に機能していない

---

src/io-dump/character-dump.cpp

博物館のアイテムをキャラクタダンプに書き出す時に、store_ptr を使用すべき箇所で誤って
st_ptr を使用しているのが原因。
我が家のアイテム出力と同じように store_ptr を使用する箇所では日本語版と英語版を分け
ないコードに修正する。

[Fix] 英語版でキャラクタダンプ出力時にクラッシュする

---

src/store/store-util.h

クラス定義内でunique_ptrを初期化した結果、std::unique_ptr\<ObjectType\[\]\> がインライン展開される
しかしObjectType型は不完全型なのでコンパイルエラーになる
Habu 氏のコメントに基づいて修正し、VS2022 v17.3 にてコンパイルが通ることを確認しました
ご確認下さい

Visual Studio 2022 v17.3 からコンパイルエラーが出るようになったのを修正した

---

src/store/store-util.cpp
src/store/store-util.h
src/store/store.cpp

掲題の通りです
過去、C言語でリファクタリングしていた頃に、ヘッダ同士の依存性を減らすべく苦闘していた頃のコードです
今はC++になったのでクラス化に伴い依存性は強制的に収束傾向、役目を終えたと思われるので引数を減らすように再修正しました
ご確認下さい

store_create() からコールバックをなくした

---

.github/scripts/check-format.sh
src/mutation/mutation-processor.cpp
src/status/bad-status-setter.cpp

Resolve #2599
以下の修正を行いました。
- 正しく clang-format-15 をインストールできるバージョン15用のAPTリポジトリを追加
- 今後の同様の事態に備えて clang-format を正しく実行できなかったときはソースコード整形チェック失敗となるようにする
- ソースコード整形チェックが正しく機能していなかった間に混入した未整形のソースコードを整形

clang-format によるソースコード整形チェックが機能していない問題を修正

---

src/object-use/read/scroll-read-executor.cpp
src/spell/spells-object.cpp
src/spell/spells-object.h

掲題の通りです
それはそれとしてamusement() 自体読みづらかったのであちこち修正しました
★太公望の釣り竿 がドロップした後は通常の釣り竿ドロップ処理に進まなくなることをステップ実行で確認しました
ご確認下さい

誰得の巻物を使うとINSTA_ART指定のベースアイテムが生成される場合がある事象を修正した

---

src/flavor/flag-inscriptions-table.cpp
src/flavor/flag-inscriptions-table.h
src/flavor/flavor-util.cpp

特性表示記号テーブルの定義について以下のリファクタリングを行いました。
- テーブルの初期化リストの整列
- except_flag を int から std::optional<tr_type> に変更
- constを付与

特性表示記号テーブル定義のリファクタリング

---

src/flavor/flag-inscriptions-table.h

except_flag をコピー渡しすると MSVC の警告 C4868 にひっかかるため参照渡しにしておく。

[Fix] flag_insc_table のコンストラクタ引数 except_flag をconst参照にする

---

src/specific-object/torch.cpp

松明を投げつけた時に燃料残量を減らす処理で負の値になってもそのままにしているのが原因。
負の値になったときは強制的に 0 にするよう修正する。

[Fix] #2577 松明の燃料残量が異様に大きな数値になる

---

src/action/weapon-shield.cpp

二刀流からメインの武器を外してサブの武器をメインに持ち替える処理で、両手持ちできるか
どうかの判定を行うアイテムを参照するポインタ変数が誤っている。
正しく持ち替えた武器を指すポインタ変数を使用するよう修正する。

[Fix] #2535 武器を構えた手が誤って表示されることがある

---

src/object-use/throw-execution.cpp
src/object-use/throw-execution.h

Resolves #2139 
バージョン 2.2.1r では必殺剣「ブーメラン」では投げるアイテムを装備中の武器しか選択でき
なかったが、リファクタリング時のロジック変更ミスにより全ての持ち物・装備から投げるアイ
テムを選択可能になってしまっていた。
これにより装備中の武器以外を選択すると配列外参照を引き起こし、異常なダメージを与えること
があるというバグの原因となっている。
2.2.1r の頃の以下の挙動に戻す。
- 両手にそれぞれ武器を持っている場合はどちらを投げるか選択する
- 片手にしか武器を持っていない場合は選択せずにその武器を投げる
なお、どちらの手にも武器を持っていない場合はそもそも必殺剣を発動することができない。

[Fix] 必殺剣「ブーメラン」で何でも投げられてしまう

---

src/artifact/artifact-info.cpp
src/system/angband-version.h

Hotfix (クラッシュバグ)につきmaster ブランチにも反映させます
ご確認下さい

アイテムから発動IDを取ろうとする処理で落ちることがある

---

src/melee/melee-spell-flags-checker.cpp

ms_ptr->t_ptr が適切な要素を指す前にその参照 t_ref を取得してしまっている。
ms_ptr->t_ptr が nullptr の場合、t_ref はヌル参照となりクラッシュする。 ms_ptr->t_ptr にアドレスが正しく代入された後に参照を取るように修正する。

[Fix] モンスターが魔法を使用する時にクラッシュする

---

src/effect/effect-player-resist-hurt.cpp

Resolves #2668
リファクタリング時の真偽反転によるエンバグ。正しい真偽値に修正する。

[Fix] 暗黒・盲目耐性なしで暗黒属性攻撃を受けても盲目にならない

---

src/spell-class/spells-mirror-master.cpp

自身をターゲットにしてスーパーレイを打つと魔法軌道の長さが 0 になるが、この時内部で保持
するサイズ 0 のコンテナに対し back() を取ってしまいクラッシュする。
長さが 0 の時はその後の処理を行わずリターンするようにする。
なお、この時何も起きずMPだけ消費することになるが、エンバグ前も同じ仕様である。

[Fix] #2667 自身をターゲットにスーパーレイを打つとクラッシュする

---

src/birth/history.cpp

掲題の通りです
一部日英切り替えのマクロがずれていました
ご確認下さい

クラスによって生い立ちが一部欠ける場合がある事象を修正した

---

configure.ac

configure の --with-setgid オプションででグループを指定してコンパイルし、make install を行うと指定された prefix ディレクトリ以下に実行バイナリとゲームのデータがインストールされるが、このときゲームのデータがインストールされるパス DEFAULT_LIB_PATH の定義が "${prefix}/share/games/hengband/lib/" と ${prefix} の部分が正しく展開されずそのまま残ってしまうためゲームのデータが読み込めず、ゲームを起動することができない。
configure.ac 内の `$datadir` を `$datarootdir` にすると ${prefix} の部分が正しく 展開されるようになるようなので、そのように修正する。

[Fix] configure の --with-setgid オプションが正しく機能しない

---

src/store/rumor.cpp
src/system/artifact-type-definition.cpp
src/system/artifact-type-definition.h

掲題の通りです
具体的にはartifact-type-definition.cpp/h に、固定アーティファクトIDから固定アーティファクトへのポインタを返すシングルトンなメソッドを実装しました
optionalなのでhas\_value() で存在確認が可能です
ついでにC言語時代の配列だらけでイミフだったので所見でも理解度が上がるように改造しました
ついでにしてはちょっと規模が大きい気もしますし、リファクタリングとしては中途半端な気もしますが、デバッグで動かしたところ、固定アーティファクト・町・ダンジョン・モンスター全て問題なく動いたのでこのままPRに出します
ご確認下さい
(続きは別チケットで行う予定)

噂を聞く時に欠番の固定アーティファクトIDを指定されるとクラッシュする不具合を修正した

---

src/main-win.cpp
src/main-win/commandline-win.cpp
src/main-win/main-win-utils.cpp

先の std::string クラスの c_str() メソッド呼び出しを data() 呼び出しに統一する修正を行った時に to_multibyte クラスの c_str() メソッド呼び出しまで巻き込んでしまっていた。
to_multibyte は独自に作成したクラスであり、対となるクラス to_wchar に wc_str() というメソッドもあるため、とりあえずこのクラスでは c_str() を呼び出すことにする。

[Fix] to_multibyte クラスの存在しないメソッド data() を呼んでいる

---

src/main-win/main-win-utils.cpp

掲題の通りです
長い名前のバリアントにも対応できるように、最大63文字までのミューテックスとしました
ご確認下さい

[Fix] #2765 OSに渡すミューテックス文字列が正しく初期化されず毎回異なる値となってアプリの多重起動を許してしまう事象を修正した

---

src/market/building-initializer.cpp
src/object/object-kind-hook.cpp
src/object/object-kind-hook.h
src/store/articles-on-sale.cpp
src/store/articles-on-sale.h
src/system/baseitem-info-definition.cpp
src/system/baseitem-info-definition.h

掲題の通りです
コンストラクタ通過後は変更できないイミュータブルクラスにしました
ご確認下さい
他の諸クラスにあるtval/sval の組み合わせは、次のチケットで順次置換する予定です
(tval/svalのアップデートはまだしない想定、するなら返り値をBaseitemKeyにしてイミュータブルを保つ)

ベースアイテムのtval/sval を一意に特定できるクラスを作った

---

src/main-gcu.cpp

Resolve #2766 
レイアウトオプションの実装でサブウィンドウを4個以上表示可能になったので、表示可能最大数
である8個（メインウィンドウ含む）までウィンドウを表示できるようにする。

[Feature] GCU版のウインドウ数を最大8個表示できるようにする

---

src/main-gcu.cpp

Resolve #2777 
curses の wclear 関数は端末全体を一旦消去した後に描画しなおす。そのためサブウィンドウ
の数だけ連続して wclear が呼ばれた時に画面全体が連続してちらついて見えることがある。
ウィンドウに表示している文字を消去するだけであれば werase 関数でも十分であり、wclear
と違い端末全体を消去して描画しなおすことがなくちらつきは発生しないので、werase 関数を
使用するようにする。

[Fix] GCU版で画面のちらつきの発生を抑制する

---

src/artifact/fixed-art-generator.cpp
src/floor/floor-object.cpp
src/monster-floor/special-death-switcher.cpp
src/room/rooms-special.cpp
src/store/store.cpp
src/system/system-variables.cpp
src/system/system-variables.h
src/world/world-object.cpp
src/world/world-object.h

`get_obj_num` という名称だとオブジェクトの個数を取得するように読めてしまうので
indexを取得することが明確になる名前にrenameしました。
合わせてコメント修正や `get_object_num_hook` -> `get_object_index_hook` へのrenameも行っています

[Refactor] get_obj_num関数をget_obj_indexにrenameした

---

src/object/object-kind-hook.cpp

#2745 の作業漏れです
元々関数オーバーロードのために意図して引数を別々にしていましたが、関数名の方を別々にしたことによって引数はBaseitemKeyでも良くなりました
チケット番号はありません、ご確認下さい

exe_lookup() の引数をtval/sval からBaseitemKey に差し替えた

---

src/flavor/named-item-describer.cpp
src/system/object-type-definition.cpp
src/system/object-type-definition.h

[【QoL向上】魔法書のアイテム名先頭にLv値を表示する](https://github.com/hengband/hengband/issues/2785)
↑issueで挙げた対応のpull reqになります。
- ロジックをいじる形で実装しましたが、`BaseItemDefinitions.txt` を下のように編集するのでも実装はできそうです（この場合Lvの表示はアイテム名の先頭ではなくなりますが）
- 例: `N:334:[入門書]` → `N:334:[Lv1 入門書]`
- 最初は魔法書かどうかの判定&Lv値追加ロジックを `describe_named_item` の下位関数である `switch_tval_description` から呼び出される各 `describe_book_*` 関数あたりに記述しようと思ったのですが、↓の理由により一旦見送りました
- describe_book_* で参照してるのが文字列ポインタの `basenm` だけなので可変する文字列を扱おうとすると変更量が多くなりそう（C/C++の文字列に対する経験値があまりないので。。）
- 言語がnot JPのときに `if (mp_ptr->spell_book == ItemKindType::LIFE_BOOK) ` で分岐している意図がわからなかった

[Feature] 魔法書の先頭にLv値を表示するようにした

---

Hengband/Hengband/Hengband.vcxproj

掲題の通りです
議論あるようであれば次回のα版に延期で問題ないです (M$の公式サイトにすらロクな情報がないのでちょっと不安)
ご確認下さい

規定で無効化されているコンパイル警告C5264 (定数不使用)を抑制した

---

src/autopick/autopick-finder.cpp
src/birth/birth-body-spec.cpp
src/cmd-item/cmd-magiceat.cpp
src/core/asking-player.cpp
src/flavor/flavor-util.cpp
src/info-reader/general-parser.cpp
src/inventory/floor-item-getter.cpp
src/inventory/item-getter.cpp
src/knowledge/knowledge-features.cpp
src/main-win.cpp
src/melee/melee-switcher.cpp
src/monster-attack/monster-attack-switcher.cpp
src/player-info/class-ability-info.cpp
src/player/player-status.cpp
src/racial/class-racial-switcher.cpp
src/racial/racial-switcher.cpp
src/room/rooms-builder.cpp
src/spell-kind/blood-curse.cpp
src/spell-kind/spells-random.cpp
src/store/service-checker.cpp
src/target/target-setter.cpp
src/term/gameterm.cpp

switch-case 文において意図したフォールスルーを行っている箇所について、コメントの代わりに C++17 から追加された [[fallthrough]] 属性を使用する。
また、もともとフォールスルーコメント不要な箇所についてはコメントを削除する。
変愚蛮怒のソースコードに起因する C5262 の警告についてはすべて [[fallthrough]] で回避するようにしましたが、STLのヘッダ内に該当の警告がひっかかる箇所があり、その部分についての警告は依然として出力されます。これはMicrosoftの対応待ちになるのでしょうか？

[Fix] 意図したフォールスルーに [[fallthrough]] 属性を使用する

---

src/autopick/autopick-entry.cpp
src/autopick/autopick-matcher.cpp
src/cmd-action/cmd-spell.cpp
src/cmd-item/cmd-destroy.cpp
src/flavor/named-item-describer.cpp
src/knowledge/knowledge-items.cpp
src/object-hook/hook-magic.cpp
src/object-hook/hook-magic.h
src/object/object-info.cpp
src/object/object-info.h
src/object/object-kind-hook.cpp
src/player/player-status.cpp
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/item-entity.cpp
src/system/item-entity.h

作業中に出てきた、「これは置換作業と別にやるべきだろう」という整理系コミットをまとめました
特に、is\_spell\_book() の扱いは、#2815 に絡んで不具合修正に近い仕様変更があります
併せてご確認下さい
(何故か呪術は魔法書でない扱いになっている等)

ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした

---

src/artifact/random-art-pval-investor.cpp
src/cmd-item/cmd-eat.cpp
src/object-enchant/weapon/abstract-weapon-enchanter.cpp
src/object-hook/hook-weapon.cpp
src/object-use/use-execution.cpp
src/object-use/zapwand-execution.cpp
src/object/tval-types.h
src/perception/object-perception.cpp
src/player/player-status.cpp
src/smith/object-smith.cpp
src/spell-kind/spells-detection.cpp
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/item-entity.cpp
src/system/item-entity.h
src/util/object-sort.cpp
src/view/object-describer.cpp
src/view/object-describer.h

掲題の通りです
ItemEntity のオブジェクトメソッドをBaseitemKey のオブジェクトメソッドにリダイレクトした他、本体作業のための最適化を複数図りました
ロジック変更も複数あります
ご確認下さい

ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その2

---

.github/workflows/build-with-autotools.yml
.github/workflows/publish-spoiler-page.yml
bootstrap
configure.ac
m4/ax_cxx_compile_stdcxx.m4

configure.ac で、 autoconf-archive に含まれるコンパイラが対応するC++の言語標準 バージョンをチェックし、コンパイルオプションに -std=... を付加するマクロを使用している。
これまでは autoconf-archive パッケージをインストールする運用をしていたが、再配布・ 改変が可能なライセンスなので手間がかからなくて済むようにソースに含めることにする。

[Add] C++の言語標準バージョンをチェックする autoconf マクロ

---

src/combat/shoot.cpp
src/combat/shoot.h
src/flavor/flavor-describer.cpp
src/object/tval-types.h
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/item-entity.cpp
src/system/item-entity.h
src/view/display-player-middle.cpp
src/view/status-first-page.cpp

掲題の通りです
ItemEntity のオブジェクトメソッドをBaseitemKey のオブジェクトメソッドにリダイレクトした他、本体作業のための最適化を複数図りました
(tval/svalに依存する関数の、BaseitemKey のオブジェクトメソッドへの繰り込み 他)
ロジック変更も複数あります
ご確認下さい

ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その4

---

src/cmd-item/cmd-eat.cpp
src/cmd-item/cmd-magiceat.cpp
src/object-use/zaprod-execution.cpp
src/object/object-flags.cpp
src/realm/realm-hex.cpp
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/item-entity.cpp
src/system/item-entity.h

掲題の通りです
ItemEntity のオブジェクトメソッドをBaseitemKey のオブジェクトメソッドにリダイレクトした他、本体作業のための最適化を複数図りました
(tval/svalに依存する関数の、BaseitemKey のオブジェクトメソッドへの繰り込み 他)
ロジック変更も複数あります
ご確認下さい

ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その5

---

src/cmd-action/cmd-hissatsu.cpp
src/cmd-action/cmd-shoot.cpp
src/cmd-action/cmd-spell.cpp
src/cmd-item/cmd-item.cpp
src/mind/mind-mage.cpp
src/realm/realm-hex.cpp
src/spell-realm/spells-craft.cpp

掲題の処理をする過程で、「ついで」で実施したような諸作業 (明示的な型宣言 → 型推論)を別PRに分離しました
ご確認下さい
(注：一部このPRから漏れて本体コミットに紛れ込んでいるかもしれませんがもはやご容赦下さい)
(その5がマージされるまではドラフト)

ItemEntity::tval/sval をBaseitemKey に差し替えるための準備 その6

---

src/info-reader/artifact-reader.cpp

偶然、buf をtokens に分解しているのに使っていない箇所を見つけたので差し替えました
2箇所だけサクッと差し替えたのでチケットはありません
ご確認下さい

parse_artifacts_info() からbuf へ直接依存している読み込みルーチンを排除した

---

Build-Windows-Release-Package.ps1

テンポラリ削除エラーに -Force を付けて対処。削除してしまっていた、mp3とreadme.txtを削除除外から外して正しくアーカイブされることを確認しました。チェックお願いします。

サブディレクトリとデフォルトmp3の追加に合わせたWindows用ビルドスクリプトを修正。

---

.github/workflows/publish-spoiler-page.yml

スポイラー生成用バイナリのビルド時にサブモジュールディレクトリが存在しないためエラーと
なるのが原因。
サブモジュールも合わせてチェックアウトされるように GitHub Actions を修正する。
簡単な修正でゲーム本体とも関係ないので対応 Issue はありません。

[Fix] github.io の自動生成スポイラーページの更新に失敗する

---

src/main/info-initializer.cpp

Resolves #2854 
GCC 11 までは問題なかったが、GCC 12 で std::vector::assign に渡す第2引数に対し {} だけを指定すると、コンテナの要素の型のデフォルトコンストラクタ呼び出しだと推論されなくなったようでコンパイルエラーが発生する。
エラーを回避するため、型名を明示的に与えるようにする。
sprintf の警告については他PR（#2861）で対応しそうなので、このPRでではコンパイルエラーにのみ対処。

[Fix] GCC 12 でビルドすると info-initializer.cpp でコンパイルエラーが発生する

---

src/flavor/flavor-describer.cpp
src/flavor/flavor-util.cpp
src/flavor/flavor-util.h
src/flavor/named-item-describer.cpp
src/flavor/tval-description-switcher.cpp

まず #2865 のとっかかりとして、これらのメンバが実際に表示するときと全く異なる場所でセットされているため flavor_type 引数を削除しながらリファクタリングするうえで邪魔になるので先に削除しておく。

[Refactor] flavor_type 構造体の show_weapon/show_armour メンバを削除

---

src/store/rumor.cpp
src/system/baseitem-info.cpp
src/window/display-sub-windows.cpp

VS 2022 でプリコンパイルヘッダ無しでビルドしたところ、いくつかヘッダのインクルード
漏れによるエラーが検出されたので必要なヘッダのインクルードを追加する。
include 行の追加だけなので Issue はなし。

[Fix] ヘッダのインクルード漏れ

---

src/wizard/monster-info-spoiler.cpp

コミット 23d1bbe において「Spd:」の表示部分が誤って消されてしまっているので復活させる。

[Fix] mon-info.txt に出力される情報がおかしい

---

src/flavor/flavor-describer.cpp
src/flavor/flavor-util.cpp
src/flavor/flavor-util.h
src/flavor/named-item-describer.cpp
src/flavor/named-item-describer.h
src/flavor/tval-description-switcher.cpp
src/flavor/tval-description-switcher.h

#2865 の一環。
この PR では describe_named_item とそこから呼ばれる関数群のリファクタリングを行っています。
flavor_ptr の追い出しとともに、ある程度 doxygen コメントの追加や処理内容に即していない関数名の修正等を含みます。

[Refactor] describe_named_item

---

src/flavor/flavor-util.cpp
src/flavor/flavor-util.h
src/flavor/named-item-describer.cpp
src/inventory/player-inventory.cpp

#2865 に関して行ってきた一連のリファクタリングの仕上げ。
describe_flavor がかつて使用していた神構造体の flavor_type とバッファ非安全な関数群 object_desc_\* をごっそり削除。

[Refactor] describe_flavor (5/5)

---

src/cmd-io/cmd-gameoption.cpp
src/cmd-visual/cmd-draw.cpp
src/core/game-play.cpp
src/core/window-redrawer.cpp
src/inventory/floor-item-getter.cpp
src/inventory/item-getter.cpp
src/io/input-key-acceptor.cpp
src/io/record-play-movie.cpp
src/main-gcu.cpp
src/main-win.cpp
src/main-x11.cpp
src/main.cpp
src/term/gameterm.cpp
src/term/gameterm.h
src/view/display-messages.cpp
src/window/display-sub-window-spells.cpp
src/window/display-sub-windows.cpp

[【リファクタリング】angband_term配列に対してループ処理を記述する際、'8'というマジックナンバーを使っているのをやめる](https://github.com/hengband/hengband/issues/2860)
↑issueで挙げた対応のpull reqになります。
- angband_term → angband_termsにrename
- angband_termsの型を配列からstd::array<term_type *, 8> に変更
- angband_termsに対するループ処理を angband_terms.size()を使って行うようにした

[Refactor] termの配列に対してループ処理をする際にマジックナンバーを使っているのをやめる

---

src/main.cpp

Resolve #2926 
ゲーム終了時に angband_terms 配列が指している term_type 構造体を破棄する時逆順で破棄しているが、最初の要素のインデクスが angband_terms.size() となっているため配列外参照となっている。
単純に size() - 1 から始めるように修正してもいいが、逆順という意図を込めるためリバースイテレータで処理するように変更する。

[Fix] angband_terms の配列外参照

---

src/term/screen-processor.cpp
src/term/screen-processor.h
src/term/z-term.cpp
src/term/z-term.h

Cスタイルの文字列(concptr)、std::string、std::string_view のいずれもシームレスに 受け取れるように、以下の関数の文字列を指定する引数を concptr から std::string_view に変更する:
- term_addstr
- term_putstr
- c_put_str/put_str
- c_prt/prt
本格的に文字列の std::string 化が進みそうなので #1450 の一環としてよく使用される関数の文字列指定引数を concptr から std::string_view にしていく。

[Refactor] 画面に文字列を出力する関数のシグネチャ変更

---

src/flavor/flavor-describer.cpp
src/flavor/flavor-util.cpp
src/flavor/flavor-util.h

get_ability_abbreviation 関数のインターフェースを、引数が指すバッファ領域に文字列 を書き込む方式から std::string 型文字列を返す方式に変更する。
#2919 について、まず get_ability_abbreviation について対応。

[Refactor] get_ability_abbreviation 関数のインターフェース

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/core/window-redrawer.cpp
src/system/monster-entity.cpp
src/system/monster-entity.h
src/window/main-window-left-frame.cpp
src/window/main-window-left-frame.h
src/window/main-window-row-column.cpp
src/window/main-window-row-column.h

[【QoL向上】ターゲットしているモンスターの画面に出す情報を追加](https://github.com/hengband/hengband/issues/2825)
↑issueで挙げた対応のpull reqになります。
- 従来の処理では恐怖状態の時にHPバーの色を紫にしていましたが、下記理由によりゲージの色を変えないようにしました
- 恐怖状態のときにテキストで表示するようにした
- 他の状態異常の時に特に色を変えてなくて一貫性がない
- 無敵と睡眠時のゲージ色は迷いましたが、恐怖よりもプレイに影響がありそうなのでそのままにしています
- 従来の処理では 
```
キャラのステータス
ターゲット情報
キャラ情報（切り傷、朦朧、空腹、探索、学習など）
``` 
といった順で表示していましたが、これだと
```
ユーザー情報
敵情報
ユーザー情報
``` 
という並び順で違和感があったので
```
キャラのステータス
キャラ情報（切り傷、朦朧、空腹、探索、学習など）
ターゲット情報
``` 
の順で表示するようにしました　 
https://github.com/hengband/hengband/issues/2825#issuecomment-1325774643
↑とのことなので、マージはそれが片付いてから
- 画面に出す文字列は定数ファイルにまとめたいと思った
- 状態異常と色の対応もまとめられると良いと思った
- defineも見つけたところからconstexpr|constに変えたいと思った

[Feature] モンスターのHP表示部に出す情報追加

---

src/load/load-util.cpp
src/load/load-util.h
src/lore/lore-util.cpp
src/lore/lore-util.h
src/term/screen-processor.cpp
src/term/screen-processor.h
src/view/display-lore.cpp
src/view/display-lore.h
src/wizard/monster-info-spoiler.cpp

format 関数の戻り値を std::string にするにあたり、事前のリサーチで format の戻り 値を直接渡している関数のうち使用箇所が多く std::string_view に変更しておいたほうが 良いと思われる以下のものを先に変更しておく。
- load_note
- roff 系関数

[Refactor] いくつかの関数の文字列引数の型を std::string_view に変更

---

src/view/display-player.cpp
src/view/display-util.cpp
src/view/display-util.h
src/view/status-first-page.cpp

display_player_one_line 関数は format 関数の戻り値をダイレクトに渡している箇所が 多いので、format 関数の戻り値が std::string になっても変更しなくてすむように引数を concptr から std::string_view に変更する。
また、現在 std::string::data() メソッドを呼び出して渡している箇所は、data() の呼 び出しが不要になるので std::string オブジェクトをそのまま渡すようにする。

[Refactor] display_player_one_line 関数のシグネチャ変更

---

src/flavor/flavor-describer.cpp
src/flavor/flavor-util.cpp
src/flavor/flavor-util.h

get_inscription 関数のシグネチャを、文字列を格納するバッファを指すポインタ引数を受け取る方式から std::string 型の戻り値で文字列を返す方式に変更する。

[Refactor] get_inscription 関数のシグネチャを変更

---

src/core/asking-player.cpp
src/core/asking-player.h

asking-player.cpp で定義されている、ユーザに入力を促す get_* の関数群に与えるの メッセージの引数の型を concptr から　std::string_view に変更する。
但し、get_quantity は nullptr の時にデフォルトメッセージを表示するという例外がある ので別途対応する。

[Refactor] asking-player.cpp の関数群のシグネチャを変更

---

src/cmd-item/cmd-destroy.cpp
src/cmd-item/cmd-item.cpp
src/core/asking-player.cpp
src/core/asking-player.h
src/spell-realm/spells-sorcery.cpp
src/store/purchase-order.cpp
src/store/sell-order.cpp

他の get_* シリーズと違い、既存の仕様で nullptr が渡された時にデフォルトメッセージを表示するという仕様があるので単純に std::string_view にできない。
したがって std::optional<std::string_view> にし、std::nullopt で対応する。

[Refactor] get_quantity 関数のシグネチャ変更

---

.github/workflows/build-with-autotools.yml
.github/workflows/publish-spoiler-page.yml
.github/workflows/pull-request-status-check.yml

GitHub Actions の Node.js 12 のサポート終了に伴い、 actions/checkout@v2 が 使用できなくなるので、actions/checkout@v3 に更新する。

[Fix] Workflow ファイルの actions/checkout のバージョン更新

---

.github/workflows/build-with-autotools.yml
.github/workflows/create-cache-for-ccache.yml
.github/workflows/pull-request-status-check.yml

C++20に備えるため、gccのバージョンを11、clangのバージョンを14にする。
また runner をこれらのコンパイラ・ツールチェインがデフォルトでインストールされている
Ubuntu-22.04 にする。
さらに Node.js 12 のサポート終了にともない、 ccache-action のバージョンを 1 から 1.2 にする。
#2894 に対する関連作業です。

[Fix] CIで使用するコンパイラのバージョンをアップデート

---

Hengband/Hengband/Hengband.vcxproj
configure.ac
m4/ax_cxx_compile_stdcxx.m4
src/maid-x11.cpp

Resolves #2894 
各プラットフォームで対応の準備が整ったので、C++ 言語の標準バージョンを C++20 にする。
なお、Visual Studio 用プロジェクトの設定は latest （C++23 の機能を含むプレビュー バージョン）が指定されていたが、こちらも C++20 を指定することとする。

[Feature] C++ 言語の標準バージョンを C++20 にする

---

src/autopick/autopick-drawer.cpp
src/birth/birth-select-realm.cpp
src/birth/birth-wizard.cpp
src/birth/history-generator.cpp
src/cmd-action/cmd-mind.cpp
src/cmd-action/cmd-racial.cpp
src/cmd-action/cmd-spell.cpp
src/cmd-item/cmd-magiceat.cpp
src/io/read-pref-file.cpp
src/knowledge/knowledge-self.cpp
src/market/building-craft-armor.cpp
src/mind/mind-elementalist.cpp
src/mind/mind-sniper.cpp
src/mind/mind-weaponsmith.cpp
src/perception/identification.cpp
src/player/process-death.cpp
src/util/buffer-shaper.cpp
src/util/buffer-shaper.h
src/view/display-player.cpp
src/view/display-util.cpp
src/view/display-util.h

shape_buffer のシグネチャを結果を格納するバッファ領域を指すポインタを受け取る方式から
std::string 型文字列の配列を返す方式に変更する。
以下に変更のポイントを記載するので、それを念頭にレビューいただきたいです。
シグネチャ変更に伴い、だいぶ読みづらい元のコードから仕様を整理し C++ 風に書き直しました。仕様の詳細は doxygen コメントにまとめています。また、禁則処理したほうがよいと思われる文字を複数追加しました。
なお、日本語独特の処理であるため、ネットを検索してもふさわしい英語がぱっと出て来ないのでローマ字名称の kinsoku のままにしています。
この処理を行う似たようなループが大量にあったので、display_wrap_around 関数にまとめそれを呼ぶようにしました。一部元のコードでは prt ではなく put_str を使っているものがありますが、この2者の違いは行末まで一旦消すかどうか（prtは消す、put_strは消さない）だけで、 put_str を使用している箇所も prt で問題ないと判断しました。これについてもチェックいただきたく。
ごちゃごちゃしていますが、#2955 で改めてリファクタリングを予定しているので、今回の PR では現在のコードを極力維持する形で修正しています。

[Refactor] shape_buffer のシグネチャ変更に伴うリファクタリング

---

src/perception/identification.cpp

Resolves #2982 
Apple Clang 14 ではまだ The One Ranges Proposal がサポートされていないので、 C++20 で追加された std::ranges::* のSTLアルゴリズムが使用できない。
したがって従来の通りイテレータペアを受け取る std::transform を使用する。

[Fix] std::ranges::transform -> std::transform

---

src/io/signal-handlers.cpp

SIGKILL はいかなる手段を用いても捕捉不可能なシグナルであり、シグナルハンドラを設定する事自体間違いなので削除する。
#2983 の補足事項で言及されている件についての対処です。

[Fix] SIGKILL にシグナルハンドラを設定している

---

src/player/process-death.cpp

Resolves #2955 
プレイヤーが殺されたモンスターの名称を墓石に表示する時、最大2行にわたって表示するが、2行に収まりきらない場合に残りを省略するコードが意図通りに動作していないので修正する。
また、モンスター名称を墓石に表示する時の仕様について doxygen コメントを追加し、関連する周辺コードをリファクタリングする。
3行以上になる時の処理の確認はゾート先生（モンスターID:1259）、『△△△』の途中で分割される時に全体を2行目にくるようにする処理の確認はシアーハートアタック（モンスターID:531）で確認できます。

[Fix/Refactor] 殺されたモンスター名を墓石に表示するコード

---

src/core/object-compressor.cpp
src/flavor/named-item-describer.cpp
src/floor/floor-streams.cpp
src/io-dump/random-art-info-dumper.cpp
src/monster-floor/special-death-switcher.cpp
src/object-enchant/weapon/melee-weapon-enchanter.cpp
src/object/object-value-calc.cpp
src/racial/racial-android.cpp
src/save/item-writer.cpp
src/spell-kind/spells-floor.cpp
src/spell-kind/spells-perception.cpp
src/store/purchase-order.cpp
src/store/service-checker.cpp
src/util/object-sort.cpp
src/wizard/wizard-item-modifier.cpp

現状、アイテムがランダムアーティファクトかどうかの判定は art_name が 0 かどうか (art_name は名称が登録された quark_str のインデクスを持つ) で判断しており、それを ラップするメソッド ItemEntity::is_random_artifact が用意されているがこれが正しく使用されていない箇所が多数あるので、すべてこのメソッドを使用するように変更する。
#2911 に関連する作業として最初にやっておいたほうが良いのでやっておく。

[Refactor] アイテムがランダムアーティファクトかどうかの判定にメソッドを使用する

---

src/artifact/random-art-generator.cpp

アーティファクト生成の巻物でランダムアーティファクトを生成した時、「秘」と「個」の徳が上昇するようになっているが、名付けをキャンセルしてランダムな名前を付けた時にこれらの徳があがらなくなっている。
常に上昇するよう修正する。
些細な修正なので Issue なし。
art_name 関連のコードを見ていて不自然だと思い2.2.1 のコードと比較したところ、リファクタリング時に early return をすることで徳を変化させるコードを通らなくなったようです。
この処理はランダムアーティファクトの名前をつける関数の責任範囲ではないので外に出しました。

[Fix] 巻物でアーティファクトを生成した時に徳が変化しない事がある

---

src/monster-floor/monster-death.cpp
src/monster/monster-damage.cpp

以前行われていた、モンスターを倒した時の状況に合わせた「殺した・葬り去った・倒した」の
メッセージ切り替えが、リファクタリング時にすべて「殺した」になってしまっていたので元の
仕様に戻す。
微修正なのでIssueなし。
該当コミット: 97eb4ef031f5cefe86abfcb6ef3e8896fa144c3e

[Fix] モンスターを倒した時のメッセージがおかしい

---

src/effect/effect-player-switcher.cpp

Resolves #2993 
過去に HURT に対応する AttributeType が MONSTER_MELEE に変更されたが、その時 switch_effects_player に MONSTER_MELEE が追加されなかったため、爆発のダメージが 入らなくなっている。
ひとまず元の MISSILE と同じく MONSTER_MELEE でも effect_player_missile を呼ぶ ようにしておく。

[Fix] モンスターの爆発でプレイヤーがダメージを受けない

---

src/artifact/random-art-generator.cpp
src/flavor/named-item-describer.cpp
src/load/old/item-loader-savefile50.cpp
src/load/old/load-v1-5-0.cpp
src/object-activation/activation-others.cpp
src/save/item-writer.cpp
src/system/item-entity.cpp
src/system/item-entity.h

Resolves #2911 
quark_add/quark_str のインデクスを持たせるのではなく直接文字列を持たせるようにする。 既存のインデクスが0以外ならランダムアーティファクト、0なら非ランダムアーティファクト
という仕様を維持するため std::optional<std::string> 型にし、非ランダムアーティファ クトの場合は std::nullopt とする。
また明確にランダムアーティファクトの名称である事がわかるようにするためメンバの名称を
randart_name に変更する。

[Refactor] ItemEntity::art_name の型/名称を変更

---

src/object-enchant/others/apply-magic-lite.cpp
src/store/store-util.cpp

光源のスタックの挙動において、重なるべきものが重ならなかったり、逆に重ならないはずのものが重なったりする。
おかしな挙動の原因は2つ。
- 初期所持の光源は pval が初期値のままだが、店売りアイテムは LiteEnchanter により pval が 0 になる。したがって pval が異なることにより重ならない。
- 店のアイテムのスタック判定 store_object_similar で fuel の値が考慮されていない ため、残りターン数が異なっても重なってしまう。
LiteEnchanter で pval を 0 にせずそのままの値とし、store_object_similar には fuel の比較を追加することで修正する。

[Fix] 光源のスタックの挙動がおかしい

---

src/autopick/autopick-entry.cpp
src/autopick/autopick-util.cpp
src/cmd-item/cmd-item.cpp
src/flavor/flavor-describer.cpp
src/flavor/flavor-util.cpp
src/flavor/named-item-describer.cpp
src/inventory/inventory-curse.cpp
src/inventory/inventory-util.cpp
src/inventory/recharge-processor.cpp
src/io/input-key-requester.cpp
src/load/old/item-loader-savefile50.cpp
src/load/old/load-v1-5-0.cpp
src/object/object-stack.cpp
src/player/player-status-flags.cpp
src/save/item-writer.cpp
src/specific-object/monster-ball.cpp
src/spell-kind/spells-enchant.cpp
src/store/purchase-order.cpp
src/store/sell-order.cpp
src/store/store-util.cpp
src/store/store.cpp
src/system/item-entity.cpp
src/system/item-entity.h

Resolves #2910 
既存の quark_str のインデクスを持たせる方式から文字列を直接持たせる方式に変更する。
空文字列を銘を刻んでいない状態とするのはやや紛らわしくなるので、std::optional<std::string> 型とし、銘を刻んでいない場合は値を std::nullopt とする。

[Refactor] ItemEntity::inscription の型を変更 

---

src/wizard/fixed-artifacts-spoiler.cpp

That was requested in the comments on https://github.com/hengband/hengband/pull/2974 .

Refactor: remove wizard/fixed-artifacts-spoiler.cpp's print_header()

---

src/player/process-death.cpp

std::string_view のイテレータのペアを引数に取るコンストラクタのオーバーロードがまだ Apple Clang でサポートされていないためコンパイルエラーになる。
サポートされている、文字列の先頭文字へのポインタと文字列の長さを取るオーバーロードに変
更する。（そもそもこちらのほうが素直だし最初からこちらにするべきだった）

[Fix] Apple Clang で日本語版がコンパイルできない

---

src/io/interpret-pref-file.cpp
src/main/game-data-initializer.cpp
src/term/gameterm.cpp
src/term/gameterm.h

既存の gf_colors (魔法やブレスなどの属性毎の描画色定義) は quark_str のインデック スを保持している。これを std::string を直接持つように変更する。
一連の quark_str 使用の削除に含まれ単体の変更量が少ないので Issue は作っていません。

[Refactor] gf_colors に直接 std::string を持たせる

---

src/grid/grid.cpp

掲題の通りです (ついでに見つけたdefine定数もconstexprにした)
ご確認下さい
ちなみに、これで2行以上のマクロ関数は絶滅したと思います
(末尾がバックスラッシュされているdefineは他になし)

マクロ関数update_local_illumination_aux() を普通の関数に展開した

---

src/flavor/tval-description-switcher.cpp

describe_flavor をリファクタリングした時に basename と modstr の順序が誤って逆に なっていた。正しい順序に修正する。
Resolves #3014 
なんというポカ。

[Fix] モンスターの死体や骨が正しく表示されない

---

src/artifact/random-art-characteristics.cpp
src/flavor/object-flavor.cpp
src/inventory/inventory-curse.cpp
src/io/files-util.cpp
src/io/files-util.h
src/io/input-key-processor.cpp
src/monster-floor/monster-move.cpp
src/monster/monster-damage.cpp
src/monster/monster-describer.cpp
src/object-enchant/vorpal-weapon.cpp
src/player/player-damage.cpp
src/store/rumor.cpp

掲題の通りです
一部「行が見つからない」というエラーパターンもあるようなので、その時はnulloptを返すように調整しました
ご確認下さい

get_rnd_line() の引数からchar *を削除し、返り値をstd::optional<std::string> に変えた

---

src/term/z-form.cpp
src/view/display-lore.cpp

#2990 に関して、ひとまず使える書式の整理と vstrnfmt 関数がだいぶ読みづらかったのでコードの整形を行いました。
内容についてはコミットログを参照してください。
`__attribute__ format` でチェックを行う件と `%^s` の書式の件については別 PR にて処理したいと思います。

[Refactor/Feature] format/strnfmt の機能整理/コード整形

---

.github/workflows/publish-spoiler-page.yml

ビルドに C++20 が必要になったため、デフォルトの GCC のバージョンが対応していない
Ubuntu-20.04 でビルドに失敗する。
Ubuntu-22.04 に変更して対応する。

[Fix] スポイラーページの自動生成に失敗する

---

src/mind/mind-sniper.cpp

Resolves #3029
スナイパーの技の説明のリストでカンマを付け忘れているため文字列リテラルが連結してしまい、
一つ分足りなくなってしまっている。正しくカンマを付けて修正する。

[Fix] スナイパーの技の説明がおかしい (英語版)

---

configure.ac
src/Makefile.am
src/system/h-system.h

- Avoid compiler error about missing sys/timeb.h.
- Pick up path to X11 headers which are not in the standard include path.
- Make it so using precompiled headers doesn't end with an error when trying to run md5sum.

Facilitate building on OpenBSD

---

src/cmd-building/cmd-building.cpp

Resolves #3045 
ダンジョンの候補を表示するときに一旦選択肢を消しているが、キャンセルされたときに戻す処
理を行っていない。画面を screen_save / screen_load する事で選択肢の表示を戻すよう にする。

[Fix] トランプ魔術の塔の選択肢が消えてしまう

---

src/io/input-key-acceptor.cpp

angband_terms[0]->scr->cx,cy に直接アクセスしているが、これらの値は
term_locate() 関数で取得するべき値なのでそうする。
また、カーソルの取得は all_term_fresh() で行うようにする。
#3026 #3040 に関連して直しておかないといけない所なのでPR単体で修正を行います。

[Fix] inkey() の処理で直接カーソル座標にアクセスしている

---

src/lore/lore-calculator.cpp
src/lore/lore-calculator.h
src/lore/monster-lore.cpp

Resolves #3050 
モンスターの完全な情報が分かるとき（cheat_knowがONのとき・スポイラー出力時など）に、
ドロップ情報のフラグを思い出の状態を考慮しない状態に更新していないのが原因。
ドロップ情報のフラグを正しく更新するようにする。
また、この処理を行っている set_drop_flags() は名称が関数の処理の実態に全く合ってい ないので、set_flags_for_full_knowledge() に変更する。

[Fix] スポイラーの出力にドロップアイテムの質が表示されない

---

src/cmd-visual/cmd-draw.cpp
src/io-dump/character-dump.cpp
src/io/files-util.cpp
src/term/screen-processor.cpp
src/term/z-term.cpp
src/term/z-term.h
src/view/display-player.cpp

Resolves #3026 
画面表示オフセットを設定するクラスを導入し、ひとまずキャラクタ情報画面の中央表示にのみ対応しました。
画面ごとの修正量自体は比較的少なく済みそうなので、この PR で方針が固まれば他の画面を１つずつ対応していきたいと思っています。

[Feature] キャラクタ情報を画面中央に表示する

---

src/core/game-play.cpp

Resolves #3060
メイン画面の resize_hook に resize_map を設定した後、誤って redraw_window を 上書きしてしまっている。
redraw_window はサブ画面にのみ設定するように修正する。

[Fix] メイン画面のサイズ変更時に自動で再描画されない

---

src/core/game-closer.cpp
src/floor/object-scanner.cpp
src/view/display-inventory.cpp
src/window/main-window-equipments.cpp

ゲームオーバー（勝利後に引退・死亡）時の画面をウィンドウの中央に表示する。
勝利後の引退時の王冠表示は元々中央に表示するように計算されていたが、今回のオフセットに
よる中央表示を一貫して適用するため 80x24 の画面に表示するときの座標に変更する。
#3040 の作業の一部です。

[Feature] ゲームオーバー時の画面をウィンドウの中央に表示する

---

src/core/window-redrawer.cpp
src/locale/language-switcher.h
src/window/main-window-left-frame.cpp
src/window/main-window-row-column.h
src/window/main-window-stat-poster.cpp
src/world/world-turn-processor.cpp

Resolves #3021 
PR #2852 で追加されたモンスターのHP表示部に追加情報を表示する機能において、画面サイズを考慮していないため小さな画面では情報がすべて表示されない。
表示内容を一旦機能追加前を基準としたものに戻したうえで、プレイヤーの切り傷・朦朧・空腹の状態やダンジョン名・経過日数はウィンドウの縦幅にあわせて下に移動させるようにし、空いたスペースにモンスターの状態を表示するようにする。
なお、縦サイズが最小の24行の場合は空きスペースは無いためモンスターの状態表示はされない。

[Fix] 画面左下部の情報が正しく表示されない 

---

src/term/z-term.cpp

オプション「デバッグ用セーブデータを自動生成する（auto_debug_save）」が ON のとき、 オプション「プレイヤーにカーソルをあわせるオプション（hilite_player）」が正しく機能せずおかしな位置にカーソルが表示される。
コミット 9ee14e6 の変更で term_queue_char および term_queue_bigchar で term_gotoxy を呼ぶようにしたためカーソルの座標が変化するようになったが、auto_debug_save による描画処理でこれらの関数を呼んでいるためカーソルの位置が変化してしまうのが原因となっている。
term_queue_char および term_queue_bigchar ではカーソルの位置が変わらないよう、 変更前にそうであったように term_gotoxy を呼ばないようにする。
#3026 に関連するエンバグの修正です。

[Fix] hilite_player オプションが機能しない事がある

---

src/io/input-key-requester.cpp

通常店舗内ではセーブはできないが、auto_debug_save オプションが ON のとき店舗内に居るにも関わらずセーブが実行されている。
デバッグ用セーブファイルとはいえ、通常では想定されていないタイミングでのセーブ実行であるためおかしな動作の原因となる事も考えられるため、店舗内ではセーブが実行されないように修正する。
#3064 に関連して調査中に発見しました。

[Fix] 店舗内でデバッグセーブを実行している

---

src/player/player-status.cpp

Resolves #3068 
攻撃回数の計算処理を行う calc_num_blow 関数で、忍者の攻撃回数ペナルティの計算を行う
処理の位置が不適切なため発生する。
適切な位置に移動して修正する。

[Fix] 忍者にふさわしくない武器の攻撃回数ペナルティが機能していない

---

src/object/object-flags.cpp

Resolves #3069
object_flags_lite 関数内の光源の灼熱エゴに関する処理で、光源の灼熱エゴ (LITE_AURA_FIRE) ではなく、クロークの灼熱エゴ (AURA_FIRE) のフラグを誤ってチェックしており、クロークに対して is_lite_requiring_fuel() を呼び出してしまうことで
例外が発生しクラッシュする。
正しいフラグに修正し、また念のため光源以外のアイテムでは early return するようにしておく。

[Fix] クロークの灼熱エゴアイテムでクラッシュする

---

src/birth/character-builder.cpp
src/cmd-io/cmd-gameoption.cpp
src/cmd-visual/cmd-draw.cpp
src/core/asking-player.cpp
src/core/game-closer.cpp
src/load/load-util.cpp
src/main-cap.cpp
src/main-gcu.cpp
src/main-win.cpp
src/main-x11.cpp
src/main.cpp
src/main/angband-initializer.cpp
src/player-info/self-info.cpp
src/store/cmd-store.cpp
src/term/gameterm.h
src/view/display-messages.cpp
src/view/display-player.cpp
src/view/display-scores.cpp
src/view/display-self-info.cpp
src/window/main-window-left-frame.cpp

Resolves #3075 
ウィンドウのデフォルトサイズ関連の値が即値で記述されている箇所が多数あるので、下記定数
を定義してそれを使用するようにする。
- TERM_DEFAULT_COLS: ウィンドウのデフォルト横サイズ
- TERM_DEFAULT_ROWS: ウィンドウのデフォルト縦サイズ
- MAIN_TERM_MIN_COLS: メインウィンドウの最小横サイズ
- MAIN_TERM_MIN_ROWS: メインウィンドウの最小縦サイズ
とりあえず 80 と 24 で検索してウィンドウのサイズに関係していそうな所は定数で置き換えました。
また、 80 と 24 そのものではなくこれらの数値からの差分として表すべき即値があると思われますが、さすがにすべてチェックはしきれないのでとりあえず目についたものだけに対応しています。

[Refactor] ウィンドウのデフォルトサイズを定数にする

---

src/cmd-building/cmd-building.cpp
src/core/show-file.cpp
src/floor/object-scanner.cpp
src/io-dump/character-dump.cpp
src/store/cmd-store.cpp
src/term/z-term.cpp
src/term/z-term.h
src/view/display-inventory.cpp
src/window/main-window-equipments.cpp

#3040 の作業の一部です。
店舗・建物内の画面をウィンドウ中央に表示します。店舗・建物内で行えることは一通り試したつもりですが、漏れがないかご確認ください。
また、建物内のコマンドの「街の概要」の表示で使用されている show_file を中央化したため、店舗・建物内の画面表示以外で show_file を使用しているものも中央に表示されるようになっています。（ヘルプや知識の表示の一部など）

[Feature] 店舗・建物内の画面をウィンドウ中央に表示する

---

src/cmd-io/cmd-autopick.cpp
src/cmd-io/cmd-gameoption.cpp

オプション画面は 80x24 で表示することを想定しているので、ウィンドウ中央に表示する。
#3040 の作業の一部です。

[Feature] オプション画面をウィンドウ中央に表示する

---

src/window/main-window-left-frame.cpp

Resolves #3086 
print_health 関数においてモンスターの一時状態異常表示欄を消去する処理が抜けていたの
で、最初に消去するように修正する。

[Fix] モンスターの一時状態異常表示が画面に残る

---

src/knowledge/knowledge-inventory.cpp
src/util/string-processor.cpp
src/util/string-processor.h

Resolves #3083
2バイト文字を考慮しつつ部分文字列を切り出す関数 str_substr を実装する。
str_substr で trim_kanji 関数を置き換える。また、str_separate 関数の処理で str_substr を使用するように変更する。

[Feature] 2バイト文字を考慮しつつ部分文字列を切り出す関数

---

src/view/display-lore-status.cpp

Resolves #3102
AQUANTIC・CAN_SWIM・CAN_FLYの3つのフラグは元々思い出記録フラグが無く、無条件で表示されていたが、PASS_WALLやKILL_WALLと一緒にMonsterFeatureTypeに統合された時に思い出記録フラグがあるものとして扱われるようになった結果表示されることが無くなってしまっていた。
以前の仕様の通りにするため、これらのフラグは思い出を考慮せず直接モンスターのfeature_flagsを見るように修正する。

[Fix] モンスターの思い出で一部の情報が表示されない

---

src/market/arena-info-table.cpp

Resolves #3107
序盤の進行を助けるためにトラップ感知のロッドの確定入手手段を追加する
具体的にはテルモラのアリーナ対戦の『らいおんはーと』の報酬とする

[Feature] トラップ感知のロッドをアリーナの報酬に追加する

---

src/artifact/random-art-generator.cpp

Resolves #3109
01660ec の修正でアーティファクト生成の巻物で作ったランダムアーティファクトの名称をラ
ンダム決定した時に《》で囲む処理が誤って失われてしまっている。ランダムで決定した時も
《》で囲むようにする。

[Fix] 巻物で生成したアーティファクトにランダムで名付けるとおかしな名称になる

---

src/monster/monster-processor-util.cpp

Resolves #3113 
update_player_window関数でモンスターの思い出の状態が更新されたかを比較し、更新されていた場合はPW_MONSTERフラグを立ててサブウィンドウのモンスターの思い出の表示を更新するようになっている。しかし比較を行うための更新前のフラグold_r_kind_flagsの初期化が抜けてしまっているため、r_kind_flagsのいず れかのフラグがONの場合つねに更新されたと判定されてしまう。その結果ゲーム
ターン経過毎に毎回モンスターの思い出の再描画が実行され、非常に動作が重たくなってしまう。
正しくold_r_kind_flagsをr_kind_flagsで初期化するようにしておく。

[Fix] サブウィンドウにモンスターの思い出を表示すると重くなる

---

src/flavor/flavor-describer.cpp

Resolves #3118 
(+5) だけでは命中補正であることが分かりづらいので、(+5,+0) のように殺戮
修正の表記でわかりやすくする。

[Fix] 秩序の指輪の命中補正の表記方法

---

src/floor/floor-object.cpp
src/monster-floor/monster-death.cpp
src/monster-floor/special-death-switcher.cpp
src/object-enchant/item-magic-applier.cpp

#3111 で言及した仕組みにより、床に固定アーティファクトを置いて階層を移動
すると元の階層に戻ってきた時に固定アーティファクトが消えてしまう。
drop_near関数に固定アーティファクトへの階層IDの記録を集約することで、固
定アーティファクトを持ち運んだ後に床置きした場合でも、階層を移動して戻っ
てきた時に消滅してしまわないようにする。

[Fix] 床置きした固定アーティファクトが階移動で消滅する

---

hengband.spec

度々で恐縮ですが、hengband.specを修正しましたので、Pull requestします。
CoprでFedoraの36-38,rawhideでビルド、配布できることを確認しています。
3.0.0Alpha78に対応しています。

Fix hengband.spec to make rpm on the new Fedora

---

src/window/main-window-row-column.h
src/window/main-window-stat-poster.cpp

メインウィンドウを大きくしていると切り傷・朦朧・空腹状態などが左下で見に
くいという意見があったので、プレイヤーのHP/MP表示の下に移動する。
サンプル：

[Fix] メインウィンドウ左のプレイヤーの状態表示

---

src/birth/birth-select-class.cpp

変数 int_cs の定義位置がまずく、ループ毎に能力修正値情報が更新されなく
なっている。適切な位置に移動する。

[Fix] #3137 キャラメイク時職業の能力修正値情報が更新されない

---

src/player/patron.cpp

「ランダムにアビリティスコアを上昇/下降させるカオスパトロン」が選ばれていた場合、確率的に表題の事象が起きることが分かりました
論理学的にそれがありえなくなるよう修正しました
ご確認下さい

カオスパトロン報酬が時々異常になる不具合を修正した

---

src/birth/birth-select-class.cpp

Resolves #3186
カーソルやテンキーで選択中の職業を変更した際に、変数csを更新していないのが原因なので、更新するように修正する。
非常に見通しの悪いコードなので本来全体的にリファクタリングしたいところでもありますが、とりあえず最小限の変更で修正しておきます。

[Fix] 職業選択時にカーソルやテンキーで選択できない

---

src/io/record-play-movie.cpp

Resolves https://github.com/hengband/hengband/issues/3225 .

Include <sstream> since prepare_movie_hooks() uses std::stringstream

---

src/autopick/autopick-reader-writer.cpp

掲題の通りです
ご確認下さい
元のコード：
```cpp
bool write_text_lines(concptr filename, concptr *lines_list)
{
char buf[1024];
path_build(buf, sizeof(buf), ANGBAND_DIR_USER, filename);
FILE *fff;
fff = angband_fopen(buf, "w");
if (!fff) {
return false;
}
for (int lines = 0; lines_list[lines]; lines++) {
angband_fputs(fff, lines_list[lines], 1024);
}
angband_fclose(fff);
return true;
}
```
今のコード (同じはず)：
```cpp
bool write_text_lines(std::string_view filename, const std::vector<concptr> &lines)
{
char buf[1024];
path_build(buf, sizeof(buf), ANGBAND_DIR_USER, filename);
auto *fff = angband_fopen(buf, FileOpenMode::WRITE);
if (!fff) {
return false;
}
for (const auto *line : lines) {
if (line == nullptr) { // このifが抜けていたのでバグ発生
break;
}
angband_fputs(fff, line, 1024);
}
angband_fclose(fff);
return true;
}
```

自動拾い設定ファイルへの書き込み時に(null)が出力される事象を修正した

---

src/action/activation-execution.cpp
src/artifact/artifact-info.cpp
src/artifact/fixed-art-generator.cpp
src/flavor/flavor-util.cpp
src/flavor/named-item-describer.cpp
src/floor/floor-changer.cpp
src/floor/floor-leaver.cpp
src/floor/floor-object.cpp
src/floor/floor-streams.cpp
src/floor/floor-util.cpp
src/grid/object-placer.cpp
src/load/old/load-v1-5-0.cpp
src/object-enchant/item-magic-applier.cpp
src/object/object-flags.cpp
src/object/object-value-calc.cpp
src/object/object-value.cpp
src/perception/identification.cpp
src/racial/racial-android.cpp
src/spell-kind/spells-floor.cpp
src/system/item-entity.cpp
src/system/item-entity.h
src/wizard/artifact-analyzer.cpp
src/wizard/wizard-item-modifier.cpp

掲題の通りです
これでbi\_id 関係のリファクタリングは一段落です

ItemEntity にget_artifact() メソッドを追加し、ArtifactsInfo から取得していた処理を差し替えた

---

hengband.spec

hengband.specのバージョンを3.0.0Alpha81に変更しました。
以下URLでこのバージョンのrpm配布も開始しています。
https://copr.fedorainfracloud.org/coprs/whitehara/hengband/

Change hengband.spec version

---

src/main-win.cpp

8ビットカラー環境のWindowsはもう絶滅したと判断し、モニタの色数チェックを除去した

---

src/cmd-action/cmd-spell.cpp
src/locale/japanese.cpp
src/locale/japanese.h
src/lore/lore-util.h
src/view/display-lore-attacks.cpp
src/view/display-lore-status.cpp
src/view/display-lore.cpp

既存のシグネチャは入力文字列としてconst char*を受け取る、引数に出力用バッファを指定する、int型引数で処理内容をスイッチする、関数名から処理内容がわからない、とツッコミが追いつかない状況なのでよりよい形に変更する。

[Refactor] #3275 jverb関数のシグネチャ改善

---

src/cmd-io/cmd-process-screen.cpp
src/floor/floor-save.cpp
src/io/files-util.cpp
src/io/files-util.h
src/load/floor-loader.cpp
src/load/load.cpp
src/main-win.cpp
src/main-win/graphics-win.cpp
src/main-win/graphics-win.h
src/main-win/main-win-cfg-reader.cpp
src/main-win/main-win-cfg-reader.h
src/main-win/main-win-music.cpp
src/main-win/main-win-music.h
src/main-win/main-win-sound.cpp
src/main-win/main-win-sound.h
src/main-win/main-win-utils.cpp
src/main-win/main-win-utils.h
src/main/angband-initializer.cpp
src/player/process-name.cpp
src/save/floor-writer.cpp
src/save/save.cpp
src/util/angband-files.cpp

あちこちpath で扱うべきグローバル変数等がchar\* やconcptr になっているので順次差し替えました
セーブ/ロード周りにも手を入れたので入念にチェック済です
ご確認下さい

path_build() のシグネチャを変える準備 その3

---

src/autopick/autopick-editor-util.cpp
src/autopick/autopick-entry.cpp
src/autopick/autopick-key-flag-process.h
src/autopick/autopick-util.cpp
src/autopick/autopick-util.h

MATCH\_KEY() 及びMATCH\_KEY2() は複雑過ぎたので残しています
拾う・破壊する・銘をつける・放置する・前方一致、全て機能しています
ご確認下さい

autopick-key-flag-process.h に定義されていた関数マクロを削除し、普通の関数に置き換えた

---

src/monster/monster-update.cpp

一時オブジェクトから自身の参照を返すメソッドを呼び出した結果を参照変数で受けているため、その参照変数を使用する時にすでに実態がなくなっており、ダングリング参照になってしまっている。
&を削除してコピーを受け取るようにして修正する。

[Fix] モンスターが動くとクラッシュする

---

src/mspell/mspell-judgement.cpp

プレイヤーを巻き込むかどうかのチェックで使用する breath_direct() 関数と実際にブレスを使用する project() 関数それぞれからの breath_shape() の呼び出しの第3引数 dist の値が、前者は障害物の有無を考慮せず後者は考慮しているため異なることがある。それによりブレスの形が巻き込みチェックと実際で変わってしまうためプレイヤーを意図せず巻き込んでしまっている。
breath_direct() 関数でも障害物の有無を考慮した値（元はiという変数名だったのでpath_nに変更する）を breath_shape() に渡すようにする。
修正は breath_direct() 関数ですが、 project() 関数側からの breath_share() の呼び出しも合わせてご確認ください。

[Fix] ペットのブレスがプレイヤーを巻き込む

---

.github/scripts/check-format.sh

Ubuntu 22.04本家のAPTリポジトリにclang-format-15が追加されたので、LLVMの APTリポジトリを追加するコードをソースコード整形チェック用スクリプトから削除する。

[Fix] 不要になったLLVMのAPTリポジトリを削除

---

hengband.spec

hengband.specを更新
- バージョン3.0.0.Alpha83
- マクロbuilddir利用に変更
- booksのテキストファイルを追加
Coprにて公開しています
https://copr.fedorainfracloud.org/coprs/whitehara/hengband/

Update the version and macros in the spec file.

---

src/specific-object/bloody-moon.cpp

#3296 関連で。
switch (randint(x)) のパターンではないが、そっちにしたほうがマシというくらい元のコードはどのフラグがつくのか分かりづらい。
この機会に新設されたフラグを追加してもいいかもしれない？

[Refactor] ブラッディムーン発動時のフラグ選択に rand_choice を使用する

---

src/spell-kind/spells-perception.cpp
src/wizard/wizard-item-modifier.cpp

*鑑定*時にサブウィンドウの更新を行う時に持ち物の並べ替えとまとめ直しが
発生しないように一時的にフラグを落としてhandle_stuffを呼ぶというトンデモ
な処理が行われている。単にwindow_stuffを呼べばよいだけなのでそのように
変更する。
また、デバッグコマンドのインベントリ全鑑定についてはサブウィンドウの更新
は不要なので持ち物の並べ替えとまとめ直しのフラグを立てるのみでよいと判断
した。
#3314 の件で私がコメントした部分について修正しました。

[Refactor] *鑑定*時のサブウィンドウ更新処理

---

src/effect/effect-monster-charm.cpp

1箇所のみの修正です、ご確認下さい
正式に禁止されるのがC++23だったのでデバッグC++20環境では通り、リリースlatest環境ではエラーになった模様

string 型にnullptrを代入していた潜在的不具合を解消した

---

src/locale/japanese.cpp

掲題の関数呼び出しは1箇所のみでしたが、その1箇所がEUC絡みのコードだったので関連の設計も含めてごそっと変えています
見た目動きそうなレベルにはしましたが確認が困難であるため、レビューは @habu1010 氏にお願いしたいです
ご確認下さい

memcmp() を廃止した

---

src/birth/auto-roller.cpp

オートローラーの生い立ちで表示される単位を日本語ではinch,lbでなくcm,kgに。
#1987 体格オートローラー修正の問題です。
現verだと、
`C3680	ユーザー定義文字列リテラルを、一致しないリテラル サフィックス識別子と連結することはできません
Hengband	src\locale\japanese.cpp`
というエラーが出るので、一週間ほど前のモノでビルドして正常に動きました。
単位変換関数はsrc/view/display-player.cppと同じなので、dumpと同じ数値になると思います。
▼適用時
▼現行版

[Feature] オートローラーの単位をcm、kgに

---

src/util/enum-range.h
src/util/flag-group.h

Resolves #3362 
次のように、VSCode上で定数をマウスホバーすることで定数の値が表示される、すなわちコンパイル時定数になっていることがわかります。
constexpr な initializer_list でのコンストラクタ呼び出し
constexpr な EnumRange でのコンストラクタ呼び出し

FlagGroupクラスのコンストラクタをconstexpr化する

---

src/window/display-sub-windows.cpp

Resolves #3144 
魔力を吸収してItemEntityのnumberが0になった瞬間に発見済みのアイテムのウィンドウ更新処理が走り、その中でアイテムの値段計算時にnumberによるゼロ除算が発生してクラッシュする。
表示するアイテムリストを作成する時にnumberが0以下のものは除外するようにして対応する。
コールチェインや、更新したくないフラグのサブウィンドウまで更新されてしまうなど構造的な問題は多々あるが、すぐに抜本的に解決するのは難しい。さすがにクラッシュバグを放置しておくのはまずいので、ひとまず発見済みのアイテムリストからnumberが0のものを除外するようにしておく。

[Fix] 足元の魔道具の魔力を吸収するとクラッシュする

---

src/melee/melee-spell-flags-checker.cpp
src/melee/monster-attack-monster.cpp
src/monster-attack/monster-attack-player.cpp
src/monster-floor/monster-death.cpp
src/mspell/mspell-lite.cpp
src/room/space-finder.cpp
src/specific-object/torch.cpp
src/spell-kind/spells-lite.cpp
src/wizard/wizard-special-process.cpp

#3343 の続きです
単純置換につきチケットはありません
ご確認下さい

dungeons_info からdungeon_type を取得するメソッドへの置換に漏れがあったので対応した

---

src/io-dump/dump-util.cpp

掲題の通りです
byte にキャストしたことで、負方向にオーバーフローした時「255と0は255の方が大きい」のように判断されて異常な結果になったようです
モンスター・アイテム・地形 全て修正されたようです
ご確認下さい

シンボルエディタのシンボルが非表示になることがある不具合を修正した

---

src/monster/monster-status-setter.cpp

今まで「hek!」だったのを汎用的なセリフに置き換えました
玲音 (透明視あり・なし)に浴びせられた時の動作を確認済です
ご確認下さい
備考：
上記は何らかの理由で異常な処理が走り、結果時止めに至った旨のメッセージだったらしい

汎用的な時止めメッセージを実装した

---

src/cmd-action/cmd-spell.cpp
src/cmd-visual/cmd-draw.cpp
src/core/stuff-handler.cpp
src/core/window-redrawer.cpp
src/player/player-status.cpp
src/system/redrawing-flags-updater.h
src/window/display-sub-windows.cpp

ITEM_KNOWLEDGTE → ITEM_KNOWLEDGE
単純なスペルミス修正なのでIssueなしです。

[Fix] スペルミス修正

---

src/term/z-term.cpp

Fix #3036 
名前の長いアイテムを博物館に寄贈しようとすると、ゲーム画面の右端まで確認メッセージが到達するが、この時ゲーム画面の実際の横幅ではなく中央寄せした時の幅で境界をチェックしているので配列外アクセスが発生している。
正しくゲーム画面の幅を得るように修正する。
#3036 の直接の原因はこれです。
ところで、これはこれとしてget_checkで長い質問文になると、行におさまりきらず[y/n]の問い合わせをされていることがわからないという別の問題があります。
↓本当に無敵の（略）『強靭なるゾート』の人形を寄贈しますか？[y/n] が見切れている。サブウィンドウにメッセージを表示していないと[y/n]の入力待ちであることがわからない。

[Fix] 名前の長いアイテムを博物館に寄贈しようとするとクラッシュする

---

src/autopick/autopick-reader-writer.cpp
src/core/show-file.cpp
src/info-reader/fixed-map-parser.cpp
src/player-base/player-race.cpp
src/player-info/alignment.cpp
src/spell-kind/magic-item-recharger.cpp
src/spell-realm/spells-hex.cpp
src/status/bad-status-setter.cpp
src/store/rumor.cpp
src/system/angband-exceptions.h
src/system/angband-version.cpp
src/system/baseitem-info.cpp
src/timed-effect/player-acceleration.cpp
src/timed-effect/player-blindness.cpp
src/timed-effect/player-cut.cpp
src/timed-effect/player-deceleration.cpp
src/timed-effect/player-poison.cpp
src/timed-effect/player-stun.cpp
src/util/angband-files.cpp
src/util/probability-table.h
src/wizard/wizard-messages.cpp

#3386 の作業
引数に与えたメッセージに、アプリのバージョン・例外発生ソースファイルと行番号を付与して例外をスローするマクロ THROW_EXCEPTION を実装し、現状の throw で例外を投げている処理を置き換えました。（捕捉処理をしている SaveDataNotSupportedException は除く）

[Feature] 例外メッセージに追加情報を付与する

---

src/view/display-monster-status.cpp

Resolves #3401 
視認していないモンスターに対してlook_mon_desc()が呼ばれた場合、視認していないにもかかわらず損傷具合が分かってしまう。
現状、現在の知識コマンドからペット一覧を表示した時が該当する。
視認していない場合は「損傷具合不明」と表示するよう変更する。

[Fix] モンスターを視認していないのに損傷具合が分かってしまう

---

src/core/player-processor.cpp
src/core/window-redrawer.cpp
src/monster/monster-describer.cpp
src/monster/monster-description-types.h
src/system/monster-entity.cpp
src/system/monster-entity.h
src/system/redrawing-flags-updater.cpp
src/system/redrawing-flags-updater.h
src/target/target-preparation.cpp
src/target/target-preparation.h
src/term/gameterm.cpp
src/window/display-sub-windows.cpp
src/window/display-sub-windows.h
src/window/main-window-left-frame.cpp

Resolves #3400 
一覧のソートの順序は以下の通り。
1. 乗馬
2. 名前をつけたペット
3. ユニーク
4. （判明しているなら）モンスターレベル降順
5. モンスターID（モンスター配列上のインデックス）昇順
サンプル：

[Feature] ウインドウ・フラグ「ペット一覧」

---

src/knowledge/knowledge-features.cpp

掲題の通りです
#3375 と修正事由は同じです
ご確認下さい

地形の明度変更コマンド打鍵時にシンボル一覧が表示されない不具合を修正した

---

src/player/player-skill.cpp
src/realm/realm-names-table.h

Resolves #3407 
呪術と歌を詠唱した時、誤ってmp_ptr->infoの要素にアクセスしているため配列範囲外アクセスが発生する。
呪術と歌の時は正しいtechnic_infoの要素にアクセスするよう修正する。
バージョン2.2.1の段階では正しく同様の場合分けがなされていましたが、リファクタリングのどこかの段階で場合分けが消えてしまったようです。（スキル経験値周りは私がリファクタリングしたので、その前の段階で消えてなければ私が犯人かもしれない）

[Fix] 呪術と歌の詠唱時の配列範囲外アクセス

---

src/autopick/autopick-editor-command.cpp
src/autopick/autopick-editor-util.cpp
src/autopick/autopick-util.h
src/cmd-io/cmd-autopick.cpp

独自実装のリンクリストをstd::vector<std::string>に置き換えることで、mallocを使用しないようにする。
#3419 の一環。
これでX11のAPIの仕様のためmallocを使わざるを得ない箇所以外からmallocが撲滅されました。

[Refactor] 自動拾いのエディタのヤンクバッファ処理

---

hengband.spec

- hengband.specのバージョンを3.0.0Alpha85に更新
- coprにて同バージョンのrpmを配信開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/build/6070484/

Update the Version in hengband.spec

---

src/birth/auto-roller.cpp
src/birth/birth-wizard.cpp
src/locale/japanese.h
src/view/display-player.cpp

Resolves #3429 
日本語版では体格オートローラの身長・体重表示をcm/kgにする修正を加えたが、身長・体重の決定時に制限値と比較する際cm/kgに変換する処理が入っていないため正しく制限値との比較できていない。
制限値との比較時にもcm/kgへの変換を行うようにする。
これと関連して、整数値での inch → cm の変換を行う都合上存在しない身長というのがあるため、その範囲をオートローラで指定するとやはり止まらないという問題があります。
例えば 64インチ → 162cm、65インチ → 165cm となるため、オートローラで身長に163-164cmを指定すると、生成可能な範囲であるにもかかわらず止まらないという現象が発生します。
これを抜本的に解決するには、身長の内部値をインチからcmに変更するくらいしかなさそうで、セーブファイルのバージョンアップも必要となりやや面倒そうです。

[Fix] 体格オートローラで指定した値で止まらない

---

src/window/main-window-left-frame.cpp

Resolves #3433 
表示幅の計算を誤っておりASCII12桁まで表示するべきところを13桁まで表示し
ているのが原因。消す処理は12桁分しか行われていないため、結果として13桁目
の文字が残る。
ヌル文字（'\0'）は文字列長には含まれていないのでコメントにあるように-1し
ているのが誤りである。正しい計算に修正する。

[Fix] メイン画面左に表示されるモンスターの状態表示の一部が残る

---

src/main-win/main-win-utils.cpp
src/main-win/main-win-utils.h

Resolves #3442 
ブロック内で生成されたstringオブジェクトのdata()メソッドで得たポインタに対しブロック外でアクセスしておりダングリングポインタ参照が発生している。
そもそもstd::filesystem::pathを使用するようになったのでto_wcharやto_multibyteは使用せずwstring()・string()メソッドを使用すればよいのでそのように書き換える。
また、戻り値はすぐにstd::filesystem::path型の変数に入れているのでget_open_filenameの戻り値もstd::filesystem::path型に変更する。

[Fix] get_open_filename関数でのダングリングポインタ参照 

---

src/autopick/autopick-editor-command.cpp

Resolves #3441 
カーソルを右に移動させる処理で、2バイト文字かどうかの判定を現在の行の長さをチェックせずに行っているため配列範囲外アクセスが発生している。
カーソル位置が現在の行の長さに収まらない時は2バイト文字かどうかの判定は行わないようにする。

[Fix] 自動拾いエディタの配列範囲外アクセス

---

Hengband/Hengband/Hengband.vcxproj

fixes #2144
これにより、英語環境でビルドしてもC4566警告が出なくなります。
日本語環境でビルドしたものでしばらく遊んで、文字化けのようなものがないことは確認しました。

[Fix] Windowsでの実行時文字コードをShift_JISに固定する

---

configure.ac

すでに削除済みの機能なのでconfigureからも削除する。
configure.acの編集をしてて気づいたので。些細な修正なのでIssueなし。

[Fix] configureの--enable-chuukeiオプションを削除

---

src/cmd-visual/cmd-draw.cpp
src/io-dump/character-dump.cpp
src/save/save.cpp
src/view/display-messages.cpp
src/view/display-messages.h
src/window/display-sub-windows.cpp

message_strの戻り値をstd::stringからstd::shared_ptr<const std::string>に 変更する。
もともとmessage_strで得られるメッセージ履歴はshared_ptrで管理している
ため、こうすうることにより文字列を毎回コピーせずにすむようになる。
https://github.com/hengband/hengband/pull/3435#pullrequestreview-1496330468 にてコメントした関連作業ですので、単独Issueはなしです。

[Refactor] message_strの戻り値を変更

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
configure.ac
src/Makefile.am
src/io/report.cpp
src/net/curl-easy-session.cpp
src/net/curl-easy-session.h
src/net/curl-slist.cpp
src/net/curl-slist.h
src/net/http-client.cpp
src/net/http-client.h

cpp-httplibを使用しない方針となったため、今後のHTTP通信を利用した機能の追加に備えて、必要最低限の機能を備えた以下の通りのシンプルなHTTP通信機能クラスを実装しました。
http 名前空間
- Client: HTTP通信クライアントクラス
- Response: HTTP通信の応答を保持する構造体
libcurl 名前空間
- EasySession: libcurl easy session APIの薄いラッパークラス
- SList: libcurl string list の薄いラッパークラス
これらを使用して現在のスコアサーバへのスコア送信機能を置き換えました。
また、cpp-httplibによる実装をrevertしたことで消えていた、buf_sprintfを使用せずstringstreamで送信ダンプを作成するようにするリファクタリングを復活させました。
[テスト用スコアサーバ](https://mars.kmc.gr.jp/~dis/heng_score_test/score_ranking.php?&sort=newcome)に送信できることを確認しています。また、現在の PR のブランチのスコア送信先はテスト用スコアサーバになっています。

[Feature] HTTP通信機能クラス

---

src/autopick/autopick-describer.cpp
src/autopick/autopick-matcher.cpp
src/cmd-io/cmd-gameoption.cpp
src/cmd-io/cmd-lore.cpp
src/cmd-visual/cmd-draw.cpp
src/cmd-visual/cmd-visuals.cpp
src/core/asking-player.cpp
src/core/asking-player.h
src/core/show-file.cpp
src/floor/pattern-walk.cpp
src/io/record-play-movie.cpp
src/market/arena.cpp
src/market/building-monster.cpp
src/market/play-gamble.cpp
src/mind/mind-weaponsmith.cpp
src/spell-kind/spells-world.cpp
src/util/string-processor.cpp
src/util/string-processor.h
src/wizard/wizard-game-modifier.cpp
src/wizard/wizard-item-modifier.cpp
src/wizard/wizard-special-process.cpp
src/wizard/wizard-spells.cpp
src/wizard/wizard-spells.h

※ 厳密には静的警告はget\_string() やaskfor() 周りの文字列操作部分で起きているので、その準備
概ね以下の3点を実施しました (3つ目がそこそこ重い)
ご確認下さい
- angband\_strstr() のラッピング
- 構造体の未初期化警告対応
- get\_string() のシグネチャ変更に備えたinput\_value() への呼び出し変更

静的警告の解消 その7

---

src/cmd-visual/cmd-map.cpp
src/core/game-closer.cpp

Resolves #3410 
広域マップでの表示位置のずれに関しては、TermCenteredOffsetSetter は関係なく、表示座標が固定になっており元々ずれてたようです。

[Fix] メッセージ表示位置のずれ

---

src/object-use/quaff/quaff-effects.cpp

Discord で「そろそろGood first issue でも直していこう」という話が出てきたので修正しました
ご確認下さい

修行僧で酔っ払いの薬を飲むと時々記憶を失い、その他のクラスでは記憶を失わない不具合を解消した

---

Hengband/Hengband/Hengband.vcxproj

何となくほったらかしになっていましたが、変愚蛮怒のソースコードはC++20のみなのでlatest に依存する必要もなく、また随時新機能が追加される関係で不具合もいくらか出ています
これをC++20に固定しました
ご確認下さい

MSVCにおけるC++バージョンをC++20に統一した

---

.github/workflows/build-test-with-msvc.yml
.github/workflows/pull-request-status-check.yml
Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/curl/lib/libcurl_a_debug.lib
Makefile.am

#3470 のMSVCでのビルドテストの実装。
自動リリースはいろいろ調整が必要になると思われるので、とりあえず簡単に追加できそうなビルドテストを試す。
実際にビルドテストする設定でCIを走らせてみるため、一旦ドラフトで提出。
※わざとMSVCのみで警告がでるようにソースを一部編集してある。

[Chore] MSVCでのビルドテストを行うワークフロー

---

src/core/asking-player.cpp

Resolves #3459 
文字列入力中にHomeキーもしくはCtrl+aで先頭に、EndキーもしくはCtrl+eで末尾に移動できるようにする。

[Feature] 文字列入力で先頭と末尾に移動

---

src/wizard/wizard-spoiler.cpp

Resolves #3477
ブロック内のstd::stringオブジェクトのdata()メンバへのポインタにブロックを抜けてからアクセスしている。
book_name を std::string に変更して対処する。

[Fix] Player spells infoスポイラーの出力でクラッシュ

---

src/action/racial-execution.cpp
src/artifact/random-art-characteristics.cpp
src/market/bounty.cpp
src/realm/realm-hex.cpp
src/room/rooms-pit-nest.cpp
src/wizard/wizard-game-modifier.cpp
src/wizard/wizard-spoiler.cpp

英語版Windowsの環境でコンパイルしたところ、警告C4566が出力されたことで意図せず日本語のメッセージが英語版にそのまま適用されている箇所が発見された。英語のメッセージに修正する。
ほぼ表示だけの問題ですが、1箇所英語版だけ倍返しの難易度が上がっているという実害がありました。

[Fix] 英語版に日本語のメッセージが含まれる

---

src/artifact/random-art-generator.cpp
src/cmd-action/cmd-move.cpp
src/cmd-action/cmd-others.cpp
src/cmd-action/cmd-pet.cpp
src/cmd-io/cmd-diary.cpp
src/cmd-io/cmd-dump.cpp
src/cmd-io/cmd-lore.cpp
src/cmd-io/cmd-process-screen.cpp
src/cmd-item/cmd-item.cpp
src/cmd-visual/cmd-draw.cpp
src/core/asking-player.cpp
src/core/asking-player.h
src/core/show-file.cpp
src/io/files-util.cpp
src/io/files-util.h
src/io/record-play-movie.cpp
src/market/building-monster.cpp
src/market/play-gamble.cpp
src/market/play-gamble.h
src/player/player-damage.cpp
src/player/process-death.cpp
src/player/process-name.cpp
src/wizard/wizard-item-modifier.cpp
src/wizard/wizard-spells.cpp

主にget\_string() 周りのリファクタリングです
numerics と同様に、input\_string() へ改名しています
取り敢えず以下の項目は確認済です (CIに諸々チェックさせたいので先出し)：
- アーティファクト命名
- ペット命名
- 休憩

静的解析警告対応 その8

---

src/birth/birth-select-personality.cpp
src/birth/birth-wizard.cpp
src/player/process-name.cpp
src/view/display-player-misc-info.cpp
src/view/display-player-misc-info.h
src/view/display-player.cpp

Resolves #3488
画面上部に表示するプレイヤー名の表示位置が固定されているため、名前が長いと右側に偏って表示されてしまう。
名前（性格含む）の長さを考慮し、中央に寄せてバランスよく表示するように変更する。

[Feature] プレイヤー名を中央寄せして表示する

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/test/test-sha256.cpp
src/util/sha256.cpp
src/util/sha256.h

ファイルの同一性を確認するために、SHA-256ハッシュ値を計算するクラスを追加する。
#3474 の一環です。一気にやるとレビューが大変なので機能ごとにPRを出します。
Issue ではハッシュアルゴリズムとして MD5 と書いていましたが、実装難度はそんなに変わらないので SHA-256 にしました。
テストプログラムも追加していて、テストパターンを通過するのと、lib/xtra/music ディレクトリのmp3ファイルのハッシュが sha256sum コマンドと一致するのを確認しています。
https://github.com/hengband/hengband/assets/1501750/e850c2e0-4768-4d51-b074-77cae4c16dc4

[Feature] SHA-256ハッシュ値計算クラス

---

src/net/curl-easy-session.cpp
src/net/http-client.cpp
src/net/http-client.h

http::Client に引数で指定したファイルに直接ダウンロードするメソッドを追加する。
#3474 実装のための機能の1つです。
以下のコードにより、The_Serpent_of_Chaos.mp3 がファイルにダウンロードできるのを確認済み。
```c++
http::Client client;
if (auto res = client.get("https://github.com/hengband/hengband.xtra/blob/master/music/The_Serpent_of_Chaos.mp3?raw=true", "The_Serpent_of_Chaos.mp3");
res && res->status == 200) {
std::cout << "Downloaded: " << res->body << std::endl;
}
```

[Feature] HTTP通信でファイルに直接ダウンロードする

---

src/net/curl-easy-session.cpp
src/net/curl-easy-session.h
src/net/http-client.cpp
src/net/http-client.h

http::Client の get メソッドの引数にコールバック関数を指定することで、HTTP通信の進捗状況の表示や通信の中断を行えるようにする。
#3474 実装のための機能の1つです。
```c++
http::Client client;
auto handler = [](http::Progress progress) {
std::cout << "progress: " << progress.now << "/" << progress.total << std::endl;
return true;
};
const auto url = "https://github.com/hengband/hengband.xtra/blob/master/music/The_Serpent_of_Chaos.mp3?raw=true";
if (auto res = client.get(url, "The_Serpent_of_Chaos.mp3", handler);
res && res->status == 200) {
std::cout << "Downloaded: " << res->body << std::endl;
}
```
上記のコードで、以下の出力が得られるのを確認しています。
```c++
progress: 0/0
progress: 0/0
progress: 0/0
progress: 0/0
(略)
progress: 0/0
progress: 0/0
progress: 7687/1925021
progress: 7687/1925021
progress: 10443/1925021
progress: 10443/1925021
progress: 11821/1925021
progress: …
```

[Feature] HTTP通信の進捗のコールバック機能

---

src/store/cmd-store.cpp

Resolves #3500 
b790502db5a8a6b26a7439fee5f4d06ec117659f で店のアイテム表示内容の更新が必要かどうかのフラグを削除してStatusRedrawingFlag::BONUSを見るようにしたが、このフラグはhandle_stuffが呼ばれると落とされるため、元のコードのように別途フラグとして保持しておく必要があった。

[Fix] 装備変更時に店のアイテム表示内容が更新されない

---

src/save/save.cpp
src/util/angband-files.cpp

Resolves #3354 （おそらく）
ゲームを普通にプレイしていると頻繁にクラッシュするという報告があり、検証の結果（デバッグ）セーブ時に std::filesystem のファイル操作関数のエラーにより例外が発生している可能性が高いことがわかった。
多分に環境に依存するファイルシステムのエラーを完全に想定することは不可能なので、例外ではなくエラーコードを受け取るようにするオーバーロードを使用して例外を投げないようにする。
エラーコードによるエラーの処理は行っていないが、std::filesystem 以降前も rename や remove 関数の戻り値はチェックしておらずそれで不具合も起きていなかったので、ひとまず実用上の問題はないかと思われる。

[Fix] （デバッグ）セーブ時にクラッシュ

---

.github/workflows/build-test-with-msvc.yml

Resolves #3511
残りの転送量がすでに100MBちょいくらいしか残っていないので、早急にマージする必要があります。
また、キャッシュが有効になった状態でビルドテストを実行するため、**仕掛中のPRは必ずこのPRがマージ後のブランチにリベースするようにしてください**。

[Chore] MSVCのビルドテストでCached LFS checkoutを使用する

---

src/core/asking-player.cpp
src/core/asking-player.h

掲題の通りです
v2.2までの動作を踏襲するようにしました
NumLockのON/OFFとは無関係であることを確認済です

数値入力プロンプトにおいて、テンキー入力を数字の入力へ強制するよう修正した

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
THIRD-PARTY-NOTICES.txt
src/Makefile.am
src/external-lib/include-json.h
src/external-lib/json.hpp
src/locale/japanese.cpp
src/locale/japanese.h

Resolves #3507 
JSON for Modern C++ の導入に加え、JSONで文字列を扱う場合エンコーディングはUTF-8である必要があるため、システムの文字コードをUTF-8に変換する関数をjapanese.cppに追加しました。
json.hpp は JSON for Modern C++ ライブラリのヘッダファイルそのままなので、その他のファイルをチェックしていただければよいです。

[Feature] JSONライブラリの導入

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
configure.ac
src/Makefile.am
src/main-win.cpp
src/main-win/main-win-exception.cpp
src/main-win/main-win-exception.h
src/net/curl-easy-session.cpp
src/net/curl-easy-session.h
src/net/curl-slist.cpp
src/net/curl-slist.h
src/net/http-client.cpp
src/net/http-client.h
src/net/report-error.cpp
src/net/report-error.h
src/system/angband-exceptions.h

Resolves #3386 
上記 Issue について、Windows版で予期していない例外捕捉時に確認ダイアログを表示し、例外メッセージをWebhookでDiscordに送信する機能を実装しました。
送信時の仕組みとしては、https://hengband.github.io/api/report-error からWebhook URLを取得し、そこにバージョンと例外メッセージを送信するようになっています。現在は公式サーバの #変愚蛮怒開発 にWebhookが送信されるようになっています。
また、その後バグ報告のページを開くか問い合わせ、OKの場合はWebブラウザで [New Issue](https://github.com/hengband/hengband/issues/new/choose)のページを開きます。
また、意図的に例外を起こすウィザードコマンドを一時的に追加しています。
`^a @` で SPELL: に 'exception' と入力すると、例外を発生させることができます。このコミットは最終的には削除する予定です。
例外発生時の確認メッセージの内容や手順など、これで良いかどうか確認・ご意見をよろしくおねがいします。

[Feature] エラー情報送信機能

---

.github/workflows/build-with-autotools.yml
.github/workflows/create-cache-for-ccache.yml
.github/workflows/pull-request-status-check.yml

Resolves #3522 
詳しい変更内容はコミットログをご確認ください。

[Chore] ccacheが使用するキャッシュを分け、ビルドテストを並列に実行できるようにする

---

src/io-dump/character-dump.cpp

33209e24c4b2cefa5086f878bd63a1ca2be297d0 で名前の中央表示を実装したが、 中央表示時に表示画面の幅が計算されておりその分右にずれてしまう。
そもそもダンプの作成時は横幅80で計算していいはずなので、make_character_dump()冒頭のermCenteredOffsetSetterをそのように設定する。

[Fix] ダンプの名前の位置が右にずれる

---

src/cmd-io/cmd-dump.cpp
src/cmd-io/cmd-macro.cpp
src/cmd-visual/cmd-draw.cpp
src/cmd-visual/cmd-visuals.cpp
src/core/asking-player.cpp
src/core/asking-player.h
src/core/show-file.cpp
src/player/process-death.cpp

~~【注意！】このコードはマクロ作成時にクラッシュします~~
**修正しました**
見た目だけそれっぽくリファクタリングしました
が、外から降ってきたchar[] を弄くり回すことに特化したコードなので、関数内部でstring を宣言するとあまりうまく行きません
カーソルを左方向に動かす都合上、stringstreamやvector\<char\>もちょっと使いにくいです
何か良さげなアイディアがあるととても助かります
なお本件をもって静的解析警告を全部除去できます
(ここまで来といてaskforと直接関係ないんちゃうかとは思いつつ無視)

askfor() の引数からchar* を除去し、戻り値をoptional<string> に変えた

---

src/external-lib/json.hpp

実際にstd::forwardしたオブジェクトを再度使用しているというバグが原因となっている。現時点での最終リリースバージョン 3.11.2 の後に本家で修正されているので、同様の修正を行う。
https://github.com/hengband/hengband/issues/3518#issuecomment-1627603568 でコメントした件の対応です。これで静的解析警告が出なくなるはずですのでご確認ください。

[Fix] nlohmann-jsonライブラリの静的解析警告

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/packages.config
src/item-info/flavor-initializer.cpp
src/term/z-util.cpp

NuGet Package にて非推奨警告が出ていたFxCopAnalyzers を、推奨パッケージであるNetAnalyzers に差し替えました
それとは別にVS2022の静的解析警告は出たり出なかったりで不安定な問題があり、警告漏れを起こしていた箇所が今回(数週間ぶりに)引っかかったので修正しました
ご確認下さい

静的解析パッケージの更新

---

.github/workflows/create-release.yml

action-gh-releaseを利用して、masterブランチにマージしたときに自動リリースを行う。
#3470 の一環です。
現在はまだ master ブランチに push されたときではなく、このPRのブランチにpushされた時に実行するようにしています。
また、動作確認のため configure.ac の AC_INIT で指定するバージョンをテスト用に 3.0.0.87-Release-Test としています。これらは最終的に本来の形に戻す予定です。

[Chore] GitHub Actionsによる自動リリースのワークフロー

---

src/store/store-key-processor.cpp

Resolves #3542 
アイテムの個数の上限を得る関数 store_get_stock_max を常に引数 StoreSaleType::HOME で呼んでしまっており、我が家と同等の個数しか表示できなくなってしまっている。
引数に実際の店舗の値を渡すように修正する。

[Fix] 博物館で240個までしかアイテムが表示されない

---

src/store/store.cpp

掲題の通りです
手元では売り買い共に異常ないことを確認しました
ご確認下さい

店で存在しないアイテム番号を選択した後にEsc で抜けるとクラッシュする不具合を修正した

---

src/io-dump/random-art-info-dumper.cpp
src/object/object-info.cpp
src/object/object-info.h
src/wizard/artifact-analyzer.cpp
src/wizard/artifact-analyzer.h
src/wizard/fixed-artifacts-spoiler.cpp
src/wizard/fixed-artifacts-spoiler.h
src/wizard/spoiler-util.cpp
src/wizard/spoiler-util.h
src/wizard/wizard-spoiler.cpp

主に「引数にポインタを入れて関数内でアドレス代入」から「戻り値で返す」に変えたものです
固定/ランダムアーティファクト共に正常動作しています
ご確認下さい

アーティファクトスポイラー周りのシグネチャ整理

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/util/candidate-selector.cpp
src/util/candidate-selector.h
src/wizard/wizard-special-process.cpp

引数で与えられた候補を画面に表示して選択する関数テンプレート select_from_candidates を追加する。
使用例として、デバッグコマンドの固定アーティファクト生成の選択ルーチンをこの関数で置き換える。
#2779 の件について、ちょっと作ってみました。暫定として util/candidates-selector.h に置いていますが、もっとふさわしい場所があるかもしれず。(暫定なのでVSのファイルリストへの追加はしていない。ヘッダの追加だけならソリューションに追加しなくてもビルド自体はできるっぽい？)
ご意見募集。

[Feature] 候補を表示して選択するクラス

---

lib/edit/quests/034_DumpWitness.txt

Resolves #3551 
クエスト「もの言えぬ証人」は部屋の中が最初から明るく照らされた状態になっているが、クローカーのいるマスだけ照らされていない状態になっている。
モンスターを設置しているマスが暗いのはチュートリアルクエストとして範囲の狭い光源の危険性を認知してもらうための意図的なものだったが、これについては扉の奥のデスソードでも伝えられ、クローカーのマスに関してはやや不自然な挙動ではあるので最初からあかるく照らされた状態に修正する。

[Fix] クエスト「もの言えぬ証人」のクローカーのマスが暗い

---

.github/workflows/publish-spoiler-page.yml

ネット機能の実装により --disable-worldscore だけでは libcurl が依然とし て必要になったため、--disable-net を指定するようにして libcurl のインストールをしなくてもコンパイルできるように修正する。
この修正が適用された段階で自動生成スポイラーページ公開のGitHub Actionsを手動起動すると、3.0.0.87-Alpha公開後に追加されたサルーインが含まれてしまうので、とりあえず修正だけしておき公開は次回リリース時のCIにて行う。

[Fix] GitHub Actionsによる自動生成スポイラーページの公開に失敗する

---

src/wizard/monster-info-spoiler.cpp
src/wizard/monster-info-spoiler.h
src/wizard/wizard-spoiler.cpp

モンスタースポイラー関係のファイル読み込みをofstream へ差し替えました
これ以上減らすには、roff\_func() を関数ポインタへ代入してる箇所を全て書き換える必要があります
かなり非現実的な箇所にofstream への依存が発生するので、そもそも~~fu~~hack\_c\_roff グローバル変数を何とかしないといけません
v3.0β に間に合わないと思われるので中期的な対応になる想定ですが、どなたか調べて頂けると嬉しいです

spoiler_file グローバル変数の使用箇所削減 その2

---

src/racial/mutation-racial-selector.cpp

レベルx2が本来正しいようなので表記修正。マゴ爺(HP350)をブレス4発で焼殺したので、実ダメージ検証済。

[Fix] 突然変異の炎のブレス威力表記がレベルx1になっていたものを実際通り、レベルx2に修正。

---

src/monster-floor/special-death-switcher.cpp

fixes #3595 
ケット・シーが地上でトランプの召喚魔法によって敵対召喚されることを想定していないため地上で倒すと靴の生成に失敗し、その失敗したアイテムをドロップしてしまっていた。
これがハングアップの原因となっていたため、ドロップしないように修正した。
ついでにアミュレットをドロップする方のイェンダーの魔法使いも同様に修正した（恐らく地上で戦闘することはないだろうが念のため）

ケット・シー及びイェンダーの魔法使い(YENDER_WIZARD_2)を地上で倒すとハングアップするバグを修正

---

src/monster-race/race-ability-mask.cpp
src/monster-race/race-ability-mask.h
src/mspell/mspell-selector.cpp

spell-selector用のマスクを追加し、spell_between()を廃止した

---

src/main-win/graphics-win.cpp

詳細はチケットをご参照下さい
ついでにearly return にコードを変更しました
ご確認下さい
(ファイナライザでグローバル変数を弄るまではしなくてもよかろうと思ったのでそのまま)

タイルを選択するとエラーになる不具合を修正した

---

src/melee/melee-spell-flags-checker.cpp

#3607 よりペットがボール魔法でプレイヤーを巻き込む問題の解決
powerfulフラグを持つモンスターは一部のボール魔法の範囲が2ではなく4になる。
ペットがこれを考慮せず、プレイヤーを巻き込んでいたため、その場合該当ボール魔法を使わないよう修正。
年経た汚物エレメンタルがプレイヤーが範囲にいるとアシッドボールを使わなくなるのを確認。

[Fix] powerfulフラグを持つペットがボールの範囲拡大を計算に入れていなかったのを修正

---

src/io/files-util.cpp

Resolve #3603 
キャラクタダンプを出力するファイル名にファイルシステム上で無効な名称を
指定したとき angband_fopen が失敗するが、その時例外を送出しているので
クラッシュする。
例外送出ではなくエラーメッセージを表示するように変更する。
また、ついでに書き出したファイルストリームでエラーが発生しなかったか
どうかもチェックするようにする。

[Fix] 不正な名前のファイルにキャラクタダンプを出力するとクラッシュ

---

src/monster-floor/special-death-switcher.cpp

ケット・シー及びイェンダーの魔法使い(YENDER_WIZARD_2)を地上で倒すと(なし)をドロップしてしまうバグを修正

---

src/autopick/autopick-reader-writer.cpp
src/autopick/autopick-reader-writer.h
src/autopick/autopick-registry.cpp

Resolves #3645 
自動破壊登録時に自動拾いファイルをpicktype-プレイヤー名.prf、picktype.prfの順に探しているが、後者のみ存在する場合後者のパスを変数に再代入するのを忘れているため前者のファイルに対して自動破壊を登録してしまう。
その結果自動破壊のみが登録されたpicktype-プレイヤー名.prfが新しく作られてしまう。
他にも上述の順序で自動拾いファイルを決定している場所があるので、この際自動拾いファイルを決定する処理を pickpref_path() に関数化し、それを使用するようにすることで修正とする。

[Fix] アイテム破壊時に自動破壊登録すると自動拾いファイルがリセットされる

---

src/dungeon/quest.cpp
src/market/bounty.cpp
src/monster-floor/monster-remover.cpp
src/monster-floor/one-monster-placer.cpp
src/monster/monster-damage.cpp
src/monster/monster-damage.h
src/monster/monster-list.cpp
src/mspell/mspell-selector.cpp
src/mspell/mspell-special.cpp
src/system/monster-race-info.cpp
src/system/monster-race-info.h

掲題の通りです
Model 側にかなり処理を寄せたので扱いやすくなったと思います
分離/合体ユニーク定義は一旦private 化してgetter で取り出すようにしていますが、ここまでしなくていいかもしれません
(元々private で済むと思ったが周辺設計上取り出さないといけないことに気付いた)
動作周りは問題ないかと思いますが上記設計を特にご確認下さい
確認済動作：
- 合体ユニークの分離
- 片方のHPが半分未満になった時の、分離ユニークの合体 (両方半分以上ならば合体しない)
- 合体ユニークを撃破してからフロア移動すれば各分離ユニークも撃破済になる
- 分離ユニークの内1体でも倒すと、即座に合体ユニークが撃破済になる
- 分離ユニークの内1体でも倒してからフロア移動すると、他の分離ユニークが撃破済になる
既存不具合 (このPRより前からあったもの)：
#3631 
将来の予定：
- 呪文定義をSPECIAL からUNIFICATION へ汎用化

MonraceList クラスを定義し、monraces_info へのアクセスをカプセル化し、もって分離/合体ユニークの処理を一般化した

---

src/core/player-processor.cpp
src/main/scene-table-monster.cpp
src/monster-floor/monster-move.cpp
src/monster/monster-describer.cpp
src/monster/monster-update.cpp
src/player/eldritch-horror.cpp
src/system/monster-entity.cpp
src/system/monster-entity.h
src/target/target-describer.cpp
src/view/display-map.cpp
src/view/display-monster-status.cpp
src/window/display-sub-windows.cpp

Resolves #3669 
以下のコミットで見た目の種族 ap_r_idx を参照している箇所を
get_real_monrace() で置き換えるという根本的な誤りをおかしている。
- 5c9a3ad1787d7e13006ce68ab4173770158ff562
- 6c732ff1c979d770d43b8b9f0c708e508186f117
ap_r_idx を参照する、get_appearance_monrace() を実装し、それを呼ぶよう 修正する。

[Fix] カメレオンやたぬきが化けない

---

hengband.spec
src/main-x11.cpp

- X11で"-g"をつけて起動するとSIGSEGVで落ちる不具合を修正。原因はタイルのファイル名を空のまま、ReadBMP関数を呼び出し。
- 本修正版を3.0.0.91-2としてCoprで公開

Fix X11 graphics

---

src/monster/monster-update.cpp

掲題の通りです
元コード (v2.2.1)は以下の通りです
```c
else if (r_ptr->flags2 & (RF2_WEIRD_MIND))
{
/* One in ten individuals are detectable */
if ((m_idx % 10) == 5)
{
/* Detectable */
flag = TRUE;
if (is_original_ap(m_ptr) && !p_ptr->image)
{
/* Memorize flags */
r_ptr->r_flags2 |= (RF2_WEIRD_MIND);
/* Hack -- Memorize mental flags */
if (r_ptr->flags2 & (RF2_SMART)) r_ptr->r_flags2 |= (RF2_SMART);
if (r_ptr->flags2 & (RF2_STUPID)) r_ptr->r_flags2 |= (RF2_STUPID);
}
}
}
```

SMART/STUPID フラグの更新処理が無意味なものになっていたので修正した

---

src/birth/game-play-initializer.cpp
src/floor/fixed-map-generator.cpp
src/load/lore-loader.cpp
src/system/system-variables.h
src/wizard/wizard-game-modifier.cpp

不具合の詳細及び修正方針はチケットをご参照下さい
不具合の再現及び修正結果の確認には添付のセーブデータを使えばOKです
ご確認下さい
[DEBUGGER_Alpha87.zip](https://github.com/hengband/hengband/files/13062901/DEBUGGER_Alpha87.zip)
なお、UNIQUE2フラグの取り扱いがUNIQUEと同じで良いのか不明瞭なのと、似通ったforループが2連続するところが少し疑問です
もしより良い修正方法があれば連絡頂ければ手直しします

最新のモンスター種族追加が反映されていないセーブデータを読み込むとそれらの種族が出現しなくなる不具合を解消した

---

.github/workflows/pull-request-status-check.yml
src/player-base/player-class.cpp
src/util/sha256.cpp

clang++-14とlibstdc++の組み合わせでコンパイルエラーが発生しているので、
clangでのビルドには標準C++ライブラリにlibc++を指定するようにする。

chore: clangでのビルドテストにlibc++を使用する

---

src/info-reader/general-parser.cpp
src/info-reader/general-parser.h
src/info-reader/info-reader-util.h
src/main/info-initializer.cpp

resolve #3702 
変更範囲は非常に少ないためとりあえず返り値の型を変えて他もそれに合わせた

グローバル変数 error_lineをなくした

---

src/monster/monster-update.cpp
src/util/flag-group.h

一時オブジェクトの、自身の参照を返すメソッドの戻り値を参照で受けている
ため、ダングリング参照になってしまっている。
値で受け取ってオブジェクトをコピーするように修正する。

[Fix] update_lite_flags()の処理におけるダングリング参照

---

src/action/movement-execution.cpp
src/action/run-execution.cpp
src/action/tunnel-execution.cpp
src/cmd-action/cmd-move.cpp
src/cmd-action/cmd-open-close.cpp
src/cmd-action/cmd-others.cpp
src/cmd-action/cmd-pet.cpp
src/cmd-action/cmd-travel.cpp
src/cmd-action/cmd-tunnel.cpp
src/cmd-building/cmd-building.cpp
src/cmd-visual/cmd-visuals.cpp
src/effect/effect-feature.cpp
src/floor/cave-generator.cpp
src/floor/wild.cpp
src/grid/door.cpp
src/grid/grid.cpp
src/grid/grid.h
src/monster-floor/monster-sweep-grid.cpp
src/pet/pet-util.cpp
src/pet/pet-util.h
src/player/player-move.cpp
src/spell-kind/earthquake.cpp
src/spell-kind/spells-fetcher.cpp
src/store/cmd-store.cpp
src/view/display-map.cpp
src/window/display-sub-windows.cpp

terrains_info[] へアクセスしているグリッドへのポインタを参照に差し替えました (一部周辺設計の都合で例外あり)
ご確認下さい

グリッドから地形へのアクセスをカプセル化する準備 その2

---

lib/edit/ArtifactDefinitions.txt

Resolves #3613 
明らかにナルサンクからコピーしてFIREをACIDに変えただけでLITEを消し忘れたミスと思われるので永久光源特性を削除する修正する。

[Fix] モルサンクに永久光源特性がついている

---

src/specific-object/chest.cpp

チケットで報告頂いた通りです
ご確認下さい
is\_valid() はsval ではなくbi\_id に紐づいていますが、無効なItemEntity クラスのオブジェクトは処理の都合上bi\_id が0になるのでこの判定で問題ないはずです
本質的な設計改善は別途行います
仕様：箱は破損しているので中のアイテムは取り出せないものとする

トラップ付の箱を開けた時、箱が破損する処理と中のアイテムを取り出す処理が競合してクラッシュする不具合を解消した

---

src/system/baseitem-info.cpp
src/system/baseitem-info.h

掲題の通りです
修正範囲が狭いのでチケットはありません
「あるアイテムが特定のアイテムに一致するか比較する」という処理が複数箇所あり、「特定のアイテム」の方をコンパイル時定数として処理することで高速化を図ったものです
BaseitemKey は元々イミュータブル保証なので、この修正により更なる堅牢化も図れます
ご確認下さい

BaseitemKey のコンストラクタをコンパイル時定数に置き換えた

---

src/cmd-building/cmd-building.cpp

* 表示前にメインウィンドウの `term_type` 内 `offset_x` と `offset_y` が先に `TermCenteredOffsetSetter` でウィンドウサイズに応じて中央に回ってしまうのが原因だった。

[Fix] 施設入場不可メッセージがズレるエラーを修正。

---

hengband.spec

- hengband.specのバージョンを3.0.1.2に更新
- 同バージョンをcoprで配布開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/

Update the version to 3.0.1.2 in hengband.spec

---

src/action/activation-execution.cpp
src/system/item-entity.cpp
src/system/item-entity.h

掲題の通りです
ご確認下さい
activation-execution は、処理を追っていくと最終的に使われていない (ので変数名がdummy)ことが分かっています
それなら符号もどうでも良いのでshort としました

VS2022 で出ているコンパイル警告を解消した

---

.github/workflows/create-cache-for-ccache.yml

PR #3689 にて clang++-14 と libstdc++ の組み合わせでのコンパイルエラーに 対処したが、その時にccache用のキャッシュ生成のWorkflowに同じ修正を行うことを忘れていた。

[Chore] clangでのccache用のキャッシュ生成にlibc++を使用する

---

src/cmd-building/cmd-building.cpp

#3791 #3792 のバグ修正。
[リファクター](https://github.com/hengband/hengband/commit/fb2116246e5879595bfff5d3b494840c5660b21d)の際に真偽値反転が抜けていたので追加。
get_arena()は闘技場内に入ってから、闘技場のペットでないモンスターが(1体でいいので)死ぬまでtrueになる。
騎兵の場合さらに挙動がおかしくなるのは、闘技場出口から出られない条件を、get_arena() && 「モンスター数>0」で判定しているため。（「モンスター数>0」は敵モンスターが必ず生成される現仕様では(多分)意味のない判定式であるが、「モンスター数>0」が無ければほとんどの@さんは出られないところだった？）

[Fix]アリーナの出口が開く条件がおかしいのを修正

---

src/player/player-status.cpp

先ほどブランチ削除で閉じてしまった #3795 の出し直しです。
#3781 のバグ修正で、none_bits(player_ptr->pet_extra_flags, PF_TWO_HANDS)の判定位置を変更しました。
[このコミット](https://github.com/hengband/hengband/commit/dbec38d8106a6001c912cad2c3c1429e79309bc6)で追加された判定です。
▼変更適用後のスクリーンショット

[Fix]両手がふさがっていてもふらつかないバグを修正

---

src/effect/effect-monster-oldies.cpp

Close #3823 
このせいで非ユニークにはクローン・モンスターが効かず、逆にナズグルが増殖するようになってしまっていた

ナズグル及びUNIQUE2によるクローン・モンスターの魔法棒の耐性判定が真偽反転しているバグを修正

---

src/spell-kind/spells-world.cpp

Issue #3611 の件。
荒野でレベルテレポートを読んだとき、帰還先になっているダンジョンの最上階に移動するべきところ該当ダンジョンの地上入口に移動していた。 移動先の指定が誤っているためこれを修正する。

[Fix] 荒野でレベルテレポートしたときダンジョン内に入らない

---

src/main-win.cpp

#3744　リファクタリング時に相対パス保存の判定が機能しなくなっていた。
セーブファイルのフルパスとhengband.exe実行フォルダのパスが前方一致している場合、INIファイルに相対パスを保存する。

[Fix] セーブファイルが相対パスで保存できない #3744

---

src/effect/effect-monster.cpp

fix #3850
血の呪いの発生箇所の指定変数が正しくない。
該当箇所を修正する。

[Fix] 悪魔領域の血の呪いの追加効果発生場所が正しくない

---

src/spell-realm/spells-craft.cpp

Resolves #3865
リファクタリング時に誤ってDEFENSE_*だったものをATTACK_*にしてしまっていたのが原因。正しくDEFENSE_*に戻す。

[Fix] 属性への免疫を唱えた時のメッセージ

---

src/load/lore-loader.cpp

Fix #3873 
バグの関係上3.0.1.8-Betaでセーブした際の地形関連思い出フラグの消失は取り戻せないのであしからず

地形の思い出フラグを読み込む際モンスターの種族情報を書き換えてしまっているバグを修正

---

src/effect/effect-item.cpp

死体復活によるペット判定がおかしいバグを修正

---

src/cmd-visual/cmd-visuals.cpp
src/io/interpret-pref-file.cpp

#3675 の事象の原因と考えられるバグだが、確証がないためClose のリンクは現状はしないでおく

タイル情報の書き出しがおかしいバグを修正

---

src/monster-floor/monster-generator.cpp
src/monster-floor/monster-generator.h
src/monster-floor/monster-summon.cpp
src/monster-floor/monster-summon.h
src/monster-floor/one-monster-placer.cpp
src/monster-floor/one-monster-placer.h
src/monster/monster-list.cpp
src/monster/monster-list.h
src/monster/monster-util.cpp
src/monster/monster-util.h
src/mspell/summon-checker.cpp
src/mspell/summon-checker.h

summon_specific()で使用する以下のグローバル変数を除去し、引数で渡すように変更する。
- summon_specific_who
- summon_specific_type
- summon_unique_okay

[Refactor] summon_specificで使用するグローバル変数の除去

---

hengband.spec

- hengband.specを3.0.1.11にバージョンアップ
- 同バージョンをCoprにて配布開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/

Update hengband.spec for 3.0.1.11

---

src/dungeon/quest.cpp
src/knowledge/knowledge-monsters.cpp
src/knowledge/knowledge-quests.cpp
src/locale/english.cpp
src/locale/english.h
src/spell-kind/spells-sight.cpp
src/view/display-lore.cpp

plural_aux() は英語版のみで使用される、名詞の複数形変化を処理する関数。
引数で与えられた文字列バッファを直接変更するインターフェスから、引数で与えられた文字列を複数形にした新規の std::string オブジェクトを返すインターフェースへ変更する。
#3204 の一貫でもあります。

[Refactor] plural_aux() のシグニチャの改善

---

src/birth/birth-wizard.cpp

負の値があり得る変数を符号なし整数で宣言してしまっているため。
符号付き整数に修正する。
Fix #3972

[Fix] キャラメイク画面で負の経験値修正が正しく表示されない

---

src/core/asking-player.cpp

確認メッセージをサブウィンドウにも表示する目的でサブウィンドウの更新だけすべきところで不要にすべての更新を行う handle_stuff() を呼んでおり、メインウィンドウの再描画まで行われてしまうことによりカーソルの位置がおかしくなってしまっている。
window_stuff() を呼ぶように修正してサブウィンドウの更新のみが行われるようにする。
FIx #3793

[Fix] 確認メッセージのカーソルが変な場所に表示される

---

src/spell-kind/spells-world.cpp

初期値として現在のダンジョンの階層を表示しているため、不自然な値となってしまっている。
選択したダンジョンの最深到達階層を初期値として表示するように修正する。
Resolves #3797

[Fix] フロア・リセットで提示される階層の初期値がおかしい

---

src/dungeon/quest.cpp
src/dungeon/quest.h
src/floor/fixed-map-generator.cpp
src/knowledge/knowledge-quests.cpp
src/market/building-quest.cpp
src/target/target-describer.cpp
src/view/display-player.cpp

クエストの説明テキストを保持する変数を固定配列から std::vector<std::string> に変更する。
#3204 に関連して、strcpyの使用箇所の1つに関連するリファクタリングです。

[Refactor] クエストの説明テキストの処理

---

src/combat/shoot.cpp
src/effect/effect-monster.cpp
src/monster/monster-pain-describer.cpp
src/monster/monster-pain-describer.h
src/object-use/throw-execution.cpp

MonsterPainDescriber の MONSTER_IDX に依存したコンストラクタをなくした

---

src/locale/japanese.cpp
src/locale/japanese.h

guess_convert_to_system_encoding() に正当なUTF-8文字列を渡しているにもかかわらず変換に失敗することがある。これは関数内で使用されている angband_strcpy() がマルチバイト文字としてShift-JISかEUC-JPを想定しておりUTF-8は対象外であるため誤動作することが原因となっている。
新たにUTF-8文字列に対し正しく動作する utf8_to_sys() を実装し、guess_convert_to_system_encoding() 内でUTF-8からシステムの文字コードに変換する ときにこれを使用するようにする。
また、utf8_to_sys() 自体を単体で使えるようにするため、グローバルスコープに追加する。

[Fix] 正当なUTF-8で guess_convert_to_system_encoding() が失敗する

---

src/player-info/base-status-info.cpp
src/player-info/body-improvement-info.cpp
src/player-info/class-ability-info.cpp
src/player-info/mutation-info.cpp
src/player-info/race-ability-info.cpp
src/player-info/resistance-info.cpp
src/player-info/self-info-util.h
src/player-info/self-info.cpp
src/player-info/weapon-effect-info.cpp
src/view/display-self-info.cpp

自己分析の情報を `const char*` の配列ではなく、 `std::vector<std::string>` で 所持するようにする。
#3204 の一貫。

[Refactor] self_info_type

---

src/view/display-messages.cpp

Resolves #4033 
ウィンドウ上部に表示されるメッセージが、ウィンドウの幅を最小の80桁より増やしている場合でも必ず80桁に合わせて折り返し表示されており勿体ないので、ウィンドウ幅に合わせて折り返すようにする。

[Feature] ウィンドウの幅に合わせてメッセージを折り返す

---

src/info-reader/race-reader.cpp

#4018 に関する修正
例外処理の不足により英語版のロード時にクラッシュしていた。
"flavor"の要素数が不足している場合の処理を修正。
要素の省略を許可して正常に処理を続けるようにした。
軽微な修正のためissueなし。

[Fix] 英語flavor textのロードで例外が発生する

---

Makefile.am

Resolves https://github.com/hengband/hengband/issues/4047 .
This change uses an approach like that used for the Visual Studio files.  An alternative would be to create a Makefile.am file in the schema directory and recurse into that directory from the top-level Makefile.am.  That is the approach used for the lib and src directories.

Include the schema directory in the output of 'make dist'

---

src/cmd-visual/cmd-draw.cpp
src/io-dump/character-dump.cpp
src/view/display-messages.cpp
src/window/display-sub-windows.cpp

Resolves #4036 
まず長い名前のアイテムやモンスターのメッセージを表示させるなどして、長いメッセージ履歴をある程度の量保存したうえで、以下の点を見ていただきたいです。
- サブウィンドウの大きさを変えた時の挙動（動的にウィンドウサイズに合わせて表示内容が変わる）
- メッセージ履歴コマンド（^P）での各種操作（メイン画面なので、ウィンドウサイズ変更を反映させるには一旦メッセージ履歴画面を抜ける必要あり）
- 死亡時にダンプ出力した時にファイルに記録される「死ぬ直前のメッセージ」
なお注意点として、このPRで起動する以前に記録された長いメッセージはすでに分割されて別々のメッセージとして保存されているために対応出来ません。また、このPRでメッセージ履歴に記録された長いメッセージは現在のdevelopで起動すると起動時に80桁で分割されて別々のメッセージ履歴として扱われるようになります。

[Feature] メッセージ履歴の改良

---

src/autopick/autopick-editor-command.cpp
src/birth/birth-util.cpp
src/cmd-building/cmd-building.cpp
src/cmd-io/cmd-diary.cpp
src/cmd-io/cmd-gameoption.cpp
src/cmd-io/cmd-help.cpp
src/core/show-file.cpp
src/core/show-file.h
src/knowledge/knowledge-autopick.cpp
src/knowledge/knowledge-experiences.cpp
src/knowledge/knowledge-features.cpp
src/knowledge/knowledge-inventory.cpp
src/knowledge/knowledge-items.cpp
src/knowledge/knowledge-monsters.cpp
src/knowledge/knowledge-mutations.cpp
src/knowledge/knowledge-quests.cpp
src/knowledge/knowledge-self.cpp
src/knowledge/knowledge-uniques.cpp
src/market/arena.cpp
src/market/play-gamble.cpp
src/object-use/read/parchment-read-executor.cpp

プレイヤー名は当該メソッドの中で値の変更がなく、再帰呼び出しする度に同じ引数を入れる必要がないと判断しました
プレイヤー名が正しくファイルに出力されたことはチェック済です
ご確認下さい

FileDisplaery のコンストラクタにplayer_name を追加し、display() メソッドの引数を減らした

---

src/combat/shoot.cpp
src/effect/effect-monster.cpp
src/monster/monster-pain-describer.cpp
src/monster/monster-pain-describer.h
src/object-use/throw-execution.cpp

Resolve #3959 
PlayerType 依存を外部に移しただけだが、MonsterPainDescriber の隠蔽化がやりやすくなる

MonsterPainDescriber のPlayerType 依存をなくした

---

configure.ac

現在の configure.ac 設定では言語標準として -std=gnu++20 が指定されるが、現在GNU拡張の機能は使っておらず、MSVCでコンパイルできる保証もないため、GNU拡張はOFFとし、 -std=c++20 が指定されるようにする。

[Feature] ./configure で言語標準に付与されるGNU拡張をOFFにする

---

.github/workflows/build-with-autotools.yml
.github/workflows/create-cache-for-ccache.yml
.github/workflows/pull-request-status-check.yml

GitHub Actions の ubuntu-24.04 でGCC 13を使えるのでバージョンを更新したいが、Clangのバージョンはデフォルトで使用可能な最小バージョンが16であり、事情により14を使いたいので、GCCとClangでrunnerを切り替えられるようにしてGCCのみ
ubuntu-24.04 で GCC 13 でビルドするようにする。
そもそもrunnerの切り替えが上手く動くかわからないので、一旦PRを上げて動作を見てみる。

[Chore] CIのビルドテストのGCCのバージョンを13に更新

---

src/info-reader/artifact-reader.cpp

Fix #4106
フレーバーが省略されているときエラーを返す仕様から無視する仕様に変更する。

[Fix] ArtifactDefinitionsのフレーバーが省略されているときエラーになる

---

src/target/projection-path-calculator.cpp
src/util/point-2d.h

a6070543a410f90e で置換する変数を誤っているのが原因。
原因を修正するとともにもう少しコードをわかりやすくする。

[Fix/Refactor] アイテムを投げた時にクラッシュ

---

src/system/artifact-type-definition.cpp
src/wizard/wizard-special-process.cpp

目的のアイテムを探しやすくするため、デバッグコマンドでの固定アーティファクト生成時の選択肢一覧をソートして表示する。
#4084 に関連して実装してみました。なお、 #4101 でのミスが見つかったので、同時に修正コミットを入れてあります。

[Feature] デバッグコマンドの固定アーティファクト生成で一覧をソート 

---

src/player/player-status-flags.cpp

別件で不具合が出ているため動作確認はしていません、一旦ドラフトにしておきます

壁抜けモンスターに騎乗すると無条件で壁抜けできる不具合を解消した

---

src/grid/grid.cpp
src/io/cursor.cpp
src/view/display-map.cpp
src/view/display-map.h
src/window/display-sub-windows.cpp
src/window/main-window-util.cpp

無敵状態時などに行われるマップの単色化処理のコピペを関数にまとめる。
表示の文字と色をまとめるPRをレビュー中に、マップの表示色を一時的に変更する処理が複数箇所にコピペされているのが気になったので、共通関数化しました。

[Refactor] マップの単色化処理

---

lib/edit/BaseitemDefinitions.jsonc
schema/ArtifactDefinitions.schema.json
schema/BaseitemDefinitions.schema.json
src/action/activation-execution.cpp
src/artifact/random-art-effects.h
src/object-activation/activation-others.cpp
src/object-activation/activation-others.h
src/object-activation/activation-switcher.cpp
src/object-enchant/activation-info-table.cpp
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/item-entity.cpp

BaseitemDefinitionsをjson化した時に、元のtxt形式のデータでACTIVATEフラグだけ持って発動内容がセットされていない魔法の笛とモンスター・ボールが発動できなくなっていた。
この2つだけ例外的にItemKindTypeによる判定を行っているというのがそもそもあまりよろしくないので、発動種別としてWHISTLEとCAPTURE_MONSTERを追加し、この2つのアイテムにそれぞれセットする。

[Fix] 魔法の笛とモンスター・ボールが発動できない

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/info-reader/artifact-reader.cpp
src/info-reader/baseitem-reader.cpp
src/info-reader/info-reader-util.cpp
src/info-reader/info-reader-util.h
src/info-reader/json-reader-util.cpp
src/info-reader/json-reader-util.h
src/info-reader/race-reader.cpp

Resolves #4148 
nlohmann-json が不要にインクルードされるのを避けるため、jsonのパースを行う関数を独立したファイルへ分離する。
ビルド環境
CPU: Ryzen 7 7735HS
OS: Ubuntu 24.04 on WSL2
コンパイラ: GCC 13
変更前
> Executed in  156.65 secs    fish           external
>    usr time   35.79 mins  239.00 micros   35.79 mins
>    sys time    2.42 mins    0.00 micros    2.42 mins
> 
変更後
> Executed in   78.93 secs    fish           external
>    usr time   17.22 mins  111.00 micros   17.22 mins
>    sys time    1.50 mins  121.00 micros    1.50 mins
>

[Refactor] jsonのパース処理を行う関数を独立したファイルへ分離

---

src/knowledge/knowledge-monsters.cpp
src/system/monster-race-info.cpp
src/system/monster-race-info.h
src/util/sort.cpp
src/util/sort.h

倒したモンスターの一覧はdevelopと変わらないように見えます
ご確認下さい
(#4141 とバッティングする可能性がある場合はしばらく保留とします)

MonraceList::sort_level() を実装し、ang_sort_comp_monster_level() とang_sort_swap_hook() を廃止した

---

src/dungeon/quest.cpp
src/dungeon/quest.h
src/io-dump/character-dump.cpp
src/knowledge/knowledge-quests.cpp
src/system/floor-type-definition.cpp
src/system/monster-race-info.cpp
src/util/sort.cpp
src/util/sort.h

新しいソート用メソッド`QuestList::get_sorted_quest_ids()` は現時点で動作しません
ステップ実行しましたが原因がまだ不明なので見て頂けると助かります
動作OKまでドラフトにしておきます
ご確認下さい

ang_sort_comp_quest_num() / ang_sort_swap_quest_num() を廃止した

---

src/io/files-util.cpp
src/io/files-util.h
src/main-win.cpp
src/main/angband-initializer.cpp

デバッグセーブ機能がなくなったので、残っていた変数や処理も消しました
古いデバッグデーブは残りますが、悪さはしないのとリリースノートにこの旨記載することで各自の環境でデバッグセーブを削除して頂く運用としたいと思います
ご確認下さい

デバッグセーブに関するグローバル変数と、古いデバッグセーブを削除するルーチンを除去した

---

src/target/grid-selector.cpp
src/target/target-preparation.cpp
src/util/sort.cpp
src/util/sort.h

このソートメソッドをFloorType に置くのは重すぎるので、最終的にターゲット選択専用のクラスを作ってutil/ からtarget/ に隔離します
look でdevelopと同じようにターゲットが動くのをチェック済です
ご確認下さい
(Doxygenは横着してほったらかしてますが次回の移設PRで整備します)

ang_sort_comp_distance() / ang_sort_comp_importance() / ang_sort_swap_position() を廃止する準備

---

src/target/grid-selector.cpp
src/target/target-preparation.cpp
src/target/target-sorter.cpp
src/target/target-sorter.h

Discord での議論を元に、PR #4159 の後続PRとしてソートにSTLを使用するようにするコミットを1つ追加しました。
先行のPRのマージ後とするため、一旦ドラフトにしておきます。

[Refactor] ターゲットのソートにSTLを使用する

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/io-dump/dump-util.cpp
src/io-dump/dump-util.h
src/knowledge/item-group-table.cpp
src/knowledge/item-group-table.h
src/knowledge/knowledge-features.cpp
src/knowledge/knowledge-items.cpp
src/knowledge/knowledge-monsters.cpp
src/knowledge/monster-group-table.cpp
src/knowledge/monster-group-table.h
src/knowledge/object-group-table.cpp
src/knowledge/object-group-table.h

動作確認しましたが特に問題なさそうです
display\_group\_list() の引数でgrp\_idx がありますが、vector 化したことで不要になったもののようにも見えます
欠番に対応している？ と思われますが、ひとまず残してあります
また呼び出している箇所の行/列が毎回同じなので引数からは除去しました (UI設計的に固定値で良さそう)
以上、ご確認下さい

display_group_list() の引数をconcptr[] からvector<string> に変えた

---

src/target/target-sorter.cpp

TargetSorter::compare_importance がSTLのソートで使用する比較関数に要求 される `a < a == false` を満たしていないため、場合によってはデバッグ用ビルドのアサーションにひっかかることがある。
最初に2つの引数が同じかどうかをチェックし同じなら false を返すようにして、要件を満たすようにする。
TargetSorter::compare_distance に関しては要件を満たしていたが、同じ位置であれば距離を計算する必要もないのでこちらも先に引数が同じかをチェックする。
PR #4162 でのエンバグに対する修正のため、単独のIssueは無しです。

[Fix] ターゲット比較関数がSTLのソート用比較関数の要件を満たしていない

---

src/monster-attack/monster-attack-player.cpp
src/monster-attack/monster-attack-player.h
src/spell-realm/spells-hex.cpp
src/spell-realm/spells-hex.h

Resolves #4181 
SpellHexクラスのMonsterAttackPlayer*を第2引数に受け取るコンストラクタでメンバ変数spell_hex_dataを正しく初期化していないため、このコンストラクタで生成したオブジェクト経由では正しくダメージが蓄積されない。
これが原因で、モンスターの直接攻撃によるダメージが我慢の反撃ダメージに蓄積されていなかった。
また、魔法やブレスによる攻撃はこのコンストラクタを使用していないため正しく蓄積が機能していた。
そもそもMonsterAttackPlayer*をメンバに持つほどの必要性が感じられないので、このコンストラクタを削除し、現在MonsterAttackPlayer*を使用しているメソッドには直接必要な引数を渡すようにする。

[Fix] 呪術魔法の我慢が正常に機能していない

---

src/load/load.cpp

Resolves #4189 
おかしなデータでゲームが再開できてしまうのを防ぐため、セーブデータのバージョンが現在のプログラムで想定されるものより新しい場合は読み込みを中断しゲームを終了する。

[Feature] 新しいバージョンのセーブデータを読み込まないようにする

---

src/cmd-action/cmd-move.cpp
src/cmd-building/cmd-building.cpp
src/core/game-play.cpp
src/dungeon/quest.cpp
src/floor/floor-changer.cpp
src/floor/floor-leaver.cpp
src/floor/floor-mode-changer.cpp
src/floor/floor-mode-changer.h
src/floor/floor-save.cpp
src/floor/floor-save.h
src/floor/pattern-walk.cpp
src/grid/trap.cpp
src/load/dungeon-loader.cpp
src/market/arena.cpp
src/monster-floor/monster-safety-hiding.cpp
src/monster/monster-processor-util.cpp
src/monster/monster-processor-util.h
src/spell-kind/spells-world.cpp
src/system/player-type-definition.h
src/wizard/wizard-special-process.cpp
src/world/world-movement-processor.cpp
src/world/world-turn-processor.cpp

掲題の通りです
イーク洞に入り、階段・坑道・フロア保存 (1F⇔2F、1F⇔3F)・ダンジョン出入り周りの動作をチェック済です
ご確認下さい

FloorChangeModesStore クラスを作ってPlayerType::change_floor_mode を廃止した

---

src/load/info-loader.cpp
src/save/save.cpp
src/system/angband-version.h
src/view/display-messages.cpp
src/view/display-messages.h

Resolves #4180 
繰り返し回数をメッセージ文字列の一部として保持するのではなく、メッセージ文字列本体と繰り返し回数を別々に保持するように変更する。
⚠️ セーブファイルバージョンが更新されるため、一度セーブするとPR以前のプログラムではセーブファイルが読み込めなくなります。

[Refactor] メッセージ履歴の繰り返しの保持方法の変更

---

configure.ac
doxygen/Hengband.doxyfile
src/monster/monster-damage.cpp
src/monster/monster-damage.h
src/system/angband-version.h

#4169 のコピーは必要なものだと判明しました
元に戻しましたのでご確認下さい
(手元では上手く再現しませんでした、再現する環境で試してみて下さい)

モンスター撃破時に経験値が入らない不具合を修正した to develop

---

src/artifact/random-art-activation.cpp

エラーレポート及びその後の議論により、例外を吐くことが間違っていることが分かりました
1行だけですのでご確認下さい

バイアスはないが発動はあるランダムアーティファクトを生成しようとすると例外を吐く設計を吐かないように修正した to develop

---

src/birth/birth-wizard.cpp

チケットはありません
恐らくstrnfmt() 周りの修正で漏れたものと思われます
ご確認下さい

プレイヤー作成ウィザードで未初期化文字を表示してしまう不具合を修正した

---

src/autopick/autopick-destroyer.cpp
src/autopick/autopick-entry.cpp
src/autopick/autopick-matcher.cpp
src/cmd-item/cmd-eat.cpp
src/effect/effect-item.cpp
src/flavor/named-item-describer.cpp
src/flavor/tval-description-switcher.cpp
src/hpmp/hp-mp-regenerator.cpp
src/load/old/load-v1-5-0.cpp
src/market/bounty.cpp
src/monster/monster-info.cpp
src/monster/monster-info.h
src/mspell/mspell-checker.cpp
src/object-hook/hook-expendable.cpp
src/object-hook/hook-quest.cpp
src/object/object-value.cpp
src/perception/identification.cpp
src/specific-object/monster-ball.cpp
src/spell/spells-object.cpp
src/spell/spells-summon.cpp
src/store/service-checker.cpp
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/item-entity.cpp
src/system/item-entity.h
src/system/monster-race-info.cpp
src/system/monster-race-info.h
src/util/object-sort.cpp

~~PlayerType::monster\_race\_idx が曲者ですが暫定措置で別途対応します~~
~~また、~~ 以前からMonsterRaceId 5000番とかいう変なオブジェクトが生成されていましたが (悪さはしなかった)、原因が判明したので修正しています
原因：ItemEntityのpvalだけ見ていて、それがモンスターかろくすっぽ判定していない箇所があった
一応起動及び軽く骨/死体の生成を試しましたが特に問題なさそうです
ご確認下さい

monraces_info からMonsterRaceInfo を取得している箇所をMonraceList に差し替えた その1

---

src/object-hook/hook-expendable.cpp

That is a regression introduced by 837179e4d1a735595e246830084e1bca9db2527b.  Resolves https://github.com/hengband/hengband/issues/4237 .

Prevent unhandled exception when corpse-eating player tries to eat

---

Hengband/Hengband/Hengband.vcxproj
Hengband/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/cmd-action/cmd-pet.cpp
src/core/player-processor.cpp
src/core/stuff-handler.cpp
src/effect/effect-monster-oldies.cpp
src/effect/effect-monster-spirit.cpp
src/effect/effect-monster.cpp
src/effect/effect-player-spirit.cpp
src/hpmp/hp-mp-regenerator.cpp
src/melee/melee-postprocess.cpp
src/melee/monster-attack-monster.cpp
src/monster-attack/monster-eating.cpp
src/monster-floor/monster-remover.cpp
src/monster/monster-compaction.cpp
src/monster/monster-damage.cpp
src/monster/monster-status-setter.cpp
src/monster/monster-update.cpp
src/mspell/mspell-status.cpp
src/spell-kind/spells-polymorph.cpp
src/system/player-type-definition.h
src/tracking/health-bar-tracker.cpp
src/tracking/health-bar-tracker.h
src/window/main-window-left-frame.cpp

適当なモンスターを召喚してlookしたり攻撃したりしてバーが引き続き表示されることはチェックしました
ご確認下さい

モンスターのHPバー管理をHealthBarTracker に移した

---

src/market/building-monster.cpp
src/system/item-entity.cpp

GCC 13においてプリコンパイルヘッダの指定無しの時にSTLヘッダのinclude不足によりコンパイルエラーとなるファイルがあるので、必要なヘッダのinclude文を追加する。
includeの追加だけであり、ごく軽微な修正なのでIssue無し。

[Fix] 不足しているSTLヘッダのinclude文を追加

---

src/autopick/autopick-destroyer.cpp
src/autopick/autopick-entry.cpp
src/autopick/autopick-matcher.cpp
src/cmd-item/cmd-eat.cpp
src/knowledge/knowledge-monsters.cpp
src/melee/melee-spell-flags-checker.cpp
src/mind/monk-attack.cpp
src/monster-floor/monster-death.cpp
src/monster-floor/monster-generator.cpp
src/monster-race/monster-race-hook.cpp
src/mspell/mspell-special.cpp
src/mspell/summon-checker.cpp
src/object-hook/hook-expendable.cpp
src/player-attack/player-attack.cpp
src/store/service-checker.cpp
src/system/item-entity.cpp
src/system/monster-entity.cpp
src/system/monster-race-info.cpp
src/system/monster-race-info.h

Resolves #4244 
MonsterRaceInfo::symbol_char_is_any_of() を実装し、モンスター種族のシンボル文字による判定を行っている箇所をこのメソッドで置き換える。

[Refactor] モンスター種族のシンボル文字による判定

---

src/flavor/tval-description-switcher.cpp
src/wizard/items-spoiler.cpp

私の環境では正常に出力されました
価格がおかしなことになっている (汚いイタズラ小僧のものが転記されている？)可能性はありますが、像や骨の価格は種族依存なので元々ダミー値ですし気にするほどではないと思われます
ご確認下さい

アイテムのスポイラー出力時にクラッシュする不具合を修正した

---

src/combat/shoot.cpp

Resolves https://github.com/hengband/hengband/issues/4300 .

Avoid drawing artifact with Rushing Arrow when base delay is zero

---

src/knowledge/knowledge-features.cpp

FIx #4299 
コピーしたオブジェクトを書き換えているため、元の地形データを書き換えておらず、シンボルの変更ができていない。
参照にすることで元の地形データを書き換えるように修正する。

[Fix] 地形シンボルエディタでカーソルキーが反応しない

---

.github/workflows/create-cache-for-ccache.yml
.github/workflows/pull-request-status-check.yml

ヘッダのインクルード不足によるコンパイルエラーを検出するため、GCCによるビルドテストでプリコンパイルヘッダを使用しないようにする。

[Chore] プリコンパイルヘッダを使用しないようにする

---

src/wizard/wizard-player-modifier.cpp

デバッグコマンドのライフレート変更 `^A P l` が実際には l ではなく n に割り当てられている。
表示どおり l に修正する。
軽微な修正なのでIssueなし。

[Fix] デバッグコマンドのライフレート変更のキー割り当て

---

src/lore/monster-lore.cpp

[Fix] 思い出の文章で天使種族の表示が反映されていないバグを修正

---

src/mspell/mspell-special.cpp
src/mspell/mspell-summon.cpp
src/mspell/specified-summon.cpp
src/spell-kind/blood-curse.cpp
src/spell-kind/spells-random.cpp
src/spell/spells-summon.cpp

関数がtrueを返した回数を、戻り値をそのまま足し算することによりカウントしているが、true == 1, false == 0 となる事を前提とするのはCの言語仕様への依存が強いので、三項演算子を用いてtrueなら1、falseなら0を明示的に足すようにする。
hack_m_idx_ii を削除するためにモンスター生成系関数の戻り値を `std::optional<MONSTER_IDX>` にしようとしていて邪魔になったので、先に修正しておく。
単体Issueはありません。

[Refactor] bool型を直接足し算でカウントするのをやめる

---

src/mind/mind-explanations-table.cpp
src/mind/mind-explanations-table.h
src/mind/mind-power-getter.cpp
src/window/display-sub-windows.cpp

数合わせのための空欄が気になったので二重vectorでmind_powersとmind_tipsを持つようにしました。
（mind_powers は 構造体のメンバを std::vector にしたことによる実質二重vector）
単体Issueはなし。

[Refactor] mind_powers、mind_tips をstd::vectorにする

---

src/core/game-play.cpp
src/core/player-processor.cpp
src/floor/fixed-map-generator.cpp
src/floor/floor-generator.cpp
src/grid/trap.cpp
src/monster-floor/monster-generator.cpp
src/monster-floor/monster-generator.h
src/monster-floor/monster-summon.cpp
src/monster-floor/monster-summon.h
src/monster-floor/one-monster-placer.cpp
src/monster-floor/one-monster-placer.h
src/monster/monster-processor.cpp
src/monster/monster-util.cpp
src/monster/monster-util.h
src/mspell/mspell-special.cpp
src/specific-object/monster-ball.cpp
src/spell-kind/spells-polymorph.cpp
src/spell/spells-summon.cpp

Resolves #4349 
グローバル変数 hack_m_idx_ii はモンスターの生成を行う関数によって生成されたモンスターに、関数呼び出し直後にアクセスする用途で使用されている。
しかし、モンスター生成関数は集団生成などが発生すると内部でネストして呼び出されることがあり、その中でさらに hack_m_idx_ii が上書きされてしまう可能性があるため、hack_m_idx_ii が本当に想定している対象のモンスターを指しているのか疑問が残る。
hack_m_idx_ii の使用箇所に関連するモンスター生成関数の戻り値を単純な生成に成功したかを示すboolの代わりに成功した場合に生成したモンスターのIDを `std::optional<MONSTER_IDX>` で返すようにし、それを使用してモンスターにアクセスするように変更し、hack_m_idx_ii は削除する。

[Refactor] グローバル変数 hack_m_idx_ii を削除する

---

src/cmd-action/cmd-hissatsu.cpp
src/cmd-action/cmd-spell.cpp
src/knowledge/knowledge-experiences.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/player/player-skill.cpp
src/player/player-status.cpp
src/realm/realm-hissatsu.cpp
src/realm/realm-types.h
src/spell-realm/spells-hex.cpp
src/spell-realm/spells-song.cpp
src/spell/spell-info.cpp
src/spell/spell-info.h
src/util/enum-range.h
src/window/display-sub-windows.cpp

#4357 の一環
変更行数が多く見えますが、最後のコミットは関数の戻り値をポインタから参照に変更したことにより、現在の魔法情報へのポインタ変数 s_ptr を参照変数 spell に変えたのと、それに合わせて spell を魔法IDとして使用しており名前が被ってしまう箇所を spell_id という名前にする単純変換にすぎないので、実質的な変更行数は最後のコミットを除いたものになります。

PlayerRealmクラスを作り、魔法情報へのアクセスをカプセル化する

---

src/effect/effect-monster.cpp
src/effect/effect-monster.h
src/effect/effect-player.cpp
src/effect/effect-player.h
src/effect/effect-processor.cpp
src/effect/spells-effect-util.cpp
src/effect/spells-effect-util.h
src/spell-class/spells-mirror-master.cpp

PR #4350 に関連する Discord 上での議論で、rakubadam_m も合わせて根本的な対応をしたほうがよいと考えましたので、 #4350 の代替案として実装しました。

落馬ダメージ処理クラスを作成し、グローバル変数 rakubadam_p, rakubadam_m を削除する

---

src/autopick/autopick-entry.cpp
src/autopick/autopick-matcher.cpp
src/cmd-action/cmd-spell.cpp
src/knowledge/knowledge-experiences.cpp
src/object-hook/hook-magic.cpp
src/object/object-info.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/player/player-status.cpp
src/util/object-sort.cpp

PlayerRealmクラスにメンバ関数に第1領域と第2領域用それぞれに get_realm*_spell_info, get_realm*_book があるが、今後メンバ関数を追加 するごとに第1領域用と第2領域用が増えるのは好ましくない。
これを避けるため、PlayerRealmに領域ごとの処理をする内部クラスRealmを実装し、上述のメンバ関数を内部クラスに移動する。
PlayerRealm::realm* により第1領域か第2領域のPlayerRealm::Realmクラスのオブジェクトを返すようにし、それを経由してアクセスするように変更する。

[Feature] PlayerRealm::Realm クラス

---

src/birth/birth-select-realm.cpp
src/object-hook/hook-magic.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/realm/realm-names-table.h
src/realm/realm-types.h
src/spell/spell-info.cpp
src/spell/technic-info-table.h
src/wizard/wizard-special-process.cpp

#4357 の一環
魔法領域の選択候補の取得をグローバル配列変数 realm*_choices に直接アクセスして取得する方法から、PlayerRealmクラスの静的メンバ関数get_realm*_choices() で取得する方法に変更する。

[Refactor] 魔法領域の選択候補の取得方法

---

src/birth/birth-select-realm.cpp
src/cmd-item/cmd-destroy.cpp
src/object-hook/hook-magic.cpp
src/player-info/class-ability-info.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/racial/class-racial-switcher.cpp
src/racial/racial-switcher.cpp
src/realm/realm-names-table.h

#4357 の一環
善良な魔法領域かどうかの判定を行うマクロ is_good_realm を廃止し、PlayerRealmクラスのメンバ関数 is_good_attribute を代わりに使用する。

[Refactor] 善良な魔法領域かどうかの判定

---

src/player/player-realm.cpp
src/player/player-realm.h
src/wizard/wizard-spoiler.cpp

Resolves #4366
また、ついでに使用可能な領域の情報のみを出力するようにしました。

[Fix] スポイラーの魔法領域出力の内容がおかしい

---

src/avatar/avatar.cpp
src/birth/character-builder.cpp
src/cmd-action/cmd-spell.cpp
src/io/read-pref-file.cpp
src/knowledge/knowledge-experiences.cpp
src/knowledge/knowledge-self.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/player/player-status-flags.cpp
src/player/player-status.cpp
src/view/display-player.cpp
src/view/object-describer.cpp
src/window/display-sub-windows.cpp

#4357 の一環
現在 REALM_NONE との比較によって領域が有効（魔法なしではなくなんらかの魔法領域を使用可能）であるかをチェックしている箇所を、PlayerRealm::Realmクラスのメンバ関数 is_available() によってチェックするように変更する。

[Refactor] 領域が有効か調べる判定

---

src/cmd-action/cmd-spell.cpp
src/knowledge/knowledge-experiences.cpp
src/player-ability/player-constitution.cpp
src/player-ability/player-dexterity.cpp
src/player-ability/player-strength.cpp
src/player-base/player-class.cpp
src/player-info/class-ability-info.cpp
src/player-status/player-speed.cpp
src/player-status/player-stealth.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/player/player-skill.cpp
src/player/player-status-flags.cpp
src/player/player-status.cpp
src/racial/class-racial-switcher.cpp
src/racial/racial-switcher.cpp
src/spell/spell-info.cpp
src/view/object-describer.cpp
src/window/main-window-stat-poster.cpp

#4357 の一環
PlayerRealm::Realmクラスにメンバ関数equalsを実装し、現在PlayerTypeのデータメンバrealm1およびrealm2との直接比較によって特定の領域であるかを調べている箇所を置き換える。
また、呪術ハイメイジ専用処理で第1領域がREALM_HEXであるかどうかを調べている箇所は特別に多いので、PlayerRealmクラスにメンバ関数is_realm_hexを実装し、この関数によりチェックするようにする。
真偽反転がないかを特に注意していただきたく。

[Reafctor] 特定の領域かどうかを調べる判定

---

src/cmd-action/cmd-hissatsu.cpp
src/cmd-action/cmd-spell.cpp
src/knowledge/knowledge-experiences.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/player/player-status.cpp
src/realm/realm-arcane.cpp
src/realm/realm-chaos.cpp
src/realm/realm-craft.cpp
src/realm/realm-crusade.cpp
src/realm/realm-death.cpp
src/realm/realm-demon.cpp
src/realm/realm-hex.cpp
src/realm/realm-hissatsu.cpp
src/realm/realm-life.cpp
src/realm/realm-nature.cpp
src/realm/realm-song.cpp
src/realm/realm-sorcery.cpp
src/realm/realm-trump.cpp
src/spell-realm/spells-hex.cpp
src/spell/spell-info.cpp
src/spell/spells-util.h
src/window/display-sub-windows.cpp
src/wizard/wizard-spoiler.cpp

#4357 の一環
呪文の名称と説明が realm-*.cpp から分離されたことにより、いろいろやらせすぎな exe_spell から呪文の名称と説明の取得処理を分離することが可能となったので対応しました。

[Refactor] 呪文の名称と説明文の取得処理 

---

src/info-reader/spell-reader.cpp
src/info-reader/spell-reader.h
src/main/info-initializer.cpp
src/player/player-realm.cpp
src/system/spell-info-list.cpp
src/system/spell-info-list.h

SpellInfoListのデータメンバ spell_info のアクセルレベルをprivateにし、 get_spell_info メソッド経由で情報を取得するようにして実装のカプセル化を促進する。
単体Issueはありません。
spell_listというデータメンバに直接アクセスしているのが気になったので修正しました。その他、include調整、スペルミス修正、constメンバ関数にし忘れなども合わせて修正しています。

[Refactor] SpellInfoListクラスのカプセル化を促進

---

src/birth/inventory-initializer.cpp
src/cmd-action/cmd-spell.cpp
src/object-hook/hook-magic.cpp
src/object/object-info.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/realm/realm-names-table.h
src/view/object-describer.cpp

#4357 の一環
魔法書のItemKindTypeからどの領域かを取得するマクロtval2realmを廃止し、PlayerRealmクラスの静的メンバ関数get_realm_of_bookで取得するようにする。

[Refactor] 魔法書のItemKindTypeから領域を取得する処理 

---

src/birth/birth-select-realm.cpp
src/birth/quick-start.cpp
src/cmd-action/cmd-spell.cpp
src/load/load-zangband.cpp
src/load/player-info-loader.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/wizard/wizard-special-process.cpp

#4357 の一環
PlayerRealmに魔法領域をセットするメンバ関数 set と魔法領域なしにするメンバ関数 reset を実装し、PlayerTypeのデータメンバrealm1とrelam2に直接 値をセットしている箇所を置き換える。

[Refactor] 魔法領域のセット処理

---

src/avatar/avatar.cpp
src/birth/inventory-initializer.cpp
src/birth/quick-start.cpp
src/cmd-action/cmd-spell.cpp
src/load/load-zangband.cpp
src/market/building-service.cpp
src/player/player-realm.cpp
src/player/player-realm.h
src/save/player-writer.cpp
src/wizard/wizard-special-process.cpp

#4357 の一環
PlayerRealm::Realmクラスにメンバ関数 to_enum() を実装し、魔法領域番号を取得するために直接PlayerRealmクラスのデータメンバrealm1とrealm2にアクセスしている箇所を置き換える。
これで player_ptr->realm1 と realm2 にアクセスするのは PlayerRealm クラスのみになります。

[Refactor] 魔法領域の取得処理 

---

src/cmd-action/cmd-spell.cpp

第2領域を変更する時、change_realm2内で生成したPlayerRealmオブジェクトで領域のセットを行っているため、change_realm2を呼び出した側のPlayerRealmオブジェクトに変更が反映されておらず、変更前の領域が参照されてしまっている。
change_realm2に呼び出し側のPlayerRealmオブジェクトを渡すようにして修正する。
#4357 でのエンバグなので、単体Issueはなし。

[Fix] 第2領域変更後の魔法選択がおかしい

---

src/birth/quick-start.cpp
src/load/player-info-loader.cpp

魔法領域なしの時にもPlayerRealm::setで領域をセットしているので、領域のチェックで例外が発生してしまう。
魔法領域なしの時はPlayerRealm::setを呼ばずに終了するように修正する。
作業中の #4357 でのエンバグなので単体Issueはなし。

[Fix] 魔法領域なしの職業のセーブデータで起動するとクラッシュ

---

Build-Windows-Release-Package.ps1
VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/main-unix/stack-trace-unix.cpp
src/main-win/main-win-exception.cpp
src/main-win/stack-trace-win.cpp
src/system/angband-exceptions.h
src/util/stack-trace.h

Resolves #4397 
StackTraceクラスを実装し、Windows版でのエラー送信機能で送信する情報にコールスタック情報を含めるようにする。

[Feature] エラーレポートにコールスタック情報を含める

---

src/spell-realm/spells-crusade.cpp

Fix #4403 
2a53154 の修正で短絡評価でなくなってしまったため、is_boundが偽であり x,y が配列範囲外の時にも cave_stop_disintegration が呼ばれるのが原因。 短絡評価に戻し、is_boundが偽の時は cave_stop_disintegration が呼ばれない ように修正する。

[Fix] 神の怒りを画面端に打つとクラッシュする

---

src/monster/monster-list.cpp

Fix #4401
25a7079 で変身元と変身先の取り違えてしまっており、変身元のモンスターに対して爆発するかどうかの判定を行うようになってしまっている。
正しく変身先のモンスターに対して判定を行うように修正する。

[Fix] カメレオンが爆発するモンスターに変身してしまう

---

src/monster/monster-processor.cpp

fix #4405 
変身処理を呼び出した後にモンスターの名前を生成してしまっていたため変身前の種族ではなく変身後の種族が参照されてしまっていた

[Fix] 乗馬中のカメレオンが変身した際のメッセージで変身後の名前で表示されてしまうバグを修正

---

src/monster/monster-status.cpp

Fix #4406
トラッキングしているモンスターの一時的な状態変化から回復した際にモンスターのヘルスバーの更新フラグを立てていないため、モンスターの状態が再描画されずないままとなっている。
トラッキングしているモンスターの一時的な状態の時間経過を更新した場合にヘルスバー更新フラグを立て、再描画が行われるよう修正する。

[Fix] ヘルスバー下部に表示されるモンスターの状態が更新されない

---

lib/edit/MonraceDefinitions.jsonc

Close #4409 
攻撃の途中でワープしてしまうモンスターかつ遠距離では悲鳴以外の実害がないモンスターのため打撃のダイスは高めにしてある

モンスター「地獄の出店」を追加

---

src/player/process-name.cpp

初期設定の名前が空（新規キャラメイク時）で、入力した名前も空の場合には「PLAYER」という名前に設定し空の名前にならないようにする仕様だったが、b6d6401 で空の名前が設定できるようになってしまっている。
以前の通り空の名前を入力した場合は「PLAYER」を設定するように修正する。

[Fix] 空の名前が設定できてしまう

---

src/main-win/main-win-exception.cpp

#4423 対応その1
システムロケールがUTF-8のWindows環境において、STLが出力する日本語の例外メッセージの文字コードはUTF-8となる。しかし、エラーレポートのコードでは文字コードはSJISであることを想定しており、UTF-8をSJISとみなして文字コードの変換を行ってしまうため文字化けが発生する。
guess_convert_to_system_encoding 関数を通すことでメッセージを一旦SJISに統一することで、システムロケールがSJISでもUTF-8でも正しく動作するようにする。

[Fix] エラーレポートの文字化け

---

src/birth/game-play-initializer.cpp
src/cmd-action/cmd-hissatsu.cpp
src/cmd-action/cmd-spell.cpp
src/load/inventory-loader.cpp
src/player/player-status.cpp
src/save/save.cpp
src/system/player-type-definition.h

魔法を学習した順序を記録する PlayerType::spell_order を固定長配列から std::vector に変更して扱いやすくする。
#4357 に関連したリファクタリングです。

[Refactor] PlayerType::spell_order

---

src/util/angband-files.cpp

#4423 対応その2
Windows環境において、std::filesystem::path::appendはstd::string_viewを受け取ると、その文字コードはシステムロケールに一致すると想定し、システムロケールからWindows内部処理の文字コードであるUTF-16に変換する。
変愚蛮怒の内部文字コードはSJIS固定であるため、システムロケールがUTF-8の環境ではSJISをUTF-8とみなしてUTF-16へ変換しようとしてしまい、変換失敗の例外が発生しクラッシュする。
対策として、Windows環境では自前でSJIS→UTF-16の変換を行い、UTF-16の文字列を渡すようにする。

[Fix] WindowsのシステムロケールがUTF-8の時クラッシュする

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/birth/game-play-initializer.cpp
src/cmd-action/cmd-hissatsu.cpp
src/cmd-action/cmd-spell.cpp
src/load/load-zangband.cpp
src/player/player-spell-status.cpp
src/player/player-spell-status.h
src/player/player-status.cpp
src/spell/spell-info.cpp
src/window/display-sub-windows.cpp
src/wizard/wizard-special-process.cpp

呪文の学習・試行・忘却状態の処理を行うPlayerSpellStatusクラスを実装し、
現状直接 spell?_learned, spell?_worked, spell?_forgotten にアクセス
している箇所をPlayerSpellStatusクラスによる処理で置き換える。
また、 #4421 の対策として、職業や領域の変更時にPlayerSpellStatusクラスを用いて、学習状況の初期化を行うようにする。

[Refactor] 呪文の学習・試行・忘却状態の処理

---

src/main-win/main-win-cfg-reader.cpp
src/main-win/main-win-cfg-reader.h
src/main-win/main-win-music.cpp
src/main-win/main-win-music.h
src/main-win/main-win-sound.cpp
src/main-win/main-win-sound.h

Resolves #4427
生ポインタとnewを使用している古くさいコードとなっているCfgReaderをModern C++な書き方でリファクタリングを行う。

[Refactor] CfgReader

---

src/main-win/main-win-sound.cpp

Fix #4432
8bitサンプリングのPCM音源の波形データはサンプルごとの値は0～255で基準値(無音)を128とするが、0を基準として振幅変調を行っているため想定通りの振幅変調が行えておらず、効果音再生時にノイズが乗ってしまう。
8bitサンプリングのPCMの場合は128を基準値として振幅変調を行うように修正する。

[Fix] 8bitサンプリングの効果音にノイズが乗る

---

src/main-win.cpp
src/main-win/main-win-utils.cpp
src/main-win/main-win-utils.h

#4423 の対応その4
WindowsのシステムロケールがUTF-8の時、パスに日本語を含む場合にBGMや効果音の設定フォルダを開く処理でUTF-16への文字コードの変換に失敗するため、正しく設定フォルダを開くことができない。
std::filesystem::path::wstring で直接UTF-16のパス文字列を取得するようにし、文字コードの変換を行わないようにする。

[Fix] システムロケールがUTF-8の時設定フォルダを開くのに失敗する

---

src/spell-kind/spells-enchant.cpp

Fix #4435 
凡庸の巻物をモンスターの人形・像・骨・死体に使用すると、pvalが0となることによりモンスター種族IDが0となるが、この状態は不正であるという扱いで例外を送出するようになっており、その結果クラッシュする。
対策として、これらのpvalをモンスター種族IDとして使用するアイテム（これらの他にモンスター・ボールも対象となる）に対して凡庸の巻物を使用できないようにする。

[Fix] 凡庸の巻物をモンスターの人形・像・骨・死体に使用するとクラッシュ

---

src/mind/mind-archer.cpp

[Fix] 骨から矢、クロスボウの矢を生成する時に骨が重ね書きされて消滅する不具合を修正。

---

src/main-win/main-win-sound.cpp
src/main-win/wav-reader.cpp
src/main-win/wav-reader.h

Resolves #4439
現状のWindows版の効果音再生処理は生ポインタとnew/deleteを伴う古臭いコードとなっているので、Modern C++によりリファクタリングを行う。

[Refactor] Windows版の効果音再生処理

---

src/core/game-play.cpp
src/core/player-processor.cpp
src/dungeon/quest-monster-placer.cpp
src/floor/fixed-map-generator.cpp
src/floor/floor-generator.cpp
src/monster-floor/monster-generator.cpp
src/monster-floor/monster-generator.h
src/monster-floor/monster-summon.cpp
src/monster-floor/one-monster-placer.cpp
src/monster-floor/one-monster-placer.h
src/room/rooms-nest.cpp
src/room/rooms-pit.cpp
src/room/rooms-special.cpp
src/specific-object/monster-ball.cpp
src/spell-kind/spells-polymorph.cpp

#4414 関連のリファクタリング
関数 place_monster_one と place_monster_specific の引数 src_idx と summoner_m_idx はどちらも召喚主のモンスターIDを渡す引数として使用しており、役割が被っているので summoner_m_idx に統合する。

[Refactor] place_monster_one/place_monster_specificのシグニチャ

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/birth/game-play-initializer.cpp
src/floor/floor-list.cpp
src/floor/floor-list.h
src/main/game-data-initializer.cpp
src/system/floor-type-definition.cpp
src/system/floor-type-definition.h

Close #4468 
`init_other()`で初期化している箇所はコメントアウトされているTODO についてFloorType のコンストラクタに移植するべきと判断し移植しているため、該当部分に関してもレビュー求む

[Refactor] シングルトンクラスにFloorType のデータを移し、初期化はFloorType のコンストラクタで行うようにした

---

src/room/rooms-special.cpp

1行だけの修正です
不具合発生前後のコミットを記載しておきます：
9ac6b930c3752b65ed9db3ca7416922612797ec8 (発生前)
fcb78d09f4fc033dea359d01c1b6e939e6343a1f (発生後)

[Fix] #4496 ガラスの床にしなければいけない箇所が壁になっていた不具合を修正した

---

src/info-reader/race-reader.cpp
src/monster-floor/monster-death.cpp
src/system/monster-race-info.cpp
src/system/monster-race-info.h

タプルよりはマシになったかと思います
ドロップ処理 (の一部？)を上手いことメソッドに繰り込めれば使い勝手も上がるかと思いますが現時点では見送りました
ご確認下さい

モンスターの固定ドロップをクラス化した

---

src/lore/lore-util.cpp
src/lore/lore-util.h
src/lore/monster-lore.cpp
src/view/display-lore-attacks.cpp
src/view/display-lore-drops.cpp
src/view/display-lore-magics.cpp
src/view/display-lore-status.cpp
src/view/display-lore.cpp

これに伴いWho クラスも微調整しています
ご確認下さい
(そもそもWho に定義されたメソッドはLore のメソッドへ付け替えてもいいかもしれないが、このPRではスキップ)

モンスター性別を表すenumが重複していたので片方を消した

---

src/lore/combat-types-setter.cpp
src/melee/melee-switcher.cpp
src/monster-attack/monster-attack-describer.cpp

[Feature] CRUSH の訳を「押し潰す」に変更し、置き換え忘れ部分を全て同様の文章に変えた

---

src/knowledge/knowledge-monsters.cpp
src/main/game-data-initializer.cpp
src/market/bounty.cpp
src/room/rooms-nest.cpp
src/system/monster-race-info.cpp
src/system/monster-race-info.h
src/target/target-preparation.cpp
src/target/target-sorter.cpp
src/util/object-sort.cpp
src/wizard/wizard-spoiler.cpp

掲題の通りです
「monrace2の方が高レベルかを判定する箇所」は2箇所見つけましたが、間違っている箇所がないか重点的にご確認下さい
注：`!monrace1.order_level(monrace2)`≠`monrace2.order_level(monrace1)` です。前者はNG

モンスター種族のレベルソートをメソッド化した

---

src/lore/lore-util.cpp
src/lore/lore-util.h
src/view/display-lore.cpp
src/view/display-lore.h

#4534 の内、純粋なリファクタリング部分だけを抽出したものです
チケットはありません
わざわざemplaceするために型を明記しているのがちょっと気持ち悪い (Clangがこうしないとコンパイルエラー)ので、多少実行時コストが重くてもpush\_backにすべきか少し悩んでいます
ご確認下さい

lore_type::build_speed() を定義して表記部分を軽量化した

---

lib/edit/MonraceDefinitions.jsonc
src/info-reader/race-reader.cpp
src/knowledge/knowledge-uniques.cpp
src/main/game-data-initializer.cpp
src/monster/monster-list.cpp
src/monster/monster-util.cpp
src/object-enchant/others/apply-magic-others.cpp
src/system/alloc-entries.cpp
src/system/alloc-entries.h
src/system/monster-race-info.cpp
src/system/monster-race-info.h

掲題の通りです
#4551 の後続チケットなので、マージされるまではドラフトにしておきます
なおdevelopブランチとフロアリセット時に生成されるモンスターが異なりますが、これはソートアルゴリズムの変更によるものです (std::sort → std::stable\_sort、同レベルモンスターが配列に格納される順番が異なるが、相異なるレベルでのソートは正常)
鉄獄50Fで何度かリセットしてみましたが、50Fらしい分布になっており異常はありませんでした
ご確認下さい
備考：
上記ソートアルゴリズムを元に戻し、^A → j → Enter2回 でdevelopとこのブランチが同じモンスター分布になることを確認可能

monraces_info へ直接アクセスしている箇所を削減した その17

---

src/birth/game-play-initializer.cpp
src/load/lore-loader.cpp
src/system/monster-race-info.cpp
src/system/monster-race-info.h
src/system/system-variables.h

掲題の通りです
#4552 の後続チケットなので、マージされるまではドラフトにしておきます

モンスターの思い出読み込み処理において、monraces_info への直接アクセスをMonraceList へ置き換えた

---

src/floor/floor-town.cpp
src/floor/floor-town.h
src/io-dump/character-dump.cpp
src/io-dump/random-art-info-dumper.cpp
src/knowledge/knowledge-inventory.cpp
src/knowledge/knowledge-self.cpp
src/load/store-loader.cpp
src/main/game-data-initializer.h
src/market/building-initializer.cpp
src/player/process-death.cpp
src/save/info-writer.cpp
src/store/black-market.cpp
src/store/home.cpp
src/store/museum.cpp
src/store/pricing.cpp
src/store/pricing.h
src/store/purchase-order.cpp
src/store/store-util.cpp
src/store/store-util.h
src/store/store.cpp
src/view/display-store.cpp

20数ヶ所ほどstocker\[i\].get() が発生していますが、次以降のPRで調整します
買った時のストック減少 (商品がなくなる/減る)・売った時のストック増加 (商品が追加される/増える)・買い尽くしの後に補充される動作をチェック済です
ご確認下さい

store_type::stock をunique_ptr<ItemEntity[]> からvector<unique_ptr<ItemEntity>> に変えた

---

src/lore/lore-util.cpp
src/lore/lore-util.h
src/view/display-lore.cpp

デバッグモードでは敵討ちが困難なので、その辺りのフラグを調整する機構を構想中です (ユニークに殺された思い出状況を意図的に作り出せない。未実装)
通常のセーブデータで再現実験中ですが、レビュアー側でも気付いたことがありましたらご指摘下さい

マクロ関数plural() を除去し、思い出表記のユニーク撃破状況についてlore_type へ文字列組み立てを移管した

---

src/cmd-building/cmd-inn.cpp
src/cmd-item/cmd-magiceat.cpp
src/hpmp/hp-mp-regenerator.cpp
src/io-dump/special-class-dump.cpp
src/load/player-class-specific-data-loader.cpp
src/load/player-class-specific-data-loader.h
src/mind/mind-magic-eater.cpp
src/player-base/player-class.cpp
src/player-info/class-specific-data.h
src/player-info/magic-eater-data-type.cpp
src/player-info/magic-eater-data-type.h
src/save/player-class-specific-data-writer.cpp
src/save/player-class-specific-data-writer.h
src/spell/spells-status.cpp

#4580 の後続チケットです
マージされるまではドラフトにしておきます
繰り込み後のメソッド名は特に思いつかなかった (職種依存のdata\_type はvariant で管理されているのでメソッド名でも区別できた方がベターと判断)ので一旦そのままにしてあります
ご確認下さい

check_magic_eater_spell_repeat() をmagic_eater_data_type のメソッドへ繰り込んだ

---

src/floor/fixed-map-generator.cpp
src/monster-floor/monster-death-util.cpp
src/monster-floor/monster-death-util.h
src/monster-floor/monster-death.cpp
src/system/baseitem-info.cpp
src/system/baseitem-info.h
src/system/floor-type-definition.cpp
src/system/floor-type-definition.h
src/system/system-variables.cpp
src/system/system-variables.h

Discord での議論により、レビュアーは @dis- 氏にお願いします
(#4608 との整合性は、CREEPING\_COIN\_DROPS においてキーをMonraceId から特定財宝ドロップフラグに変えることで実現できると思われます)
財宝に関して、以下を実現しました：
- 価値の低い順で並んでいる必要はない
- sval 順で並んでいる必要はない
- ベースアイテムIDが連続している必要はない
- バリアントなどで「最初の財宝」を示すベースアイテムIDが変わってもOK (現在はID 480)
- クリーピングコインの追加が(以前に比べて)簡単になった
手元で、ベースアイテム定義はas-is の条件で、developと同じ動作を確認しました：
- フロアのランダム床落ちが同じ
- クエストの固定床落ちが同じ
- クリーピングコインのドロップが個数・金額も含めて同じ
- 一般的な財宝ドロップモンスターのドロップが個数・種類も含めて同じ (金額までは上記で担保できていると考え省略)
テストとしては以下の項目が考えられます
追加財宝例は「スピネル」とか「途方も価値のない錆びた偽物の金塊」があります
もしヌケモレありましたら適宜追加実施お願いします
- ベースアイテムID 440～479 に財宝を追加しても正常動作する
-  銅貨1 (ID 480)より価値の低いもの
- アダマンタイトより価値の高いもの
- 中間くらいの価値のもの
- ベースアイテムIDが指し示す中身を入れ替えても正常動作する (IDそのものを入れ替えると初期化処理でアウト)
- 銅貨1と銀貨1
- 銅貨3とアダマンタイト
- その他
- アイテムの価値 (cost値)を入れ替えても正常動作する
- ガーネットとエメラルド
- ダイヤモンドとアダマンタイト
- その他 …

coin_type とOBJ_GOLD_LIST を廃止し、財宝ドロップ関連処理をBaseitemList でモデル化した

---

src/cmd-visual/cmd-visuals.cpp
src/knowledge/knowledge-features.cpp

符号付き/なしで異常な表示になる可能性のある場所を符号なしに統一
TerrainList を2回取得している箇所を1回に統一
上記2点実施しました
たまたま目についたものの微修正なのでチケットはありません
ご確認下さい

Visual Editor 周辺の小修正

---

src/store/store-util.cpp
src/store/store-util.h
src/store/store.cpp
src/system/item-entity.cpp
src/system/item-entity.h

unique\_ptr::get() を削減しました
https://github.com/hengband/hengband/pull/4616 がマージされるまでドラフトにしておきます

is_similar_for_store() をItemEntity のオブジェクトメソッドへ繰り込んだ

---

src/grid/grid.cpp

上から降ってきたGrid に対して判定が必要なところ、プレイヤー自身の座標にあるGrid で判定してしまっていました
ご確認下さい

隠しドアが見つからない不具合を修正した

---

src/action/tunnel-execution.cpp
src/effect/effect-feature.cpp
src/grid/grid.cpp
src/grid/grid.h
src/player/player-move.cpp
src/system/grid-type-definition.cpp
src/system/grid-type-definition.h

リリース直前に出た不具合修正について、変更範囲からPlayerType がなくなったので掲題の通りリファクタリングしました
軽微なのでチケットはありません
ご確認下さい

is_hidden_door() をGrid のオブジェクトメソッドへ繰り込み、PlayerType への依存を外した

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/main/angband-initializer.cpp
src/monster-floor/monster-death.cpp
src/system/baseitem/baseitem-list.cpp
src/system/baseitem/baseitem-list.h
src/system/services/baseitem-monrace-service.cpp
src/system/services/baseitem-monrace-service.h

※ これは摺り合わせのための暫定ドラフトです
#4608 で導入されたフラグを組み込みました
設計上の課題2点についてはスルー中です：
- ベースアイテムとモンスター種族 (のフラグ)が密結合のままである。後でサービスクラス化して差し替えることを検討
- 同一モンスター種族に2つ以上の特定財宝ドロップ (例：DROP\_SILVER かつDROP\_EMERALD)があってもスルーしてしまう。チェックルーチンを検討中

モンスター種族IDではなくモンスターの特定財宝ドロップフラグに基づいて生成する財宝を選択するようにした

---

src/main/angband-initializer.cpp
src/system/services/baseitem-monrace-service.cpp
src/system/services/baseitem-monrace-service.h

- ロジックの修正で可読性と計算量のオーダーの改善
- 関数名をチェック内容がわかりやすいように変更
PR #4651 を見てのちょっとした改善点なので、単独Issueは無し。
※ 今思うと `std::bitset` のメソッド名に合わせたような記憶があるので、discordで言及した `EnumClassFlagGroup::count()` -> `popcount()` の変更は見送り。

[Refactor] 特殊財宝ドロップフラグの重複チェック処理

---

src/system/floor-type-definition.cpp

コードを確認したところ、地上ならば生成基準階層を1Fに固定すればなさそうだと判断しました
ご確認下さい

地上でLv1の財宝ドロップモンスターを倒すと異常アイテムを生成してしまう不具合を修正した

---

src/monster-floor/monster-generator.cpp

正常に帰還 (フロア生成)ができることをチェック済です
ご確認下さい

vectorの要素数が変わる前後で同じ参照を見続けた結果、ダングリング化してフロア生成に失敗する不具合を解消した

---

src/floor/floor-object.cpp
src/monster-floor/special-death-switcher.cpp
src/room/rooms-special.cpp
src/store/store.cpp
src/system/alloc-entries.cpp
src/system/alloc-entries.h
src/system/floor-type-definition.cpp
src/system/floor-type-definition.h
src/system/system-variables.cpp
src/system/system-variables.h
src/world/world-object.cpp
src/world/world-object.h

掲題の通りです
一連の作業でクラスの役割分担が進展したかと思います
床落ちアイテムがdevelopと同じであることをチェック済です
ご確認下さい

get_obj_index() をFloorType::select_baseitem_id() に繰り込み、確率テーブル処理をBaseitemAllocationTable へ移した

---

src/io-dump/random-art-info-dumper.cpp
src/knowledge/knowledge-inventory.cpp
src/load/store-loader.cpp
src/player/process-death.cpp
src/store/home.cpp
src/store/museum.cpp
src/store/purchase-order.cpp
src/store/store-util.cpp
src/store/store.cpp
src/view/display-store.cpp

#4665 の続きです、先行チケットがマージされるまでドラフトにしておきます
これにてスマートポインタ対応完了です

store_type::stock へのアクセスをunique_ptr から参照に差し替えた

---

src/inventory/inventory-object.cpp

PR #4687 で、装備を外したとき持ち物が一杯だと外した装備でなく持ち物の一番下のアイテムがあふれて地面に落ちるようになってしまっている。
player_ptr->inventory_list[INVEN_PACK] は装備を外したときに持ちきれないアイテムを一時的に保持しておく場所であり、この場所もまとめてソートされるように変更してしまっていたために生じた不具合。
この場所は除外してソートするように修正する。
また、サブウィンドウの持ち物一覧を更新するフラグを立てる処理が消えてしまっていたので、それもあわせて復活する。

[Fix] 持ち物が一杯で装備を外したときの挙動

---

src/action/weapon-shield.cpp
src/autopick/autopick-destroyer.cpp
src/cmd-item/cmd-destroy.cpp
src/cmd-item/cmd-eat.cpp
src/core/object-compressor.cpp
src/floor/floor-generator.cpp
src/floor/floor-object.cpp
src/grid/object-placer.cpp
src/inventory/inventory-object.cpp
src/load/store-loader.cpp
src/object-use/quaff/quaff-execution.cpp
src/perception/object-perception.cpp
src/smith/object-smith.cpp
src/spell/spells-status.cpp
src/store/cmd-store.cpp
src/store/home.cpp
src/store/purchase-order.cpp
src/store/store-util.cpp
src/system/item-entity.h
src/wizard/wizard-item-modifier.cpp

ItemEntityクラスのコピーコンストラクタとコピー代入演算子を隠蔽し、オブジェクトのコピーが必要なところでは明示的に ItemEntity::clone() を呼ぶようにする。
そもそもコピーする必要がない箇所については std::move() でムーブすることで対応し効率化を図る。
Issue #4686 の一環。

[Refactor] ItemEntityのコピーコンストラクタとコピー代入演算子を隠蔽

---

src/floor/floor-changer.cpp
src/floor/floor-generator.cpp
src/floor/floor-leaver.cpp
src/monster/monster-compaction.cpp
src/monster/monster-damage.cpp
src/spell-kind/spells-polymorph.cpp
src/system/monster-entity.cpp
src/system/monster-entity.h

MonsterEntityクラスのコピーコンストラクタとコピー代入演算子を隠蔽し、オブジェクトのコピーが必要なところでは明示的に ItemEntity::clone() を呼ぶようにする。
また、ItemEntityとの対称性を考慮し、MonsterEntity::wipe()も実装する。
#4686 の一環。

[Refactor] MonsterEntityのコピーコンストラクタとコピー代入演算子を隠蔽

---

VisualStudio/Hengband/Hengband.vcxproj

以下の作業を行いました
ビルドには問題なかった他、軽くテストプレイしましたが特にエラーにはなりませんでした
ご確認下さい
- English-Debug で出ていた警告の解消
- 警告レベルの引き上げ＆ローカル環境でのビルドエラー化
- AVXの有効化 (AVX2以降は64ビットバイナリである必要があるため却下)
- リリースビルドからデバッグ情報の削除

MSVCのビルド設定を改善した

---

src/target/target-getter.cpp

リピートコマンドに方向入力が含まれるとき、方向の値の妥当性を調べずそのまま方向として設定しているので、何らかの理由により値が異常だった場合におかしな値となってしまい、クラッシュの原因となる可能性がある。
方向の値として正しい場合のみ設定するようにする。
Maybe Fix #4708

[Fix] リピートコマンドで方向入力の値の妥当性をチェックする

---

src/birth/game-play-initializer.cpp
src/cmd-action/cmd-move.cpp
src/dungeon/quest.h
src/floor/fixed-map-generator.cpp
src/floor/floor-generator.cpp
src/floor/floor-leaver.cpp
src/floor/wild.cpp
src/floor/wild.h
src/info-reader/dungeon-reader.cpp
src/io-dump/character-dump.cpp
src/knowledge/knowledge-features.cpp
src/load/world-loader.cpp
src/main-win/main-win-music.cpp
src/main/game-data-initializer.cpp
src/main/info-initializer.cpp
src/market/bounty.cpp
src/player/player-status.cpp
src/save/player-writer.cpp
src/spell-kind/spells-world.cpp
src/store/rumor.cpp
src/system/building-type-definition.cpp
src/system/dungeon/dungeon-definition.h
src/system/dungeon/dungeon-list.cpp
src/system/dungeon/dungeon-list.h
src/system/floor/floor-info.cpp
src/system/floor/floor-info.h
src/system/h-type.h
src/system/player-type-definition.h
src/target/target-describer.cpp
src/wizard/wizard-special-process.cpp

DungeonDefinition::outer\_wall などの地形特性ID とfeat\_hoge のグローバル変数廃止との整合性を取っていく上で先にやっておいた方が良さそうだと判断しました
この次のPRも含め、帰還とフロア・リセット周りの挙動が正常に動いていることをチェック済です
クラスのモデル化は別途行います
ご確認下さい

dungeons_info をDungeonList に差し替えた

---

VisualStudio/Hengband/Hengband.vcxproj
src/flavor/object-flavor.cpp
src/main-gcu.cpp
src/main-win.cpp
src/main-x11.cpp
src/term/gameterm.h

詳細は以下の通りです
リリース作業に支障がある可能性が高いのでお早めにチェック頂けると助かります
- リリースビルドにおける単なる情報表示 (C4711、インライン関数展開)が警告扱いになってコンパイルエラーを起こしているので、デバッグビルドのみWIN_DEBUG のプリプロを定義した
- 4061 など新たに追加されているが、これらはVS2022 のデフォルト抑制
- 戻り値がvoid でない関数においてquit() が呼ばれる時、デバッグビルドではダミー戻り値を返すコードを書いていたが、リリースビルドでは警告からのコンパイルエラーになるので、リリースビルドのみ抑制した
- デバッグビルドでは、AVX 命令が有効でもほぼ性能向上は見込めず、それどころかステップ実行に悪影響が出る可能性があるらしいので、デバッグビルドにおいては拡張命令全般を無効化した
- MSVC 専用拡張記法を無効化した (GNU 拡張は以前に無効化済)
- その他main-win.cpp におけるサジェスト対応 (define 定数、static 関数、ナローキャスト)

MSVC において、デバッグビルド以外のビルドに失敗する問題を修正した

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/packages.config

(バグはバグでもいわゆるデグレ)
旧バージョンはサーバから消えてしまったようなので最新版にしました
過去のどこかでNuGetパッケージのない環境からマージされてしまっていたようですが、このコミットが正のはずです
ご確認下さい

旧バージョンの静的解析ツールを指していたNuGetパッケージ一覧を最新版まで引き上げた

---

src/floor/cave-generator.cpp

ed8a18aa で迷宮生成時の引数のx,y,xsize,ysizeをPos2D,Pos2DVec型に変えたときに順序を取り違えていたのが原因。正しい順序に修正する。
Fix #4726

[Fix] 迷宮が狭い

---

VisualStudio/Hengband/Hengband.vcxproj

今まで実際にゲーム内で使われる事はないので日本語の文字についての警告を無視していたが、警告をエラー扱いするオプションが設定された影響でビルドエラーとなっている。
日本語版と同じく、 /execution-charset:shift-jis をその他のオプションに 設定することでGitHub Actionsのインスタンス上でも警告が出ることなくビルドを行えるように修正する。

[Fix] 自動リリースのWorkflowで英語版のビルドに失敗する

---

src/lore/lore-util.cpp

Resolves https://github.com/hengband/hengband/issues/4745 .

English: in revenge part of lore, add missing space and match verb to subject

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/system/baseitem/baseitem-allocation.cpp
src/system/baseitem/baseitem-allocation.h
src/system/baseitem/baseitem-list.cpp
src/system/baseitem/baseitem-list.h
src/system/monrace/monrace-allocation.cpp
src/system/monrace/monrace-allocation.h
src/system/terrain/terrain-list.cpp
src/system/terrain/terrain-list.h
src/util/abstract-vector-wrapper.h

std::vectorをラップする抽象クラスAbstractVectorWrapperを導入し、std::vectorをラップしているクラスをAbstractVectorWrapperを継承する形に変更することで、内部のコンテナに移譲するだけのボイラープレートを削減する。
#4719 の作業の一環。まずは std::vector をラップするクラスについて抽象クラスを作成してみました。

[Refactor] AbstractVectorWrapperによるボイラープレートの削減

---

hengband.spec

- hengband.specのバージョンを3.0.1.23に更新
- 同バージョンのrpmをCoprにて配布開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/

Update hengband.spec versionto 3.0.1.23

---

src/system/dungeon/dungeon-record.cpp

DungeonRecord::reset() を呼ぶつもりが std::shared_ptr::reset() を呼んでしまっており、その後のアクセスがヌルポアクセスとなりクラッシュしている。
正しく DungeonRecord::reset() を呼ぶように修正する。
直近のPR #4754 でのエンバグの修正なので単体Issueなし。

[Fix] 新規キャラクター作成時にクラッシュ

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/birth/birth-select-realm.cpp
src/cmd-action/cmd-move.cpp
src/io-dump/character-dump.cpp
src/knowledge/knowledge-features.cpp
src/load/world-loader.cpp
src/market/bounty.cpp
src/player/player-status.cpp
src/spell-kind/spells-world.cpp
src/system/building-type-definition.cpp
src/system/dungeon/dungeon-list.cpp
src/system/dungeon/dungeon-list.h
src/system/dungeon/dungeon-record.cpp
src/system/dungeon/dungeon-record.h
src/system/enums/dungeon/dungeon-id.h
src/system/services/dungeon-service.cpp
src/system/services/dungeon-service.h

shared\_ptr を直接取得するメソッドが残っていますが、これは後でFloorType::dungeon\_id をshared\_ptr に差し替える計画です (その他将来の拡張)
ご確認下さい

DungeonService クラスを作り、DungeonDefinition とDungeonRecord の両方に依存する処理を移設した

---

src/floor/cave-generator.cpp
src/system/dungeon/dungeon-data-definition.cpp
src/system/dungeon/dungeon-data-definition.h

他作業でちょっと気になったので修正です
小規模なのでチケットはありません
ご確認下さい
- vector\<bool\> の中身は元からfalse で初期化されるので削除
- cent\_n も0初期化されているので削除
- 部屋数はコンストラクタ引数に変更

DungeonData のコンストラクタを改善し、外から初期化する項目を減らした

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/dungeon/quest.cpp
src/dungeon/quest.h
src/load/quest-loader.cpp
src/system/artifact-type-definition.cpp
src/system/artifact-type-definition.h
src/system/dungeon/dungeon-list.cpp
src/system/dungeon/dungeon-list.h
src/system/dungeon/dungeon-record.cpp
src/system/dungeon/dungeon-record.h
src/system/monrace/monrace-list.cpp
src/system/monrace/monrace-list.h
src/util/abstract-map-wrapper.h

std::mapをラップする抽象クラスAbstractMapWrapperを導入し、
std::mapをラップしているクラスをAbstractMapWrapperを継承する形に
変更することで、内部のコンテナに移譲するだけのボイラープレートを削減する。
Resolves #4719

[Feature] AbstracMapWrapperによるボイラープレートの削減

---

src/monster-floor/one-monster-placer.cpp
src/monster/monster-list.cpp
src/monster/monster-list.h
src/monster/monster-processor.cpp
src/monster/monster-util.cpp
src/monster/monster-util.h
src/system/enums/monrace/monrace-hook-types.h
src/system/grid-type-definition.cpp
src/system/grid-type-definition.h

カメレオンの変身先選択ルーチンをdo_get_mon_num_prep() から分離した

---

src/cmd-io/cmd-lore.cpp
src/system/monrace/monrace-list.cpp
src/system/monrace/monrace-list.h

MonraceList にモンスターの検索を行うメソッドを追加し、現在do_cmd_qeury_symbol 関数で行っているモンスター検索処理を追加したメソッドで置き換える。
#4775 の作業、検索メソッドの追加と do_cmd_query_symbol のリファクタまで。

[Refactor] do_cmd_query_symbol

---

src/system/services/dungeon-service.cpp

むしろ最初の1回が出ないバグです
ご確認下さい
なおローカル環境ではイーク洞の入口が0Fになるバグが別途出ていましたが、どうもコーディング中の動作確認で一時的に出たものらしくリリース時のコミットでは再現しませんでした
万が一今後bisect中にどこかのコミットで再現するかもしれませんが、その時は以下の手順で復旧できます
- 一旦イーク洞に入る (が、すぐ地上に戻される)
- 広域マップに出る
- もう一度辺境の地に入る

ダンジョン突入フラグが反対になっていたのを修正した

---

src/system/monrace/monrace-list.cpp
src/wizard/wizard-spells.cpp

デバッグコマンドでモンスターを召喚する時以下の選択方法を可能にする
- モンスターのシンボル文字を入力し、該当モンスター一覧から選択
- 入力した文字列がモンスター名称に部分一致するモンスター一覧から選択
- 既存のモンスター種族IDを入力する方法
また、英名で検索する時に正しくcase-insensitiveになっていない不具合があったので合わせて修正しました。
選択候補の表示ではとりあえずモンスターの名称のみを表示していますが、MonsterIDやその他の情報で合わせて表示されていると便利そうなものがあれば対応できそうです。
Resolves #4775

[Feature] デバッグコマンドでモンスターを選択しやすくする 

---

src/birth/inventory-initializer.cpp
src/core/player-processor.cpp
src/dungeon/quest.cpp
src/monster-floor/one-monster-placer.cpp
src/monster-race/monster-race-hook.cpp
src/monster/monster-util.cpp
src/monster/monster-util.h
src/object-enchant/others/apply-magic-others.cpp
src/player/eldritch-horror.cpp
src/room/rooms-special.cpp
src/system/building-type-definition.cpp
src/system/enums/monrace/monrace-hook-types.h

「無理やりシグネチャを統一した関数ポインタを返す関数」とかいう闇の深い設計を廃止して見通しが良くなりました
ご確認下さい

get_monster_hook() を廃止した

---

src/monster/monster-util.cpp
src/monster/monster-util.h
src/room/pit-nest-util.h
src/room/rooms-nest.cpp
src/room/rooms-pit.cpp
src/system/enums/monrace/monrace-hook-types.h

これにてモンスター生成フィルタ周りの関数ポインタ絶滅が完了しました
ご確認下さい

function型の引数を取るget_mon_num_prep() を廃止した

---

hengband.spec

- hengband.specのバージョンを3.0.1.24に更新
- 同バージョンのrpmをCoprにて配布開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/

Update hengband.spec version

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/monster-race/monster-race-hook.cpp
src/monster-race/monster-race-hook.h
src/monster/monster-util.cpp
src/system/floor/floor-info.cpp
src/system/floor/floor-info.h
src/system/monrace/monrace-allocation.cpp
src/system/monrace/monrace-allocation.h
src/system/monrace/monrace-definition.cpp
src/system/monrace/monrace-definition.h
src/system/services/dungeon-monrace-service.cpp
src/system/services/dungeon-monrace-service.h

#4795 のサービスクラスバージョンです
個人的にはこっちの方が対称性が高くて扱いやすい印象です
(フラグ有無を確認しているところは相変わらず露出したままだが、本質的ではないので省略)

モンスター生成フィルタ用のグローバル関数解体 その1 (B案)

---

src/monster/monster-damage.cpp
src/system/monrace/monrace-definition.cpp
src/system/monrace/monrace-definition.h
src/system/monrace/monrace-list.cpp

現状合体ユニークを倒した時、合体先・分離先のモンスターも死亡済みにする処理においてあわせて倒した数の記録も増やされるようになっているが、やや不自然な挙動なので合体先・分離先のモンスターは死亡済みにする処理のみを行い、倒した数の記録を増やすのは実際に倒した対象のみとする。
Resolves #4805 
Fix #4800

[Fix] 合体ユニークの倒した数の記録の扱いがあいまい

---

src/target/projection-path-calculator.cpp

ProjectionPathHelper の実行結果とは無関係にpositions をムーブすべきところでできていなかったのが原因です
ご確認下さい

ターゲッティングが正しく実行できない不具合を修正した

---

src/dungeon/dungeon-processor.cpp
src/dungeon/quest.cpp
src/floor/object-allocator.cpp
src/io-dump/character-dump.cpp
src/knowledge/knowledge-monsters.cpp
src/load/load-zangband.cpp
src/lore/lore-util.cpp
src/mspell/summon-checker.cpp
src/system/dungeon/dungeon-definition.cpp
src/system/monrace/monrace-definition.cpp
src/system/monrace/monrace-definition.h
src/system/monrace/monrace-list.cpp

死亡済みのユニークモンスターかどうかの判定を MonraceDefinition::max_num を直接調べている箇所が多数あるので、MonraceDefinition::is_dead_unique() にカプセル化する。
#4811 の作業に先立ってコードを確認していて気になったので、一旦これだけ単体PRとして提出します。

[Refactor] 死亡済みのユニークモンスターかどうかの判定

---

src/perception/identification.cpp

That matches what view/display-characteristic.cpp does and resolves https://github.com/hengband/hengband/issues/4739 .
The handling for TR_RES_CURSE currently mimics what's in src/view/display-characteristic.cpp.  It was not clear to me if it also needed to test for item.curse_flags.has(CurseTraitType::VUL_CURSE) not being there as that is tested for when printing "It decreases your resistance to curses.".

For descriptions, immunities and vulnerabilities override resistances

---

src/dungeon/dungeon-processor.cpp

f1e668fb によるエンバグ。
元々きちんとダンジョンの主が存在するかどうかのチェックをするべきであるところなので、先に has_guardian() による判定を行うようにする。

[Fix] 荒野でダンジョンの主に関するメッセージが出てしまう

---

src/dungeon/quest-completion-checker.cpp
src/floor/floor-changer.cpp
src/floor/floor-util.cpp
src/floor/floor-util.h
src/mind/mind-elementalist.cpp
src/mind/mind-ninja.cpp
src/monster-floor/monster-death-util.cpp
src/monster-floor/monster-death-util.h
src/monster-floor/monster-generator.cpp
src/monster-floor/special-death-switcher.cpp
src/mspell/specified-summon.cpp
src/object-activation/activation-bolt-ball.cpp
src/player/player-status.cpp
src/realm/realm-crusade.cpp
src/room/vault-builder.cpp
src/spell-kind/spells-lite.cpp
src/spell-kind/spells-neighbor.cpp
src/wizard/wizard-spells.cpp

(#4813 の件はありますが、これとこの次のPRはしばらく前に作って順繰りにレビューしてもらっていたものなので取り敢えず出すだけ出しておきます)
ざっくり検証ですが、ダンジョンをdevelopとこのブランチでデバッグ生成したところ、同じモンスター配置になりました
ご確認下さい
たった1コミットでえらいことになっていますが分割は難しいです (floor\_ptr → floor はコミットを分ける余地もあったか……)

scatter() の引数と戻り値をPos2D に差し替えた

---

src/room/rooms-vault.cpp

部屋のサイズのxとyを取り違えているため配列範囲外アクセスが発生しているのが原因。正しく修正する。
e99c103972da3cae5dc742de114527ae5035ebad でのエンバグの修正なのでIssueなし。

[Fix] ランダムVault生成でクラッシュ

---

src/autopick/autopick-editor-command.cpp
src/autopick/autopick-reader-writer.cpp
src/autopick/autopick-reader-writer.h
src/autopick/autopick-registry.cpp
src/cmd-io/cmd-autopick.cpp
src/core/show-file.cpp
src/util/angband-files.cpp
src/util/angband-files.h

掲題の通りです
angband\_fputs() はこれといってバッファオーバーフロー対策を何もやっていない無意味なラッパー関数感があるので、この際消してしまっても良いように思います
ご意見あればお願いします

自動拾い関係の引数からPlayerType を掃き出した

---

src/room/rooms-maze-vault.cpp
src/room/rooms-vault.cpp
src/room/treasure-deployment.cpp
src/room/treasure-deployment.h
src/util/point-2d.h

https://github.com/hengband/hengband/pull/4819#pullrequestreview-2546018618 のRect2D化です。
厳密にはxとyのイテレーションの優先順位が入れ替わっています（元は for x for y、each_areaの実装は for y for x）が、本質的に問題は無いと思います。
なお、room_info_nomral テーブルをいじって build_type10 が呼ばれまくるようにした状態にしたうえで、一時的に元と同じ順序の優先順位でのイテレーションをする each_area2 を実装してfill_treasureからそちらを呼ぶようにしたものと、変更前のコードで同じセーブファイルから複数回ダンジョンを生成し、毎回同じマップが生成されるのを確認しています。

[Refactor] fill_treasureの引数をRect2D型にする

---

src/monster/monster-util.cpp

過去のバージョンにあった引数「restrict\_to\_dungeon」を削除する時に全部true と見なしてしまったようです
消した箇所はfalse だったらスキップする箇所です
ご確認下さい

日付変更時に日替わり賞金首が確定できない不具合を修正した

---

src/floor/floor-streams.cpp
src/system/dungeon/dungeon-definition.cpp
src/system/dungeon/dungeon-definition.h

単なるshort型のグローバル変数IDより大分可読性が上がったかと思います
ご確認下さい
なお、distance() の引数がXとYで逆ですが、これを変えると川生成ルーチンが全体的に変わるので一旦そのままにしてあります
関数の中身で異常な座標は生成されないような処理ですが、変更しても問題なければその旨コメント頂ければ助かります
(ゲーム内で川が生成される確率そのものは変わらず、形が変わるだけ)

川生成ルーチン周りをTerrainTag を使って改善した

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/birth/character-builder.cpp
src/cmd-io/cmd-autopick.cpp
src/cmd-visual/cmd-draw.cpp
src/core/game-closer.cpp
src/core/game-play.cpp
src/dungeon/quest.cpp
src/knowledge/knowledge-self.cpp
src/load/extra-loader.cpp
src/load/load.cpp
src/monster-floor/monster-death.cpp
src/save/player-writer.cpp
src/save/save.cpp
src/util/elapsed-time.cpp
src/util/elapsed-time.h
src/window/display-sub-windows.cpp
src/world/world-movement-processor.cpp
src/world/world.cpp
src/world/world.h

現在プレイ時間を生の整数型で管理しているが、新たにElapsedTimeクラスを作成してこれを使用して管理するようにする。
Resolves #4860 
std::chrono::steady_clock を使用しているので、少なくとも「◯◯年問題」系にはひっかからなくなったはず。セーブファイル上に保存するプレイ時間が符号なし32bit整数なので、合計68年間変愚蛮怒を遊ぶとオーバーフローする問題は依然としてある。
自動拾いエディタを起動中はプレイ時間が進まなくなるのは仕様であるが、#3606 の不具合はサブウィンドウ描画のためにプレイ時間更新処理が行われることが原因と思われる。
ElapsedTimeクラスに pause() / unpause() を実装して自動拾いエディタ起動中は確実にプレイ時間の進行をストップするようにしたので、この不具合も修正されたはず。

[Refactor] プレイ時間をElapsedTimeクラスで管理する

---

src/monster-race/monster-race-hook.cpp
src/monster-race/monster-race-hook.h
src/monster/monster-util.cpp
src/system/monrace/monrace-definition.cpp
src/system/monrace/monrace-definition.h
src/system/monrace/monrace-list.cpp
src/system/monrace/monrace-list.h

この次はグローバル変数の読み書きが発生する極悪ゾーンです
それ以外は全て繰り込み完了しました
ご確認下さい
(次かその次でようやくmonraces\_info の完全な撲滅が達成できる予定)

Nest 関係のモンスター生成フィルタをMonraceDefinition のオブジェクトメソッドに繰り込んだ

---

src/effect/effect-processor.cpp
src/monster-floor/monster-direction.cpp
src/mspell/mspell-judgement.cpp
src/mspell/mspell-lite.cpp
src/spell-realm/spells-crusade.cpp
src/spell/range-calc.cpp
src/spell/range-calc.h

Resolves #4868
los() と同様Pos2D型の引数を使用したシグネチャに変更し、それに伴い呼び出し箇所を修正する。
ちなみに in_disintegration_range() は los() と !cave_los_bold か cave_stop_disintegration のどちらを呼ぶか以外にロジックに違いがないコピペコードのようである。

[Refactor] in_disintegration_range()のシグネチャを変更

---

hengband.spec

- hengband.specのバージョンを3.0.1.25に更新
- 同バージョンのrpmをCoprにて配布開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/
- rpm内のライセンス関連ファイルとしてTHIRD-PARTY-NOTICES.txtを追加
- rpm内のドキュメントファイルとしてautopick.txtおよびautopick_eng.txtを追加
- rpmの説明文に補足を追加

Update hengband.spec and others

---

src/autopick/autopick-drawer.cpp
src/autopick/autopick-editor-command.cpp
src/autopick/autopick-editor-util.cpp
src/autopick/autopick-entry.cpp
src/autopick/autopick-entry.h
src/autopick/autopick-finder.cpp
src/autopick/autopick-finder.h
src/autopick/autopick-inserter-killer.cpp
src/autopick/autopick-reader-writer.cpp
src/autopick/autopick-reader-writer.h
src/autopick/autopick-registry.cpp
src/autopick/autopick-util.cpp
src/autopick/autopick-util.h
src/cmd-io/cmd-autopick.cpp
src/knowledge/knowledge-autopick.cpp

※ ドラフトにしておきます。他のPRレビューを優先して下さい
最初のコミットで既にバグっています
具体的には自動拾いエディタを開いてもサンプル設定以降が表示されません
他にも複数箇所怪しい動きをしている箇所があるかもしれません
ステップ実行したところ、以下のコード (cmd-autopick.cpp)までは正常に読み込めているようです
お手すきのタイミングで確認頂けると助かります
```cpp
tb->lines_list = read_pickpref_text_lines(player_ptr->base_name, &tb->filename_mode);
```

自動拾い関係のconcptr をstring に変えた

---

src/autopick/autopick-drawer.cpp

f3051295 でのエンバグ。msg_ptrの内容を表示すべきところで*msgを表示しているためおかしな表示となる。
せっかくなのでstring_view型を使用して表示内容を決定するよう修正する。

[Fix] 自動拾いエディタの横スクロールの挙動がおかしい

---

src/info-reader/artifact-reader.cpp
src/monster/monster-util.cpp
src/object-enchant/object-ego.h
src/system/artifact-type-definition.cpp
src/system/artifact-type-definition.h
src/system/baseitem/baseitem-definition.h
src/system/monrace/monrace-definition.h

Resolves #4686 
ムーブコンストラクタだけは初期化の都合上必要なので残しています。（std::mapで持っている場合ムーブコンストラクタも削除できなくはないが、初期化のコードをかなりいじらないといけないので面倒）

[Refactor] コピーされるべきでないクラスのコピーコンストラクタ/コピー代入演算子の削除

---

src/autopick/autopick-util.h
src/cmd-io/cmd-autopick.cpp

自動エディタのカーソルを上下方向に動かした時（スクロールアップ/ダウンやエディタの先頭行・最終行への移動を含む）に、移動前の行より短い行に移動した場合にカーソルの位置も短い行にあわせて移動させる。
またその行から長い行に行った場合に元のカーソルの位置に戻そうとする。
Resolves #4836

[Feature] 自動拾いエディタのカーソル上下の挙動を自然にする

---

src/info-reader/dungeon-reader.cpp
src/system/dungeon/dungeon-definition.cpp
src/system/dungeon/dungeon-definition.h
src/system/dungeon/dungeon-list.cpp

100個の配列に地形IDを展開する方法からProbabilityTableクラスを使用する方法に変更する。
Resolves #4884

[Refactor] 床と壁の確率による選択

---

src/effect/effect-processor.cpp

ブレスの場合: 発射した地点が見えていればいればすべての軌道が見える
ボールの場合: 着弾点が見えていればすべての軌道が見える
Resolves #4874

[Feature] 分解のブレス/ボールの軌道の表示を自然にする

---

src/monster-floor/monster-sweep-grid.cpp
src/monster-floor/monster-sweep-grid.h

元のコード (というべきか設計というべきか第1次リファクタリングのミスというべきか)がぐちゃぐちゃなのであまり自信がありませんが論理的には合っているように思います
引数/戻り値をPos2D に変えてポインタ引数がなくなったらもう設計を見直すのが良いかと思います
ご確認下さい

sweep_ranged_attack_grid() の引数をPos2D に変え、戻り値をoptional<Pos2D> に変えた

---

src/window/main-window-left-frame.cpp

マインドフレアは14桁必要だが、メイン画面の種族表示欄は12桁までしか想定されていないので表示がはみ出る。
またマップで上書きされたタイミングで「ア」が消える。
どうしようもないので12桁で切って表示するようにする。
（現在該当するのは日本語版におけるマインドフレアのみと思われる）
FIx #4780

[Fix] メイン画面の種族表示がはみ出る

---

src/cmd-io/cmd-macro.cpp

マクロ設定で空のファイル名を指定すると、path_build内で配列範囲外アクセスを引き起こしクラッシュする。
空のファイル名を指定した場合ESCAPEと同様にキャンセルするようにする。
また、他にもマクロ設定において空の文字列が入力されてはならないと思われる箇所もESCAPEと同様の処理とする。
Resolves #4770

[Fix] マクロ設定で空のファイル名を指定するとクラッシュ

---

src/spell-kind/earthquake.cpp

魔道具術師で地震の杖を強力発動したとき、呼び出し側は半径15を指定しているが、earthquake()側で最大半径12までに制限されているため半径12での発動となっている。
半径15でも問題はないと思われるので最大15までに修正する。
（内部で使用しているmapという二次元配列の変数も15までは対応している）
なお、半径15より大きな数値で呼ばれるのは「自然の脅威」の魔法により発生する地震で、20 + plev / 2 で最大半径45というとんでもない数値になっているがあまりにも大きすぎるし、上述の二次元配列の都合もあるのでひとまず15までとする。
FIx #4510

[Fix] 強力発動地震の杖の半径

---

src/monster-floor/monster-sweep-grid.cpp
src/monster-floor/monster-sweep-grid.h
src/monster/monster-processor-util.cpp
src/monster/monster-processor-util.h

今思えばp\_pos が引数のメソッドは、中でPlayerType::get\_position() を呼べば良いだけの気もしますが、取り敢えずシグネチャを維持する方針で修正しました (意味的なリファクタリングを別途する方針もDiscord で議論している)
必要があれば引数を消す方向でコミットを積みますのでご連絡下さい

MonsterSweepGrid のメソッドからポインタ引数を掃き出した

---

src/realm/realm-hex.cpp

指定したテレポート先の周囲にモンスターが居るかどうかを調べる時、配列の要素番号5をスキップしているが、この番号は方向IDではなく周囲を順番にスキャンするための配列の要素番号にすぎないのでスキップするのは誤りである。
スキップしないように修正する。
Fix #4906

[Fix] 影移動の魔法が特定の位置関係で失敗する

---

src/monster-floor/monster-safety-hiding.cpp
src/monster-floor/monster-safety-hiding.h
src/monster-floor/monster-sweep-grid.cpp
src/monster-floor/monster-sweep-grid.h

モンスターの移動先決定処理のコードが複雑で処理が追いにくくなっているため、処理の構造を大幅にリファクタリングして理解しやすくする。
#4901 の一環。
逃走処理は移動先を一旦決定した後に行うため、まず移動先を決定する処理をリファクタリングしました。
全体の構成としては、
モンスターの移動先決定処理をそれぞれ `MonsterMoveGridDecider` のサブクラスとして定義し、MonsterMoveGridDecidersFactory::create_deciders() によりどの移動先決定処理を採用するかを決め、順に実行して最初に決定したものを採用する、
といった流れになります。
一通りの移動先決定パターンを試した限りではリファクタリング前と同様の挙動をしているように見えます。

[Refactor] モンスターの移動先決定処理

---

src/monster/monster-list.cpp

差分には出ていませんが数行下でmoveしておりMSVCで「const 変数をmove するな」と怒られています
ご確認下さい
(ちなみに、慣例的にoptional はどこもかしこも参照ではなく値を渡していますが問題ないでしょうか？)

polymorph_of_chameleon() の引数で出ていた警告を除去した

---

src/room/rooms-normal.cpp

壁を設置する時座標にy2bを指定すべきところで誤ってy1bを指定しているため、下側の壁が設置されていない。
この際なのでRect2Dクラスを使用して設置するように修正する。
Fix #4495

[Fix] 十字型の部屋の内部の小部屋の下側の壁がない

---

src/action/open-util.cpp
src/action/travel-execution.cpp
src/cmd-action/cmd-travel.cpp
src/effect/effect-feature.cpp
src/floor/floor-events.cpp
src/floor/geometry.h
src/floor/tunnel-generator.cpp
src/grid/feature-generator.cpp
src/grid/grid.cpp
src/mind/mind-warrior.cpp
src/monster-floor/monster-move.cpp
src/monster-floor/monster-sweep-grid.cpp
src/monster/monster-list.cpp
src/mutation/mutation-processor.cpp
src/pet/pet-fall-off.cpp
src/player-attack/player-attack.cpp
src/player/player-move.cpp
src/realm/realm-hex.cpp
src/realm/realm-hissatsu.cpp
src/room/cave-filler.cpp
src/room/rooms-builder.cpp
src/room/rooms-special.cpp
src/spell-kind/earthquake.cpp
src/spell-kind/spells-floor.cpp
src/spell-kind/spells-lite.cpp
src/spell-realm/spells-chaos.cpp
src/system/floor/floor-info.cpp
src/target/target-getter.cpp

#4905 の一環
後で ddx / ddy と CCW_DD を使用した処理も組み込む予定ですが、今回の範囲は一旦 ddd / ddx_ddd / ddy_ddd の箇所のみを変更しています。
- 元のループ範囲と、仕様する範囲の対応が合っているか
- [0, 9) → Direction::directions()
- [0, 8) → Direction::directions_8()
- [0, 4) → Direction::directions_4()
- [4, 8) → Direction::directions_diag4()
- [7, 0] → Direction::directions_8_reverse()
- 元のコードで差分に掛け算をしている場合に変更先でベクトルに掛け算するのを忘れていないか
なお、get_monster_crowd_number() は [0, 7) になっていますが明らかに間違いと思われるので [0, 8) としています。

[Refactor] 方向ベクトルとそれを使用する処理

---

src/wizard/wizard-special-process.cpp

装飾品はItemEntity::known = trueだけだとおかしな表示になる。
describe_flavor の mode 引数に OD_STORE を設定すると店舗に並んだ時の表示となり最も適切と思われるのでそのように修正する。
Fix #4942 
装飾品のリストを表示させてみましたが問題なさそうです。

[Fix] 固定アーティファクトのデバッグ生成の名前表示

---

src/system/monrace/monrace-allocation.cpp
src/system/monrace/monrace-list.cpp
src/system/monrace/monrace-list.h

テーブルのソートはMonraceAllocationTable自身が行うべきものなので、MonraceList::get_sorted_monraces() に頼らず自前で処理するようにする。
MonraceList::get_sorted_monnaces() は当該の処理のみでしか使用されて いないため削除する。
これも `MonraceDefinition *r_ptr` を参照に変えるうえで邪魔になってくるところの事前修正。

[Refactor] MonraceAllocationTable::initialize()

---

src/monster/monster-describer.cpp
src/monster/monster-status.cpp

幻覚時にランダム表示されるモンスター名の候補決定処理を MonraceList::search() により行うようにする。
これにより、コード内でnullptrを使用することを避けることができる。
r_ptr を monrace に置き換える作業をどうやろうかと r_ptr を眺めている時に nullptr の使用箇所があったので先に対処しておく。

[Refactor] 幻覚時のランダム表示されるモンスター名の処理

---

src/wizard/wizard-spells.cpp

デバッグコマンドによるモンスター生成 (^An) で ^I を入力するとモンスターのID番号による入力を行えるが、この時 ^I（あるいはTABキー）にマクロを設定しているとマクロの内容が入力されてしまい正常に動作しない。
通常のコマンド入力関数 input_command() ではなく inkey_special() を 使用することで入力したキーそのものを取得するように修正する。
Fix #4945

[Fix] デバッグコマンドのモンスター生成で^Iが効かないことがある

---

src/system/item-entity.cpp
src/system/item-entity.h

エラーレポートの内容が不足しており、例外が発生したことはわかるものの原因の絞り込みがしずらい。
例外が発生したアイテムの種別をもう少し絞り込めるようにするため、例外メッセージにアイテムの詳細情報を付与するようにしておく。

[Feature] 例外メッセージにアイテムの詳細情報付与

---

src/main-x11.cpp

基本ウェイト量の設定が0の時、X11版ではusleep(0)が呼ばれるが、引数が0でもプロセスは一旦スリープ状態に入るので次にタスクスイッチでプロセスが起動されるのを待つことになり、結果的に最小の時分割単位でディレイが発生してしまう。
この問題を回避するため、ウェイト量が0の場合はusleep()自体を呼ばないようにする。
軽微な修正なのでIssueなし。

[Fix] X11版: 基本ウェイト量が0でもスリープしてしまう

---

src/birth/game-play-initializer.cpp
src/floor/wild.cpp
src/system/floor/wilderness-grid.cpp
src/system/floor/wilderness-grid.h
src/wizard/wizard-special-process.cpp

Use initialize_position() during player birth.  Resolves https://github.com/hengband/hengband/issues/4957 .
The interaction with old save files (see use of initialize_position() in load/world-loader.cpp's load_wilderness_info()) has not been tested:  the old code always set the current wilderness position to (48,5), the new code sets it to whatever was remembered after parsing WildernessDefinition.txt.

Remember wilderness starting position; use it in initialize_position()

---

src/blue-magic/blue-magic-ball-bolt.cpp
src/blue-magic/blue-magic-ball-bolt.h
src/blue-magic/blue-magic-breath.cpp
src/blue-magic/blue-magic-breath.h
src/blue-magic/blue-magic-caster.cpp
src/blue-magic/blue-magic-spirit-curse.cpp
src/blue-magic/blue-magic-spirit-curse.h
src/blue-magic/blue-magic-status.cpp
src/blue-magic/blue-magic-util.cpp
src/blue-magic/blue-magic-util.h

#4962 に関連して、方向入力処理を行っている箇所を調べていたところ、青魔法のボール・ボルト・ブレス・精神攻撃の類の処理が強力発動コピペの嵐になっていたので、魔法属性をテーブルにまとめて関数を共通化しました。
これで修正しないといけない get_aim_dir が数十個減らせます（なおまだ300個近くある模様）

[Refactor] 青魔法の処理をまとめる 

---

src/action/open-util.cpp
src/action/open-util.h
src/cmd-action/cmd-open-close.cpp
src/dungeon/dungeon-processor.cpp
src/io/input-key-requester.cpp
src/io/input-key-requester.h
src/mutation/mutation-processor.cpp
src/racial/racial-switcher.cpp
src/realm/realm-hex.cpp
src/realm/realm-hissatsu.cpp
src/system/floor/floor-info.cpp
src/system/floor/floor-info.h
src/system/player-type-definition.cpp
src/system/player-type-definition.h
src/target/target-getter.cpp

#4962 関連作業。
方向入力処理をDirectionに置き換える上で、command_dirを先にDirection型に 対応させておかないと色々面倒なので、`Direction`に型を変更しておく。

[Refactor] command_dirの型をDirectionにする

---

src/action/open-util.cpp
src/action/run-execution.cpp
src/action/travel-execution.cpp
src/mind/mind-warrior.cpp
src/pet/pet-fall-off.cpp
src/player-attack/player-attack.cpp
src/player/player-move.cpp
src/realm/realm-hissatsu.cpp
src/spell-kind/earthquake.cpp
src/spell-realm/spells-chaos.cpp
src/system/player-type-definition.cpp
src/system/player-type-definition.h

PlayerType::get_neighbor()に、Direction型を取るオーバーロードを追加し、 player_type->get_position() + dir.vec(); のパターンをこのオーバーロードで置換する。
すでに（dir が int型(a.k.a DIRECTION)の） `player_type->get_neighbor(dir);` というコードが多量にあるので、Direction型に置き換えた時にいちいち書き換えなくてすむようにするため。

[Refactor] PlayerType::get_neighbor()にDirection型を取るオーバーロードを追加

---

src/cmd-item/cmd-item.cpp
src/core/scores.cpp
src/floor/floor-generator.cpp
src/floor/wild.cpp
src/io/report.cpp
src/knowledge/knowledge-monsters.cpp
src/monster/monster-list.cpp
src/player-info/alignment.cpp
src/player-info/alignment.h
src/player/player-status.cpp
src/player/player-status.h
src/system/player-type-definition.cpp
src/system/player-type-definition.h

少なくともMSVCにおけるlong はint と変わらないのと、明らかに21億/43億を超える見込みがない箇所しかないです (真に64ビット幅が必要な場所はなく、ある種の固定小数点演算の代わりに使っている箇所のみ)
取り敢えず最低限動いているように見えます
ご確認下さい

フォーマット指定子がlong になっている箇所をintまたはfmt::format() に差し替えた

---

src/action/travel-execution.cpp

トラベルコマンドで移動している時、一歩ごとに基本ウェイト量に設定されたディレイがかかるようになっている。
移動経路をじっくり確認できることよりも、無駄に時間がかかるデメリットのほうが大きいと思われるのでディレイを削除する。
Resolves #4976

[Fix] トラベルコマンドで移動中のディレイをなくす

---

src/cmd-action/cmd-mane.cpp

switch case の分岐内でそれぞれ get_aim_dir() で行われているターゲッティング処理を削除し、ターゲッティングが必要な魔法の場合は分岐前にまとめてターゲッティング処理を行うように修正する。
#4962 の関連作業。 `get_aim_dir()` の数を減らしつつコピペコードの削減。

[Refactor] ものまねのターゲッティング処理

---

VisualStudio/Hengband/Hengband.vcxproj

Discord で議論になっていた件です
\<fmt/format.h\> の導入に伴って出た警告ですが、最終的な出処がWindows の標準ライブラリなので手出しできません
詳細はコミットコメントをご確認下さい

リリースビルドの作成に影響のあるコンパイル警告を抑制した (MSVCのみ)

---

src/action/movement-execution.cpp
src/action/run-execution.cpp
src/cmd-action/cmd-move.cpp
src/floor/geometry.h
src/io-dump/dump-util.cpp
src/knowledge/knowledge-monsters.cpp
src/target/target-getter.cpp

- Direction::self() : 自身のマスを示すインスタンスを生成するstaticメンバ関数（Direction(5)の代わりに意図をわかりやすくする。また、下記のtargetting()との区別がつきやすくする）
- Direction::is_axial() : 軸方向（上下左右）を指しているかを返す関数
- Direction::targetting() / is_targetting() : 特定のマスをターゲット中であることを示すインスタンスを生成するstaticメンバ関数と、その状態であるかをテストするメンバ関数
- 不要なコピーコンストラクタ呼び出しの削除
- シンボルエディタで端を超えて移動できてしまう（Directionクラスに置き換えた時のエンバグ）
- ついでに見つけたシンボルエディタでの文字コード表示の不具合

Directionクラスの機能追加と関連する修正

---

src/mutation/mutation-processor.cpp
src/target/target-getter.cpp
src/target/target-getter.h

#4962 の関連作業。
両者の違いは前回と同じターゲットを自動選択するか・繰り返しコマンドの対象となるかの違いだけなのでget_aim_dir()に処理を統合する。

[Refactor] get_aim_dir()にget_hack_dir()を統合

---

src/mspell/monster-power-table.cpp

Fix #4994 
出力する青魔法のテーブルが不足しているため、「メテオストライク」「スターライトアロー」を覚えているとクラッシュする。
テーブルにこれらの項目を追加する。

[Fix] 青魔道士でキャラクタダンプ出力時にクラッシュ

---

src/monster-floor/monster-direction.cpp
src/monster-floor/monster-sweep-grid.cpp
src/monster-floor/monster-sweep-grid.h

Resolves #4992
Apple Clang 15で暗黙のコピーコンストラクタ宣言によりmmの型である`std::span<Direction>`においてDirection型の完全な型が必要となりコンパイル エラーが発生する。
mmをメンバで持たせるのがそもそも違和感があるので、メンバから削除しget_movable_grid()の引数として渡すようにする。
最終的にはモンスターの移動候補クラスのようなものにしたいが、複数の関数に範囲にわたって配列の参照を引き回しているため設計の見直しが必要となりそうなので、とりあえずコンパイルエラーを回避する暫定処置。

[Refactor] MonsterSweepGrid::mmを削除

---

src/action/travel-execution.cpp
src/action/travel-execution.h
src/cmd-action/cmd-travel.cpp
src/target/target-setter.cpp

lookコマンド中に`g`キーを入力することで、そのマスへのトラベルに移行する
機能を実装する。
Resolves #5000 
トラベルの開始確認は不要かなと思ったのでとりあえず無しにしています。

[Feature] lookコマンドから直接トラベルする機能 

---

src/cmd-action/cmd-travel.cpp

d6d25a06 で真偽反転により発生したエンバグを修正する。
ついさっきの #5001 によるエンバグの修正なのでIssueなし。

[Fix] トラベルコマンドが効かない

---

VisualStudio/Hengband/Hengband.vcxproj
VisualStudio/Hengband/Hengband.vcxproj.filters
src/Makefile.am
src/monster-floor/monster-direction.cpp
src/monster-floor/monster-direction.h
src/monster-floor/monster-move.cpp
src/monster-floor/monster-move.h
src/monster-floor/monster-movement-direction-list.cpp
src/monster-floor/monster-movement-direction-list.h
src/monster-floor/monster-sweep-grid.cpp
src/monster-floor/monster-sweep-grid.h
src/monster/monster-processor-util.cpp
src/monster/monster-processor-util.h
src/monster/monster-processor.cpp

Resolves #5004 
MonsterMoveListクラスを実装し、現在生の std::vector<Direction> とその 参照で持ち回っているモンスターの移動方向のリストを、MonsterMoveListクラスで管理するようにする。

[Refactor] モンスターの移動方向のリスト管理

---

src/spell-kind/spells-fetcher.cpp
src/spell-realm/spells-crusade.cpp

エンバグの時期は調べてませんがrowとcolが逆でした
未報告ですが神の怒りも似たような問題を起こすことが分かったので併せて修正済です
ご確認下さい

ターゲット座標のYとXが逆だったのを修正した

---

src/combat/shoot.cpp
src/core/game-play.cpp
src/dungeon/dungeon-processor.cpp
src/floor/geometry.h
src/mind/mind-ninja.cpp
src/monster-floor/monster-remover.cpp
src/monster-floor/monster-sweep-grid.cpp
src/monster/monster-compaction.cpp
src/object-use/throw-execution.cpp
src/specific-object/death-crimson.cpp
src/spell-class/spells-mirror-master.cpp
src/spell-kind/spells-fetcher.cpp
src/spell-kind/spells-launcher.cpp
src/spell-kind/spells-polymorph.cpp
src/spell-kind/spells-teleport.cpp
src/spell-realm/spells-crusade.cpp
src/target/target-checker.cpp
src/target/target-checker.h
src/target/target-getter.cpp
src/target/target-setter.cpp
src/view/display-map.cpp
src/wizard/wizard-spells.cpp

#4993 続き。
DirectionクラスにTargetを持たせるようにし、get_aim_dir() 後の各種処理で方向ではなく特定ターゲットを目標とする時に使用するようにすることで、グローバル変数 target_who/target_row/target_col を参照せずにすむようにしました。
また、グローバル変数 target_who/target_row/target_col は廃止したうえで、前回狙ったターゲットを引き継ぐ処理のために静的変数（前コミットで追加済）を使用するようにします。

Targetクラスを実装し、グローバル変数 target_who/target_row/target_col を廃止して代わりにTargetクラスを使用する その2

---

src/main-gcu.cpp

range-v3にmetaという名前空間があり、range-v3のヘッダのインクルード状況によってはcursesの関数metaと名称が衝突してしまいコンパイルエラーとなるので、curses名前空間にこれらの宣言を入れる。
curses名前空間内で `curses.h` をインクルードし、cursesのAPIに `curses::` を付与しただけなのでコードの内容チェックは不要と思います。
したがって、GCU版でプレイされている @tanguband 氏を勝手ながらレビューアに割り当てさせていただきます。

[Fix] curses.hの内容をcurses名前空間に入れる

---

src/stdafx.h
src/util/enum-range.h
src/util/point-2d.h

#4926 に関連
この修正により、EnumRangeやRectangle2Dをrange-v3の各種APIにわたすことが可能になります。

EnumRangeとRectangle2Dをrangeコンセプトに対応させる

---

src/external-lib/include/fmt/base.h

'{' や '}' を含むSJISの文字が渡されると誤動作を起こすのでその対策として書式のパース中にSJIS文字が現れたら飛ばすようにする。
Resolves #5023

[Fix] {fmt}におけるSJISのダメ文字問題

---

src/action/mutation-execution.cpp
src/cmd-item/cmd-usestaff.cpp
src/melee/melee-switcher.cpp
src/mind/mind-berserker.cpp
src/mind/mind-elementalist.cpp
src/monster-attack/monster-attack-switcher.cpp
src/object-activation/activation-others.cpp
src/player-attack/player-attack.cpp
src/realm/realm-hissatsu.cpp
src/realm/realm-nature.cpp
src/realm/realm-song.cpp
src/spell-kind/blood-curse.cpp
src/spell-kind/earthquake.cpp
src/spell-kind/earthquake.h
src/spell-kind/spells-neighbor.cpp
src/spell-kind/spells-random.cpp
src/spell-realm/spells-trump.cpp
src/spell/spells-summon.cpp

#4846 関連作業。
中心座標をy, x別々でなくPos2D型で受け取る。
また、ほとんどがプレイヤーによる地震なので引数m_idxのデフォルトを0とする。

[Refactor] earthquake()のシグネチャ変更

---

src/spell/range-calc.cpp

Fix #5047
5b4cc60 の変更で引数に pos_breath を渡すべきところで pos_source を渡して いるのが原因。
正しい引数を渡すよう修正する。

[Fix] LOSでブレスがヒットしない

---

src/floor/cave.cpp
src/floor/cave.h
src/monster-floor/monster-generator.cpp
src/monster-floor/special-death-switcher.cpp
src/realm/realm-crusade.cpp
src/system/floor/floor-info.cpp
src/system/floor/floor-info.h

PlayerType::get\_position() をなるべくループの外に出しているのは、ループの中からPlayerType を掃き出すためです (カプセル化しやすくなるはず……)
ご確認下さい

is_cave_empty_bold2() をFloorType::can_generate_monster_at() に繰り込んだ

---

src/core/object-compressor.cpp
src/dungeon/dungeon-processor.cpp
src/effect/effect-item.cpp
src/floor/floor-changer.cpp
src/floor/floor-events.cpp
src/floor/floor-generator.cpp
src/floor/floor-object.cpp
src/floor/floor-object.h
src/floor/floor-util.cpp
src/inventory/player-inventory.cpp
src/inventory/recharge-processor.cpp
src/monster-floor/monster-object.cpp
src/monster-floor/monster-remover.cpp
src/save/floor-writer.cpp
src/save/save.cpp
src/spell-kind/spells-detection.cpp
src/spell-kind/spells-floor.cpp
src/spell-kind/spells-polymorph.cpp
src/system/floor/floor-info.cpp
src/system/floor/floor-info.h

Resolves #5045 
FloorType::o_list を正しく可変長配列として扱うことで、FloorType::o_cntと FloorType::o_maxを廃止する。

[Refactor] FloorType::o_cnt,o_maxを廃止する

---

src/dungeon/quest-completion-checker.cpp
src/floor/cave-generator.cpp
src/floor/floor-events.cpp
src/floor/floor-generator.cpp
src/floor/floor-leaver.cpp
src/floor/floor-object.cpp
src/floor/floor-util.cpp
src/floor/object-allocator.cpp
src/floor/wild.cpp
src/grid/grid.cpp
src/knowledge/knowledge-items.cpp
src/mind/mind-mirror-master.cpp
src/monster-floor/one-monster-placer.cpp
src/save/floor-writer.cpp
src/spell-class/spells-mirror-master.cpp
src/spell-kind/spells-detection.cpp
src/spell-kind/spells-floor.cpp
src/spell-kind/spells-grid.cpp
src/spell-realm/spells-chaos.cpp
src/system/floor/floor-info.cpp
src/system/floor/floor-info.h
src/target/grid-selector.cpp
src/util/point-2d.h
src/wizard/cmd-wizard.cpp
src/world/world-turn-processor.cpp

Resolves #5043
変更行数が多そうに見えるかもしれませんが、y, xの二重ループが一重ループになってネストが減った分インデントが変わっただけの行が多いので、実質的にはそんなに多くはありません。（賢い差分エディタならわかりやすいはず）

[Refactor] フロア全マスのループにFloorType::get_area()を使用する 

---

src/floor/floor-object.cpp

削除リストを降順に処理するようにする。
そうすれば、処理中に残りの削除対象のインデックスが変わることはないので、削除リストの書き換え処理を省略できシンプルになるとともに、計算量のオーダーも O(N^2) から O(NlogN) となる。

[Refactor] delete_items()

---

src/birth/quick-start.cpp
src/mind/mind-elementalist.h
src/system/player-type-definition.h
src/wizard/wizard-special-process.cpp

Fix #5057
元素使いの魔法領域は通常の領域と別扱いなのでデバッグコマンドで領域選択が行われず正しい領域が選択されていない状態のままとなるので魔法を使用するとクラッシュする。
元素使い用の領域選択処理を実装し職業変更時に領域を選択できるようにする。
また領域変更コマンドにも対応する。

[Fix] デバッグコマンドで元素使いに職業を変更して魔法を使用するとクラッシュする

---

src/birth/birth-select-realm.cpp
src/birth/character-builder.cpp
src/birth/quick-start.cpp
src/io/report.cpp
src/load/player-info-loader.cpp
src/mind/mind-elementalist.cpp
src/mind/mind-elementalist.h
src/racial/racial-draconian.cpp
src/save/player-writer.cpp
src/system/player-type-definition.h
src/view/display-player.cpp
src/wizard/wizard-special-process.cpp

PlayerType::element の型をElementRealmTypeにし、element_realmに改名する

---

src/combat/shoot.cpp

Fix #5071 
周辺のリファクタリング時にロジックが変わってしまい、吹き飛ばす時1マスずつ移動させる処理で移動元が固定されてしまっているのが原因。
更新した移動元を使用するように修正する。

[Fix] 烈風弾が1マス分しかモンスターを吹き飛ばさない

---

.github/workflows/pull-request-status-check.yml
configure.ac

https://github.com/hengband/hengband/commit/5efb20507bbe024d1c18ad0af3ee7c5b924229f9 のコミットより[ccache用のキャッシュ生成ワークフロー](https://github.com/hengband/hengband/actions/workflows/create-cache-for-ccache.yml) がエラーで失敗するようになっていたので、その対策を行う。

ccache用キャッシュ生成ワークフロー実行エラーの対策

---

src/monster-floor/monster-sweep-grid.cpp

モンスターの移動ルーチンで単にプレイヤーから離れようとする時の計算式が誤っておりプレイヤーに近づいてしまうようになっている。
ペットコマンドで「少し離れていろ」「離れていろ」を選択した際にもこのルーチンが使用されるので、結果としてこれらの指示を行うとペットが近づいてきてしまう。
ただしい計算式に修正し、プレイヤーから離れようとするようにする。
Fix #5076

[Fix] モンスターの逃走処理

---

src/autopick/autopick.cpp
src/inventory/player-inventory.cpp
src/inventory/player-inventory.h
src/monster-floor/monster-object.cpp

床上アイテムリストをイテレーションしている途中で床上のアイテム削除によりリストから消去されるとイテレータが無効となるためクラッシュする。
range-based forではなく自前でイテレータを走査し、ループ処理の先頭でイテレータを次の要素へ進めておくことでこの問題を回避する。

[Fix] easy_floorが「いいえ」でアイテムを拾うとクラッシュ

---

src/cmd-io/cmd-diary.cpp
src/core/game-play.cpp
src/game-option/play-record-options.cpp
src/game-option/play-record-options.h
src/inventory/player-inventory.cpp
src/spell-kind/spells-perception.cpp
src/store/purchase-order.cpp

プレイ記録に入手したアイテムを記録するためにアイテム名を記憶しておく変数である record_o_name の型を std::string に変更し、record_item_name に改名する。
ちょっとしたリファクタリングなのでIssueはなし。

[Refactor] record_o_name

---

src/util/string-processor.cpp

文字列の前後の空白を除去する関数群 str_trim / str_ltrim / str_rtrim の 処理を、range-v3 を用いてシンプルにする。
gemini-code-assist のプルリクレビュー機能の味見を兼ねる。

[Refactor] str_trim / str_ltrim / str_rtrim

---

src/cmd-item/cmd-throw.cpp
src/object-use/throw-execution.cpp
src/object-use/throw-execution.h

薬を投げて敵に当たらなかった場合に、敵に当たった時の情報を格納しておくポインタにアクセスしてしまいヌルポインタアクセスが発生している。
修正とともに敵に当たった時の情報をObjectThrowHitBodyクラスにまとめて扱うようにする。
Fix #5098

[Fix] 薬を投げた時にクラッシュする

---

src/object-use/read/scroll-read-executor.cpp

Hello!
The previous implementation seemed to short circuit on the first condition of the `if` statement, causing the part after the `or` operator to be ignored. This resulted in `Scrolls of Door/Stair Location` only showing doors, and `Scrolls of Treasure Detection` only showing buried treasure.
Doors and stairs, as well as buried treasure and treasure, should properly show now.
I'm not familiar with C++, so there are probably many better ways to fix these :)

Fixing scrolls of door/stair location and treasure detection

---

src/io-dump/character-dump.cpp

"上位10体のユニーク・モンスター" を囲む二重角括弧の閉じ括弧が欠けているので追加する。
#4990 で誤って削除されてしまった模様。些細な修正なのでIssueはなし。

[Fix] キャラクタダンプの二重角括弧閉じ忘れ

---

src/Makefile.am
src/external-lib/include/tl/expected.hpp
src/external-lib/include/tl/optional.hpp
src/stdafx.h
src/system/monrace/monrace-definition.cpp
src/system/monrace/monrace-definition.h
src/system/monrace/monrace-message.cpp
src/system/monrace/monrace-message.h

Resolve #5094 
使用例として `std::optional<MonsterMessage>` を返す関数の戻り値を、 `tl::optional<const MonsterMessage &>` に変更して、不要なオブジェクトのコピーが発生しないようにする。

tl::optional および tl::expected の導入

---

src/system/monrace/monrace-message.cpp
src/system/monrace/monrace-message.h

- 文字列を受け取る引数の型を std::string_view に変更
- emplaceを真にemplaceするように修正
- mapのキーが見つからない場合にデフォルトコンストラクタでオブジェクトをつくる処理を operator[] を使用することでシンプルにする。

[Refactor] monrace-message.cpp/h

---

src/monster/monster-damage.cpp
src/monster/monster-processor.cpp
src/util/string-processor.cpp
src/util/string-processor.h

Resolves #5130 
使用例として MonraceDefinition::get_message() の結果をmsg_formatで表示している処理をmsg_printでの置き換えるときに str_upcase_first を使用するコミットを追加。

[Feature] `str_upcase_first()` の追加

---

hengband.spec

- hengband.specのバージョンを3.0.1.28に変更
- 同バージョンのrpmをCoprにて配布開始 https://copr.fedorainfracloud.org/coprs/whitehara/hengband/
- hengband-dataパッケージ（実行バイナリ以外のデータファイル一式）が古いまま、新しいhengband,hengband-enパッケージ（実行バイナリ）をインストールでき、結果として起動時にエラーとなる問題を修正。
- 具体的にはデータパッケージとバイナリパッケージが同一バージョンとなるように依存関係を追加した。

Update hengband.spec for 3.0.1.28

---

src/dungeon/quest-completion-checker.cpp
src/floor/floor-object.cpp
src/floor/floor-object.h
src/grid/object-placer.cpp
src/grid/object-placer.h
src/monster-floor/special-death-switcher.cpp
src/room/rooms-special.cpp
src/system/baseitem/baseitem-allocation.cpp
src/system/baseitem/baseitem-allocation.h
src/system/floor/floor-info.cpp
src/system/system-variables.cpp
src/system/system-variables.h

ベースアイテム生成でベースアイテムの種別を制約するための関数を指定するグローバルな関数ポインタ select_baseitem_id_hook を廃止する。
代わりに制約関数は引数で引き渡すようにする。
すべての日本語でコメントしてください。

[Refactor] ベースアイテム生成の制約処理

---

src/dungeon/quest-completion-checker.cpp
src/floor/floor-object.cpp
src/floor/floor-object.h
src/grid/object-placer.cpp
src/monster-floor/monster-death.cpp
src/monster-floor/special-death-switcher.cpp
src/specific-object/chest.cpp
src/spell-kind/spells-floor.cpp
src/spell/spells-object.cpp
src/system/item-entity.cpp
src/system/item-entity.h
src/wizard/wizard-item-modifier.cpp

make_object()のシグネチャを、戻り値として生成の成否・出力引数に生成したアイテムを格納する形から、戻り値に生成したアイテムを保持するoptional型を返す形に変更する。
また、シグネチャ変更によるリファクタリングの副産物として #5115 が修正される。
Resolves #5160 
Fix #5115 
Please all summary and review comments in Japanese.
すべて日本語でコメントしてください。

[Refactor] make_object()のシグネチャ

---

src/monster/monster-util.cpp

カメレオンは変身する時、変身元が善良なら変身先も善良、変身元が邪悪なら変身先も邪悪、変身元が善良でも邪悪でもないなら変身先も善良でも邪悪でもないモンスターのみ選択できる。
しかし、この制限を加えるロジックが 69feb9b で意図せず書き換わってしまったことにより、変身元が善良でも邪悪でもない場合にどのモンスターも選択できなくなってしまっており、結果として元のモンスターのまま、二度と変身しないという不具合が発生している。
元のロジックを復活させ、変身先に善良でも邪悪でもないモンスターを選択できるようにする。
Fixes #5181 
Write all summary and review comments in Japanese.

[Fix] 善良でも邪悪でもないモンスターに変身したカメレオンがその後二度と変身しない

---

.prettierrc.yaml

VSCodeに含まれるprettierのバージョンが古いのが原因で、VSCodeでjsoncファイルを整形するとtrailingCommaが削除されてしまう。
拡張子jsoncのパーサにjson5をを強制的に指定すると古いバージョンにおいてもこの問題を回避できることがわかったので、ワークアラウンドとして導入する。

[Chore] VSCodeのprettier拡張用のワークアラウンド

---

src/floor/floor-object.cpp
src/inventory/floor-item-getter.cpp
src/system/floor/floor-info.h

繰り返しコマンドでアイテムを指定するとアイテム配列の要素番号が記録されるが、アイテムが削除された時に配列の要素の書き換えが起きるためおかしな挙動が発生してしまう。
アイテムが消えた時は繰り返しコマンド内でのアイテム要素番号の繰り返しを禁止するフラグを立て、繰り返しコマンドがアイテム選択で中断するようにする。
Fix #5192 
Write all summary and review comments in Japanese.

[Fix] 繰り返しコマンドで床置きアイテムを壊した時の不具合

---

src/combat/attack-criticality.cpp
src/combat/attack-criticality.h
src/combat/shoot.cpp

強撃武器のクリティカル時の期待値計算において650*650通りのパターンそれぞれについて計算するナイーブな実装となっているため、ここがボトルネックとなりゲームの動作が重くなっている。
期待値計算をパターンの分布に基づき効率化することでゲームが重くならないようにする。
注記：このPR適用前後で強撃武器を装備しているときにキャラクタ情報に表示されるダメージ期待値が変わりますが、割り算の切り捨て誤差が原因であり、今回割り算の回数が減ることでむしろ正確な値に近づいたはずです。
Fix #5209

[Fix] 強撃武器を装備中にゲームが重くなる

---

src/blue-magic/learnt-power-getter.cpp
src/cmd-action/cmd-mane.cpp
src/cmd-action/cmd-pet.cpp
src/cmd-action/cmd-spell.cpp
src/cmd-io/cmd-floor.cpp
src/cmd-item/cmd-magiceat.cpp
src/core/asking-player.cpp
src/core/asking-player.h
src/market/building-monster.cpp
src/mind/mind-archer.cpp
src/mind/mind-elementalist.cpp
src/mind/mind-power-getter.cpp
src/mind/mind-weaponsmith.cpp
src/spell-realm/spells-hex.cpp
src/target/target-getter.cpp

微妙な修正なのでIssueはなし。
馬鹿馬鹿蛮怒で敵の魔法を増やして、選択肢がzまで到達したときに問題を確認。zがキャンセル充てるフラグを指定されたため選択ができなくなっていた。変愚でも将来発生し得る不具合なので予め修正を提案。
ついでに、直後の値が得られたかの判定も `tl::optional` が利用させたことに合わせて修正した。ご確認お願いします。

(Interface)[Fix] zを充てられた青魔法が選択できずキャンセルになる。

---

src/player/player-damage.cpp

ユーザ入力より後に死因をセーブすると、ユーザ入力のタイミングでゲームを終了した場合、死因がデフォルト値の「元気に生きている」になることが分かりました
死んだ瞬間に死因をセーブデータに保存することでこれを回避しました
ついでながら、周辺のコードが意味不明なくらい深いネストだったので修正しました
ステップ実行した感じ、死亡時ロジックは維持されているようです
ご確認下さい

異常な死因に殺されないようにした
