- src/object-use/quaff-execution.c
These are initial attempts at the three messages (one for SV_POTION_WATER, SV_POTION_APPLE_JUICE, and SV_POTION_SLIME_MOLD) that are currently empty in English.
Attempts to resolve #5 .
> Add English translations in src/object-use/quaff-execution.c

- src/perception/identification.c
- Swap position of adverb in description for a poison needle.
- Reword description of decreased light radius to be more idiomatic.
- Use "undead" rather than "undeads" in description of undead summoning curse.
> 3.0.0.0: minor English edits for src/perception

- .github/workflows/buildtest-on-linux.yml
Linux(Ubuntu-20.04)でビルドが通ることを確認するWorkflowを作成した。
このWorkflowは日本語版/英語版ともにエラーなくビルドができる
状態であることを確認する。
GCCのオプションに "-Werror -Wall -Wextra" を与えて、
警告レベル最大で警告をエラーとして扱うようにする。
ただし、現状のコードを鑑みて以下の警告は抑制する。
- format-overflow
sprintfはstrcatなどのバッファサイズを指定しない文字列操作関数が
大量に使用されており、警告をなくすにはすべてsnprintfなどに
修正する必要がある。
- no-switch
アイテム等の種類によるスイッチでdefault句が無い箇所が多い。
enumのすべてが列挙されていない場合defaultが無いと警告が出る。
とりあえず抑制しておく。
- no-sign-compare
符号ありと符号無しで比較している箇所が多すぎて修正が困難。
- no-unused-parameter, no-unused-function
修正や日英切り替えにより出る事があるが、ソースが壊れるわけではないので
ひとまず許可する。
> [feature] #1 Linuxでビルドテストを行うWorkflow

- src/player-info/body-improvement-info.c
- src/player-info/class-ability-info.c
- src/player-info/weapon-effect-info.c
- Match quoted cost for beastmaster's dominate living things ability to that in the Japanese description and the implementation in racial/class-racial-switcher.c.
- For clearer English, replace "greate damages" with "great damage".
- Use terser, and perhaps more idiomatic, descriptions for the easy_spell and heavy_spell effects.
> 3.0.0.0: minor English edits for src/player-info

- src/pet/pet-fall-off.c
- Drop two commas that aren't separating independent clauses.
- Add some indefinite articles to be more idiomatic
> 3.0.0.0: minor English edits for src/pet

- src/player/patron.c
- src/player/player-class.c
- src/player/player-damage.c
- src/player/player-status.c
- src/player/process-death.c
- Use "last words" rather than "last word" to be more idiomatic.
- Correct spelling mistake for "archmage".
- Correct comment introducing English titles for the cavalry class.
- Correct spelling mistake for "magnificent".
- Swap position of "still" so it doesn't split "have" from the main verb.
- Use "happens" with "nothing" for subject/verb agreement.
> 3.0.0.0: minor English edits for src/player

- src/player/player-status.c
clang (at least in version 12) will issue a warning by default for whether a construct like "if ((x == y)) ..." was intended to be "if ((x = y)) ...".  This pull request removes some extra parentheses in src/player/player-status.c to avoid that warning since, in all the affected cases, the intent is to test "if (x == y)".
> Cosmetic: avoid clang's warnings about ((x == y)) versus ((x = y))

- src/autopick/autopick-describer.c
This is one way to try and resolve https://github.com/hengband/hengband/issues/31 .  Another would be to extend each of the static buffers involved by at least one byte (that would be similar to how describe_autopick_jp() handles the problem).  I went with this way to avoid the static writable buffers and to be less fragile if the range allowed for entry->dice or entry->bonus changes.
> Resolve two potential buffer overflows in describe_autopick_en()

- src/room/rooms-vault.c
- Change cheat message for build_bubble_vault(): was "Room Vault", the same as for build_room_vault().
- Change cheat message for build_target_vault(): was "Elemental Vault", the same as for build_elemental_vault().
- Change cheat message for build_type17():  replace "fix" with "fixed" and capitalize each word like the other similar cheat messages.
> 3.0.0.0: minor English edits for src/room

- src/realm/realm-arcane.c
- src/realm/realm-chaos.c
- src/realm/realm-craft.c
- src/realm/realm-crusade.c
- src/realm/realm-death.c
- src/realm/realm-demon.c
- src/realm/realm-hex.c
- src/realm/realm-hissatsu.c
- src/realm/realm-life.c
- src/realm/realm-song.c
- src/realm/realm-trump.c
- Remove extraneous capitalization in failed elemental summoning message.
- For completeness, mention doors in the description of "Trap / Door Destruction".
- Make "Create Golem" failure message closer to the form of the success message rather than similar to the failure messages for typical summoning spells.
- To be more idiomatic, swap position of adverb in description of "Remove Enchantment".
- For clarity, reword description of "Holy Aura".
- Change "damages to" to "reduces" in the description of "Orb of Entropy".
- Mention that a group is possible in the description of "Summon Manes".
- Correct typo ("Nather" rather than "Nether").
- Use "Lava Flow" rather than "The Flow of Lave" for title of demon spell.
- Use "Succubus's Kiss" rather than "Kiss of Succubus" for title of demon …
> 3.0.0.0: minor English edits for src/realm

- src/spell/spells-status.c
- src/spell/spells-summon.c
- Use past tense rather than present for message after changing the life rating.
- Reword message about attempt to fish without any water nearby.
- For summoning messages that use "A group of x appear" use "servants" or "enemies" to match the use of the plural verb with "group".
> 3.0.0.0: minor English edits for src/spell

- .github/workflows/buildtest-on-linux.yml
GitHubホストランナーはマルチコアCPUなので、ビルドテストを
並列ビルドに対応させる。
nprocコマンドでCPUスレッド数が取得できるので、makeコマンドの
-jオプションにnprocコマンドの結果を与えるようにする。
> [update] #1 ビルドテストを並列実行する

- src/target/target-setter.c
#38で実装したtarget_clear()内のverify_panel()が不要だった。
fix_monster_list()内で座標更新処理が行なわれていたため、描写が二重になっていた。
該当の処理を省くことで処理を正常化する。
> [Fix] 視界内のモンスター表示中、center_playerの描写がおかしくなる #66

- src/mind/mind-ninja.c
変わり身の攻撃回避部分が失敗したときテレポートを試みるが、このときのメッセージが
* 成功時「失敗！攻撃を受けてしまった。」
* 失敗時「失敗！逃げられなかった。」
となっており、慣れていないと何が失敗したのかわかりにくい。
そこで、「変わり身失敗！〜」というメッセージに変更する。
> [Fix] 変わり身失敗時のメッセージをわかりやすくした

- src/spell-kind/spells-fetcher.c
- src/spell-kind/spells-genocide.c
- Simplify message for no object at the target location in fetch_item().
- To be more idiomatic, reword English message for genocide failing in an arena.
> 3.0.0.0: minor English edits for src/spell-kind

- src/maid-x11.c
- src/main-x11.c
Fixes #73.
バッファサイズが不十分な場合の例外などまだ課題はありますが、とりあえず元のコードと機能的に同等のまま valgrind 警告が出なくなるようにしました。
> [Fix] X11 ドライバで valgrind 警告が出なくなるようにした

- src/main-x11.c
Fixes #77.
`iconv()` は引数として与えたバッファサイズを残りバッファサイズに書き換える。よって、両者の差分から出力サイズを計算できる。
> [Fix] X11 ドライバで日本語入力時にゴミが入ることがあるのを修正

- src/floor/floor-object.c
- src/inventory/inventory-slot-types.h
魔法書のを選択する時にchoose_objectがNULLを返した場合、
item == INVEN_FORCEなら練気術が選択されたとするアドホックな
実装がなされているが、選択をキャンセルした場合もNULLが
返され、その場合itemは更新されていないので未初期化の変数itemが
たまたまINVEN_FORCEっだった場合にdo_cmd_mind()が呼ばれてしまう。
そもそもinventory_slot_typeにスロット非選択状態の値があるべきなので、
INVEN_NONEを新設して-1を割り当てる。
(enumに-1を割り当てるのはC言語の仕様としてvalid)
choose_object()の最初で、第2引数に参照渡しされた変数をINVEN_NONEで
初期化するようにする。
> [fix] #65 未初期化の変数を参照している

- src/status/bad-status-setter.c
- src/status/body-improvement.c
- src/status/shape-changer.c
- src/status/temporary-resistance.c
- For flavor, change the messages about blinding for androids to be closer to what Google Translate gives for the Japanese messages.  Similarly, use a specialized message for androids when there's no longer any cuts.
- Reword message about fast regeneration lapsing - want to avoid implying that there's three states (fast, normal, and slow) rather than two (fast and normal).
- Modify test for "a" or "an" in race change message to allow case where effect_msg begins with a vowel.  Should have no effect with current code:  all callers to change_race() use either empty strings or strings beginning with consonants for effect_msg.
- Replace "x resistant" with "x-resistant" to indicate the noun and adjective are combined to form and adjective.  Could use "resistant to x" instead, but that's …
> 3.0.0.0: minor English edits for src/status

- src/term/z-term.c
ターミナルのサイズをbyteからTERM_LEN(int)に拡張したのに、
座標を代入する時に(byte)に不要なキャストをしているのが原因。
キャストせずそのまま代入するようにする。
> [fix] 横幅をめちゃくちゃ広くすると、インベントリの表示などが乱れる #86

- src/monster-attack/monster-attack-player.c
Fixes #21.
`check_hit_from_monster_to_player()` が偽を返したときに回避時の処理を行うべきだが、そうなっていなかった。
本修正により、打撃をかわしたときに盾技能が成長するようになる。以前は打撃を食らったときに盾技能が成長していた。
> [Fix] 打撃回避判定のバグ修正

- src/market/bounty.c
- src/monster/monster-list.c
- src/monster/monster-util.c
- src/monster/monster-util.h
#20 の修正です。賞金首選定用に `get_mon_num_prep_bounty()` を設けて対応しました。
モンスター生成時のデバッグ用統計情報ですが、従来のコードでは重みが 0 のものもカ
ウントされていたため、動作確認時にカメレオン1種のみになっているかどうかわかりま
せんでした。そこで、重みが正のもののみカウントするように変更しました。
もし仕様的にまずい点があればご指摘ください。
今のところ本修正によって賞金首選定が失敗することはないと予想しますが、本来
`get_mon_num()` は生成失敗がありうるという仕様なので、bounty.c 側でも一定回数以
上失敗したら何か適当なモンスターを採用する、などの措置をとる方が安全かもしれま
せん。
> [Fix] カメレオン洞に通常モンスターが生成されるのを修正

- src/load/load.c
- src/system/system-variables.h
生成されるスクリーンダンプのサイズ制限を、256KiB→1MiBに拡張する。
また、セーブファイルからスクリーンダンプをロードする時に
スタック領域に1MiBのバッファを積むことはできないので、
ヒープ領域にバッファを用意する。
> [update] 大きなサイズのマップもスコアサーバへ送信できるようにしたい #43

- src/spell-realm/spells-arcane.c
- src/spell-realm/spells-craft.c
- src/spell-realm/spells-crusade.c
- src/spell-realm/spells-hex.c
- src/spell-realm/spells-song.c
- src/spell-realm/spells-trump.c
- Change "light item" to "light" in message about the arcane spell to refuel a torch or lantern.
- Remove extraneous "do" and capitalization in the message for the onset of immunity from a craft spell.
- Fix English messages to select an item with the polish shield spell.
- Reword English message for the lapse of "An Eye for An Eye".
- Move negative from object to verb in the message about no hex spell to stop.
- Use "resume" rather than "restart" for the message about singing again.
- Drop "the" from "Judgement" when referring to the Tarot card.
> 3.0.0.0: minor English edits for src/spell-realm

- src/window/display-sub-windows.c
Linux/UNIX環境のGCU版で、サブウィンドウに視界内のモンスター
一覧を表示していると、毎ターン画面がちらつく。
原因は、視界内のモンスター一覧で最初に画面を全消去するため
term_clear()を呼んでいる事にある。
GCU版では、term_clearにより画面の全消去が入ると、端末全体の
再描画が行われるようになっているので、モンスター一覧のみで
なく画面全体の再描画が行われてしまう。
対応策として、term_clear()による全消去は行わずモンスター一覧を
表示する時に1行ずつterm_eraseで消去してから書くようにする。
これはサブウィンドウの持ち物一覧表示などでも使用している
方法で、先に全消去するよりもパフォーマンスもいいのではないかと
推察する。
> [fix] モンスター一覧を表示すると画面がちらつく#96

- src/core/hp-mp-regenerator.c
- src/core/player-processor.c
- src/monster/monster-status.c
- src/spell-realm/spells-song.c
- src/term/z-util.c
- src/term/z-util.h
Fixes #75.
第1引数をシフトする際に `u32b` にキャストするようにした。
将来的には 64bit 型で演算するようにしたい。
> [Fix] s64b_RSHIFT() の未定義動作を修正

- configure.ac
./configureに --enable-xft と --disable-worldscore の両方の
スイッチを渡すと、XFTの検出ができずエラーとなる。
現象から判断するに、先にlibcurlの検出をしていると
XFTの検出もできる模様。
他のソフトウェアのconfigure.acの例を見て、
PKG_PROG_PKG_CONFIG (pkg-configの検出)を追加すると
--enable-xft と --disable-worldscore の両方を渡しても
正常に検出できるようになった。
正直 configure.ac は複雑すぎてわからないところだらけで
PKG_PROG_PKG_CONFIG の追加でOKになった理由も
よくわからないが、どのみち pkg-config の検出は
あったほうが良いと思われるので追加して修正とする。
> [fix] pkg-config のチェックを追加 #12

- src/main-win.c
コマンドライン等からセーブファイルを起動するときcheck_for_save_file()にて引数を判断している。
ここでグローバル変数savefileが空であることを前提にしてstrcatしていたためパスを正常に指定できなくなっていた。
コマンドライン等からの起動であるとき、INIファイルを無視して指定セーブを開く挙動が正しい。
よってsavefileを上書きするstrcpyを使用するよう変更した。
> [Fix] セーブファイルを指定して起動した時にpath指定がおかしくて起動しない #101

- src/cmd-building/cmd-store.c
Fixes #42.
我が家/博物館の場合、一時的に現在地 (`player_ptr->town_num`) を辺境の地に偽装して処理するが、その偽装を解除する前に `select_floor_music()` していたのが原因。偽装解除後に `select_floor_music()` するように修正。
そもそも `player_ptr->town_num` 自体を書き換える必要があるのかは疑わしい。今後のリファクタ課題。
> [Fix] 我が家/博物館から出た際に辺境の地のBGMが鳴るバグを修正

- src/blue-magic/blue-magic-caster.c
ファイア・ボルトのみコスト消費判定が反転している。
該当箇所を修正。
> [Fix] 青魔導士のファイア・ボルトがMP消費ターン消費なし #115

- src/core/window-redrawer.c
- src/io/input-key-requester.c
- src/window/display-sub-windows.c
- src/window/display-sub-windows.h
マクロ動作完了後、キー入力前のタイミングで必要項目を再描画するようにしました。
全サブウィンドウに対してこの処理を実行するので、視界内のモンスター表示のみを強制描写していた処理が不要になりました。
fix_monster_list()の引数を減らし、never_freshフラグを操作して描写処理を行います。
> [Fix] 床置きアイテム自動破壊時にメッセージウインドウが遅れる #92

- src/view/display-self-info.c
- src/view/display-util.c
- For self information about the demon forms, put "nether" after "breathe" to be more idiomatic and match other messages about breath weapons.
- Replace "Bare hand" with "Barehanded" as character sheet label for fighting without weapons.
> 3.0.0.0: minor English edits for src/view

- lib/help/editor.txt
- lib/pref/pickpref.prf
Make the existing lib/pref/autopick.prf and lib/help/editor.prf consistent with this commit, https://github.com/hengband/hengband/commit/7def7b1376f35c5fa2ccaf393aa72681ef6679ef#diff-927c5529b966f004336ea19da011b8949442e4753146eab1f314ea1b537e533e  , that changed "junks" to "junk" for the autopick key in the source code.
That earlier commit does break backwards compatibility for old autopick preference files that reference the "junks" key.  If that backwards compatibility is desired, then that commit should be reverted back and this pull request should be closed as not being relevant.
> English autopick adjustments for "junks" to "junk" change

- src/cmd-io/cmd-lore.c
- src/knowledge/knowledge-monsters.c
- src/lore/lore-util.c
- src/lore/lore-util.h
- src/lore/monster-lore.c
- src/lore/monster-lore.h
- src/market/building-monster.c
- src/target/target-describer.c
- src/view/display-lore.c
- src/view/display-lore.h
可読性が厳しかったため、enumにして条件を整理した。
通常用、調査時専用、デバッグ専用の3種類のモードがある。
> [Refactor] モンスターの思い出表示のモードをenumに変更

- src/inventory/floor-item-getter.c
コマンド繰り返しでタグ付アイテムを使用する行動を繰り返すとき、個数が0になっても該当アイテムを選択し続けていた。
check_floor_item_tag_inventory()の処理がv2.2.1と異なっていたため、従来の挙動通りになるように再度実装した。
具体的には、コマンド繰り返しでタグ付アイテムの取得に失敗したときに以降の処理を打ち切ってFALSEを返すように変更した。
> [Fix] アイテム選択時にクラッシュ #117

- src/info-reader/race-info-tokens-table.c
- src/info-reader/race-info-tokens-table.h
- src/monster-attack/monster-attack-effect.h
- src/monster-attack/monster-attack-types.c
- src/monster-attack/monster-attack-types.h
Fixes #105.
mbe_info の配列サイズが足りておらず、INERTIA(減速), STUN(朦朧), FLAVOR(フレーバー) に対応する要素がなかったため、これらの効果の打撃を受けると配列外参照が発生していた。
mbe_info の配列サイズを拡張し、上記3効果に対応する要素を追加した。これで配列外参照が起こらなくなっているはず。
要素の内容:
* FLAVOR はただのフレーバーなので (0, GF_NONE) を設定した。
* INERTIA, STUN は、他のデバフ系効果の power が 0~10 程度なのでとりあえず power=5 とした。また、この効果で爆発するモンスターはいないので、とりあえず explode_type は GF_MISSILE とした。
配列サイズ変更忘れの再発を防ぐため、rbm_type, rbe_type にバリアント数を示すバリアント(接頭辞 `NB_`) を追加し、これを配列サイズ計算に用いることとした。これで少なくとも配列外参照はなくなるが、配列内容の変更忘れまでは防げない。今後の課題。
> [Fix] mbe_info の配列外参照を修正

- src/view/display-lore.c
- src/view/display-lore.h
- src/wizard/monster-info-spoiler.c
デバッグ情報の出力が現在のキャラクターの状態に依存していて不安定であった。
将来的にコマンドラインからコールすることも考慮し、依存関係を排除する。
> [Feature] mon-info.txtの出力情報を現在のプレイヤー情報に依存させない

- src/autopick/autopick-matcher.c
- src/flavor/flavor-describer.c
- src/flavor/object-flavor-types.h
- src/main-win.c
- src/object-hook/hook-quest.c
- src/object-hook/hook-quest.h
- src/wizard/artifact-analyzer.c
- src/wizard/cmd-wizard.c
- src/wizard/fixed-artifacts-spoiler.c
- src/wizard/fixed-artifacts-spoiler.h
- src/wizard/items-spoiler.c
- src/wizard/items-spoiler.h
- src/wizard/monster-info-spoiler.c
- src/wizard/monster-info-spoiler.h
- src/wizard/wizard-spoiler.c
- src/wizard/wizard-spoiler.h
exe_output_spoilers()で呼び出されるspoiler file生成関数が現在のplayerの状態に依存している。
この依存関係を解消し、playerの状態に寄らずspoiler fileの出力を一定にした。
必要な部分にdummyのplayer構造体を与える処理、デバッグ出力に不要な処理の排除を行った。
> [Feature] Spoiler File出力関数のplayer_type依存解消

- src/wizard/fixed-artifacts-spoiler.c
make_fake_artifact内でARTIFACT_IDXをbyteにキャストしているため、name1を257で処理するべきところで1になっていた。
該当の行は現在両辺ともにARTIFACT_IDXなのでキャストは不要である。
> [Fix] artifact.txtにガラドリエルのスリングが出力される

- src/autopick/autopick-describer.c
- Simplify handling of subject/verb agreement by having body_str be a plural noun in all cases.  Adjust dependent phrases and possessives to match that.
- To be more idiomatic, replace "have x quality" with "are of x quality".
> 3.0.0: more English adjustments for the autopick describer

- src/save/save.c
Debugセーブのパフォーマンスを改善するため、セーブファイルの容量の大半を占めるメッセージログをcompress_savefile使用時と同じ40行に制限した。
この変更によりsave/log内に自動生成されるセーブファイルには40行を越えるメッセージは保存されなくなる。
通常セーブに関する挙動は変更しない。
> [Feature] Debugセーブのメッセージログを40行に制限

- src/main-win.c
- src/main.c
- src/main/angband-initializer.c
- src/main/angband-initializer.h
現在のゲームデータ初期化関数init_angband()は、ゲーム画面がすでに
存在する事を前提としている。
スポイラーを出力するにはゲームデータの初期化を行う必要があるので、
コマンドラインからスポイラーを出力して終了する機能を実装するにあたり、
ゲーム画面が必須となるのは具合が悪い。
init_angbandの第3引数(仮引数名no_term)にTRUEを渡すことでゲーム画面無しでも
ゲームデータの初期化を行えるようにする。
> [feature] ゲーム画面無しでゲームデータ初期化を行うスイッチ

- src/view/display-lore.c
display_monster_exp()内で経験値の小数点以下を表示する計算部に誤りがあり、表記が正しくなかった。
経験値補正項の*3/2を余りの計算後にかけていたが、経験値量を*3/2してから余りを取るのが正しい。
> [Fix] モンスターの経験値表示に不具合 #155

- src/core/window-redrawer.c
- src/core/window-redrawer.h
例えばサイズを1行まで縮めてから再度拡大すると2行目以降が表示されなくなっていた。
`redraw_window()` で `window_flags` に `PW_MONSTER_LIST` を含めていなかったのが原因なので、そこを修正。
個別のウィンドウフラグの OR をとる方式だと今後ウィンドウフラグを新設したときまた漏れが生じうるので、全ウィンドウフラグの論理和 `PW_ALL` を新設した。
なお、Windows ドライバだと従来のコードでもリサイズ時に再描画が行われていた模様。`term_redraw()` 呼び出しがあるため?
> [Fix] X11 ドライバで視界内モンスターリストウィンドウがリサイズ時に再描画されていなかった

- src/target/grid-selector.c
- src/target/target-preparation.c
- src/target/target-preparation.h
- src/target/target-setter.c
- src/target/target-setter.h
- src/util/sort.c
- src/util/sort.h
- src/window/display-sub-windows.c
- src/window/display-sub-windows.h
※ ブランチ名が間違っていたのでRenameしたら勝手にPRがCloseされたので上げ直し。どうやらブランチ名変更に追従はしてくれないらしい。
サブウィンドウへのモンスター一覧表示にlookの処理を使い回すと副作用が発生するため、専用の処理を作成してそれを使うようにしました。
既存のモンスター一覧表示の仕様は、「画面内に表示されているモンスターの一覧」ですが、これは完全にlookによるターゲッティングの都合（画面外がターゲットされないようにするため）にすぎないと思われるので、新しい処理ではとりあえず感知しているすべてのモンスターの一覧にしました。
したがって、啓蒙などでフロア全体のモンスターが見えているときは、フロア全体のモンスターから一覧が表示されます。この辺の仕様には議論の余地があるかもしれません。
> [feature] モンスター一覧表示用のターゲット準備処理 #159

- src/main-win.c
- src/wizard/wizard-spoiler.c
- src/wizard/wizard-spoiler.h
全スポイラーを出力するoutput_all_spoilers()を実装した。
コマンドラインオプションが--output-spoilersのとき、これをコールしてアプリケーションを終了する。
> [Implement] Windows環境で--output-spoilersオプションの実装

- src/window/display-sub-windows.c
> [Fix] モンスターリストウィンドウが行数不足のとき最終行の表示がおかしいのを修正

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/locale/japanese.c
- src/locale/utf-8.c
- src/locale/utf-8.h
- src/main-x11.c
#178 の対策として、1文字ずつ座標を計算して描画する処理を実装してみました。
今の所体感できるような描画パフォーマンスの低下はなさそうに思います。
X11版という事で @taotao54321 氏にはレビューしていただきたいのでレビューアに割り当てました。
> [fix] X11版でXFTを有効にすると、フォントのサイズによって描画が崩れる #178

- lib/edit/r_info.txt
These changes are to try to improve the English descriptions for the different forms of falmer and chaurus.  At least for my taste, the descriptions for the falmer shadowmaster, greater falmer skulker, greater falmer nightprowler, greater falmer shadowmaster, and greater falmer warmonger are still problematic, but I don't know what to recommend as changes since I don't know the source material.  The greater falmer nightprowler (just the first sentence is an issue; what is "finally dangerous" supposed to mean) and greater falmer shadowmaster (I'm not sure what the second sentence is about; it doesn't seem to match up with something in the creature flags) are likely the easiest to fix.
> English: falmer and chaurus descriptions

- lib/edit/r_info.txt
- Use "medium" rather than "middle" in the names and descriptions to be a bit more idiomatic.
- Prefer infinitives rather than gerunds in the descriptions for the extra large forms
- Fix "a" and "an" to match the word that immediately follows the article.
- Rephrase the description for the small illusion from the 2nd lap.
> English: aqua illusion edits

- src/blue-magic/blue-magic-checker.c
- src/blue-magic/blue-magic-checker.h
- src/effect/effect-player-curse.c
- src/effect/effect-player-resist-hurt.c
- src/effect/effect-player-spirit.c
- src/mspell/mspell-attack.c
- src/mspell/mspell-checker.c
- src/mspell/mspell-dispel.c
- src/mspell/mspell-floor.c
- src/mspell/mspell-learn-checker.c
- src/mspell/mspell-status.c
- src/player/player-damage.c
Fixes #172.
例えばプラズマボルトで朦朧としたのにラーニングが成功したりしていた。
`learn_spell()` があちこちで呼ばれており、判定に一貫性がなくなっていた。
`learn_spell()` の呼び出しを `make_attack_spell()` 内に一本化して修正。
ただし、モンスター特技「暗闇」は特定条件下でライトエリアになる関係上、やむを得ず特技処理内にラーニングも含めることとした。
また、従来のコードで曖昧だった仕様について以下のように定めた:
* ラーニングを行うためには、モンスターが特技を使う前の時点でプレイヤーがモンスターを視認できていなければならない。
* 分身による回避はラーニングの可否に影響しない。
> [Fix] 青魔道師の一貫性のないラーニング判定を修正

- src/monster-floor/one-monster-placer.c
FRIENDLYフラグ持ちのエルフ・ロードがアリーナでも
友好的な状態で出現する。
アリーナで友好的というのはやはりおかしい気が
するのでアリーナではFRIENDLYフラグ持ちでも
友好的な状態で生成しないようにする。
> [fix] アリーナで友好的な敵が出現 #202

- src/monster-race/monster-race-hook.c
- src/util/bit-flags-calculator.h
mon_hook_shallow_water()で浅い水地形に出現するモンスターの判定結果が反転していた。
フラグ判定の可読性のなさはは随所で問題になっているので、マクロtest_bitを定義してこれを使用する。
monster-race-hook.c全体にこれを適用した。
> [Fix] 水辺に出てくる敵の出現率が低下 #197

- src/main.c
Issues #28 に対応。
PR #152 で対応されたコマンドラインからのスポイラー出力機能を、Linux/UNIX環境でも --output-spoilers を与えることで実現する。
また、コマンドラインオプションのヘルプ出力時にプログラム名がangband固定になっているので、プログラム名が表示されるように変更する。
> [feature] UNIX系環境用のスポイラーを出力するオプション

- src/player/player-status.c
- src/util/bit-flags-calculator.h
可読性向上のため、動作変更を伴わない整理を行う。
ついでに、初回定義時に誤っていたreset_bit()マクロの定義を修正。
> [Refactor] player-statusのBIT_FLAGS処理をマクロを用いて表記

- src/cmd-action/cmd-move.c
- src/cmd-action/cmd-pet.c
- src/core/player-processor.c
- src/dungeon/dungeon-processor.c
- src/effect/effect-processor.c
- src/game-option/map-screen-options.c
- src/game-option/map-screen-options.h
- src/game-option/option-types-table.c
- src/game-option/option-types-table.h
- src/io/input-key-requester.c
- src/mind/mind-mirror-master.c
- src/spell-kind/spells-genocide.c
- src/spell-kind/spells-sight.c
- src/term/z-term.c
- src/term/z-term.h
- src/view/display-messages.c
描画過多を解消するためfresh_afterコマンドに手を入れていった結果、旧来のfresh_afterコマンドとはかなり挙動が異なるものに変化していた。
旧来のfresh_afterコマンドとの差分を分離し、新たにfresh_onceコマンドとして独立させる。
このコマンドがONのとき、一度のキー入力に対し描写を一度に制限する。
> [Feature] fresh_afterコマンドの分割

- .github/workflows/publish-spoiler-page.yml
https://hengband.github.io/spoiler/ に
自動生成スポイラーを自動的に生成してアップロードする
GitHub Actions workflow
仕組みとしては、リリース時（具体的にはmasterブランチにコミットがあった時）に、自動生成スポイラー出力機能でスポイラーを生成し、hengband/spoiler リポジトリの docs ディレクトリ(GitHub Pagges公開用ディレクトリ)にそれらのファイルを追加して、gh-pagesブランチにpushします。
あとは GitHub Pages の機能で自動的に Web に公開してくれます。
> [feature] 自動生成スポイラーのサイトをpublishするWorkflow

- src/io/input-key-requester.c
マクロじゃないコマンドが実行されるときに、inkey()のキューの如何に関係なくsave_player()関数でデバグセーブをしていて、その後キューを消されていたので、想定外にinkey()によるキー待ち状態になっていた。
なので、キューの末尾じゃないコマンドを解釈するときは自動セーブしないようにした。
> セーブ直後にキャラクターが移動できない #231

- src/game-option/option-types-table.c
option_typeのo_bitを保存している領域の都合上、o_bitは0～31しか記録できないようである。
そのため、fresh_onceをTRUEでセーブしても次回起動時デフォルトのFALSEになっていた。
今回は空き番号を使用して回避する。
> [Fix] fresh_onceオプションをセーブできない

- src/player/player-status-flags.c
has_icky_wield_weapon()内の判定にて、盾装備が許可されていなかった。
従来の仕様に合わせて修正する。
> [Fix] スペルマスター、プリーストが盾装備時ふさわしくない武器判定される

- src/game-option/game-play-options.c
- src/game-option/game-play-options.h
- src/game-option/option-types-table.c
- src/game-option/option-types-table.h
- src/main-win.c
オプションkeep_subwindowsを新設する。
このオプションが有効なとき、Hengbandがフォーカスを失うときにサブウィンドウを表示する。
> [Implement] アプリを切り替えてもサブウィンドウが消えないオプションが欲しい #14

- src/combat/shoot.c
Fix drawing oddly moving points of monster which is rushed by rushing arrow with many @s because update_monster() reference wrong monster's index.
> [Fix] drawing sniper rushing arrow's moving points #251

- src/load/dungeon-loader.c
Fixes #239.
起動時の `latest_visit_mark` の値が 1 固定だったため、セーブ/ロードを挟むと保存フロアがいっぱいになったときの削除順がおかしくなっていた。
ロード時に全ての保存済みフロアについての `visit_mark` の最大値 + 1 を `latest_visit_mark` の値とすることで解決。
> [Fix] ロード時に latest_visit_mark を復元

- src/term/screen-processor.c
思い出を描画中にASCII文字で端末の右端に到達した場合、
区切りの良い場所から次の行へ移動させるために
遡って半角スペースを探しているが、直前が日本語の
全角文字だった場合にスペースがみつかるまで
大幅に遡ってしまい、改行位置がおかしくなる。
遡った時に半角スペースに加え、全角文字である場合も
探すのを終了するべきだが、全角文字の2バイト目のコードが
SHIFT-JISの場合ASCIIとコードが被っており後ろからの
検索では全角文字の2バイト目の正確な判定ができないので、
行の先頭からASCIIと全角文字を読み分けながら次の行へ
移す位置を探すように修正する。
> [fix] 思い出の改行位置がおかしい #17

- src/main-win.c
常に相対パスにすると、特定のフォルダにセーブファイルを固める運用をしている人が困る。
Hengband.exeの存在するフォルダより下の階層にセーブファイルがあるときのみ、相対パスを指定するよう設定した。
相対パス指定ではGetOpenFileNameが期待通り動いてくれないので、フルパスに展開して渡すようにする。
> [Feature] hengband.iniに刻まれるセーブファイルのpathをexeからの相対pathにして欲しい #181

- src/angband.rc
- src/game-option/game-play-options.c
- src/game-option/game-play-options.h
- src/game-option/option-types-table.c
- src/game-option/option-types-table.h
- src/main-win.c
keep_subwindowsの所作はwindowsのみに影響があるので、ゲームメニューオプションにあるべきではなかった。
オプションからは削除し、メニュー処理として改めて実装する。
ウィンドウズ固有の処理なので、保存領域としてはHengband.INIを使用する。
> [Fix] #247のサブウィンドウ関連オプションをウィンドウズのメニュー処理に移行

- src/player/player-status-flags.c
表示のみ浮遊になっているが、実際に浮遊を付与する処理が漏れていた。
該当箇所を修正。
> [Fix] 魔法の鎧使用時、実際には浮遊していない

- src/main-win.c
snprintfの第二引数はバッファの最大長を指定するべきと指摘があったので修正。
> [Fix] snprintfの第二引数を訂正 #267

- src/wizard/cmd-wizard.c
- src/wizard/wizard-spells.c
- src/wizard/wizard-spells.h
Implement #234.
敵を倒した時の挙動が確認しやすくなるように、敵を一撃で
倒すデバッグコマンドを追加する。
発動は ^A y で、目当ての敵を倒す以外の作用が起きない
ように、GF_MISSILE属性でダメージ100万・半径0の
ボールを放つ。
> [feature] 敵を一撃で倒すデバッグコマンド #234

- src/monster-race/monster-race-hook.c
山と火山に水棲動物が出現していた問題に対応。ダンジョンにマッチした荒野の出現フラグを持たない水棲動物は出現禁止。
> [Fix] Aquatic monsters appear in moutain or volcano dungeons. #51

- src/monster-race/monster-race-hook.c
[Fix] Monsters which have WILD_ONLY and WILD_OCEAN flags sametime can not appear in wild maps. #274
同様の現象がWILD_ONLYとWILD_****の組み合わせでも起こりえたのでひっくるめて解消。
> [Fix] WILD_ONLYとWILD_OCEANを同時に持つと荒野に登場しない #274

- src/floor/floor-leaver.c
レベルテレポートで移動した時に移動元フロアの階段から適当なものを
選んで移動先のフロアにつなげる処理が呼ばれていないため、移動元
フロアの最後に居た位置に戻ってしまうのが原因。
そもそも上述の処理が呼ばれていない原因となっている、フロアIDを
新規に取得する処理が不要だと思われる（後に再度取得されている）
ので、その部分の処理を削除して階段をつなげる処理が必ず
行われるようにする。
> [fix] テレポートレベル巻物で下の階へ移動してから階段を登ると巻物を読んだ場所に出ることがある #192

- src/mspell/element-resistance-checker.c
- src/mspell/high-resistance-checker.c
可読性向上のため、BIT_FLAGS演算をマクロで置換する。
動作は変更しない。
> [Refacotr] resistance-checkerのBIT_FLAGS演算をマクロで置換

- src/main-x11.c
参考資料: https://www.uninformativ.de/blog/postings/2017-04-02/0/POSTING-en.html
コピー対象文字列が空白のみからなる場合にバッファオーバーランしていたので、ついでに修正。
clang-format による整形コミットが含まれるので、レビューの際は個別コミットで見る方が良いと思います。
> [Fix] X11 ドライバで画面コピーに失敗するのを修正 #215

- .editorconfig
新規ファイルを追加する際、エンコーディングなどが統一されないミスが生じていたので、自動で統一されるよう .editorconfig を追加する。
設定は以下の通り:
* エンコーディング: UTF-8-BOM
* ファイル末尾の改行: あり
> ﻿[Add] .editorconfig を追加

- src/view/display-characteristic.c
display_player_flag_info_2()内での初期化処理が漏れていた。
重複コードがこのようなバグの原因であるため、処理の重複を解消する。
> [Fix] 特性フラグ一覧表示の2ページ目がランダムに緑や赤になる #295

- src/player-attack/player-attack.c
攻撃中の武器がimpactフラグを持っているかの判定に誤りがあった。
該当部を修正する。
> [Fix] 地震を起こす武器で地震が起こらない #286

- src/locale/japanese.c
- src/locale/japanese.h
- src/main-gcu.c
- src/main-x11.c
X11ドライバとGCUドライバでそれぞれ独自に行っている
UTF-8とEUC-JP間の変換処理をlocale/japanese.cにまとめ
共通化する。
Linux/UNIX(EUC-JP)環境では utf8_to_sys からも同じく
共通化した処理を使用する。
> [refactor] UTF-8 ↔ EUC-JPの変換処理を共通化

- src/player/player-status-flags.c
- src/player/temporary-resistances.c
表示用のテンポラリフラグ取得関数に、外部実装されているものを可能な限り使用するよう変更した。
二重に実装されている部分を排除する目的。
ついでに発見した、一時的赤外線視力のフラグが適切に反映されていないバグを修正。
> [Refactor] tim_player_flagsから二重実装になっている判定を排除

- src/monster-floor/monster-remover.c
- src/monster/monster-processor.c
詳細な原因は下記を参照:
https://github.com/hengband/hengband/issues/302#issuecomment-786108417
対応策として、召喚元の親モンスターが消滅した場合は、召喚された
子モンスターのparent_m_idxを自分自身のm_idxを指すようにし、
召喚された子モンスターを消す処理でparent_m_idxが自分自身の
m_idxを指している場合も消すようにする。
> [fix] ペットが召喚したペットが消えない #302

- src/combat/shoot.c
- src/knowledge/knowledge-monsters.c
- src/monster-floor/monster-death-util.c
- src/monster-race/monster-race-hook.c
- src/mspell/element-resistance-checker.c
- src/mspell/high-resistance-checker.c
- src/player-attack/player-attack.c
- src/player/permanent-resistances.c
- src/player/player-status.c
- src/player/temporary-resistances.c
- src/util/bit-flags-calculator.h
- src/wizard/monster-info-spoiler.c
複数形への修正 set_bit -> set_bits, reest_bit -> reset_bits
ビットテストマクロの細分化
test_bit -> any_bits (第二引数で指定したいずれかのビットがON)
all_bits (第二引数で指定した全てのビットがON)
none_bits (第二引数で指定した全てのビットがOFF)
以上の導入と、以前に使用していたマクロの置換を行った。
> [Refactor] ビットテスト/ビット操作マクロの再整理案 #283

- Makefile.am
That will let "make dist" or "make distcheck" work correctly on Unix or Macintosh.
> Update top-level Makefile.am for the renaming of readme.txt

- src/knowledge/knowledge-items.c
> Fix: 既知の★一覧でID256以上の★の表示がおかしい #326

- src/monster-floor/monster-summon.c
カオスパトロンの召喚時は summon_specific_who が -1 になっている
にも関わらず配列のインデクスとして使用されているため
配列外アクセスを引き起こしている。
summon_specific_who が -1 の時は配列を参照しないようにする。
> [fix] カオスパトロンの報酬の召喚で配列外アクセス #331

- src/knowledge/knowledge-monsters.c
- src/lore/lore-util.h
https://github.com/hengband/hengband/pull/277 の変更にて、modeをenumに変更するべき場所が不足していた。
該当箇所を修正。
> [Fix] '%'キーの画面表示の設定項目が減っている #335

- src/cmd-action/cmd-move.c
- src/floor/floor-leaver.c
- src/player/player-move.c
地上に戻って帰還するときにキャンセルするのではなく、ダンジョンやクエストから地上に戻ったときに帰還をキャンセルするようにした。
[Feature] Cancel recall when exit from dungeons or quests.
> [Feature] 帰還できるダンジョンがないのに帰還してしまう #284

- readme.md
That way, the output is formatted with one command per line.
> Japanese readme: format Unix shell commands with backticks

- src/wizard/monster-info-spoiler.c
現状のスポイラー自動生成機能で出力される mon-desc.txt は
名前の欄のカラム幅が非常に長く見づらくなっている。
名前の欄のカラム幅を狭くして、1行に表示できないものは
折返し表示して見やすくする。
1行に表示できるのはとりあえず全角で20文字までとする。
英語版については単語の途中で折り返されることがあるが、
もし必要であれば別途対応とする。
> [feature] mon-desc.txt の折返し表示

- .editorconfig
UTF-8 BOM付のファイルを読み込むと、先頭のBOMが処理できなくてエラーになります。
.cと.hだけBOM付で、他はなしにしました。
> [Fix] 設定ファイルがBOM付で保存される #333

- src/cmd-building/cmd-building.c
- src/main-gcu.c
- src/mspell/mspell-attack-util.h
- src/system/h-type.h
- src/term/screen-processor.c
- src/term/z-term.c
すでにC99準拠の書き方が使われている(コードブロックの途中で
変数宣言を行う、for文の中で変数宣言を行う等)ので、
typedef char bool ではなく、C99準拠で正式に採用された bool 型を
定義する <stdbool.h> を導入する。
すでにC99準拠以上でなくてはコンパイルが通らなくなっている
はずだが、一応 `__STDC_VERSION__` をチェックしてC99以上の時のみ
インクルードする。
また、正式な bool 型を導入した事で bool 型をインクリメント/
デクリメントしているコードやbool型でswitchしているコード、
bool型に0を連続で代入しているコードが見つかったので、
合わせて修正する。
> [refactor] 正式なbool型の導入

- lib/edit/a_info.txt
アーティファクト武器を調整。
古い城の報酬にする予定のドン・キホーテとサンブレードを含む。
> アーティファクト装備の能力等を調整 (α9)

- src/cmd-building/cmd-building.c
- src/cmd-building/cmd-store.c
- src/core/game-closer.c
- src/core/game-play.c
- src/core/window-redrawer.c
- src/io/input-key-acceptor.c
- src/player/player-status.c
- src/term/screen-processor.c
- src/world/world.h
真のbool型導入により、character_ickyがTRUEかFALSEの値のみしか
取らなくなったが、実際は整数型として使用されていたため、
描画周りに不具合が発生するようになった。
character_ikcyを元と同様のbyte型に定義しなおし、変数名を
実情に合わせてcharacter_icky_depthに変更する。
> [fix] character_icky の型変更による不具合

- src/mutation/mutation-investor-remover.c
> [Refactor] BIT演算マクロへの置換を進める。mutation-investor-remover.c後半。

- src/birth/inventory-initializer.c
- src/core/game-play.c
魔術師の杖に加えてムチも配備されていたためおかしくなっていた。
スペマスの場合はムチの配備と熟練度はなし。
> [Fix] セクシースペルマスターの初期武器

- src/player-info/class-ability-info.c
魔獣使いの生物支配の真の消費MPが(level+3)/4であることを確認し、自己分析で表示されるメッセージを修正した。
加えて他の職業能力のメッセージも確認と修正を行なった。
・消費なしの表記がブレていた。(消費なし)で統一。
・MPのないクラスの表記を(X HP)で統一。
・魔道具術師の強力発動の説明を追加。
・鍛冶師の目利きの説明を追加。
> [Fix] 自己分析メッセージ中のコスト表示不一致 #388

- src/player-attack/player-attack.c
- src/player/permanent-resistances.c
- src/player/player-status-flags.c
- src/player/player-status-flags.h
- src/player/player-status-resist.c
- src/player/temporary-resistances.c
flag_cause列挙子はBIT_FLAGS演算で使用することを前提としていたが、各処理でBIT_FLAGSへの変換を要求していたので処理漏れが発生する原因となっていた。
あらかじめBIT_FLAGSとして定義しておくとこでこれを改善する。
合わせて、インクリメント処理をしていたplayer-status-resist.c内部の処理を修正する。
> [Refactor] flag_cause列挙子の修正 #287

- src/cmd-item/cmd-equipment.c
- src/inventory/inventory-object.c
- src/store/purchase-order.c
- src/store/sell-order.c
インベントリアイテム増加時にキャラ情報の更新フラグを立てる。
購入時にmsg_formatが更新フラグを投げ捨てるのでその前にhundle_stuff()を配置。
売却時にmsg_formatが更新フラグを投げ捨てるので最後にフラグを立て直す。
装備を外すときに更新フラグを立てる。
> [Fix] 店や家でサブウィンドウのキャラ情報が更新されない #259

- src/lore/combat-types-setter.c
- src/lore/lore-util.h
- src/lore/monster-lore.c
- src/view/display-lore-attacks.c
- src/view/display-lore-attacks.h
手段は、朦朧あり、切傷あり、接触なし、その他で色分け。
効果は、ブレス・呪文の色を参考に色分け。
> [Feature] モンスターの思い出で打撃を手段や効果で色分けする

- src/player/player-status-flags.c
player-status-flags.c内でinventory_slot_typeからflag_causeへの変換を都度行なっていた。
変換処理を行う関数を用意して処理を置換する。
現時点ではinventory_slot_typeとflag_causeの並びが同じなので一括変換もできそうだが、一対一対応を保証しておく方が将来の面倒がなさそうなのでナイーブに列挙しておく。
> [Refactor] BIT演算処理を整理する player-status-flags.c #393

- src/player/player-status-flags.c
- src/player/temporary-resistances.c
get_player_flags()に装備由来でしかフラグが立たないものを実装した。
加えてplayer_flags_brand_*()を実装し、TR_BRAND_*に対応させた。
この修正を使用してtim_player_flags()からTR_BRAND_*例外処理を排除した。
> [Refactor] get_player_flags()を整理

- src/main-win.c
- src/main/sound-of-music.c
main-winでミュートの処理が漏れていたため、音が止まらなかった。
BGM選択の条件が甘く、ダンジョンにいても街の音楽を選択することがあった。
> [Fix] BGM未定義のシチュエーションで街のBGMが鳴る

- src/player/player-status-flags.c
- src/player/player-status-flags.h
- src/player/player-status.c
- src/player/player-status.h
- src/player/temporary-resistances.c
プレイヤーの速度計算をcalc_speed()関数が一括で行なっていたが、これを速度変化の原因毎に分解して処理する。
(ついでにマーフォークが一時的種族変化時に加減速計算を適用したままであった部分を修正)
分解した処理を流用してplayer_flags_speed()を作成し、速度変化の原因をBIT_FLAGで取得可能とする。
これを流用してtim_player_flags()から加速/減速状態の例外処理を除外する。
(ついでに光速移動時の一時フラグがCの画面に表示されていなかったバグを改善する)
> [Refactor] calc_speed()関数を分解・整理し速度増減の由来を取得可能とする

- src/core/player-processor.c
- src/dungeon/dungeon-processor.c
- src/floor/floor-changer.c
- src/floor/floor-save-util.c
- src/floor/floor-save-util.h
- src/monster-floor/one-monster-placer.c
- src/spell-kind/spells-detection.c
プレイヤーの行動処理中に一時的にモンスターにフラグを
設定しておき、プレイヤーの行動後にまとめてモンスターの
処理を行う時に、この処理が必要かどうかを設定する
repair_monstersというグローバル変数のフラグがある。
しかし、このフラグが設定されていない場合に軽減できる
処理は雀の涙程度のものでしかなく、しかも今後同様の
モンスターをフラグを立てておくような処理を追加する
たびに、そのすべての場所でrepair_monstersをTRUEに
設定する必要がある。
はっきり言ってコストにリターンが見合っていないので
repair_monstersを削除する。
> [refactor] repair_monstersフラグの削除

- src/player/player-status.c
二刀流時に呪われて利き手の武器を外すと、利き手に把持せず両手持ちになる状態が発生するが、これに対応した。
> [Fix] 両手持ちの修正計算時に利き手のみを把持対象としていた #407

- src/player/player-status-flags.c
- src/player/player-status.c
- src/player/player-status.h
プレイヤーの隠密計算をcalc_stealth()で一括で行っていたが、これを隠密修正の原因毎に分解する。
分解した処理を流用してplayer_flags_stealth()を作成し、隠密修正の原因をBIT_FLAGSで取得可能とする。
現時点では、Cの画面2に一時的隠密が反映されるようになった。呪術、狂戦士化、隠遁の歌が該当する。
> [Refactor] calc_stealthの分解・整理し隠密修正の成分取得を可能とする

- src/cmd-building/cmd-store.c
- src/market/articles-on-sale.c
- src/market/articles-on-sale.h
- src/market/building-initializer.c
- src/store/purchase-order.c
- src/store/service-checker.c
- src/store/store-util.c
- src/store/store-util.h
- src/store/store.c
- src/store/store.h
[Feature] 店舗の常時陳列商品を設定 #419
store_stock_item_type型を定義して、store_regular_table配列とstore_table配列に利用する。
店舗陳列の更新ループをstore系の関数外で回して何度も商品整理していたので、store_maintenance()内で回す。
常時陳列商品のランダム出現率を調整して、別の商品を追加した。
> 店舗の常時陳列商品を設定

- lib/help/attack.txt
1. Remove the lines about the special symbols differentiating fixed and random artifact names:  those are only present in the Japanese version.
2. Update the footer to reflect that the document was changed for 3.0.0.
> [English documentation] corrections to attack.txt

- src/core/hp-mp-processor.c
判定の真偽が逆。
ただし、この直後にmagic-effect-timeout-reducerで即直るためメッセージ以外影響なし。
src/world/world-turn-processor.c 行225-226
```
process_player_hp_mp(player_ptr);
reduce_magic_effects_timeout(player_ptr);
```
この処理順は前後逆であるべきに思えます。
> [Fix] 毒の沼で耐毒があると毒状態におかされる

- src/term/z-form.c
- src/view/display-lore.c
英語版で経験値表示でクラッシュしていたのを修正。
・z-form.cの書式を整形
・shimiteiさんのformat()に関する64bit対応の修正を適用
・display_monster_exp()の表示等に関する修正
> [Fix] モンスターの思い出の経験値表示でクラッシュ (英語版) 

- src/knowledge/knowledge-inventory.cpp
自動銘刻みの文字の方に合わせた。
自動銘刻み:「閃」「暗」「恐」「麻」「視」「経」「遅」「活」「Si」
知識コマンド:「光」「闇」「怖」「痺」「透」「命」「消」「復」「Se」
> [Fix] 現在の知識コマンドの鑑定済みの装備の耐性のヘッダ #444

- .clang-format
clang-formatが過剰に1行に整形してしまう場面があるので、
そうならないように以下の設定を変更する。
AllowShortFunctionsOnASingleLine: All → Empty
空ブロックの時のみ1行にする。
AlwaysBreakTemplateDeclarations: false → Yes
template 宣言は単独行のほうが見やすいのでそうする。
> [update] clang-formatの設定を更新

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/player-status/player-speed.cpp
- src/player-status/player-speed.h
- src/player-status/player-status-base.cpp
- src/player-status/player-status-base.h
- src/player/player-status-flags.cpp
- src/player/player-status-flags.h
- src/player/player-status.cpp
- src/player/player-status.h
player_typeの各能力値は種族/職業/装備等の多様な要素により修正を受ける。
これらは現在のところ能力毎に混然と処理されていて、しかも実数値とdump用表記の二重実装となっている。
各数値の内部処理をなるべく統一し、画一的に出力するためPlayerStatusBaseクラスを導入する。
これを継承して各能力値の処理クラスを実装し、見通しを良くしたい。
とりあえずは基底クラスと速度計算クラスを導入する。
> [Refactor] PlayerStatusBase、PlayerSpeedクラスの導入

- src/artifact/random-art-generator.cpp
- src/autopick/autopick.cpp
- src/birth/inventory-initializer.cpp
- src/cmd-io/cmd-floor.cpp
- src/cmd-io/cmd-gameoption.cpp
- src/cmd-item/cmd-equipment.cpp
- src/cmd-item/cmd-item.cpp
- src/cmd-item/cmd-throw.cpp
- src/cmd-item/cmd-usestaff.cpp
- src/cmd-item/cmd-zaprod.cpp
- src/cmd-item/cmd-zapwand.cpp
- src/core/game-play.cpp
- src/core/window-redrawer.cpp
- src/core/window-redrawer.h
- src/floor/floor-object.cpp
- src/floor/floor-object.h
- src/inventory/inventory-object.cpp
- src/mind/mind-mindcrafter.cpp
- src/mind/mind-priest.cpp
- src/player/player-move.cpp
- src/spell-kind/spells-enchant.cpp
- src/spell-kind/spells-perception.cpp
- src/spell/spells-object.cpp
- src/status/base-status.cpp
- src/target/target-setter.cpp
- src/term/gameterm.cpp
- src/window/display-sub-windows.cpp
- src/window/display-sub-windows.h
- src/wizard/wizard-item-modifier.cpp
#160のプルリクエストを最新のdevelopに合わせて再実装。
・普段は @ の足元が対象となる。look コマンドやターゲッティング動作中はカーソルのあるマスが対象。
・現在カーソルのある位置の座標とモンスター名/地名が表示される
[既知のバグ等]
・ターゲッティング動作中にサブウィンドウのサイズを変更すると @ の足元表示に切り替わってしまう
　→ターゲッティング状況をグローバルに保持しておく必要があり、やや重い変更となるので将来の対応に任せる
　　ターゲッティング中はメインウィンドウのリサイズも不具合があるので、合わせて変更？
・ダンジョン、クエスト及び一部街の建物の入り口の名称がメインウィンドウと異なる
　→本機能のために名称取得処理を実装または流用するのは、やや重い変更となるので将来の対応に任せる
> [Feature] 足元/床上のアイテム一覧ウィンドウフラグ (from 東方勝手版)

- src/birth/birth-select-class.cpp
- src/birth/birth-select-personality.cpp
- src/birth/birth-select-race.cpp
- src/birth/birth-select-realm.cpp
- src/birth/birth-wizard.cpp
種族、職業、性格を選択時にHD、隠密、赤外線視力も表示する。
オートローラー画面ではそれらの合計値を表示する。
> [Feature] キャラ作成画面に追加の能力値表示 #436

- src/load/dummy-loader.cpp
- src/load/floor-loader.cpp
- src/load/info-loader.cpp
- src/load/load-util.cpp
- src/load/load-util.h
- src/load/load.cpp
- src/save/save.cpp
- src/spell/spells-util.h
- src/system/angband-version.h
セーブファイルのバージョンを本体のバージョンと分離する。
今後はセーブファイルの仕様を更新する時は、
SAVEFILE_VERSIONをインクリメントし、
loading_savefile_version_older_than関数を使用して
通常の読み込み処理と古いセーブファイルの読み込み処理の
分岐を行う。
この仕様で、flag_group導入によるセーブファイルの仕様変更に対応出来ていることを手元で確認しています。
マージされたら、flag_groupのPRもこの方式のものに切り替えます。
> [feature] セーブファイルの仕様バージョンを本体のバージョンと分離する #470

- src/load/item-loader.cpp
- src/load/lore-loader.cpp
追加モンスター種族やアイテムがある状況でセーブして、ないバージョン
のブランチ等に移動したとき、配列が多すぎてロードできないのを改善。
> [Feature] 知識情報配列のロードの改修

- src/target/target-preparation.cpp
- src/target/target-preparation.h
- src/window/display-sub-windows.cpp
- src/window/display-sub-windows.h
pos_listの使用をやめ、std::vectorを使用してモンスターリストを
作成する。
また、リストの内容は位置情報ではなくモンスターのidxにする。
ソートにはstd::sortを使用し、比較関数ang_sort_cmp_importanceは
元来look用のためモンスター以外のものも比較しているので、
モンスターに特化した比較関数を用意して使用する。
> [refactor] モンスター一覧の表示

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/util/flag-group.h
セーブファイルの仕様を変えなくていいところでFlagGroupクラスだけ先に使いたいという要望があったので、FlagGroupクラスの導入コミットだけを分離したPRを出します。
> [feature] FlagGroupクラス

- src/effect/effect-monster.cpp
一部効果のみ許可する仕様だったため、それ以外の効果については効果がない旨をメッセージ表示する
> [Fix] 乗馬した状態で足元をターゲットに魔法棒等を放っても何の効果も発生しない #467

- src/object-enchant/apply-magic-armor.cpp
- src/object-enchant/apply-magic-weapon.cpp
- src/object-enchant/apply-magic.cpp
- src/object-enchant/object-ego.cpp
通常エゴには呪いが付加されるエゴを選出しない(悪魔など)
呪いエゴにはレーティングが0または呪いが付加されるエゴを選出(悪魔など)
#325のようなエゴに対応できるように前準備として。
また、高級品確定ドロップで呪いエゴが落ちるのは序盤厳しいという意見もあるので。
> [Feature] 通常エゴと呪いエゴの選出ルーチンを変更

- src/effect/effect-player-resist-hurt.cpp
- src/flavor/flag-inscriptions-table.cpp
- src/flavor/flag-inscriptions-table.h
- src/flavor/flavor-util.cpp
- src/object-enchant/object-boost.cpp
- src/object/object-value-calc.cpp
- src/perception/identification.cpp
- src/player/permanent-resistances.cpp
- src/player/player-status-flags.cpp
- src/player/player-status-resist.cpp
- src/player/player-status-resist.h
リファクタリングも込み。
時間と水属性は、以下のものにはまだ未対応
・鍛冶師のエッセンス(耐性エッセンス付加画面の改修が必要)
・*鑑定*済みの装備の耐性一覧(画面レイアウトの改修が必要)
・'C'コマンドの耐性一覧(レイアウトの大幅改装が必要)
> [Feature/Fix] 地獄、時間、水属性の追加実装と不具合の修正 #473 #474 #476

- src/util/flag-group.h
Mac App版のビルドでコンパイラにclangを使用すると
FLAG_TYPE_MAXの定義が見つからずエラーになる。
clangではスコープの決定がMSVC/gccより厳密なのかも
しれない。
回避策としてFLAG_TYPE_MAXの定義をFlagGroupクラスの
定義冒頭に移動する。
> [fix] FlagGroupの定数定義をクラス定義の冒頭に移動する

- .github/workflows/publish-spoiler-page.yml
51c0357 で行ったC++17標準のコンパイラ対応チェックマクロが
含まれるautoconf-archiveパッケージの追加を自動更新スポイラー
deploy用Workflowではやっていなかったためバイナリのビルドに
失敗していた。
自動更新スポイラーdeploy用Workflowにもautoconf-archiveを
追加する。
> [add] 自動更新スポイラーdeploy用Workflowにautoconf-archive追加

- src/player-status/player-stealth.cpp
- src/player-status/player-stealth.h
派生クラスでclass_base_value()の名前を間違っていたので正しくoverrideされず、
職業の基礎値が計算から漏れていた。名称を修正して期待される挙動に戻す。
> [Fix] 隠密計算に職業の基礎値が足されていない #515

- src/effect/effect-monster.cpp
おそらくブレスも同様。広がったボール魔法でもメッセージが出ていた。
メッセージを出すGF_XXXを絞った。
足元にビーム等の効果があるべきかという話もあるので、今回はこの対応で。
> [Fix] どのビーム魔法でも足元のペットに効果がない旨が表示される #510

- src/artifact/random-art-characteristics.cpp
- src/maid-x11.cpp
- src/store/rumor.cpp
- src/system/system-variables.cpp
- rumor.cpp:
配列のアドレスのnullチェックをしていて常にtrueになる無意味な
判定になっている。空文字列かどうかのチェックにする。
- random-art-characteristics.cpp:
bool変数でswitchするという独創的な分岐をしている。
普通にif文にする。
- system-variables.cpp:
上のコメントにあるように、使用されていないコピーライト
文字列。コメントアウトしておく。
- random-art-characteristics.cpp:
x1,x2,y1,y2はポインタ経由で更新されている。
#pragma によりこのループでの警告を抑制する。
> [fix/refactor] clangのWarning対策

- src/core/asking-player.cpp
【バグ】 賢者の塔で魔道具を全てのアイテムを再充填しようとすると 50 feet[y/n] と表示される #523
の修正で。
> [Fix] get_check()でauto_more使用時にプロンプト用の文字列を破棄してしまってから一時バッファにコピーしている #523

- src/core/hp-mp-processor.cpp
> [Fix] 毒の沼のダメージ計算式バグを修正

- src/main-win.cpp
高DPI環境での若干ぼやけた表示、メニュー部分やダイアログは特に、をきれいに表示したい。
Windows10（バージョン1809以降）の高DPIスケール設定を適用するときれいな表示になります。
効果としては、Hengband.exeのプロパティを開き互換性タブにある「高DPI設定の変更」で「システム（拡張）」を設定した場合と同等の効果があります。（プロパティで上書きしている場合は、上書き設定が適用される。）
挙動としてはOSにDPIスケーリングをおまかせで、高DPI非対応のこれまでと同じです。表示内容がきれいになるだけ。
Windows10（バージョン1809）より前でも動作するようにしています。非対応の場合は何も設定されません。
> [Feature] Windowsの高DPI環境での表示改善

- src/Makefile.am
- src/main/game-data-initializer.cpp
- src/monster/monster-list.cpp
- src/object-enchant/object-ego.cpp
- src/room/room-generator.cpp
- src/room/rooms-pit-nest.cpp
- src/system/alloc-entry-definition.h
- src/util/probability-table.h
- src/world/world-object.cpp
モンスター/アイテム/ダンジョンの部屋の生成などで、
選択確率に重み付けされた複数の候補のリストを生成して
その中から抽選するという同じような処理があるので
処理を共通化した確率テーブルクラスを導入する。
既存の処理は選択時の探索が線形探索なので計算量が
O(N)だが、確率テーブルクラスでは二分探索をするので
O(log N)ですむ。
但し現状は毎回候補のテーブルを生成しており、
そちらがO(N)なので高速化の効果はほぼ無い。
> [feature] 確率テーブルクラス

- src/info-reader/general-parser.cpp
- src/io-dump/character-dump.cpp
- src/main/angband-headers.h
- src/main/info-initializer.cpp
- src/object-enchant/trg-types.h
アイテムのTRGフラグの付け間違い(1多かった)があったが、環境によって*.rawファイルが更新されず、番号が1ずれたフラグとして認識される不具合を修正。
#527 apply_magicの無限ループに影響。
> [Fix] *.rawの更新がされず齟齬が生じる可能性がある / TRGフラグのクラス化で番号の付け違い

- src/action/activation-execution.cpp
- src/object-activation/activation-switcher.cpp
- src/object-activation/activation-switcher.h
- src/spell/spells-status.cpp
- src/spell/spells-status.h
落とした方の元装備品へのアドレスをポインタを通じて返す。
裸にtimeout設定しなくなり、装備欄の(なし)も同時に解決。
> [Fix] ブロンズ・クロスを発動で脱ぐと裸にtimeoutが設定される #547

- src/Makefile.am
Adjusts a recent change to DEFAULT_INCLUDES in src/Makefile.am so that "./configure --disable-japanese ; make DISTCHECK_CONFIGURE_FLAGS=--disable-japanese distcheck" does not immediately fail because autoconf.h is not found ("make distcheck" tests building in separate directory from the source files).
> [Linux/Unix] allow testing of distribution generation with "make distcheck"

- src/player-status/player-basic-statistics.cpp
- src/player-status/player-basic-statistics.h
- src/player-status/player-charisma.cpp
- src/player-status/player-charisma.h
- src/player-status/player-status-base.cpp
- src/player-status/player-status-base.h
- src/player-status/player-stealth.cpp
- src/player-status/player-stealth.h
- src/player/player-status-flags.cpp
- src/player/player-status.cpp
クラスのメンバ関数をlower_snakeで統一する。
player-status/以下のlowerCamelを使用していたメンバ関数の名称を変更した。
> [Refactor] メンバ関数の命名規則の統一

- src/birth/game-play-initializer.cpp
- src/load/inventory-loader.cpp
キャラクタの作成を途中でやりなおした時、
C_KILLを呼ぶべき箇所で誤ってC_WIPEを呼んでおり、直後に
C_MAKEでポインタを上書きしているため以前に確保した
領域が解放されておらずメモリリークが発生している。
正しくC_KILLを呼ぶようにする。
軽微なのでPRのみ。
ちなみにキャラクタ作成時に最初からを繰り返すことで無限にメモリリークを発生させることができます。
> [fix] キャラクタ作成時のメモリリークの可能性

- src/util/string-processor.cpp
- src/util/string-processor.h
- src/wizard/cmd-wizard.cpp
- src/wizard/wizard-item-modifier.cpp
- src/wizard/wizard-item-modifier.h
Issueなし。
★のIDを探すのが大変なことがあるので、文字列で願えるコマンドを追加。
マッチする例:
・リンギル
・★リンギル
・『リンギル』
・ロング・ソード『リンギル』
・ガラドリエル
・ガラドリエルの
・ガラドリエルの玻璃瓶
・玻璃瓶 (ベースがINSTA_ART)
> [Feature] 願いコマンドをwizardモード用に実装

- src/player-status/player-speed.cpp
- src/window/main-window-stat-poster.cpp
内部加速値は加速しておらず、表示上のみ数値が+10されていた。
探索モード中の内部数値-10を右下表記に反映させないための+10が誤爆していた。
乗馬中の探索モードに減速が適用されていなかったことが原因。
修正点は2つ。
・乗馬中の探索モードも通常時と同様に-10加速とする
・探索モード中は右下の加速表記を-10して実数値をプレイヤーが認識できるようにする。
> [Fix] 乗馬中探索モードに入ると右下表記がおかしくなる #565

- src/autopick/autopick-util.cpp
- src/main/game-data-initializer.cpp
- src/main/info-initializer.cpp
- src/term/z-virt.h
コード修正量が少なくて済むよう、z-virt.h で定義されているメモリ操作系マクロで呼ばれる最終的な実装を修正する。
修正方法は #564 に従う。
但し、全ての構造体の定義で初期値を与えるようにするのは手間がかかるので、SFINAEによりトリビアルコピーが可能かどうかで分岐し、トリビアルコピーが可能であればmemsetでのゼロクリアやmemcpyでのコピーを行う。
したがって、std::vectorやstd::string等、トリビアルコピーが不可能なクラスオブジェクトを持たせない構造体は初期値を与える必要はなく現状のままの定義で使用できる。
とりあえず現時点では既存の構造体の定義はいじっていないので、malloc/freeがnew/deleteになる以外に動作が変わる所はないはず。
> [feature] 各種構造体のPOD型としての扱いをやめる #564

- src/birth/birth-stat.cpp
- src/birth/birth-stat.h
- src/birth/birth-wizard.cpp
> [Fix] キャラクタメイク時の経験値修正に職業の修正が入っていない #554

- src/term/z-virt.h
std::is_trivial_v が false かつ std::is_trivially_copyable_v
が true の型に memset してゼロクリアしようとするとgccが
警告を発するので、memsetでのクリアを行うのは std::is_trivial_v
が true の型に条件を狭める。
POD型の扱いを改めたうえで、いざFlagGroupを入れようとすると、gccが以下の警告を出した。
>./term/z-virt.h:59:35: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct player_type’; use assignment or value-initialization instead [-Werror=class-memaccess]
>   59 |     return static_cast<T *>(memset(p, 0, sizeof(T)));
>      |                             ~~~~~~^~~~~~~~~~~~~~~~~
FlagGroupクラスはtrivially_copyableな型である条件を満たしているので、それを導入したplayer_typeクラスもtrivially_copyableだが、memsetによるゼロクリアが警告となる。
trivially_copyable な型であればmemsetによるゼロクリア可能と認識していたが、 trivial型でないとmemsetによるゼロクリアは無理なのかもしれない。（少なくともGCCに警告を出される。）
memcpyに関しては trivially_copyable …
> [fix] 構造体のゼロクリアの条件

- src/window/main-window-left-frame.cpp
> [Fix] Wizardモードのモンスター闘技場のHP/MP表示 #577

- src/mind/mind-elementalist.cpp
Habuさんの報告より。Issuesなし。
領域をアルファベットキーで選んだ時に選択しきらない。
> [Fix] 元素使いの領域選択でシンボルキーで選択した場合の挙動

- src/cmd-io/cmd-lore.cpp
- src/object-activation/activation-switcher.cpp
- In src/cmd-io/cmd-lore.cpp, change header label for the monster list selected by matching a substring so it is the same as what's used in src/market/building-monster.cpp.
- In src/object-activation/activation-switcher.c, change an adjective to an adverb for the ACT_CURE_MANA_FULL message.  The Japanese activation message uses the same message as the mana ball activation, but the English messages differ (mana ball uses "becomes pale"; this one is "glows palely").
> [English] make two minor changes to messages

- src/cmd-io/macro-util.cpp
- src/io/interpret-pref-file.cpp
> [Fix] キー定義のないマクロ定義を読み込んで誤爆登録する #418

- src/io/input-key-acceptor.cpp
- src/io/input-key-acceptor.h
- src/term/z-term.cpp
- src/term/z-term.h
macro_running()の判定に一部漏れがあった。
判定関数をinput-key-acceptor.cppに移して修正した。
> [Fix] fresh_onceオプション使用時、マクロ使用直後にサブウィンドウが更新されない

- Hengband/Hengband/Hengband.vcxproj
- src/main-win.cpp
- src/main-win/main-win-bg.cpp
- src/main-win/main-win-bg.h
壁紙の選択ダイアログでBMPの他に、PNGとJPEGを読み込めるようにした。
また、効果音、BGMの初期化フラグのスコープをローカル変数にした。
画像の読み込みをGDI+で行うように変更した。
Windows XP以降は標準でGDI+に対応している。
> [Feature] 壁紙の対応画像形式追加 #596

- src/main-win.cpp
- src/main-win/main-win-mci.cpp
- src/main-win/main-win-mci.h
- src/main-win/main-win-music.cpp
- src/main-win/main-win-music.h
MCI_OPENとMCI_PLAYでは渡す構造体が異なるため、適切なものを渡すように修正した。
また、main-win.cppに残っていたBGM（MCI）の処理をmain-win-mci.cpp、main-win-music.cppへ移した。
> [Fix] MCIコマンド処理修正

- Makefile.am
Do that with a dist-hook rule rather then explicitly adding them to EXTRA_DIST to simplify handling the spaces in "x86 Debug" and "x86 Release".
> [Linux/Unix] add the libcurl archive libraries for Windows to the result of "make dist"

- src/view/display-lore.cpp
> [Fix] ナズグル系ではないモンスターの思い出にXX体生きていると表示 #608

- src/perception/object-perception.cpp
アイテムが判明済みかどうかの判定と判明済みフラグを立てる
順番がリファクタリングで入れ替わってしまったのが原因。
順番を正しいものに戻すと同時に、変数名をわかりやすくし、
さらにplayrecodに記録しない条件式が長くて判断しずらいので
条件がわかりやすいように分割する。
> [fix] playrecordに未判明アイテムの識別が記録されない #610

- src/load/load-v1-5-0.cpp
- src/load/monster-loader.cpp
- src/monster-race/race-flags4.h
- src/player-status/player-basic-statistics.cpp
- src/player/player-view.cpp
- src/target/target-preparation.cpp
> [refactor] VSが出力する警告に対処

- src/main-win/main-win-bg.cpp
- src/main-win/main-win-music.cpp
GDI+のヘッダーから出る警告はpragma warningで抑制する。
> [Refactor] main-win系処理のVS警告への対処

- src/mind/mind-elementalist.cpp
ターンも経過していなかったようなのでまとめて修正。
また、消失量が大きすぎるので調整。
> [Fix] 元素使いで魔法を失敗し魔力が氾濫したときにMPが更新されない #623

- src/core/player-processor.cpp
- src/monster/monster-flag-types.h
- src/monster/monster-update.cpp
プレイヤーの移動処理が完了する前にsanity_blastの処理が行われ、
地形の表示が移動前の状態なのでモンスターの位置だけずれて
しまうのが原因。
MFLAGにSANITY_BLASTを新設し、プレイヤーの移動処理中には
フラグを立てるだけにしておき、移動完了後にsanity_blastの
処理を行うようにする。
> [fix] sanity_blast時にモンスターの表示位置がずれる #330

- src/target/grid-selector.cpp
[オリジナルキー]
0番はターゲット決定に割り当てられているので現状移動できない。
店舗は1～9で指定できないのでshift+1～9の指定。
[ローグキー]
店舗は1～9及びshift+1～9で指定可能。
※ 次元の扉などに影響あり
ただ、shift+キーのカーソル移動はオリジナルキーでは使用できないのと、ローグキーでこの時だけ数字キーで移動指定することはないと思われるので、問題ないと思われる。
> [Feature] トラベルコマンド等で、建物(+)と店(0-9)の位置を文字入力で指定できる #627

- src/mspell/mspell-floor.cpp
表示されるボールも弱い光属性で、部屋も光で照らすようにしかなっていなかった。
> [Fix] モンスターがモンスターに対して撃った暗闇が常にライトエリア #631

- src/load/angband-version-comparer.cpp
- src/load/angband-version-comparer.h
- src/load/birth-loader.cpp
- src/load/extra-loader.cpp
- src/load/info-loader.cpp
- src/load/load-v1-5-0.cpp
- src/load/load-zangband.cpp
- src/load/load-zangband.h
- src/load/load.cpp
- src/load/option-loader.cpp
- src/load/player-attack-loader.cpp
- src/load/player-info-loader.cpp
- src/load/quest-loader.cpp
- src/load/store-loader.cpp
- src/load/world-loader.cpp
- src/system/angband-version.h
- src/world/world.h
セーブファイルの読み込みやworld_typeからZAngbandバージョンを廃止。
これに伴って、ZAngbandバージョン2.0.6でセーブされていたかなり初期の変愚蛮怒のセーブデータの互換性はなくなる。
ZAngband2.0.6以前のセーブデータについては、おそらくすでに互換性の保証はなかったと思われる。
セーブファイルや*.rawファイルの冒頭に保存される偽バージョンは残る。
> [Refactor] ZAngbandバージョンの廃止

- src/main/scene-table.h
With clang 12 on macOS and no use of precompiled headers, there were compilation errors with the current version of main/scene-table.h:  implicitly defined template for vector in the declaration of  get_scene_table_iterator().  Including vector got rid of the errors.
> [clang compatibility] include <vector> in main/scene-table.h

- lib/edit/t0000001.txt
> [Fix] ワーグクエストの報酬が報酬時と成功後次クエスト移行時の2回報酬を落としていた

- src/load/monster-loader.cpp
#462のエンバグ
a13のデータを移行するとペットがペットでなくなってしまう。
> [Fix] セーブバージョン1の旧友好/ペットフラグを読んで移行してから新友好/ペットフラグをクリアしている

- src/wizard/items-spoiler.cpp
アイテムのidを格納する配列whoのスコープが狭すぎるため、
最適化が有効だとwhoの内容が不定となるのが原因。
whoをループの外に移動することで解決する。
> [fix] obj-desc.txtの出力がおかしい #657

- src/term/z-virt.h
ポインタを進め忘れているというしょうもないやらかしにより
先頭の要素だけを何度もクリアしており、残りの要素が
クリアされていない。
やはり自前でループを実装するのは悪。プリコンパイルヘッダの
導入によりコンパイル時間が伸びる懸念はなくなったので、
std::fill_nを使用するようにする。
hotfix出したばかりで申し訳ないが、敵がアイテムを拾うとほぼ確実にフリーズするのでhotfix案件かと思います。
> [fix] C_WIPEで先頭の要素しかクリアされていない

- src/game-option/option-types-table.h
Avoids compilation errors when using clang 12 on macOS and the precompiled headers via stdafx.h are not used.
> [Compatibility for without precompiled headers] include <array> in option-types-table.h

- configure.ac
- src/Makefile.am
The option is --disable-pch .  The use cases would be:
- compiling on some platform (not certain if there are any) that does not use gcc/clang's syntax for precompiled headers or does not support precompiled headers at all
- testing that the software builds when not using precompiled headers
- universal builds on macOS (i.e. x86_64 and ARM) using multiple -arch flags since clang doesn't support precompiled headers when multiple -arch flags are present
I don't know if those are sufficient to justify the extra code in configure.ac and src/Makefile.am.
> [Linux/Unix] add configure option to disable use of precompiled headers

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- lib/xtra/sound/sound.cfg
- src/Makefile.am
- src/main-win.cpp
- src/main-win/main-win-cfg-reader.cpp
- src/main-win/main-win-cfg-reader.h
- src/main-win/main-win-file-utils.cpp
- src/main-win/main-win-file-utils.h
- src/main-win/main-win-music.cpp
- src/main-win/main-win-music.h
- src/main-win/main-win-sound.cpp
- src/main-win/main-win-sound.h
- src/main/scene-table.cpp
- src/main/scene-table.h
.cfgの読み取りクラスCfgReaderを作成し、処理を置き換えた。
データ構造を配列からmapに変更し、再生時の対象ファイル取得を簡略化した。
sound.cfgの[Device]項目は、効果音再生には不要なこととBGMの同設定項目と競合するため削除した。
> [Refactor] .cfgファイル読み込み処理のリファクタリング #635

- src/cmd-action/cmd-others.cpp
探索コマンドにおいても、探索モードでは追加の探索処理を実行する。
> [fix] 探索モード中に探索コマンドを実行するとその場に留まるより損をする #680

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/grid/grid.cpp
- src/monster-floor/monster-lite.cpp
- src/player/player-view.cpp
- src/room/cave-filler.cpp
- src/specific-object/torch.cpp
- src/spell-kind/spells-lite.cpp
- src/util/point-2d.h
2次元平面の座標を扱うPoint構造体が複数箇所で定義されている。
DRYの原則に反しているし、今後別の処理で使うことが考えられる
ので、point-2d.h ヘッダに定義をまとめる。
> [Refactor] Point構造体の定義を一箇所にまとめる

- src/birth/game-play-initializer.cpp
- src/flavor/flavor-describer.cpp
何かの要因でk_info[0]の情報が更新された場合にエンバグで不要な情報を表示してしまう((なし)以外は不要)
基本的にエンバグ対策。
> [Fix] 装備してない欄の(なし)の表記が(なし) {未判明}などになる #695

- lib/help/dungeon.hlp
- lib/help/dungeon.txt
That most notably affects the lists of feature symbols and the description of dangerous terrain. Make some minor changes to punctuation, to avoid assuming a male character, and to avoid an incomplete sentence.
> [documentation] align the contents of dungeon.txt with jdungeon.txt

- src/inventory/floor-item-getter.cpp
- src/inventory/item-getter.cpp
タグ文字列を取得できた場合、!*の銘を確認しないでbreakしていた。
> [Fix] アイテム選択時にアルファベットのタグを選択すると!*の確認が無視される #642

- src/inventory/floor-item-getter.cpp
> [Fix] 床上のアイテムを選択する場合にタグがないとクラッシュ

- src/io/store-key-processor.cpp
- src/load/store-loader.cpp
- src/market/building-initializer.cpp
- src/store/store-util.cpp
- src/store/store-util.h
- src/store/store.cpp
- src/store/store.h
**\*注意\* セーブデータバージョンは上がりませんが、店舗が24アイテムを超えて陳列しているセーブデータは過去のバージョンで読み込めない可能性があります**。
-----
店舗スロット最大数を関数で取得するように変更して、店舗の最大スロット数を3ページ(24*3)に増加して物を売るスペースを確保。
できるだけ多くの商品数が入れ替わるように処理を変えた。
> [Feature] 店舗商品入れ替え処理の向上

- src/birth/game-play-initializer.cpp
- src/core/game-play.cpp
- src/core/player-processor.cpp
- src/dungeon/dungeon-processor.cpp
- src/game-option/cheat-options.cpp
- src/game-option/cheat-options.h
- src/game-option/option-types-table.cpp
- src/game-option/option-types-table.h
- src/io/signal-handlers.cpp
- src/load/option-loader.cpp
- src/player/player-damage.cpp
- src/save/info-writer.cpp
実装してみました。実質死を欺くオプションの上位互換みたいになってしまった感はあるかもしれません。＠の生死や行動不能というかなり重大なところいじったことになるので何らかの手落ちがないかよろしくお願いします。
> [Add] 不滅チートオプション実装．　/ Implement cheat_immortal.

- src/flavor/object-flavor.cpp
デバグ、知識コマンドあたりにのみ影響。
人形、像、ボールあたりが対象。
> [Feature] 一部アイテムのベース名表示で#が残らないように変更

- src/effect/effect-monster-charm.cpp
捕まえられないのに弱らせないととも出なかった。
種族の最大HPで捕まえられれば最低保証のHP閾値以下で捕まるように変更。
満たない場合は弱らせないとと連呼する。
> [Fix] モンスターボールがHPの低すぎるモンスターを捕まえられない #731

- src/wizard/wizard-spells.cpp
That prevents a compilation error if not using precompiled headers.
> Include <vector> in wizard-spells.cpp

- src/dungeon/dungeon.cpp
- src/dungeon/dungeon.h
- src/grid/feature.cpp
- src/grid/feature.h
- src/main/info-initializer.cpp
- src/monster-race/monster-race.cpp
- src/monster-race/monster-race.h
- src/object-enchant/object-ego.cpp
- src/object-enchant/object-ego.h
- src/object/object-kind.cpp
- src/object/object-kind.h
- src/player/player-class.cpp
- src/player/player-class.h
- src/player/player-skill.cpp
- src/player/player-skill.h
- src/room/rooms-vault.cpp
- src/room/rooms-vault.h
- src/system/artifact-type-definition.cpp
- src/system/artifact-type-definition.h
new[] による配列領域の確保を std::vector に置き換える。
ひとまず置き換えのみで misc.txt によってサイズを指定する
仕様はそのまま継続。
misc.txt によるサイズ指定を無くすとしたら別途対応する。
> [feature] *_info の std::vector 化

- src/autopick/autopick-entry.cpp
- src/autopick/autopick-matcher.cpp
- src/birth/birth-select-realm.cpp
- src/birth/quick-start.cpp
- src/birth/quick-start.h
- src/io/read-pref-file.cpp
- src/io/report.cpp
- src/knowledge/knowledge-experiences.cpp
- src/knowledge/knowledge-self.cpp
- src/load/player-info-loader.cpp
- src/mind/mind-elementalist.cpp
- src/object-hook/hook-magic.cpp
- src/object/object-info.cpp
- src/player/player-status-flags.cpp
- src/player/player-status.h
- src/racial/racial-draconian.cpp
- src/save/player-writer.cpp
- src/view/display-player.cpp
- src/view/object-describer.cpp
元素使い系統を別プロパティとしてplayer_typeに設置。
Issueの#746に対応。(realm1がREALM_NONEになるのでヒットしなくなる)
> [Fix] 元素使い系統を第一領域と共有したことによる不具合

- src/io/input-key-acceptor.cpp
- src/io/input-key-requester.cpp
start_term_fresh()にて描画再開時にhandle_stuff()を呼んで全描画を更新するように変更した。
start_term_fresh()はinkey()でキー待ちになる度必ずコールされるので描写漏れがなくなることが期待できる。
> [Fix] 【バグ】fresh_onceを入れてマクロでターゲッティングするとモンスターの思い出サブウィンドウが更新されない #742

- src/birth/quick-start.cpp
- src/cmd-visual/cmd-draw.cpp
- src/core/game-play.cpp
- src/player/process-name.cpp
- src/player/process-name.h
#676のエンバグ
リファクタリング込み。
いつの間にか消えていたSAVEFILE_MUTABLEのマクロ変数を削除してkeep_savefileオプションで一本化。
判定のロジック等がわかりにくかったので書き直し。
セーブファイル名及びsavefile_baseは完全新規スタート時またはkeep_savefileオフでスタートした場合に変更される。
> [Fix] savefile_baseが更新されず、一時ファイルとplayrecord.txtのファイル名がおかしい #738

- src/term/z-form.cpp
formatで文字列を生成した時に、桁数制限により2バイト文字の前半で
文字列がターミネートされてしまうのが原因なので、2バイト文字の
前半で文字列が終了している場合はその部分を空白に置き換える。
> [Fix] ダークエルフの種族レイシャルパワーが表示されない #758

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- lib/xtra/music/music.cfg
- src/Makefile.am
- src/core/window-redrawer.cpp
- src/main-win.cpp
- src/main-win/main-win-cfg-reader.cpp
- src/main-win/main-win-cfg-reader.h
- src/main-win/main-win-music.cpp
- src/main-win/main-win-music.h
- src/main/music-definitions-table.cpp
- src/main/music-definitions-table.h
- src/main/scene-table-floor.cpp
- src/main/scene-table-floor.h
- src/main/scene-table-monster.cpp
- src/main/scene-table-monster.h
- src/main/scene-table.cpp
- src/main/scene-table.h
- src/main/sound-of-music.cpp
- src/main/sound-of-music.h
- src/term/z-term.h
- src/window/display-sub-windows.cpp
視界内モンスター表示のリスト先頭モンスターのBGMを再生する。
視界内モンスターを表示しない設定であっても、モンスターBGMが設定されている場合は視界内モンスターリストを取得する。
以下の順にBGMの再生を試みる。条件にマッチしない場合は、通常のBGM再生を試みる。
- あやしい影 ([Basic] shadower)
- モンスターIDのBGM ([Monster] monsterXXXX)
- ユニーク ([Basic] unique)
- 未知のモンスター ([Basic] unk_monster)
- 既知の高レベルモンスター ([Basic] hl_monster)
より上位のモンスターを見かけた場合、そのモンスターをBGM対象に設定する。
対象のモンスターが視界から消えても、一定のターンが経過するまではBGM対象とする。
モンスターBGM設定有無をチェックし、設定がある場合は視界内モンスターリストを取得し再生する。
サブウインドウで視界内モンスターリストを表示している場合はリストを再利用する。
1つの選曲テーブルにモンスターBGMと通常BGMの両方を載せることで、モンスターBGM条件にマッチしない場合には通常BGMに切り替える。
BGM対象モンスターを覚えておくことで対応する。
BGM対象モンスターと視界内モンスターから、最上位のモンスターを新しいBGM対象に設定する。
雰囲気のBGMを認識できる程度には短時間でも再生したい。
通常BGMの選曲処理（select_floor_music）でBGM対象モンスターをリセットし、さらに数秒間通常BGMを優先して再生する。
新しいフロアに移動した時なども通常BGMが優先されるが、仕様ということで。
いつまでも見かけた上位のモンスターBGMが流れ続けるのは避けたい。 …
> [Feature] モンスター遭遇時にBGMを再生する

- src/core/window-redrawer.cpp
#727 のモンスター遭遇BGM対応時のエンバグ。
PW_MONSTER_LISTフラグが立っている場合に処理を行うように修正した。
> [Fix] サブウインドウ更新毎に視界内モンスター表示処理が行われる

- src/birth/birth-select-realm.cpp
> [Fix] プリーストが生命と破邪を選べない

- src/main/scene-table.cpp
「未知の敵遭遇時」＞「ゲーム中断時」のようにモンスターBGMが優先されてしまっていた。
割り込み系BGMが優先されるように修正した。
> [Fix] モンスターBGMが割り込み系BGMより優先されてしまう

- src/effect/effect-monster.cpp
- src/monster/monster-describer.cpp
ひとまず対応してみた。視認できていないモンスターは死ぬまでダメージ状況見えてなくていいと思うのでそこも意図して。
> [Fix] 見えていないモンスターのダメージメッセージが不自然に流れる。 / Unnatural message by damage of unseen monsters.

- src/io/input-key-acceptor.cpp
- src/io/input-key-acceptor.h
- src/io/input-key-requester.cpp
#754 でキー入力待ち時に強制的に再描画(および諸処のゲーム情報の更新)を
行うようになったが、意図しないタイミングで再描画が行われる事により
様々なエンバグが発生している。
これに対処するため、強制的に再描画するかどうかの引数を inkey() に設け、
とりあえずやっても問題ないタイミングと思われる request_command() での
inkey() でのみ強制的な再描画を行うようにする。
> [Fix] 指定した時だけキー入力待ち時の再描画を行う

- src/inventory/floor-item-getter.cpp
- src/inventory/item-getter.cpp
> [FIx] 刻んだ銘タグでアイテムを選ぶとき大文字で警告が出る #786

- src/action/open-close-execution.cpp
- src/floor/floor-changer.cpp
- src/floor/object-allocator.cpp
- src/grid/grid.cpp
- src/grid/grid.h
- src/monster-floor/monster-move.cpp
- src/spell-kind/spells-grid.cpp
- src/spell-realm/spells-chaos.cpp
こういう所からチマチマplayer_type通しを削除していく。
> [Refactor] feat_state()がplayer_typeを必要とせず、floor_typeのみで事足りたので引数掃き出し。

- src/io-dump/dump-util.cpp
- src/knowledge/knowledge-features.cpp
地形等のシンボルエディタで、カーソルが豆腐(127)の位置を超えた時に処理がおかしくなっていた。
座標をcharで管理しているため、負になっていた。
> [Fix] シンボルエディタで右端の移動がおかしい

- lib/edit/k_info.txt
> [Fix] 魔法を防ぐクロークのsvalがクロークと同じだった

- Build-Windows-Release-Package.ps1
- src/main-win.cpp
英語版でも使用されなくなったため、term_data構造体からfont_fileメンバを削除した。
関連して不要になった関数の引数を削除した。
また、Win版のリリースパッケージにlib/xtra/fontを含めないようにした。
> [Refactor] main-win.cppから"lib/xtra/font/*.fon"関連を削除する

- src/view/display-inventory.cpp
- src/window/display-sub-windows.cpp
サブウィンドウのサイズが十分であれば、落ちることはない。
合わせて、サブウィンドウの装備/持ち物一覧で選択時に選択不能のアイテムでシンボルが消えて表示位置がずれるのを修正。
> [Fix] サブウィンドウサイズの高さが足りない場合に装備/持ち物一覧で落ちる #840

- src/inventory/player-inventory.cpp
easy_floor有効時の拾う処理に効果音が含まれていなかったため追加した。
> [Feature] easy_floor有効時にも財宝($)を拾う時にSOUND_SELL効果音を鳴らす

- src/cmd-action/cmd-attack.cpp
GCC バージョン8以前には、初期化リストの型推論時に要素の型に不要にconstを
付けてしまうというバグがあるため、GCC 8以前でコンパイルするとエラーとなる。
これを避けるために初期化リストの型を明示する。
Issue無し。
> [modify] GCCのバグを回避するため初期化リストの型を明示

- lib/edit/k_info.txt
- src/perception/identification.cpp
\*鑑定\*時に邪悪スレイがあると善良スレイの説明を表示し、善良スレイがあるときには出ていなかった。
魔法を防ぐクロークの価格設定がクロークのままだった。
> [Fix] α19新規追加要素の修正(善良スレイ説明文、価格設定) #846

- src/player/player-race.h
That avoids a compiler error when not using precompiled headers.
> [Linux/Unix] Include vector in player-race.h

- src/birth/birth-wizard.cpp
- src/core/hp-mp-processor.cpp
- src/effect/effect-monster-psi.cpp
- src/effect/effect-monster-resist-hurt.cpp
- src/effect/effect-monster-switcher.cpp
- src/effect/effect-player-resist-hurt.cpp
- src/load/angband-version-comparer.cpp
- src/mind/mind-elementalist.cpp
- src/monster-attack/monster-attack-switcher.cpp
- src/monster-floor/monster-summon.cpp
- src/player-info/race-ability-info.cpp
- src/player-status/player-basic-statistics.cpp
- src/player-status/player-charisma.cpp
- src/player-status/player-status-base.cpp
- src/player/player-status-flags.cpp
- src/room/rooms-pit-nest.cpp
- src/spell-kind/spells-detection.cpp
- src/spell-realm/spells-chaos.cpp
- src/spell/spells-status.cpp
- src/store/articles-on-sale.cpp
- src/target/grid-selector.cpp
- src/util/string-processor.cpp
- src/view/display-lore.cpp
- src/view/display-messages.cpp
- src/wizard/cmd-wizard.cpp
多数ミスっててドキュメントに適用されないものが多数あったのでとにかく機械的に置換.
> [Fix] @param と @details の綴りミス置換.

- Build-Windows-Release-Package.ps1
This reverts commit 61ee1520e11f577698a9d9d2d8bf04412e85a73f.
fontフォルダ毎削除されたため、リリースパッケージ作成スクリプト内でfontフォルダを削除する必要がなくなりました。
> Revert "[Refactor] 不要なフォントファイルをリリースパッケージから除外する"

- src/main-win.cpp
データ読み込み後に行わないと街の数等が0になってしまうため、BGMの[Town]や[Quest]等の設定が読み込まれなくなっていた。
> [Fix] 街やクエスト等のデータ読込後にBGM初期化を行うように修正

- src/cmd-action/cmd-racial.cpp
- src/cmd-action/cmd-spell.cpp
- src/cmd-action/cmd-spell.h
- src/mind/mind-elementalist.cpp
- src/racial/class-racial-switcher.cpp
- src/racial/class-racial-switcher.h
- src/racial/mutation-racial-selector.cpp
- src/racial/race-racial-command-setter.cpp
- src/racial/racial-util.cpp
- src/racial/racial-util.h
- src/realm/realm-sorcery.cpp
レイシャル/クラスパワーを選択する画面で説明文を表示できるようにする。
現在の想定では、大文字で選んで確認が出るときに説明文を出るようにしたい。
もしくは、何かキーを押して閲覧モードに切り替える。
それにともなって、レイシャル/クラスパワー画面のインターフェースをできる限り魔法の呪文選択画面に近づける。
今回は超能力系のものに合わせる。(将来的には選択処理を統一化できるとよいかも)
まずは、レイシャルクラスパワー定義と一覧表示/入力の部分を改修したのでドラフトとしてアップする。
> [Feature] レイシャルパワーの説明文を表示できるようにする #625

- src/market/building-quest.cpp
#607のエンバグによりクエストが初期化されていた。
#607実装中は修正箇所がtrue時になぜかうまく動作していなかったが、再度falseにして正常に動くことを確認。コードも確認した。
> [Fix] 宝物庫の報酬がクエスト受注元でメッセージを出すたびに変わる

- src/cmd-item/cmd-quaff.cpp
かつてdo_cmd_quaff()以下にアリーナのチェックを入れた際にエンバグしていた模様。
> [Fix] アリーナで呪術の薬物吸入ができない #882

- src/cmd-action/cmd-racial.cpp
- src/racial/class-racial-switcher.cpp
> [Fix] クラスパワーでtextをinfoに代入していた(鏡使い分)

- src/combat/shoot.cpp
> [Fix] 射撃術の爆発の矢を無傷球中の敵に撃つと爆発のダメージが0 #848

- src/cmd-action/cmd-racial.cpp
always_show_list が yes の時でもレイシャルコマンドで '*'
(もしくは ' ' ) を押した時に一覧表示/非表示が切り替わる
ようにする。
（魔法の一覧表示/非表示切り替えの挙動と合わせる）
https://github.com/hengband/hengband/pull/876#issuecomment-824876140 の件の修正。
Issue無し。
> [fix] レイシャルパワーの一覧表示/非表示の切り替え

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/main-win.cpp
- src/main-win/string-win.h
#896 の中で影響の少ないAPIからワイド文字列版へ移行してみた。
「ベータ:ワールドワイド言語サポートでUnicode UTF-8を使用」にチェックを入れた環境（システムロケールがUTF-8）でもメッセージボックスと「画面をHTMLで保存」は文字化けなく動作している。
> [Feature] MessageBox,GetSaveFileName APIをワイド文字列版へ移行

- src/main-win.cpp
- src/term/z-term.cpp
- src/term/z-term.h
- term_win はコンストラクタで初期化
- 配列には std::vector を使う
- term_win の動的確保領域の保持に std::unique_ptr を使う
#891 を実現するにあたり、現状のコードのままだと term_type/term_win のメモリ動的確保処理が煩わしくなりそうだったので、前段階の作業として z-term.cpp を vector や unique_ptr を使用してリファクタリングしました。
> [Refactor] z-term.cpp をC++の機能で書き換える

- src/knowledge/knowledge-monsters.cpp
既知がいない場合は、シンボルの変更をダミー変数に入れて捨てる。
左のグループに「ユニーク」と出るが、これをどうにかするのは大改修になるので今回は見送り。
> [Fix] 既知のモンスターで1体も既知ではない場合の配列外アクセス

- src/cmd-action/cmd-spell.cpp
- src/cmd-action/cmd-spell.h
- src/io/input-key-processor.cpp
- src/racial/racial-switcher.cpp
do_cmd_cast()に戻り値がないため、連続魔でキャンセルかどうか判定できていなかった。
また、1回目のターゲットを捨てていなかった。
> [Fix] 赤魔導士の連続魔で1回目でキャンセルできない、また2回目できちんとターゲット指定できない #905 #906

- src/main-win/main-win-music.cpp
変数は使いまわしているため、期待しているIDとは異なるかもしれない。
通知メッセージのパラメータの方が信用できる。
> [Fix] 通知メッセージパラメータのデバイスIDをMCIコマンドに使うように修正

- src/system/angband.h
Doxygenのホームに追加されるmainpageをangband.h中心に記述してみました。今後これからのリファクタリングも俯瞰しながら記述していく予定です。
> [Add] Doxygen用のメインページをangband.hに追加．

- src/stdafx.h
- src/term/screen-processor.cpp
- src/term/screen-processor.h
- src/term/z-term.cpp
- src/term/z-term.h
従来はscreen_save()/screen_load()で保存できる画面は1画面のみだったが、
複数の画面遷移を行き来したい場合に1画面のみでは不便なため、
多重に画面を保存できるようにする。
> [Feature] screen_save()/screen_load()で多重に画面を保存する #891

- src/term/z-form.cpp
生い立ちエディタで2バイト文字を"%c%c"で1バイトずつ出力
するという想定外の使用方法がされているため、過去のコミット
7ee574d2c5244b61f8ec13c8d383a865630e00fb で文字化けが
発生するようになっていた。
2文字以上出力の時のみ、2バイト文字の前半で終了した時に
その部分を空白で置き換えるようにする。
#759 によるエンバグ。
> [Fix] 生い立ちエディタの文字化け #946

- src/wizard/wizard-item-modifier.cpp
> [Fix] デバグのインベントリ内全*鑑定*でawareしない #913

- src/birth/history-editor.cpp
- src/term/z-form.cpp
#948 での修正は他に影響が出ているためRevertして、生い立ちエディタ処理の方を修正した。
> [Fix] 生い立ちエディタの文字化け修正

- Hengband/Hengband/Hengband.vcxproj
存在しないmain-win\tile-info.hの記述を削除する。
> [Fix] 存在しないファイルをHengband.vcxprojから削除

- src/main-win.cpp
SetBkColorで設定した背景色での塗りつぶしを行っているため、背景ブラシによる画面クリアを抑制する。
背景ブラシ(hbrBackground)をNULLに設定し、WM_ERASEBKGNDに非0を返すことでBeginPaint時に背景ブラシによるクリアが行われなくなる。
画面のちらつき軽減にもなるらしいが、ダブルバッファリングほどには体感できない。
> [Feature] 不必要な背景ブラシによる塗りつぶしを省略する

- src/wizard/cmd-wizard.cpp
- src/wizard/wizard-item-modifier.cpp
- src/wizard/wizard-item-modifier.h
- src/wizard/wizard-spells.cpp
- src/wizard/wizard-spells.h
アイテム設定メニューを追加
・ドロップ系をその下に移動
・アーティファクトの出現フラグセット/リセット
・発動IDを変更する(固定アーティファクトは変更しても変化しないはず)
必殺コマンドを拡張
・ダメージと属性指定でモンスターに半径0のボールを放つ
・ダメージと属性指定で自分に半径0のボールを放つ(制御できない魔力の奔流)
> [Feature] 各種テスト用にデバグコマンドの拡張α21

- src/view/display-lore.cpp
Issueなし。
デバッグ時に特定のモンスターを呼びたい時に、いちいち種族IDをr_info.txtやdiscordのbotで調べるのが面倒なので、思い出で表示されていれば便利かなと。
> [feature] cheat_knowオン時にモンスターの種族IDを表示する

- Hengband/Hengband/Hengband.vcxproj
#947 の漏れ。
Hengband.vcxprojからmain-win\string-win.hの記述を削除した。
存在しないファイルがHengband.vcxprojに書かれていても特にエラーも警告も出ないようだ。
> [Fix] vcxprojから存在しないファイルの記述を削除する

- src/window/main-window-util.cpp
MMマップ作成ルーチンで横幅の計算が1桁(ないしは2桁)多いため、Term表示バッファの領域外にアクセスしている。
MMマップ作成ルーチンの修正(横幅計算ないしはその後の生成部分)をきちんとするのが正しい対応だが、現象としては上記なので。
> [Fix] 文字2倍幅表示のときにMMマップを表示するとクラッシュ #990

- src/target/target-describer.h
- src/target/target-setter.h
- src/target/target-types.h
That avoids a compiler error when compiling target/target-setter.cpp with Ubuntu 20.04's default g++ and no precompiled headers.  The error was "found ':' in nested-name-specifier, expected '::'" when compiling "enum target_type : uint8_t;", presumably because the compiler didn't recognize uint8_t as something appropriate for setting the size of the enum.
> Include system/h-basic.h in target/target-setter.h

- src/view/display-lore.cpp
元々Wizardモードの時にモンスター種族IDが表示される仕様だった
ので、cheat_knowオプションでのモンスター種族ID表示を追加した
ことで2重に表示されてしまっている。
デバッグ用途としては全モンスターの思い出とその種族IDは同時に
欲しいので、cheat_knowがONの時にも表示する仕様とする。
名前が長いモンスターだと種族IDが確認できない可能性があるので、
表示箇所は従来のWizardモードでの位置である名前の後ろではなく、
行頭への表示を採用する。
> [Fix] cheat_know + Wizardモードで2重にモンスター種族IDが表示

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/main-win.cpp
- src/main-win/commandline-win.cpp
- src/main-win/commandline-win.h
printfデバッグ用にコンソールを出すオプション（--debug-console）を追加する。
コンソールには標準出力が表示される。
システムロケールUTF-8の動作確認が手間なので、デバッガに頼らない手軽な確認方法を追加したい。
> [Feature] Win版にコマンドラインオプション追加（デバッグ用コンソール表示）

- .github/workflows/buildtest-on-linux.yml
普段プリコンパイルヘッダを使用していることで、必要ヘッダのインクルード
忘れによりプリコンパイルヘッダ未使用時にコンパイルエラーが発生するように
なっていることがたまにあるので、clangでのビルドテストではプリコンパイル
ヘッダを使用しないようにする。
> [Feature] clangでのビルドテストではプリコンパイルヘッダを使用しない

- lib/edit/k_info.txt
合わせて魔法を防ぐクロークのアイテムレベルを修正。
前回レビューでobject-desc.txtを出力したにもかかわらず見逃していた。
レア度が60/+100、4/+100されてしまうので修正。
Issueなし。
> [Fix] 力の杖のレアリティ設定のtypoを修正

- src/cmd-item/cmd-eat.cpp
- src/cmd-item/cmd-usestaff.cpp
- src/object-hook/hook-expendable.cpp
- src/object-use/quaff-execution.cpp
- src/player/mimic-info-table.cpp
- src/player/player-race.cpp
- src/player/player-race.h
- src/player/race-info-table.cpp
インプの生命が悪魔タイプで生者ではないため、食料であまり栄養が取れなくなっていた(#820のエンバグ)のを修正。
> [Fix/Feature] 種族の食料タイプを設定 #820

- src/floor/floor-object.cpp
複数のアイテムを拾った場合、その間にサブウィンドウ描画フラグ
PW_FLOOR_ITEM_LIST が ON にならないために足元のアイテム一覧が
更新されない。
さらに元を辿れば delete_object_idx() でフロアのアイテムが削除された
時は床上のアイテム一覧の更新の可能性があるはずなので、
delete_object_idx() で PW_FLOOR_ITEM_LIST を ON にするようにする。
> [Fix] 【バグ】 足元のアイテムを複数拾おうとした時にサブウィンドウ：あなたの足元のアイテム一覧が更新されない #995

- src/view/display-characteristic.cpp
> [Fix] Cコマンドで永久光源欄の@列に . を表示し忘れている

- src/save/save.cpp
不要なキャストにより32768件目以降のメッセージ履歴にアクセス
できておらず、結果として32767件までしかメッセージ履歴が保存
されない。
(MESSAGE_MAX が 81920件なので、65536件目以降は再び(0件目
からのメッセージが)保存されるようになるが、現状のメッセージ
履歴処理関数の仕様ではこの件数を超えることはまずあり得ない)
意図したものとは思えないのでキャストを取り除く。
> [Fix] メッセージ履歴が正しく保存されない

- src/window/display-sub-windows.cpp
「足元/床上のアイテム一覧」サブウィンドウの表示が幻覚状態でも「～の足元の発見済みアイテム一覧」とモンスターを判別できる表示になっていた。
幻覚時には「何か奇妙な物の足元の発見済みアイテム一覧」と表示するように修正した。
アイテム部分の表示の方は以前から問題なく、幻覚時には「何か奇妙な物」と表示されます。
> [Fix] 幻覚状態時に足元のアイテムサブウィンドウでモンスターを判別できる問題の修正

- src/flavor/flavor-util.cpp
- src/wizard/wizard-item-modifier.cpp
- sprintf風にuintの値を文字列に変換するobject_desc_num関数で、値によっては無限ループ？に陥る問題を修正した。
- pval値は符号付16ビットなので、入力値がこの範囲を超えないように制限する。
最大値より大きい入力は最大値、最小値より小さい値は最小値で受け取るようにした。
> [Fix] ウィザードモードでのpval99999入力ハングの修正

- src/system/player-type-definition.h
- src/util/flag-group.h
e3d1038fa79f9c612575e800db357f1d8f11d482 でインクルード
関係の修正が行われているが、flag-group.h で
mutation-flag-types.h をインクルードするのは明らかに変なので
player-type-definition.h へ移動する。
軽微な修正につき Issue 無し。
> [Fix] mutation-flag-types.h のインクルード関係

- src/main-win.cpp
タスクバーやAlt+Tabでのタスク切り替えで変愚蛮怒をアクティブにしたとき、これまではサブウインドウがアクティブになっていた。
サブウインドウをアクティブにせず、メインウインドウがアクティブになるように修正した。
> [Fix] タスク切り替え時にメインウインドウをアクティブにする

- src/main/game-data-initializer.cpp
- src/view/display-messages.cpp
- src/view/display-messages.h
#1027 の修正と合わせると、最大81919件のメッセージが保存されるようになり、セーブファイルからメッセージ履歴読み込み時の計算量もO(N log(N))に改善する。
また、人間に理解できるコードになった。
レビューがしやすいように、以下の2つにコミットを分けている。
- std::dequeを使用したメッセージ履歴の管理の実装
- 上記を元にstd::shared_ptrを使用した同一メッセージの共有の実装
> message_add 関数をC++機能でリファクタリングする #1026

- src/main-win.cpp
#966 の背景ブラシ省略によりクリア範囲がマージン分（上下左右各2ピクセル）狭くなり、ウインドウサイズ変更時に描画ゴミが出たりウインドウの外観が以前と異なっていた。
背景ブラシと同様の範囲（クライアント領域全体）をクリアするように修正した。
また、ウインドウサイズ変更時の行/列サイズ算出を修正した。TOP, LEFTのマージンだけでなくRIGHT, BOTTOMのマージンも考慮するように修正した。
Alpha21で発生する描画ゴミ
Alpha21でウインドウ端が黒くならない
> [Fix] Windows版でウインドウサイズ変更時に端の描画が残らないように修正

- src/cmd-action/cmd-travel.cpp
トラベルコマンドの中断後に手動で移動し、目的地で再度トラベルコマンドを実行した場合に「トラベルを継続しますか？」の確認を出さないようにする。
> [Feature] 目的地に居る場合にトラベル継続確認を行わない

- src/player/player-status.cpp
参照するメンバ名がbless_bladeではなくblessedになっており
祝福された装備をしている時でなく一時的効果の祝福時に
魔法防御が上昇している。
本来の効果であるbless_bladeに修正する。
> [Fix] 祝福による魔法防御上昇の誤り #1047

- src/main-win.cpp
- src/main-win/graphics-win.cpp
- src/main-win/graphics-win.h
#936 のエンバグ。
reset_visuals関数（表示シンボルの初期化）はタイル表示時のみ呼び出す（以前のバージョンからの動作）ように修正した。
また、グラフィクス/グラフィックスの表記ゆれをメニューに合わせて「グラフィクス」に統一した。
> [Fix] 地形等のシンボルが常に初期化される問題の修正

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/combat/shoot.cpp
- src/floor/fixed-map-generator.cpp
- src/floor/floor-object.cpp
- src/floor/floor-object.h
- src/floor/floor-util.cpp
- src/grid/grid.h
- src/grid/object-placer.cpp
- src/inventory/floor-item-getter.cpp
- src/load/floor-loader.cpp
- src/load/item-loader.cpp
- src/load/load-v1-5-0.cpp
- src/load/savedata-flag-types.h
- src/monster-attack/monster-eating.cpp
- src/monster-floor/monster-object.cpp
- src/object/object-index-list.cpp
- src/object/object-index-list.h
- src/save/item-writer.cpp
- src/spell-kind/spells-fetcher.cpp
- src/stdafx.h
- src/system/monster-type-definition.h
- src/system/object-type-definition.h
- src/target/target-describer.cpp
セーブファイルのバージョンは上がりませんが、アイテムセーブフラグ `SAVE_ITEM_STACK_IDX` を新たに導入しているので過去のセーブファイルとの互換性はなくなります
----
object_type にアイテムリスト中の位置を記録するメンバ stack_idx
を設け、セーブファイルに記録するようにする事でセーブ/ロードを
行っても床上のアイテムリストの順序が変化しないようにする。
> [Feature] 床上のアイテムリストのスタック順を保持する #992

- src/mspell/mspell-status.cpp
ディアボロはセリフ風ではあるが、一律で見えないときは表示しない。
> [Fix] 見えないときにモンスターの無敵発動時のメッセージが表示される #1034

- src/monster/monster-processor.cpp
該当のフラグをsetするべきところでsetされていない。
そのため、壁抜け@に対する変則ピラーダンス封じが機能していない。
以前と同様にフラグをsetすることで正常な挙動に戻す。
> [Fix] 壁抜け対策のMFLAG2::NOFLOWが機能していない

- src/view/display-messages.cpp
軽微につき Issue なし。
std::weak_ptr のコンストラクタで型推論ができずにコンパイルエラーと
なるようなので、明示的に型を与えるようにする。
> [Fix] Mac版Clangで display-messages.cpp のコンパイルエラー

- src/util/flag-group.h
軽微につき Issue 無し。
9e83442dc1904a7a70511fbef436ccd7e713ca10 のようなミスを
防止するため、FlagGroup のメンバに nodiscard 属性を付与する。
間違いやすいのは has() と set() だと思われるが、この際なので
戻り値を無視する事はあり得ないであろうメンバにはすべて
nodiscard 属性を付けておく。
> [Feature] FlagGroup のメンバに nodiscard 属性を付与する

- src/main-win/main-win-utils.cpp
セーブファイルを開くとき、 #1023 のエンバグでファイル名が設定されなくなっている。
以前と同様にファイル名の初期値を設定するようにした。
> [Fix] Windows版ファイル選択ダイアログでファイル名初期値が常に未設定

- src/combat/attack-criticality.cpp
- src/combat/attack-criticality.h
- src/combat/shoot.cpp
- src/combat/shoot.h
- src/market/building-craft-weapon.cpp
- src/view/status-first-page.cpp
武器匠でのダメージ表示とステータス画面の平均ダメージに
強撃フラグの効果が反映されるようにする。
これまでのような一次式による期待値計算は難しいので、
実際にd650+d650の全パターンを網羅して期待値を計算する。
> [Fix] 武器匠での会心ダメージやステータス画面上の平均ダメージに強撃の効果が反映されない #897

- src/cmd-io/cmd-macro.cpp
- src/util/angband-files.cpp
長いマクロは画面に表示しきれないため、80バイト分のみ表示することで回避する。
また、angband_fgets関数でバッファサイズを超えてNULL終端を書き込む問題も修正した。
> [Fix] 長いマクロ表示でスタックが破壊される問題の修正

- Hengband/Hengband/Hengband.vcxproj
- src/main-win.cpp
- src/main-win/main-win-cfg-reader.cpp
- src/main-win/main-win-file-utils.cpp
- src/main-win/main-win-mci.cpp
- src/main-win/main-win-mci.h
- src/main-win/main-win-music.cpp
- src/main-win/main-win-sound.cpp
- src/main-win/main-win-utils.cpp
- src/main-win/main-win-utils.h
文字セットをマルチバイトからUnicodeへ変更する。
システムロケールUTF-8環境でウインドウのタイトル「変愚蛮怒」が文字化けしなくなる。
文字セットをいつでも切り替えできるようにWin32 APIは末尾A/Wまで記述して使い分けている。
UTF-8環境で現在未対応な事項
- 日本語の画面出力 #766 で対応するはず
- ~~日本語入力 WM_UNICHARに対応すればOK？~~
※注意事項
.iniファイルの処理はWin32 APIを使用しているためシステムロケールの影響を受ける。
システムロケールを変更する場合、Hengband.INIは削除推奨。どうしても使いたい場合は文字コードをシステムロケールに合わせて変換すること。
> [Feature] Windows版をUnicode文字セット(UTF-16)へ移行

- src/player/player-status-flags.cpp
extra_blowsの計算で両手持ちだけではなく両手マーシャルアーツの
チェックも行うようにする。
> [Fix] 両手の空いたマーシャルアーツで利き手でない方の指に追加攻撃の指輪を付けても攻撃回数が増えない #1071

- src/wizard/wizard-item-modifier.cpp
> [Fix] 足りないヘッダーファイル追加

- src/info-reader/race-reader.cpp
#909のエンバグ。
これまで呪文確率の1_IN_Xはそれのみで1行に書かれていたため問題なかったが、最新の追加モンスターでは同じ行に呪文種別のフラグも記載されたため顕在化。
> [Fix] r_info.txtのモンスターの呪文フラグで書式によってうまく読めない #1091

- src/spell-kind/spells-enchant.cpp
他の選択させるメッセージは「どの○○を○○しますか？」となっているため、凡庸化のメッセージを「どのアイテムを凡庸化しますか？」に変更した。
巻物の英語名はMundanityだけれど、mundane_spell関数のコメントで「Mundanify an object～」と書かれていたので英語メッセージは「Mundanify which item? 」としました。
Mundanifyという単語はないみたいだけれども、Mundanity, mundaneも動詞に使うような言葉ではなさそうなのでMundanity＋FY=Mundanifyでいいんじゃないかと。
> [Fix] 凡庸化メッセージの修正

- src/cmd-io/cmd-macro.cpp
#1073 の修正漏れ分の対応です。
4) マクロの作成、8) キー配置の作成でも登録マクロのバッファをそのまま再利用するため、長いマクロが登録されているとスタックが壊れる。
4,8ではバッファに空文字列を設定してから編集を行うようにした。
> [Fix] 長いマクロが登録されているとマクロ設定画面でスタックが破壊される問題の修正

- src/util/angband-files.cpp
Without that, the changes to kind-reader.cpp in https://github.com/hengband/hengband/commit/8c1ee0d91accd2d33b46ad0756a832ae71ef4c0d cause the English version to bail out at line 117 of k_info.txt (the Japanese characters in that line are all ignored by the current version of angband_fgets() leaving an empty string that triggers a parsing error in kind-reader.cpp).
> [English] In angband_fgets() replace nonprintables with '?' rather than strip them

- src/monster/monster-util.cpp
#1094 で議論している内容。固定クエストにRES_ALL持ちモンスターが生成された場合、対処手段が限定されるため「毒針」を持参するなどしなければ達成が著しく困難となる。
これは単に強力なモンスターが出現するよりも理不尽であるため修正する。
> [Feature] 固定クエストにRES_ALL持ちモンスターを生成しない

- src/main-win/main-win-cfg-reader.cpp
英語版ビルド時はguess_convert_to_system_encoding関数を使わないようにした。
> [Fix] 英語版ビルドエラー修正

- src/cmd-io/cmd-macro.cpp
長いマクロで落ちる対策で使えなくなっていた機能を再実装した。
マクロ設定画面では80文字分しか作成できないため、80バイト分を編集用バッファに取り入れるようにした。
また、#1104 でキー待ちしないオプション対策をしたら逆にオプション無効時に-続く-が多くなり使いにくくなったので調整した。
> [Feature] 最後に確認したマクロを作成時に編集データに用いる

- src/info-reader/info-reader-util.h
- src/info-reader/magic-reader.cpp
m_info.txt の xtra フラグは 0x05 のような16進数で記述しているが
10進数として std::stoi に渡しているため正しく値が読めず 0 に
なってしまっている。
info_set_value() に基数を指定する引数を追加し、 xtra フラグは
16進数として読むようにする。
#1119 #1120 の原因。
その他に、同様の原因により最低失敗率 5% が反映されていない問題も修正。
> [Fix] m_info.txt の xtra フラグが正しく読めていない

- lib/edit/a_info.txt
- lib/edit/misc.txt
- lib/edit/t0000001.txt
- lib/edit/t_lite.txt
★苦痛のグレイブ相当の武器として実装し、戦士/狂戦士の古い城報酬にする。
> [Feature] 固定アーティファクト『ドラゴンころし』の追加

- src/cmd-io/cmd-dump.cpp
- src/cmd-io/cmd-macro.cpp
- src/cmd-visual/cmd-visuals.cpp
- src/io/read-pref-file.cpp
- src/io/read-pref-file.h
同名ファイルがANGBAND_DIR_PREFに存在する場合に読み込めないため、カラーの設定/マクロの設定/画面表示の設定での「ユーザー設定ファイルのロード」はANGBAND_DIR_USERからに限定する。
> [Fix] ユーザー操作での.prfファイル読み込みをANGBAND_DIR_USERからに限定する

- src/main-win.cpp
マウスドラッグ選択時にゲームの進行を止めるのが困難なので、マクロ実行中はマウス選択不可としました。
> [Fix] Windows版でマクロ実行中は画面をマウス選択不可に制限する

- src/main-win.cpp
TERM_XTRA_REACTでの処理は表示シンボルのリセットを伴うため、起動時にグラフィクスモードの初期化（シンボルリセットなし）を行う。
この変更により、タイル表示で起動の度に表示シンボルがリセットされることがなくなる。
> [Fix] グラフィクスモードの初期化をTERM_XTRA_REACTに依存せず起動時に行う

- src/dungeon/dungeon.h
- src/wizard/wizard-special-process.cpp
掲題の通りです
手元の環境で正常に動作することを確認しました
ご確認下さい
> [Fix] #1130 存在しないダンジョンID及び階層を指定したら再入力を促すようにした

- src/autopick/autopick-util.cpp
- src/store/purchase-order.cpp
Issue #1121 の修正。 
自動拾いファイルの設定によって自動刻みされた場合に
同じ銘のアイテムが2つになる可能性があるので、
PU_COMBINE フラグを立ててまとめるようにする。
既存のコードでは店で購入したアイテムをザック内でまとめ直してから
自動刻みを行っているが、これだと元々持っていた銘の無いアイテムに
重なった場合にそのアイテムもろとも銘が刻まれてしまう。
アイテムを拾う時と同じように、先に銘を刻んでからザック内でまとめ
直すようにする。
> [Fix] 店で購入したアイテムに対する自動刻み関連の修正

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/main-win.cpp
- src/main-win/main-win-term.cpp
- src/main-win/main-win-term.h
描画はオフスクリーンに対して行い、表示画面への描画回数を減らす。
描画するものがあればオフスクリーンに描画し、InvalidateRectを呼び出しておく。
InvalidateRectはWM_PAINTメッセージを生成するため、
WM_PAINTの処理でオフスクリーンから表示画面へ描画する。
WM_PAINTを待つとタイトル画面の初期化中メッセージは表示されないので
TERM_XTRA_FRESHでUpdateWindowする。
UpdateWindowは即WM_PAINTを処理するAPI。
WM_PAINTがオフスクリーンから描画するだけになるため
再描画の意味でInvalidateRectを使っていたところはterm_redrawに置き換える。
他にはウインドウのリサイズが起きたらオフスクリーンを破棄して再描画する。
ターミナルの行数、列数に変化が無い場合はterm_redraw、
行数、列数が変わる場合はterm_resize（中でterm_redrawされる）を使う。
#980 との違い等は以下の通り。
- 方向性や手法は同じ。描画はオフスクリーンに対して行い、表示画面への描画回数を減らすことで高速化する。
- Windows仕様によりそった処理を行う。InvalidateRectに領域を渡すとOS側でクリッピングした領域をBeginPaintで受け取れるので自前で描画対象領域を処理しなくて良い。WM_EXITSIZEMOVEでウインドウサイズ変更おしまいを受け取れるので、オプションなしにウインドウサイズ変更時には再描画する。
- ターミナルのhookを活用する。TERM_XTRA_FRESHで画面更新すると矢の軌跡も再描画もうまく処理できる。resize_hookは内部で使われているためmain-winから使えない。
- …
> [Feature] Windows版の描画にダブルバッファリング導入

- lib/xtra/sound/sound.cfg
- src/combat/shoot.cpp
- src/main/sound-definitions-table.cpp
- src/main/sound-definitions-table.h
- src/mind/mind-sniper.cpp
射撃術使用時の効果音をSOUND_SHOOTからSOUND_ZAPに変更し、再生タイミングを変更しました。
「精神集中」は選択時、他は方向を決めた時に再生します。
※Windows版は効果音を複数同時に再生できないため、SOUND_ZAP再生後にSOUND_SHOOTが再生されると聞こえません。
ついでにsound.cfgの空腹、クリティカル、ヴォーパル各項目にコメントを追加しました。
ヴォーパル倍率1（細切れにした）の項目名が"shred_hit "と後ろに不要なスペースが入っていたので削除しました。
> [Fix] スナイパーの射撃術を使うとSOUND_SHOOTが不自然に鳴る

- src/main-win.cpp
2バイト文字を描画する時に、描画する文字以外もUTF-16変換を行っていたため「タイルを2倍幅で表示」では顕著に遅くなっていたと考えられる。
描画する文字のみUTF-16変換を行うようにした。
> [Fix] Windows版の2バイト文字描画を最適化

- src/spell-kind/spells-teleport.cpp
テレポートした後の座標の周囲のモンスターをスキャン
しているのでついてこれるわけがない。
テレポート前の座標の周囲をスキャンするようにする。
また、is_resistible という変数名の意味が分かりづらい
ので can_follow に変更する。
> [Fix] モンスターがテレポート追尾しない #1157

- src/monster-attack/monster-eating.cpp
magic_masteryを持っているときに複数本の杖から魔力を吸収されたとき、pvalが0以下になる場合がある。
複数本の杖を所持しているとき、pval減少量を倍加させていたのが原因。倍加するべきはモンスターの体力回復値である。
> [Fix] 杖の充填魔力を吸収されたときアンダーフロー

- lib/xtra/sound/sound.cfg
- src/combat/shoot.cpp
- src/effect/effect-player-resist-hurt.cpp
- src/main/sound-definitions-table.cpp
- src/main/sound-definitions-table.h
- src/mspell/mspell-bolt.cpp
~~sound.cfgはコメントを各項目に移動し、射撃命中音のshoot_hit項目を追加した。~~
~~enum sound_typeは順番を入れ替えやすいように明示的に初期化しない（先頭0、以降の項目は+1になる）。~~
Refactor分は #1147 でマージ済み
sound.cfgにshoot_hitの項目を追加した。
プレイヤーの射撃の命中時、モンスターの射撃がプレイヤーに命中時にこの効果音を再生する。
> [Feature] 射撃命中音の効果音対応

- src/window/display-sub-windows.cpp
掲題の通りです
ご確認下さい
たぬき・カメレオンも同根なので併せて解消されます
> [Fix] #1156 足元のアイテムを表示する時に見かけのモンスターを表示するようにした

- src/player/player-status.cpp
- src/player/player-status.h
calc_weapon_weight_limit は両手持ちの時に重量上限が2倍になる
処理があるため、近接武器を両手持ちしているとこのボーナスが
弓にも適用されてしまっているのが原因。
calc_bow_weight_limit を新設し弓はそちらを使用するようにする。
ついでにこれらの関数の戻り値を重量の型に合わせて WEIGHT
にする。
> [Fix] 弓が重すぎて運搬中になると命中率が上がる #1133

- src/player/player-status.cpp
二刀流が非常に強力なこれらのクラスに両手持ちの選択肢を与える試み。
両手持ちボーナスが入るとき、str_indexをレベル23、レベル46で追加で1増やす。
これにより、最終的には25kgの獲物を両手持ちなら上限回数まで振るうことが可能となる。
> [Feature] 戦士/狂戦士の両手持ちボーナスを強化

- src/player/player-status.cpp
射撃回数計算関数 calc_num_fire()内にて運搬中の射撃武器の回数計算に誤り。
運搬中は射撃回数でそれぞれの武器の初期値を使用するべきところで0を使用していた。
このため実際に運搬中に射撃を行うとゼロ除算が発生し強制終了の原因となっていた。
該当箇所を修正し、正常な値を返すようにする。
また、update_bonuses()内でcalc_num_fire()をコールする箇所に誤りがあったので合わせて修正する。
> [Fix] 【バグ】 運搬中状態のヘヴィ・クロスボウで射撃すると異常終了 #1182

- src/info-reader/dungeon-reader.cpp
d_info.txt にピットとネストの生成許可フラグを16進数で
設定しているが、読み込み時に10進数として読んでいるため
すべて 0 になってしまい、絶対に生成されなくなっている。
正しく16進数として読み込むようにする。
#1122  で修正したのと同様のバグ。
念の為他の \*\_info.txt も含め 0x で始まる項目が他にないか確認したが、これで最後の模様。
> [Fix] ピット/ネストが生成されない #1189

- src/main-win/main-win-utils.h
漏れてた。
「タイルを２倍幅で表示」だと描画毎にメモリが溜まっていく。
> [Fix] Windows版のマルチバイト/ワイド文字列変換のメモリリーク修正

- src/io-dump/character-dump.cpp
過去に使えた領域をビット位置で保存する変数の判定が
反転しているのが原因。
ビットが立っていない場合にスキップするのが正しい。
> [Fix] ダンプに過去に使えた領域が記録されない #1205

- src/hpmp/hp-mp-regenerator.cpp
ボール中モンスターのHP自然回復処理で描画フラグが立つため、広域マップ移動が重くなっていた。
現在は、モンスターのHP回復がモンスターボールの表示に影響することがないため、描画フラグ処理をコメントアウトすることで解消する。
> [Fix] モンスターボールで広域マップ移動が重くなる

- src/view/display-characteristic.cpp
軽微な修正につき、Issue無し。
ダンプ画面で「呪文難度減少」と表記されているが、反対の効果を
もたらす HEAVY_SPELL では「魔法難度増加」となっている。
*鑑定*での表示では、「魔法の難易度を(上|下)げる」となって
いるので、魔法難度のほうに統一する。
> [Fix] EASY_SPELL の表記ゆれ

- src/perception/identification.cpp
object_type の curse_flags の TRC::BERS_RAGE のチェック漏れによるもの。
他の呪いフラグと同じようにチェックするようにする。
> [Fix] 呪いの一時効果の狂戦士化の説明文が*鑑定*時に出ない #1059

- src/spell-kind/spells-teleport.cpp
根本としてテレポートアウェイ効果をフェーズアウト状態には一切受けないように修正した。同効果が将来にデバッグや、新能力に利用することを想定した上の修正案。
闘技場のモンスターに点Pやlainが出ることが珍しいと思うので、実際問題が抑止されているかはprocess_quantum_effect()内を少しいじってどんなモンスターでも量子的効果を起こすようにしてから試してもらえれば。
> [Fix] フェーズアウト状態(カジノ闘技場観戦)時にプレイヤーがテレポートアウェイ効果の影響そのものを受けないよう修正．

- src/core/asking-player.cpp
入力値の符号付32ビット整数を符号付16ビット整数としてキャストしているため、例えば101010の入力をマイナスの値として扱う不整合が出ていた。
入力値の制限を0から符号付16ビット整数の最大値までとすることで不整合を回避する。
COMMAND_CODEをs16bからs32bにすることで解決しようとしたところ、関連する値がs16bの型のようで断念した。
根本的な原因はサイズの異なる型の変数をやり取りしているせいで、本来エラーや警告なりが出て検出できるはずだが、キャストしているため気づけなくなっている。他にもありそう。
> [Fix] 数の指定で受け付けない入力値がある

- lib/xtra/sound/sound.cfg
- src/cmd-item/cmd-equipment.cpp
- src/main/sound-definitions-table.cpp
- src/main/sound-definitions-table.h
- src/mspell/mspell-bolt.cpp
- src/spell/spells-status.cpp
・モンスターからプレイヤーへの射撃効果音の復活
・装備した/装備を外した時の効果音を追加
　『ドラゴン・クロス』発動時にもSOUND_TAKE_OFFを鳴らす。
> [Feature] 効果音の追加v3.0.0 α28

- src/io/mutations-dump.cpp
- src/view/display-player.cpp
これで2.2.1の頃と同じ挙動に治ったはずなのでチェックよろしくお願いします。
> [Fix] ラッキーマンが変異を他に持たない状態でも突然変異一覧に表示できるよう修正.

- src/store/purchase-order.cpp
- src/store/sell-order.cpp
ひとまずこれで売買価格固定/未固定でメッセージが変わらなくなったはず。固定フラグそのものを除くのは別Issueでリファクタリング扱いにでもする。
> [Fix] 値切りシステム廃止後の売買のメッセージ統一を推進．

- src/market/building-enchanter.cpp
- src/spell/spells-object.cpp
enchant_equipment 内でアンドロイドの装備によるLV計算処理
calc_android_exp が呼ばれており、種族がアンドロイドの場合
その中で最終的に handle_stuff が呼ばれてアイテムを重ねる
フラグなどの処理が行われてしまう。
結果として店舗でのアイテム強化処理の途中で強化した
アイテムが重なり、重なった後の分の数にしたがった料金が
所持金から引かれるため、所持金がマイナスになるという
バグが発生する。(Issues #1240)
所持金がマイナスにならなかった場合でも、重なった数の
分だけ、余分に料金を取られている。
enchant_equipment を呼び出した後でも calc_android_exp は
呼び出しているので、 enchant_equiptment 内では
calc_android_exp を呼び出さないようにする。
なお、他の enchant_equipment の呼び出しを一通り確認したが
アンドロイドの装備によるLVの再計算が必要な場合は
すべて enchant_equipment の呼び出し後に calc_android_exp を
呼び出しているため、enchant_equipment 内での呼び出しの
削除が他に影響することはないと思われる。
また、料金（単価×個数）を何度も計算しているのが
そもそもおかしいので、一度計算した値を変数に入れて
使用するようにする。
> [Fix] 種族アンドロイドで店舗でのアイテム強化した時の処理

- src/dungeon/quest.cpp
- src/dungeon/quest.h
- src/floor/fixed-map-generator.cpp
- src/system/system-variables.cpp
- src/wizard/wizard-game-modifier.cpp
改良の余地はまだあるが別件と合わせて別Issue化予定．
* 階段で正規にダンジョンに突入する処理と統合．
* ワーグクエストのようなダンジョンの階層に依存するクエスト以外では即座にクエストに飛ぶよう処理．
> [Fix] ウィザードモードのクエスト突入機能が正しく動作するよう修正＆リファクタリング．

- src/cmd-action/cmd-move.cpp
馬鹿馬鹿のバグ直している間に発見。ちょっとした修正なのでIssueは立てず。確認誰かお願いします。
> [Fix] is_echizen()がTRUE(セリフがアレの状態)の時、地上に戻る際の帰還残り時間がリセットされない不具合を修正.

- src/info-reader/race-reader.cpp
8c1ee0d91accd2d33b46ad0756a832ae71ef4c0d
上記コミットのパーサ書き換え時にモンスターの英語名の
E_name メンバへの読み込み自体が削除されている。
その結果、ゲーム上の直接的な影響は無いがスポイラー
ファイル mon-info.txt のモンスター名の英語表記の併記が
消えてしまっている。
元の通り E_name メンバに英語名をロードするようにする。
> [Fix] r_info.txt の英語名がロードされていない

- src/melee/melee-spell-flags-checker.cpp
ボール魔法を所持しているかどうかの真偽チェックが
反転しているため、巻き込むボール魔法を除外する
コードが動作していない。
真偽チェックを正しく修正する。
> [Fix] ペットに巻き込むなって言ってるのに巻き込む #1255

- src/object-enchant/special-object-flags.h
- src/store/pricing.cpp
- src/store/purchase-order.cpp
- src/store/sell-order.cpp
- src/store/store.cpp
- src/view/display-store.cpp
以下の問題を修正する。
- #1257 
- #1252 
- 価格交渉削除前の仕様で価格交渉で最大限に値切れた時に付与されていた IDENT_FIXED フラグを削除する。これにより店舗の価格表示の後ろに「固」が表示されることがなくなる。
> 店舗の価格交渉削除後に残っている問題の修正

- configure.ac
Recent versions of autoconf/autoheader/... complain about some of the constructs in configure.ac (see this log from building my fork of hengband on macOS:  https://github.com/backwardsEric/hengband/runs/3040495359?check_suite_focus=true ).  This pull request addresses all of those:  mostly by removing macros which check for behavior where only quite old (20+? years) systems deviate from the standards.
> Linux/Unix:  avoid warning messages about obsolete usage when running bootstrap

- src/racial/class-racial-switcher.cpp
おそらくコピペ後の修正漏れで明鏡止水の回復量になっている。
静水の実際の回復量を正しく表示するようにする。
> [Fix] 静水のMP回復量表示の誤り #1266

- src/system/object-type-definition.cpp
66e2ed76dce76b461cbcdbfb78bb3cda6ca989c5 で床上にスタックした
アイテムの順序を保持するようにしたが、エッセンス抽出に伴う
object_type::prep の呼び出しでスタック順序を保持するメンバ変数
stack_idx もクリアされてしまっているため、順序が変わってしまう。
凡庸化の処理でも同様の現象が起きるものと思われる。
対策として、object_type::prep を呼び出しても stack_idx は保持
されるようにする。
> [Fix] 床上のアイテムのエッセンスを抽出するとスタック順が変わる

- lib/edit/a_info.txt
- lib/edit/r_info.txt
- src/perception/identification.cpp
The small edits are to the descriptions for Corpser, Kuafu's staff, and items with RES_CURSE.
> English:  fix whitespace in monster descriptions and make a few small edits

- src/monster-floor/one-monster-placer.cpp
#1241 
モンスター生成処理の際、友好化の条件が「モンスターが友好的な特性を持つ場合、"または"召喚主が友好、または強制的に友好にする場合」という処理だったため、モンスターが友好の特性を持つかどうかの判定を自然生成（whoが0）の時にのみするように変更するのはいかがでしょうか。
これであれば召喚主が敵対している場合は普段友好なモンスターも召喚された際に敵対して生成されます。
> 敵対モンスターの友好モンスター召喚時のバグについて

- src/monster-floor/monster-sweep-grid.cpp
- src/monster-floor/monster-sweep-grid.h
ざっくり言えば「最小コストでない移動のみする」って挙動になってのが原因でした
あとcalc_run_cost()という関数名は適切でないので修正
> モンスターが下に走る現象の修正と関数名の変更

- src/monster/monster-damage.cpp
With the ubuntu-latest runner on GitHub and the source configured with "--disable-worldscore --disable-pch", monster/monster-damage.cpp fails to compile because of no prototype for get_rnd_line().  A log from a failed compilation is here, https://github.com/backwardsEric/hengband/runs/3274556727?check_suite_focus=true .
This change resolves that by always including io/files-util.h in monster/monster-damage.cpp regardless of if JP is set.
> Fix monster/monster-damage.cpp compilation when world score disabled

- src/spell/spells-status.cpp
リファクタリングの結果、体力ランクが既知の状態でシャッフルの魔法や
新生の薬等でHPが再計算された時、再計算後もoptions引数の条件により
体力ランクが既知のままとなっている模様。
不自然なので、HP再計算時には必ず体力ランクの既知フラグをリセットする。
> [Fix] HPが再計算された時に体力ランクを不明にする

- src/hpmp/hp-mp-processor.cpp
- src/info-reader/general-parser.h
- src/target/grid-selector.cpp
On Debian Buster (gcc is 8.3.0) with the source configured with "--disable-worldscore --disable-pch", floor/fixed-map-generator.cpp, hpmp/hp-mp-processor.cpp, info-reader/general-parser.cpp, main/info-initializer.cpp, and target/grid-selector.cpp fail to compile because of a missing definition for std::function.  Those compiled without problems on GitHub's ubuntu-latest runner.
This change works around that by include functional in more places so std::function will be visible where it is used.
> Fix Debian Buster compilation for std::function

- src/mind/mind-priest.cpp
ビットフラグでない変数に対しビット操作を誤って行っており
簡易鑑定状態がリセットされないので、武器祝福が成功しても
簡易鑑定状態が「呪われている」のままとなってしまう。
ビット操作ではなく代入に修正する。
> [Fix] 武器祝福で簡易鑑定状態がリセットされない

- src/load/load.cpp
- src/player/player-class.h
- src/player/player-status.cpp
- src/system/player-type-definition.h
- src/util/bit-flags-calculator.h
なるべくマクロの使用は避けるべきなので、ビットフラグ操作
マクロを関数に変更する。
対象: set_bits, reset_bits, any_bits, all_bits, none_bits, match_bits
また、関数化にあたり追加した引数型のアサーションにより
見つかったビットフラグとして扱っている符号付き変数を、
符号無し変数に変更する。
> [Refactor] ビットフラグ操作マクロ群を関数に変更

- src/lore/combat-types-setter.cpp
Avoids a spelling mistake and implies an action rather than a state.
> Change English description for HUNGRY blows

- lib/edit/a_info.txt
That's primarily for more consistent verb tenses and subject-verb agreement.
> Edit the English description of Nezumi-Kozou

- src/effect/effect-processor.cpp
- src/melee/melee-postprocess.cpp
- src/monster-floor/monster-summon.cpp
- src/mspell/mspell-bolt.cpp
- src/mspell/mspell-breath.cpp
- src/mspell/mspell-special.cpp
- src/mspell/mspell-util.cpp
- src/mspell/mspell-util.h
- src/spell-kind/spells-world.cpp
プレイヤーから見えないところで見えない場所へのモンスター召喚が行われた等、不自然な効果音の再生を行わないようにする。
-  SOUND_REFLECT：反射したモンスターが見える場合か、プレイヤーorペットが発射したボルトが反射された場合に再生する
-  SOUND_KILL（SOUND_N_KILL）：対象が見えない場合は再生しない
-  SOUND_SUMMON：召喚主がプレイヤーorペット、召喚主のモンスターが見える、召喚目標地点が見える場合に再生する。
-  SOUND_SHOOT：モンスターAからモンスターBへの射撃は、プレイヤーから近くてAB両方見える場合に再生する。
-  SOUND_BREATH：プレイヤーがブレスを吐くモンスターと近いか、ブレス対象が見える場合に再生する。
-  SOUND_FALL：対象がプレイヤーの場合に再生する。
-  SOUND_TPLEVEL：モンスター対象のレベルテレポートは対象が見える場合に再生する。
> [Fix] プレイヤーが感知不能な場面の効果音を制限する

- src/monster-floor/monster-summon.cpp
player_can_see_bold関数への引数のxyの順番を取り違えていた。
> [Fix] #1340 で引数のxyの順番を間違えていた

- src/room/rooms-city.cpp
ダンジョンで地下街が生成された時にブラックマーケットがすでに存在する
場合は2軒目以降のブラックマーケットを生成しないようにする事を意図した
コードが存在するが、誤って f_info のインデックスと地形特性フラグを
比較しているため機能していない。
正しく f_info[].flags の内容をチェックするようにする。
なお、生成する部屋を選択するところで地下街が選択された場合は2つ目
以降の地下街の生成自体が抑制されるため、修正しても現状ではこの
コードが機能することはない。
軽微なので Issue なし。 #1385 の作業中に発見。コミットメッセージの通り、地下街が2つ以上生成される事が無いので現状は実質死に体のコードではあるが、バグはバグなので直しておく。
ちなみにログを確認したところ、地下街が導入された時点からすでにバグっていた模様。
> [Fix] ブラックマーケットが複数生成されないようにするコードが機能していない

- src/core/window-redrawer.cpp
- src/window/display-sub-windows.cpp
- src/window/display-sub-windows.h
サブウィンドウにアイテムや装備の一覧を表示する関数 fix_\* を
リファクタリング時に TvalItemTester を使用するように修正したが、
第2引数は現状 TV_NONE で呼び出されておりこれはリファクタリング
前の仕様ではすべてのアイテムにマッチするというものだった。
そもそも第2引数が TV_NONE 固定なのに用意された経緯は不明だが、
とりあえずこれらの関数では ItemTester を受け取るように修正し、
呼び出し側は ItemTester に AllMatchItemTester を設定してリファクタ
リング以前の仕様に従うようにする。
> [Fix] #1426 サブウィンドウのアイテム欄の記号が表示されない

- src/core/window-redrawer.cpp
- src/floor/floor-object.cpp
- src/object/item-tester-hooker.h
- src/window/display-sub-windows.cpp
- src/window/display-sub-windows.h
ItemTester クラスによるリファクタリングによりアイテム選択記号が絞り込まれなくなっているので、その機能を復活させる。
> サブウィンドウでのアイテム選択記号の絞り込みを復活させる

- src/effect/effect-item.cpp
- src/effect/effect-player-resist-hurt.cpp
- src/inventory/inventory-damage.cpp
- src/inventory/inventory-damage.h
- src/object/object-broken.cpp
- src/object/object-broken.h
- src/player/player-damage.cpp
詳細は #1398 参照
アイテム破損関数のポインタを引数に使ってるinventory_damage() もクラスのconst 参照に変えてます
> アイテム破損関数のクラス化

- src/object/item-tester-hooker.h
ItemTesterの各派生クラスで clone() メンバ関数の実装が繰り返されている。
DRYの原則に従い、これらの実装をCuriously Recurring Template Pattern
によって共通化する。
ちょっとした改善なのでIssue無し。
> [Refactor] ItemTester の clone() メンバ関数をCRTPで共通化

- src/artifact/random-art-characteristics.cpp
短い＆たまたま目についた処理だったのでチケットはなしで
get_random_art_filename() について、concptr ではなくstd::string を返すようにしました
これにより似たようなswitch文が2回入っていたのを簡略化できました
ご確認下さい
> ランダムアーティファクトの銘を選択するルーチンが冗長だったので簡略化した

- src/main-cap.cpp
- src/main-gcu.cpp
- src/system/h-system.h
Turbo CやWatcom Cはもうサポート外なので削除しました
ご確認下さい
なお以下は放置中です、見たところlinux以外は不要な気もしますがハッキリしなかったのでそのままです
不要だと分かる方はコメントもらえると助かります
```
#if defined(Pyramid) || defined(NCR3K) || defined(ibm032) || defined(__osf__) || defined(ISC) || defined(linux)
```
> もう使われていないプリプロの削除＠h-system.h

- src/grid/feature.cpp
- src/system/grid-type-definition.cpp
- src/system/grid-type-definition.h
- src/target/grid-selector.cpp
現在grid_type 構造体に実装されているメソッド群は全てconst関数なのでconstを付けました
更にis_symbol() をgrid-selector.cpp/h から移してきました
ご確認下さい
(ついでですが、関連するメソッドtgt_pt_move_to_symbol() をtgt_ptr_into 構造体に押し込みました)
> grid-type.cpp/h のリファクタリング＆メソッド移動

- src/hpmp/hp-mp-processor.cpp
溶岩等の地形ダメージ判定時に、ダメージを受けなかった時に自然回復なしフラグがリセットされてしまう。
地形ダメージを受けた場合のみ自然回復なしフラグを設定するように修正しました。
> [Fix] 地形ダメージ判定時の自然回復フラグ修正

- lib/xtra/sound/sound.cfg
- src/hpmp/hp-mp-processor.cpp
- src/main/sound-definitions-table.cpp
- src/main/sound-definitions-table.h
- terrain_damage 地形によるダメージ
- damage_over_time 毒/切り傷によるダメージ
日光、オーラ、壁抜けによるダメージについては冗長な感じなので保留にする。
付けるとすれば別の効果音設定で対応したい。
> [Implement] 地形や毒等のダメージ発生時の効果音を追加

- src/load/item-loader.cpp
- src/load/load-util.h
- src/load/load-v1-5-0.cpp
- src/load/lore-loader.cpp
- src/load/monster-loader.cpp
- src/load/player-info-loader.cpp
これまで個別に実装していたビットフラグをFlagGroupに移行するコードを、
TrFlagsをFlagGroupにした時にに導入した migrate_bitflag_to_flaggroup 関数に
より共通化する。
今後他のフラグをFlagGroup化する場合も使えるはず。
> [Refactor] ビットフラグをFlagGroupに移行するコードに共通関数を使用する

- src/cmd-item/cmd-smith.cpp
「必要数/所持数」より「所持数/必要数」の表記のほうが直感的にわかりやすい。
他のゲームでも後者の表記が一般的だと思われるので、後者の表記に変更する。
> [Feature] 鍛冶師のエッセンスの所持数と必要数の表記位置を入れ替える

- .clang-format
適切な場所での改行を可能にし、勝手に1行に連結されるのを抑制する。
> [Feature] clang-format の設定の ColumnLimit を 0 にする

- src/object-enchant/object-smith.h
That way compiling without precompiled headers works.  Resolves #1505 .
> object-enchant/object-smith.h include unordered_map

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/object-enchant/object-smith.cpp
- src/object-enchant/object-smith.h
- src/object-enchant/smith-info.cpp
- src/object-enchant/smith-info.h
- src/object-enchant/smith-tables.cpp
- src/object-enchant/smith-tables.h
鍛冶情報を、単純な一種の構造体から smith_info_base を基底クラスと
した派生クラスを作成し、鍛冶効果の内容をカスタマイズしやすくする。
ひとまず既存の鍛冶効果の実現のため下記のクラスを作成した。
- basic_smith_info: 特性フラグを付与(最も基礎的な効果)
- activation_smith_info: 発動効果を付与
- slaying_glove_smith_info: 殺戮の小手の鍛冶専用
- enchant_weapon_smith_info: 武器の命中/ダメージ修正の強化
- enchant_armour_smith_info: 防具のAC修正の強化
- sustain_smith_info: 装備保持効果
> [Refactor] 鍛冶効果情報をカスタマイズしやすく再設計

- src/object-enchant/object-smith.cpp
- src/object-enchant/object-smith.h
- src/wizard/cmd-wizard.cpp
- src/wizard/wizard-spells.cpp
- src/wizard/wizard-spells.h
^A E で鍛冶師のエッセンスを全て最大所持量にするデバッグコマンドを
追加する。
職業鍛冶師でデバッグコマンドを実行すると、所持エッセンスがすべて
最大所持量になる。
（これまでの ^A E は青魔道士の時のみ青魔法をすべてラーニング済みに
するコマンド）
また、あわせて最大所持量を定数化しておく。
> [Feature] 鍛冶師のエッセンスを全て最大所持量にするデバッグコマンド

- src/mind/mind-weaponsmith.cpp
- src/object-enchant/object-smith.cpp
- src/object-enchant/smith-info.cpp
- src/object-enchant/smith-info.h
- src/object-enchant/smith-tables.cpp
- src/object-enchant/smith-types.h
鍛冶効果を追加するにあたり、エッセンス一覧や付与画面が1画面に収まりきらなくなるので複数ページに対応させました。
また、複数ページ対応の動作を見るに当たり実際に増やして確認する必要があるので、同じPRにてかねてから予定していた以下の鍛冶エッセンスの追加を行います。
- 耐水（水耐性）
- 耐時間逆転（時間逆転耐性）
- 耐呪力（呪力耐性）
- 善良倍打（善良スレイ/\*善良スレイ\*/善良ESP）
> 鍛冶コマンドの複数ページ対応/いくつかの鍛冶効果を追加

- src/mind/mind-weaponsmith.cpp
リファクタリング時にpvalの判定の位置を誤ったため、追加攻撃の
エッセンスを付与する時に個数を選べるようになってしまっていた。
そもそも数値の制限が必要かどうかをインターフェース処理側で
行っている設計がおかしいがそれは今後の課題とし、ひとまず
追加攻撃を付与する時はpvalが1に制限されるようにする。
> [Fix] +2以上の追加攻撃の鍛冶ができてしまう

- src/object-enchant/smith-info.cpp
以前からのおかしな仕様として、矢弾の類に無効な武器属性（追加攻撃や
カオス攻撃など）を付けることができてしまう。
付けても特に効果は無いので通常プレイわざわざ付ける事はないが、不親切
なので武器属性付与では効果のあるもの（四属性と毒攻撃）以外では矢弾が
付与の候補に選ばれないようにする。
> [Fix] 矢弾に効果の無いエッセンスが付与できてしまう

- src/object-enchant/smith-info.cpp
以前からあるおかしな仕様として、矢弾の類に耐性や能力値などの装備品に
付けなければ意味のないエッセンスを付与できてしまう。
不親切なのでこれらのエッセンスでは矢弾が候補に選ばれないようにする。
> [Fix] 矢弾に装備品用のエッセンスを付与できる

- lib/edit/r_info.txt
> [Fix] #1138 あてどなくふらつく商人の説明文に誤訳、「魅力のアミュレット」ではなく「装飾のアミュレット」に修正した

- src/mind/mind-weaponsmith.cpp
メニューコマンドでエッセンスを付与しようとすると、カーソルの上下で
ページが切り替わってしまうという不具合を修正する。
また、カーソルの左右でページが切り替わるようにする。
> [Fix] メニューコマンドでエッセンス付与する時の挙動

- src/dungeon/dungeon.h
- src/grid/feature.h
- src/info-reader/artifact-reader.cpp
- src/info-reader/dungeon-reader.cpp
- src/info-reader/ego-reader.cpp
- src/info-reader/feature-reader.cpp
- src/info-reader/kind-reader.cpp
- src/info-reader/race-reader.cpp
- src/info-reader/vault-reader.cpp
- src/object-enchant/object-ego.h
- src/object/object-kind.h
- src/room/rooms-vault.h
- src/system/artifact-type-definition.h
- src/system/monster-race-definition.h
配列のループ処理を range-based for で記述したいのに、中で要素の
index が必要な時に結局ループ変数を使用することになる。
自身のindexを持っておけば、それを参照すればよくなる。
とりあえずメンバを追加したのみです。これを使用しての range-based for への書き換えは追々気が向いたら。
> [Feature] *_info 配列の要素のメンバに自身のindexを持たせる

- src/object-enchant/smith-info.cpp
リファクタリング時に鍛冶をできるか判定する関数を間違っていた。
正しい関数に修正する。
とりあえず develop を元にPRを出しています。
HotFix案件であれば、release を元にしたブランチに差し替えます。
> [Fix] 鍛冶で遠隔武器や矢弾の命中/ダメージ修正を強化できない

- src/info-reader/artifact-reader.cpp
- src/info-reader/dungeon-reader.cpp
- src/info-reader/ego-reader.cpp
- src/info-reader/feature-reader.cpp
- src/info-reader/kind-reader.cpp
- src/info-reader/race-reader.cpp
- src/info-reader/vault-reader.cpp
- src/knowledge/knowledge-items.cpp
- src/object-enchant/object-smith.h
- src/object-enchant/smith-info.h
- src/object-enchant/smith-types.h
- src/system/object-type-definition.h
Visual Studio が出力している以下の警告に対処する。
- 各infoのidxメンバに代入する時の整数型のナローイング
- std::reduce の初期値を設定してない事による整数型のナローイング
- SmithEffect の値をセーブデータに格納する時の整数型のナローイング
> [Fix] Visual Studio の警告に対処

- src/action/activation-execution.cpp
- src/cmd-action/cmd-pet.cpp
- src/cmd-io/cmd-lore.cpp
- src/dungeon/dungeon.cpp
- src/flavor/object-flavor.cpp
- src/io-dump/character-dump.cpp
- src/knowledge/knowledge-features.cpp
- src/knowledge/knowledge-items.cpp
- src/knowledge/knowledge-monsters.cpp
- src/knowledge/knowledge-quests.cpp
- src/knowledge/knowledge-uniques.cpp
- src/load/floor-loader.cpp
- src/load/load.cpp
- src/locale/japanese.cpp
- src/main/game-data-initializer.cpp
- src/market/building-monster.cpp
- src/room/rooms-city.cpp
- src/room/rooms-maze-vault.cpp
- src/room/rooms-vault.cpp
- src/save/floor-writer.cpp
- src/term/z-form.cpp
- src/wizard/monster-info-spoiler.cpp
- src/wizard/wizard-special-process.cpp
C_MAKE マクロが使用されている箇所のうち、一時的なバッファ用途の物
(同一スコープでC_KILLが呼ばれている)を std::vector で置き換える。
まずは恒常的に使用する領域ではないものについて、 std::vector によるバッファ確保に置き換えました。
> [Refactor] C_MAKEによる一時的バッファをstd::vectorで置き換える

- src/object-enchant/object-smith.cpp
Fix #1575.
以前からこの仕様だったようだが、割引率が消去される正当な理由も無いので
エッセンス抽出では割引率は保持されるようにする。
> [Fix] エッセンス抽出で割引率が消去される

- src/mind/mind-weaponsmith.cpp
- src/object-enchant/object-smith.cpp
- src/object-enchant/object-smith.h
Fix #1577.
エッセンス付与可能回数を取得する、Smith::get_addable_count で矢弾のような1個
あたりの消費量が変化するアイテムが考慮されていないのが原因。
get_addable_coount にアイテムへのポインタを受け取るようにし、アイテム1個
あたりの消費量に基づいた付与可能回数が得られるように修正する。
エッセンス選択画面ではアイテムが確定していないので、矢1本だけを強化する時に
エッセンスが足りているのに選択不可能な問題は残っているが、以前からそうだし
先にアイテムを選択するようにするなど大幅なインターフェース変更が必要なので
とりあえずおいておく。
> [Fix] 鍛冶で矢弾を強化する時エッセンス数が足りているのに不足していると判定される

- src/dungeon/dungeon.cpp
- src/dungeon/dungeon.h
- src/dungeon/quest.cpp
- src/dungeon/quest.h
- src/floor/floor-generator.cpp
- src/floor/floor-object.cpp
- src/floor/wild.cpp
- src/floor/wild.h
- src/main/game-data-initializer.cpp
- src/monster/monster-status.cpp
- src/system/floor-type-definition.h
- src/window/display-sub-windows.cpp
配列へのポインタからvectorになったので const性の厳密さが増したため、一部 const修飾を外す必要がありました。
（本来const引数でOKなはずの関数の引数がconstじゃないせいなのですが、それを修正すると芋づる式に大量に修正しないといけないので断念）
> [Refactor] floor_typeの配列的に扱うメンバ、荒野、クエスト、ダンジョン探索深度に std::vector を使用する

- src/birth/game-play-initializer.cpp
- src/load/inventory-loader.cpp
- src/system/player-type-definition.h
C_MAKE を排除するために配列をSTLのコンテナに変更する作業を進めていますが、まとめてPRを出すと変更量が多くてレビューが大変になるので小分けして出すことにします。
C_MAKE マクロの使用を避けるため、player_type::inventory_list の型を
単なるポインタから shared_ptr<object_type[]> へ変更する。
vector にすると player_type 型を使用するすべてのファイルで
object_type を定義したヘッダのインクルードが必要になってあまりに
煩わしいので、shared_ptr を使用することにする。
> [Refactor] player_type::inventory_list の型を shared_ptr<object_type[]> に変更

- src/floor/floor-town.cpp
- src/floor/floor-town.h
- src/market/building-initializer.cpp
- src/store/store-util.h
C_MAKE マクロの使用を避けるため、街・店舗の情報を std::vector で
保持する。店舗のアイテム情報は std::vector にすると town_type や
store_type を使用するすべてのファイルで object_type を定義する
ヘッダのインクルードが必要になり煩わしいので
std::unique_ptr<object_type[]> にする。
> [Refactor] 街・店舗・店舗のアイテム情報を std::vector もしくは std::unique_ptr にする

- src/cmd-io/cmd-macro.cpp
- src/cmd-io/macro-util.cpp
- src/cmd-io/macro-util.h
- src/io/input-key-acceptor.cpp
- src/io/interpret-pref-file.cpp
- src/main/game-data-initializer.cpp
- src/term/z-util.cpp
- src/term/z-util.h
- src/util/string-processor.cpp
- src/util/string-processor.h
マクロ関連の配列変数を std::vector にするにあたり、以下の変更も行っています。
- マクロの内容を std::string で持つ
- マクロに関連する concptr を受け取る関数を std::string_view を受け取るように変更
- マクロ設定コマンドの編集バッファを従来のマクロバッファから分離
> [Refactor] マクロ関連の配列変数をstd::vectorにする

- src/io/read-pref-file.cpp
- src/main/angband-initializer.cpp
- src/util/angband-files.cpp
- src/util/angband-files.h
C_MAKE マクロの使用を避けるため、ファイル読み書き用のバッファを
std::vector にする。また、全くグローバルである必要が無いためローカル
変数にする。
> [Refactor] ファイル読み書き用のバッファを std::vector にする

- src/util/quarks.cpp
- src/util/quarks.h
C_MAKE を避けるため、アイテムに刻んだ銘を扱う配列変数を
std::vector<std::string> にする。
quark関連の変数や定数はグローバルで見える必要が無いので、cppファイルに
移動する。
> [Refactor] quark関連のコード

- src/autopick/autopick-describer.cpp
- src/autopick/autopick-drawer.cpp
- src/autopick/autopick-editor-util.cpp
- src/autopick/autopick-entry.cpp
- src/autopick/autopick-finder.cpp
- src/autopick/autopick-initializer.cpp
- src/autopick/autopick-matcher.cpp
- src/autopick/autopick-pref-processor.cpp
- src/autopick/autopick-reader-writer.cpp
- src/autopick/autopick-reader-writer.h
- src/autopick/autopick-registry.cpp
- src/autopick/autopick-util.cpp
- src/autopick/autopick-util.h
- src/cmd-io/cmd-autopick.cpp
- src/cmd-visual/cmd-map.cpp
- src/knowledge/knowledge-autopick.cpp
C_MAKE の使用を避けるため、自動拾い設定リスト autopick_list と、
自動拾いエディタのテキスト領域 text_body_type::lines_list を
std::vector にする。
また、string_make によるメモリリークを避けるため autopick_type の
メンバ name と insc を std::string に変更する。
これにより autopick_free_entry 関数は不要となるので削除する。
> [Refactor] 自動拾い関連の配列変数を std::vector にする 

- src/main-win.cpp
C_MAKE で確保した領域を解放していないためメモリリークしている。
std::vector にすることで修正する。
> [Fix] Windows版でマウスドラッグ時にメモリリーク

- src/maid-x11.cpp
- src/main-x11.cpp
MAKE マクロの使用を避けるため、MAKE マクロで領域を確保しているポインタ変数を
std::unique_ptr に変更し、std::make_unique により領域を確保する。
XCreateImage に渡すデータ領域は、APIの使い方に従って malloc で確保するようにする。
(XDestroyImageがデータ領域まで解放するらしいので、newで確保した領域を渡すと
どうなるのか確信が持てないため。)
> [Refactor] X11版のメモリ領域確保の方法を変更

- src/term/z-virt.h
すべてのメモリ確保/解放マクロの使用を排除できたので、またこれを
使用しようというバカな気を起こさないようにマクロを完全に削除する。
STLのコンテナやスマートポインタがあるいまとなっては、これらを使用
する必要は一切無い。
> [Delete] メモリ確保/解放関連のマクロを削除

- src/view/display-player-stat-info.cpp
Fix #1602.
特性フラグを FlagGroup 化した時にロジックを読み間違えて能力値維持フラグを
渡すべきところを能力値アップフラグを渡すようにしてしまっていた。
正しく能力値維持を渡すように修正する。
> [Fix] 維持のない能力値アップが明るい緑でなく深い緑で表示される

- src/wizard/cmd-wizard.cpp
- src/wizard/wizard-game-modifier.cpp
- src/wizard/wizard-item-modifier.cpp
- src/wizard/wizard-player-modifier.cpp
std::vector<std::vector<std::string>> である必要はないので、
std::array<std::tuple<char, concptr>> にする。(std::array の推論補助を使用)
また、 constexpr 定数とする。
ちょっとした改善なのでIssue無し。
このあいだ、これこんな型の必要ある？という話が出てたので。
サブメニュー表示のコードも同じものがコピペされていてちょっとアレですがそちらはまたの機会ということで。
> [Refactor] デバッグコマンドのメニューテーブルの型

- src/main-win.cpp
Fix #1618.
WIPE マクロを排除した時に term_data 本体でなくポインタの方を初期化
するようにしてしまっていた。
> [Fix] 誤ってterm_dataへのポインタを初期化している

- src/core/asking-player.cpp
- src/core/asking-player.h
- src/wizard/wizard-special-process.cpp
- src/wizard/wizard-spells.cpp
> [Fix] ウィザードモードのID指定モンスター生成(N/n)が回数指定の事前入力のみを想定した仕様で手動指定が足りなかった

- src/combat/attack-criticality.cpp
- src/combat/attack-criticality.h
- src/monster-attack/monster-attack-player.cpp
- src/timed-effect/player-cut.cpp
- src/timed-effect/player-cut.h
- src/timed-effect/player-stun.cpp
- src/timed-effect/player-stun.h
#553 の前段作業です
ご確認下さい
- カプセル化と設計上の呼び出し関係を維持する (具体的にはPlayerCut/Stunにplayer\_ptrへの参照を保持させない)ため、calc\_player\_cut/stun() についてはmonster\_attack\_player.cppに残しています
- 切り傷の方は蓄積ランクの補正を行う予定はないので、取得メソッドをprivateにしています
- 朦朧の方は今後新仕様に基づく補正を行うので、取得メソッドをpublicにしています
> calc_monster_critical() を廃止してPlayerCut/PlayerStun::get_accumulation()/get_accumulation_rank() に個別定義した

- src/blue-magic/blue-magic-checker.cpp
- src/blue-magic/blue-magic-checker.h
- src/blue-magic/learnt-power-getter.cpp
- src/io-dump/special-class-dump.cpp
- src/mind/mind-blue-mage.h
青魔法のタイプ blue_magic_type を enum から enum class に変更する。
それに関連して set_rf_masks の引数名を修正するとともに、Doxygen
コメントの内容がモンスター特殊能力の FlagGroup 化前の物だったので
現状に合わせて修正する。
https://github.com/hengband/hengband/pull/1628#pullrequestreview-763071815 でコメントされた内容に対応しました。
小修正につき Issue は無し。
> [Refactor] 青魔法のタイプを enum から enum class にする

- src/Makefile.am
Resolves https://github.com/hengband/hengband/issues/1631 .
> Linux/Unix:  include player-info/class-specific-data.h in the output of "make dist"

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/cmd-building/cmd-inn.cpp
- src/cmd-item/cmd-magiceat.cpp
- src/cmd-item/cmd-magiceat.h
- src/hpmp/hp-mp-regenerator.cpp
- src/io-dump/special-class-dump.cpp
- src/load/player-class-specific-data-loader.cpp
- src/load/player-class-specific-data-loader.h
- src/mind/mind-magic-eater.cpp
- src/player-base/player-class.cpp
- src/player-info/bluemage-data-type.h
- src/player-info/class-specific-data.h
- src/player-info/force-trainer-data-type.h
- src/player-info/magic-eater-data-type.cpp
- src/player-info/magic-eater-data-type.h
- src/player-info/smith-data-type.h
- src/player-info/spell-hex-data-type.h
- src/save/player-class-specific-data-writer.cpp
- src/save/player-class-specific-data-writer.h
- src/spell/spells-status.cpp
- src/sv-definition/sv-rod-types.h
- src/sv-definition/sv-staff-types.h
- src/sv-definition/sv-wand-types.h
引き続き、魔道具術師の固有データの分離。
また、 #1633 も副次的に修正される。
それから、これまで追加していた職業固有データのヘッダファイルに BOM が付いていなかったので付けておいた。
（いいかげん VSCode のワークスペース設定で規定のファイルエンコーディングを BOM 付きUTF-8にしておく。）
> [Refactor] 魔道具術師の固有データを magic_num から分離する

- src/realm/realm-hex.cpp
リファクタリング前の名残で詠唱中の呪術があるかどうかのチェックで
吟遊詩人の処理を呼んでしまっている。
SpellHexクラスの該当のメソッドを呼ぶように修正する。
> [Fix] 呪術の処理から吟遊詩人の処理を呼んでいる

- src/mspell/mspell-dispel.cpp
- src/player-info/spell-hex-data-type.h
- src/spell-realm/spells-hex.cpp
- src/spell-realm/spells-hex.h
呪術ハイメイジのデータで謎だった magic_num1[1] は、吟遊詩人の詠唱一時
中断処理と共用されている事が分かった。職業固有データに分離した事で一時
中断後に詠唱を再開しなくなってしまっている。
呪術ハイメイジ専用の一時中断する SpellHex::interrupt_spelling を実装し、
呪術ハイメイジの時はそちらを呼ぶことで詠唱の一時中断～再開の処理を
行うようにする。
> [Fix] 呪術ハイメイジで詠唱一時中断後に詠唱を再開しなくなっている

- src/player-info/bard-data-type.h
- src/player-info/bluemage-data-type.h
- src/player-info/force-trainer-data-type.h
- src/player-info/magic-eater-data-type.h
- src/player-info/smith-data-type.h
- src/player-info/spell-hex-data-type.h
職業専用データのメンバに初期化子をつけていなかったが、組み込み型の
メンバは初期値が不定になるかもしれない。ひとまず組み込み型以外も
含めすべて {} を付けて確実にデフォルト値で初期化されるようにしておく。
> [Refactor/Fix] 職業専用データのメンバに初期化子をつける

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/birth/game-play-initializer.cpp
- src/blue-magic/blue-magic-checker.cpp
- src/cmd-action/cmd-mane.cpp
- src/core/player-processor.cpp
- src/load/player-class-specific-data-loader.cpp
- src/load/player-class-specific-data-loader.h
- src/load/player-info-loader.cpp
- src/melee/melee-spell.cpp
- src/mspell/mspell-attack.cpp
- src/player-base/player-class.cpp
- src/player-info/bluemage-data-type.h
- src/player-info/class-specific-data.h
- src/player-info/mane-data-type.h
- src/save/player-class-specific-data-writer.cpp
- src/save/player-class-specific-data-writer.h
- src/save/player-writer.cpp
- src/status/action-setter.cpp
- src/status/bad-status-setter.cpp
- src/system/player-type-definition.h
- src/window/main-window-stat-poster.cpp
player_type にものまね師しか使わない専用のメンバがあるので、職業固有
データ mane_data_type を定義してメンバを移動させる。
また例によって new_mane が青魔道士の学習フラグと共有されていたので、
青魔道士の専用データと別々に分離する。
さらに覚えているものまねのリストを単純な配列からSTLコンテナにして
コードを読みやすくする。
> [Refactor] ものまね師の専用データを職業固有データに移動する

- src/stdafx.h
GCC/Clang ではほぼ効果がなかったですが、VSだとフルビルドにかかる時間が手元のマシンで75秒→60秒程度に短縮されるようなので、追加しておきます。
> [Add] プリコンパイルヘッダをいくつか追加

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/cmd-action/cmd-shoot.cpp
- src/combat/shoot.cpp
- src/core/player-processor.cpp
- src/flavor/flavor-describer.cpp
- src/io/input-key-processor.cpp
- src/load/player-class-specific-data-loader.cpp
- src/load/player-class-specific-data-loader.h
- src/load/player-info-loader.cpp
- src/mind/mind-sniper.cpp
- src/monster/monster-update.cpp
- src/player-base/player-class.cpp
- src/player-info/class-specific-data.h
- src/player-info/sniper-data-type.h
- src/player/player-status.cpp
- src/save/player-class-specific-data-writer.cpp
- src/save/player-class-specific-data-writer.h
- src/save/player-writer.cpp
- src/status/bad-status-setter.cpp
- src/system/player-type-definition.h
- src/window/main-window-stat-poster.cpp
player_type にスナイパーしか使用しない集中度と集中度リセットフラグが
あるので、職業固有データ sniper_data_type を定義して移動させる。
職業固有データの分離の続き。スナイパーを見落としていた。
また、集中度0とそうでない時の不要な分岐が多々見受けられたので、それも修正しています。
> [Refactor] スナイパーの専用データを職業固有データに移動する

- src/cmd-action/cmd-spell.cpp
Resolve #1293.
MPを減らすタイミングがおかしいため魔法をキャンセルしてもターンが
経過せずMPだけが消費される。
元々そんな仕様ではなかったと思われるのでリファクタリングのどこかで
エンバグしたように思うが、ともかくおかしな仕様になっているので修正
しておく。
> [Fix] 魔法をキャンセルしたのにMPが消費される

- src/util/flag-group.h
FlagGroupクラスにフラグ集合のONになっているフラグのうち最初の1つを
取得するメンバ関数 first() を実装する。
> [Feature] FlagGroup::first() を実装

- src/cmd-item/cmd-equipment.cpp
Resolve #1442.
現状、武器と盾を装備している時はモンスター・ボールを装備すると強制的に
盾と交換されてしまう。
一発で武器と交換できてはならない理由はないので交換できるようにする。
> [Feature] モンスター・ボールを武器と交換できるようにする

- src/action/open-close-execution.cpp
- src/action/open-util.cpp
- src/cmd-action/cmd-open-close.cpp
- src/flavor/flavor-describer.cpp
- src/grid/trap.cpp
- src/grid/trap.h
- src/player/player-move.cpp
- src/specific-object/chest.cpp
- src/specific-object/chest.h
~~注：このブランチはコンパイルできません~~
コンパイルが通るように調整しました
証人クエやその他箱のデバッグ生成をした感じ、問題なさそうです
ご確認下さい
~~trap.h に定義されているChestTrapType (developではdefine定数の塊)ですが、chest\_traps にて配列 (このブランチにてvectorに変換)で定義されています
chest\_traps の実体はtrap.cpp にありますが、現在かなりの力技で定義しています
vector\<EnumClassFlagGroup\<ChestTrapType\>\> で定義したいところですが、vectorに変数名を宣言せずEnumClassFlagGroupを埋め込む記法がイマイチ分かっていません
お手数ですがご確認下さい~~
> chest.cpp/h のクラス化 w/ ChestTrapTypeの定義

- src/player-base/player-class.cpp
- src/player-base/player-class.h
- src/player/permanent-resistances.cpp
- src/player/player-status-flags.cpp
かねてからの懸案事項であった、職業から得られる特性フラグの決定処理が実際の判定用と表示用で別々に実装されている問題に対処します。
職業(およびそのLV等)で得られる特性フラグを得る関数 add_class_flags を
PlayerClass::tr_flags() に移動する。
既存の player-status-flags.cpp 内の特性フラグの有無をチェックする関数群で
職業由来の特性フラグの取得条件はプレイヤー情報表示用(旧 add_class_flags)と
別に二重実装されていた。
当然よろしくない状態なので、add_class_flags から移動させた PlayerClass::
tr_flags() を使用するようにする。
また、装備のスロット/種族/職業由来の特性フラグ有無を得る処理を
common_cause_flags() に共通化して同じコードが繰り返されないようにする。
> 職業由来の特性フラグの処理のリファクタリング

- src/monster-attack/monster-attack-switcher.cpp
掲題の通りです
本来はmonap->damage へ値を格納してそれを朦朧値の蓄積に使用するのが正しいのですが、誤ってローカル変数で痛恨のダメージを計算していました
ご確認下さい
> 痛恨の一撃を食らった時に朦朧値が正しく蓄積しない不具合を修正した

- src/player/player-status-flags.cpp
究極の耐性と無双の型はあらゆる一時耐性を得る特徴を持っているが、
最近新規に追加された耐性フラグの水・時間逆転・呪力に対応していない。
特徴からいってこれらの耐性も得られるべきだと思われるので追加する。
他と合わせておくため今回は set_bits は使っていません。
そもそも、こいつらもいい加減全部の耐性所持判定に書くのではなくまとめたいところ。
> [Feature] 究極の耐性と無双の型に新規耐性を追加

- src/birth/game-play-initializer.cpp
- src/cmd-building/cmd-inn.cpp
- src/cmd-item/cmd-eat.cpp
- src/cmd-item/cmd-usestaff.cpp
- src/effect/effect-player-resist-hurt.cpp
- src/hpmp/hp-mp-processor.cpp
- src/mspell/high-resistance-checker.cpp
- src/object-hook/hook-expendable.cpp
- src/object-use/quaff-execution.cpp
- src/player-base/player-race.cpp
- src/player-base/player-race.h
- src/player-info/race-info.cpp
- src/player-info/race-info.h
- src/player-info/resistance-info.cpp
- src/player/eldritch-horror.cpp
- src/player/permanent-resistances.cpp
- src/player/player-status-flags.cpp
- src/player/player-status-resist.cpp
- src/player/race-resistances.cpp
- src/realm/realm-nature.cpp
以下の種族関連の処理を PlayerRace クラスのメンバ関数にする。
- player_race_has_flag / add_player_race_flags
→ 内容がほぼ同一なので PlayerRace::tr_flags() にまとめる
- get_player_race_info
- player_race_life / player_face_food
> [Refactor] 種族関連の処理を PlayerRace クラスへ移動する

- src/wizard/wizard-special-process.cpp
デバッグコマンドで職業変更/領域変更を行った時、参照する職業固有データを
変更する必要がある可能性があるので、PlayerClass::init_specific_dataを
呼び出して職業固有データを適切なものに更新する。
やっとかないといけないと思いつつデバッグコマンドだからと後回しにしていた。
> [Fix] デバッグコマンド実行時に職業固有データを更新する

- src/blue-magic/learnt-power-getter.cpp
- src/io-dump/special-class-dump.cpp
- src/main-win/main-win-cfg-reader.h
- src/main-win/main-win-sound.cpp
- src/main-win/main-win-utils.cpp
- src/melee/melee-spell-flags-checker.cpp
- src/mspell/mspell-attack.cpp
- src/spell-realm/spells-hex.cpp
- src/system/h-system.h
- src/wizard/wizard-spoiler.cpp
h-system.h にある標準的なCのヘッダのインクルードはWINDOWSでもインクルードしておいてよいと思うので、WINDOWSでもインクルードされるようにします。
また、プリコンパイル済みヘッダの利用により、本来インクルードが必要なファイルがインクルードされていない状態になっているので、一旦プリコンパイル済みヘッダ無しでコンパイルを行い適宜ヘッダのインクルードを追加しました。
> Windows(Visual Studio)用の必要ヘッダファイルの調整

- src/core/player-processor.cpp
- src/monster-attack/monster-attack-player.cpp
- src/status/bad-status-setter.cpp
- src/status/bad-status-setter.h
- src/timed-effect/player-stun.cpp
- src/timed-effect/player-stun.h
掲題の通りです
今回は、直接打撃に基づく朦朧値の蓄積を緩やかにしました
それ以外 (例：轟音ブレス)は敢えて手つかずにすることで緩やかな蓄積となるように調整しました
手元で確認したところ、「Lv50のちからじまんサイクロプス戦士が宵闇のローブ＋両手に肉体強化の指輪を着ている」というレベルの極端な状況でない限り「昏倒＝行動不能」にはならないようになりました
また、そうであるが故にアイテム使用全般に失率を設けるのも妥当と判断しました
ご確認下さい
> 新しい朦朧の仕様を実装した

- src/blue-magic/learnt-power-getter.cpp
get_learned_power に始まる青魔法の選択処理は、元々長大な１つの
関数だったものをいくつかの処理に機械的に分割したため、関数間の
パラメータの受け渡しが多くの不要なものを含め巨大な構造体に全部
ひっくるめて入れられており、実質的にグローバル変数による実装に
なってしまっている。
あまりにも読みづらいため、基本的な分割単位は維持しつつ全面的に
処理を書き直す。
> [Refactor] 青魔法の選択処理

- src/util/int-char-converter.h
int-char-converter.h に定義されている、ASCII文字と整数の変換を行うマクロを
関数にする。
まずマクロは特別に理由がなければ使用を避けるべきであるという点と、I2A等は
マクロであるため値が int であり、例えば std::stringstream に << 演算子で
I2A(0) などをそのまま入れると "a" ではなく "97" になってしまうといった
問題が避けられる。
> [Refactor] ASCII文字↔整数の変換マクロ群を関数化する

- src/io-dump/random-art-info-dumper.cpp
- src/wizard/fixed-artifacts-spoiler.cpp
- src/wizard/items-spoiler.cpp
- src/wizard/spoiler-table.cpp
- src/wizard/spoiler-table.h
アイテムおよびアーティファクトのスポイラーファイル出力に使用するカテゴリ
分け用のテーブルが直感的でないので、テーブルの定義と関連するコードをカテ
ゴリ分けとして直感的になるようにリファクタリングする。
修正前と後で、artifact.txt および object-desc.txt のdiffを取って全く同一である事を確認済みです。
> [Refactor] スポイラー出力に使用するアイテムのカテゴリ分けテーブル

- src/effect/effect-player.cpp
- src/mind/mind-ninja.cpp
- src/monster-attack/monster-attack-player.cpp
掲題の通りです
そもそも変わり身状態か否かをkawarimi() の外側で判定することに意味がなかったので関数内に繰り込みました
ご確認下さい
> 忍者以外でも変わり身で攻撃を回避する場合がある不具合を解消した

- src/wizard/cmd-wizard.cpp
- src/wizard/wizard-special-process.cpp
- src/wizard/wizard-special-process.h
いちいち a_info.txt を見て固定アーティファクトのIDを調べるのがいいかげん
面倒くさくなった。
装備のカテゴリのリスト→アーティファクトのリストで選択できるようにする。
IDを入力する方式のものはこれがあれば要らないと思うので `^A C` を置き換えています。
> [Feature] デバッグコマンドの固定アーティファクト生成をリストで選択する

- src/cmd-io/cmd-gameoption.cpp
Fix #1702.
カーソルの位置を持つ変数の宣言位置がまずく毎回0になってしまっている。
ループの前に宣言するように修正する。
ついでに変化する事がない定数もループの外に出しておく。
> [Fix] 詐欺オプションでカーソルが動かない

- src/object-enchant/smith-tables.cpp
適当に25にしていたが、消費量が少なすぎるという意見があった。
採掘+1あたり10を消費する事を考えると採掘+2.5相当で3ターン毎に岩石溶解が
発動できるのは確かにバランスが悪いと思われるので、エッセンス消費量を100
とする。
> [Feature] 鍛冶で岩石溶解の発動付加のエッセンス消費量を増やす

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/cmd-action/cmd-move.cpp
- src/dungeon/dungeon-processor.cpp
- src/effect/effect-feature.cpp
- src/floor/floor-events.cpp
- src/floor/floor-leaver.cpp
- src/grid/feature.cpp
- src/load/player-class-specific-data-loader.cpp
- src/load/player-class-specific-data-loader.h
- src/mind/mind-ninja.cpp
- src/monster-floor/monster-lite.cpp
- src/monster/monster-damage.cpp
- src/monster/monster-processor.cpp
- src/player-base/player-class.cpp
- src/player-info/class-specific-data.h
- src/player-info/ninja-data-type.h
- src/player/special-defense-types.h
- src/save/player-class-specific-data-writer.cpp
- src/save/player-class-specific-data-writer.h
- src/specific-object/torch.cpp
- src/spell-kind/earthquake.cpp
- src/spell-kind/spells-floor.cpp
- src/spell-kind/spells-lite.cpp
- src/window/main-window-stat-poster.cpp
忍者特有の超隠密・変わり身の発動中かどうかのフラグを忍者の職業固有データ
ninja_data_type を定義して移動させる。
早駆けについは player_type::action だけで制御できるようなのでそのままに
しておく。
また、超隠密状態を解除する処理 set_superstealth(player_ptr, false) を呼ぶ
時に事前に超隠密状態かどうかをチェックしているが、set_superstealthの内部
でも超隠密状態かどうかチェックされており、超隠密状態でなければ何も起きない
ので、呼ぶ前のチェックをすべて削除する。
> [Refactor] 忍者のデータを職業固有データに移動する

- src/realm/realm-hex.cpp
- src/status/action-setter.cpp
Fix #1708.
他に詠唱している呪文があるかどうかの判定が反転している。
正しい判定に修正して他に詠唱中の呪文がなければ ACTION_NONE をセットする
ようにする。
詠唱中の呪術がなくなった時、「呪文の詠唱を中断しました。」の後に「呪文を
詠唱していません。」と不要なメッセージが出る。
これは本来呪文を詠唱していないときに詠唱をやめるレイシャルを使用した時の
メッセージだが、リファクタリングでコールチェーンが変わった結果表示される
ようになってしまっている。
呪文の詠唱を中断しました。の後には呪文を詠唱していません。は表示されない
ようにする。
> 呪術のおかしな挙動の修正

- src/effect/effect-player.cpp
掲題の通りです
原因は、「とにかく変わり身処理をして、それからモンスターからの打撃が当たったかどうか等を判定する」とリファクタリング作業中に順番が逆になっていたことでした
修正しましたのでご確認下さい
> 忍者の変わり身が意図せず発動する事象を修正した

- src/dungeon/quest-completion-checker.cpp
- src/dungeon/quest-completion-checker.h
- src/floor/floor-object.cpp
- src/floor/floor-object.h
- src/grid/object-placer.cpp
- src/monster-floor/monster-death.cpp
- src/monster-floor/special-death-switcher.cpp
- src/specific-object/chest.cpp
- src/spell/spells-object.cpp
- src/wizard/wizard-item-modifier.cpp
#1725 の後段作業で、#1413 の本体です
チケット内の仕様通りに実装しました
添付のファイルをロードし、目の前にいる『ハルコン』へ^Ay*t で一撃死させると破邪の矢の生成をスキップします
ステップ実行でご確認下さい
[DEBUGGER_破邪の矢除外.zip](https://github.com/hengband/hengband/files/7273435/DEBUGGER_.zip)
> ランダムクエスト報酬を改善した

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/flavor/object-flavor.cpp
- src/floor/wild.cpp
- src/load/info-loader.cpp
- src/monster-floor/special-death-switcher.cpp
- src/mspell/specified-summon.cpp
- src/object-enchant/apply-magic-ring.cpp
- src/save/info-writer.cpp
- src/term/z-rand.cpp
- src/term/z-rand.h
- src/util/rng-xoshiro.cpp
- src/util/rng-xoshiro.h
- src/world/world.h
C++化の一環として乱数生成関連で以下のリファクタリングを行いました。
- <random> ヘッダを使えるように現在の xoshiro128** を実装する Uniform Random Bit Generator 要件を満たすクラス Xoshiro128StarStar の作成
- 上記のオブジェクトをRNGとして world_type 構造体のメンバに持たせる
- 一様整数分布乱数に std::uniform_int_distribution を使用する
- 正規分布乱数に std::normal_distribution を使用する
また、next_bool() という半々の確率でtrue/falseのいずれかを返す関数がありますが、one_in_(2)で十分で存在意義が見いだせない（むしろ1/2という情報が無くなって曖昧になってしまっている）ので削除しました。
> 乱数生成に STL を使用する

- src/info-reader/artifact-reader.cpp
- src/info-reader/dungeon-reader.cpp
- src/info-reader/info-reader-util.cpp
- src/info-reader/info-reader-util.h
- src/info-reader/kind-reader.cpp
- src/info-reader/race-reader.cpp
現在*_info.txtに記述される英語版のフレーバーテキストは、2行以上にわたる
場合スペースを挟んで連結されるように行末か行頭にスペースを入れている。
しかし、行末にスペースを入れると視認しづらいし、どちらに入れるにしても
メンテナンスが面倒になるので、パーサの処理時に自動的にスペースを挟んで
連結するようにする。
既存のフレーバーテキストのスペースは削除しなくて済むように、パーサ側で
両端のスペースは削除しながら連結する。
ちなみに現時点でも、第○の乗り手のユニークなどスペースが挿入されておらず思い出を表示すると行の前後が繋がってしまっているものがいくつかあるようです。
> [Feature] 英語版のフレーバーテキストを良い感じに連結する

- src/load/birth-loader.cpp
- src/load/dummy-loader.cpp
- src/load/dungeon-loader.cpp
- src/load/extra-loader.cpp
- src/load/floor-loader.cpp
- src/load/info-loader.cpp
- src/load/inventory-loader.cpp
- src/load/item-loader.cpp
- src/load/load-util.cpp
- src/load/load-util.h
- src/load/load-v1-5-0.cpp
- src/load/load-v1-7-0.cpp
- src/load/load-zangband.cpp
- src/load/load.cpp
- src/load/lore-loader.cpp
- src/load/monster-loader.cpp
- src/load/option-loader.cpp
- src/load/player-attack-loader.cpp
- src/load/player-class-specific-data-loader.cpp
- src/load/player-info-loader.cpp
- src/load/quest-loader.cpp
- src/load/store-loader.cpp
- src/load/world-loader.cpp
- src/util/flag-group.h
tmp8u などの一時変数を頻繁に使用する事になっている主な原因として、セーブ
ファイルから整数を読み込む関数群 rd_byte/s16b/u16b/s32b/u32b のインター
フェースが引数にポインタを受け取りそのポインタが指す領域にセーブファイル
から読み込んだ値を書き込むようになっている事が挙げられる。
そもそも読み込んだデータを戻り値として返すのが自然であるし、コードの冗長
性が大幅に減らせるのでそのようにインターフェースを変更する。
#1729 に対応しようとしていて、そもそもコードが煩雑になっている原因は rd_\* のインターフェースにあるという事に気づいたのでそちらのほうをまず修正することにしました。 これで #1729 はひとまず現状のままでもいいかなという感じもします。
> [Refactor] セーブファイルから整数値を読み込む関数のインターフェース

- src/core/asking-player.cpp
- src/wizard/wizard-spells.cpp
現在ウェイト処理のms指定とデバッグモードのモンスターID指定にだけ用いています。
レビューお願いします。
> [Implement] get_value()が参照代入値ポインタの入力前値をデフォルト値にするよう仕様追加。

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/load/dummy-loader.cpp
- src/load/floor-loader.cpp
- src/load/monster/monster-loader-base.h
- src/load/monster/monster-loader-factory.cpp
- src/load/monster/monster-loader-factory.h
- src/load/monster/monster-loader-version-types.h
- src/load/old/load-v1-5-0.cpp
- src/load/old/monster-loader-savefile10.cpp
- src/load/old/monster-loader-savefile10.h
#1724 の前段作業で、#1798 の亜種です
このチケットによるセーブデータのバージョン変更はありません
Alpha42を目処に、読み込み処理を切り替える予定なので、その準備です
設計はitem-loaderと同様です
ご確認下さい
(注：#1724 がマージされるのを前提としたブランチなので、それまではドラフトにしておきます)
> monster-loader.cpp/h をクラス化し、ファクトリクラスで処理を分割した

- src/mspell/mspell-ball.cpp
Fix #1808.
ファイア・ボールのメッセージの設定で対象がプレイヤー用とモンスター用の
ものが入れ替わってしまっているのが原因。
正しいものに修正する。
HotFix案件っぽいです。
> [Fix] 敵がファイア・ボールを唱えた時にクラッシュする

- src/birth/birth-select-class.cpp
Fix #1815.
#1754 でのエンバグ。変数のスコープの狭めすぎや取り違えがあわさっておかしな
挙動となっていた。
> [Fix] キャラメイクの職業選択時におかしな挙動が発生する

- src/cmd-action/cmd-spell.cpp
- src/knowledge/knowledge-experiences.cpp
- src/player/player-skill.cpp
- src/player/player-skill.h
- src/player/player-status.cpp
- src/player/player-status.h
- src/spell-realm/spells-hex.cpp
- src/spell-realm/spells-hex.h
- src/spell-realm/spells-song.cpp
- src/spell/spell-info.cpp
- src/spell/spell-info.h
魔法の熟練度経験値上昇処理を PlayerSkill クラスのメンバ関数へ移設
- gain_spell_skill_exp():
魔法を詠唱した時の熟練度経験値上昇処理
- gain_continuous_spell_skill_exp():
継続して詠唱する魔法(歌・呪術)の熟練度経験値上昇処理
- gain_spell_skill_exp_over_learning():
学習済みの魔法をさらに学習した時の熟練度経験値上昇処理
現在の熟練度経験値を得る関数 experience_of_spell を PlayerSkill::
exp_of_spell に移設
熟練度経験値から熟練度レベルを得る関数 spell_exp_level を PlayerSkill
クラスの静的メンバ関数にする
> [Refactor] 魔法の熟練度処理を PlayerSkill クラスに移設

- src/player-base/player-class.cpp
- src/player-base/player-class.h
- src/player-base/player-race.cpp
- src/player-base/player-race.h
- src/status/bad-status-setter.cpp
PlayerRaceの内外に処理が散っていたのでPlayerRace内に処理を集約した。
また、関数名を実態に即したものに変更した。
ついでに類似のネーミングであったPlayerClass.can_resist_stun()もhas_stun_immunity()に変更。
いずれも動作変更は行わない。
> [Refactor] 変身中の切り傷無効処理の可読性向上

- src/birth/birth-stat.cpp
- src/cmd-action/cmd-spell.cpp
- src/combat/shoot.cpp
- src/core/game-play.cpp
- src/info-reader/skill-reader.cpp
- src/knowledge/knowledge-experiences.cpp
- src/load/player-info-loader.cpp
- src/object-hook/hook-weapon.cpp
- src/player/player-skill.cpp
- src/player/player-skill.h
- src/player/player-status-flags.cpp
- src/player/player-status.cpp
- src/spell/spell-info.cpp
- src/view/display-player-middle.cpp
- src/wizard/wizard-special-process.cpp
リファクタリングの一環として既存の熟練度レベルを表す定数 EXP_LEVEL_* を
enum class にする。型名は PlayerSkillRank とし、関連する関数名も合わせて
変更する。
またこれに伴い、熟練度レベルを表す文字列をもつグローバルな配列変数を削除し、
PlayerSkill クラスの静的メンバ関数 skill_rank_name() を使用して取得する
ようにする。
#1833 を前提としているので draft PR にしています。
> [Refactor] 熟練度レベルの定数を enum class にする

- lib/edit/a_info.txt
- src/flavor/flag-inscriptions-table.cpp
- src/hpmp/hp-mp-processor.cpp
- src/info-reader/kind-info-tokens-table.cpp
- src/object-enchant/smith-tables.cpp
- src/object-enchant/tr-types.h
- src/perception/identification.cpp
- src/player-info/body-improvement-info.cpp
- src/player/player-status-flags.cpp
- src/view/display-characteristic.cpp
新パターンのデメリット装備として装備中ダメージを受け続けるものを導入する。
10ゲームターン毎にレベルと同値のダメージを受けるという重いデメリットを課す。
二重耐性+急回復で相殺でき、免疫があればデメリットを踏み倒すことが可能。
常用不可、短期決戦用の強力な装備を選択肢として提示することを期待する。
試験枠として★バルログの長ゴスモグのムチを強化してみた。要調整。
> [Feature] 継続自傷ダメージ装備の導入

- lib/edit/a_info.txt
- src/artifact/fixed-art-types.h
- src/effect/effect-monster.cpp
- src/melee/melee-postprocess.cpp
- src/monster-floor/monster-death.cpp
- src/monster-floor/monster-death.h
- src/monster-floor/quantum-effect.cpp
- src/monster-floor/special-death-switcher.cpp
- src/monster-floor/special-death-switcher.h
- src/monster-race/race-indice-types.h
- src/monster/monster-damage.cpp
要望のあった★の追加。
加えて、メカジキを冷気属性で倒したときに10%の確率でドロップするようにした。
条件ドロップの実装テストも兼ねて。
> [Feature] ★『レイトウメカジキ』の追加

- src/combat/shoot.cpp
- src/combat/slaying.cpp
- src/combat/slaying.h
- src/monster-floor/monster-death.cpp
- src/monster-floor/monster-death.h
- src/monster-floor/special-death-switcher.cpp
- src/monster-floor/special-death-switcher.h
- src/monster/monster-damage.cpp
- src/monster/monster-damage.h
- src/object-use/throw-execution.cpp
- src/player-attack/player-attack-util.h
- src/player-attack/player-attack.cpp
- src/spell/spell-types.h
複数属性を持つ武器/射撃によるアタックを評価するためMDPを拡張した。
例示として実装しているメカジキだが、適当な棒など複数属性武器で攻撃した際に
該当武器に冷気ブランドが含まれていればドロップする実装となった。
> [Feature] MonsterDamageProseccorに複合属性渡しを許可する

- src/spell/spells-object.cpp
アーティファクトID取得ループでID取得ができなくなっていた。
IDを取得するように修正。
> [Fix} 誰得の巻物で固定アーティファクトが生成されない

- src/market/arena.cpp
- src/monster-race/monster-race.cpp
- src/monster-race/monster-race.h
今後モンスターの評価値計算を汎用的にシステムに絡めていくための移設です。問題なければよろしくお願いします。
> [Refactor] モンスター闘技場のモンスター種族評価値を calc_monrace_power() に分離して、monster-race.cpp/h へ移動。

- src/inventory/inventory-curse.cpp
AC低下等の呪いで既に実現しているギミックを恐怖/狂戦士化に拡張する。
該当のアイテムにかけられた呪いが強力であるとき、頻度と持続時間を強化する。
具体的には10ゲームターン毎1/1500から1/150に、持続時間は倍にする。
> [Implement] 強力に呪われているとき、恐怖/狂戦士化の呪いを強化する

- src/spell-kind/earthquake.cpp
earthquake()内でkillerにformatを直接渡しているため、後にtake_hit()内で上書きされていることが原因。
killerをstd::stringにして文字列のコピーとして保持するよう修正する。
> [Fix] 地震による落盤で死ぬと死因が0feetになる #1883

- src/flavor/flag-inscriptions-table.cpp
- src/info-reader/kind-info-tokens-table.cpp
- src/inventory/inventory-curse.cpp
- src/object-enchant/smith-tables.cpp
- src/object-enchant/tr-types.h
- src/object-enchant/trc-types.h
- src/object/object-value-calc.cpp
- src/perception/identification.cpp
- src/player/player-status-flags.cpp
- src/player/player-status-flags.h
- src/player/player-status.cpp
- src/view/display-characteristic.cpp
- src/wizard/artifact-analyzer.cpp
- src/wizard/fixed-artifacts-spoiler.cpp
- src/wizard/spoiler-table.cpp
- src/wizard/spoiler-table.h
- src/wizard/spoiler-util.h
魔法防御半減はペナルティとして強力すぎて使いにくいので、気軽に導入できるペナルティとして呪力弱点を導入する。
呪力耐性と関連させて耐性-弱点の関係とする。
平常時MR-10、強力に呪われているときMR-30とした。複数装備しても重複しない。
> [Implement] 呪力弱点の導入

- src/cmd-item/cmd-equipment.cpp
AC低下がうっかり重複していたため二刀流するとACが最大-60される。
意図した挙動ではないため修正。
> [Fix] アヌビス-チャリオッツでACが二重に下がる

- src/player/player-skill.cpp
吟遊詩人の一部の歌の熟練度が上がらない #1898 の修正
継続しない歌/呪術の熟練度が上昇しなくなっていた。
通常の魔法と同様に熟練度を上昇させるように修正する。
> [Fix] 継続しない歌/呪術の熟練度が上昇しない

- src/cmd-io/cmd-macro.cpp
長いマクロを確認しようとするとゲームが落ち、起動できなくなる #1897 の原因。
macro_bufに長すぎる文字列を格納するためメモリが破壊される。
strncpyを使用して格納文字列に上限を設ける。
> [Fix] do_cmd_macros内のbuffer overflow

- src/cmd-visual/cmd-visuals.cpp
Issue #1909 の件。
該当の出力箇所でループ形式を変更した際、ループカウンタを使用していた箇所が正常動作しなくなっていた。
そもそもループカウンタではなくモンスターの種族IDを使用するべきなので、そのように修正。
> [Fix] モンスターの色/文字を正常にprfファイルに保存できない

- src/game-option/option-types-table.cpp
Issue #1903 の件。
スコアへの影響はないので表記を修正する。
> [Fix] 同一のセーブファイルでゲームを開始するオプションに不要なアスタリスク

- src/birth/birth-stat.cpp
- src/core/game-play.cpp
- src/knowledge/knowledge-experiences.cpp
- src/object-hook/hook-weapon.cpp
- src/player/player-skill.cpp
- src/player/player-skill.h
- src/player/player-status-flags.cpp
- src/player/player-status.cpp
- src/system/player-type-definition.h
- src/wizard/wizard-special-process.cpp
特別に武器スキルの最大値を変化させる時、スキル情報テーブル s_info の保持している最大
値を変化させているが、これが原因でマーフォークから別の種族に変化した時に三叉槍やトライ
デントのスキル最大値がゲームを再起動するまで達人のままになるという現象が発生している。
そもそもの設計として read-only であるべきテーブルの値をいじっているのがよくないので
最大値の定義を必要に応じて PlayerType クラスのメンバにコピーし、最大値の変更や参照は
そちらを使うようにする。
> [Fix] PlayerType クラスのメンバに武器スキルの最大値を持たせる

- src/birth/birth-select-class.cpp
カーソルでランダムが選択されているかを判定する部分で比較する変数が誤っている。
正しいものに修正する。
> [Fix] #1931 職業選択時、ランダムをカーソル＋Enterで選択すると強制終了する

- src/lore/lore-util.cpp
モンスターのオーラフラグを monster_race::aura_flags に分離した際、それに伴い
lore_type::aura_flags も追加したが、これを初期化する処理を追加し忘れているのが原因。
initialize_lore_type() で lore_type::aura_flags も他と同様に初期化するように
する。
> [Fix] #1938 モンスターの思い出にオーラの情報が表示されない

- src/object/object-stack.cpp
鍛冶のリファクタリングを行った時に鍛冶効果の付与をメンバ変数 xtra3 から分離したため
同一のアイテムかどうかの判定が正しく行われなくなっていた。
判定に Smith::object_effect および Smith::object_activation の比較を追加して
異なる鍛冶効果のアイテムが重ならないようにする。
> [Fix] #1924 異なる鍛冶効果を付与したアイテムが重なってしまう

- src/mspell/mspell-summon.cpp
モンスターの召喚魔法は種類によってプレイヤーの連続行動を阻害する条件が異なっていた。
これを統一して「プレイヤーが召喚魔法を受けた場合」「感知範囲内に召喚者または被召喚者がいる場合」のみ連続行動を阻害するように変更する。
> [Feature] モンスターの召喚魔法によるプレイヤー連続行動阻害の条件を統一

- src/mspell/mspell-special.cpp
- src/mspell/mspell-status.cpp
距離無制限で連続行動を阻害していたものについて修正を入れ、プレイヤー周辺の事象のみを阻害の対象にする。
「時を止める」をどうするか判断に迷うところだが、能力の危険性も加味して暫定的に距離無限で気づけるものとしている。
> [Feature] モンスターの特殊な行動、回復について連続行動阻害の要件を整理

- src/monster-attack/monster-attack-processor.cpp
Issue #1941の件。
モンスターがモンスターを殴る条件を精査した結果、KILL_BODYフラグ持ちが弱いモンスターを殴るときに限り地形の侵入不可を考慮していることが分かった。
プレイヤーへの攻撃、敵対的モンスターへの攻撃、混乱時の攻撃では地形を考慮していない。
また、プレイヤーからモンスターの攻撃でも攻撃先の地形は考慮されない。
整合性を取るため、この条件から地形進入不可を排除する。
この条件が難読であるためコード整理も行った。
> [Fix] モンスターがモンスターを殴る際の地形条件の統一

- lib/edit/r_info.txt
* カコデーモンのトゲ（角）の本数を間違っていたのと"spike"(トゲ)ではなく"horn"(角)だったため日英双方そちらに合わせて修正しました。また、とても丸っこいは"very round"よりも"spherical"の方が直接的なのでそっちに修正いたしました
* アラクノトロンは脳みそのようなやつが本体なのでそう捉えられるように訂正しました
> カコデーモンとアラクノトロンの説明文を修正

- src/knowledge/knowledge-monsters.cpp
PR #1933 でのエンバグ。
display_group_list() において、渡された grp_idx[] 配列の終了条件として負数を想定
しているが、上記のPRで配列の最後に -1 を入れる処理が削除されてしまっている。
元のコードとの互換動作となるよう、配列の最後に -1 を挿入するようにする。
> [Fix] #1993 「既知のモンスター」を開いた際に落ちる

- lib/edit/q0000005.txt
- lib/edit/q0000006.txt
- lib/edit/q0000007.txt
Issue #2006 の件。3.0alpha以降の調整で機能不全となっている旧来のクエストを修正する。
クエスト「塔」のランダム配置モンスターを撤去し、固定モンスターを配置する。
また、若干のアイテムを配置して追加の報酬とする。
3.0alpha以降のモンスターの追加・再配置によりランダム配置で実装当初よりも強力なモンスターが出現するようになったことへの対応。
また、全体的にアイテム生成が良くなったことでクエスト報酬の耐毒の指輪の価値が相対的に下がっている。アイテム生成を増やすことでクエストを受注する価値を高める。
> [Feature] クエスト「塔」のバランス調整

- lib/edit/q0000004.txt
Issue #2007 の件。3.0alpha以降のバランス調整を受けて既存クエストを修正する。
序盤のアイテム生成が良くなった結果、クエスト『宝物庫』の報酬が相対的に不十分になり受注機会が減った。
早期にクエストを受注できるようにするため、クエスト難易度の調整を行う。
敵の密度を大幅に下げ、脅威をドラゴンとミスリルゴーレムに絞った。
ランダムモンスターとミミックからの召喚をなくすことで不確定要素を排除した。
番兵としてキノコを設置。叫ばせた場合は加速ミスリルゴーレムに追われることになる。一部屋だけ意地悪な配置にしてあるが、叫ばせずに投擲で対処可能な位置にしている。
> [Feature] クエスト『宝物庫』のバランス調整

- src/birth/game-play-initializer.cpp
- src/io/uid-checker.cpp
- src/system/h-config.h
In my hands, these changes resolve the issues I saw with escalating and dropping privileges on Debian (mentioned in #1974 ).  I don't know if they'll resolve the issues when running in Cygwin.
> Resolve _POSIX_SAVED_IDS issues on Debian

- src/info-reader/general-parser.cpp
掲題の通りです
assign済のvectorに対しては代入だけしていれば良かったのですが間違ってpush\_backしていました
アーチャーでの修正を確認済です
ご確認下さい
> 種族や職業に依存する割引が動作していない事象を修正した

- configure.ac
現在英語バージョンのスコアサーバは運営していないので、"--disable-japanese" をつけて
./configure を実行したときは "--disable-worldscore" がついていなくてもスコア送信
機能を無効にする。
> [Fix] 英語バージョンでスコア送信機能を無効にする

- src/core/scores.cpp
- src/core/show-file.cpp
- src/io/report.cpp
- src/load/info-loader.cpp
- src/load/load.cpp
- src/main-win/main-win-utils.cpp
- src/main.cpp
- src/main/angband-initializer.cpp
- src/save/save.cpp
- src/system/angband-version.cpp
- src/system/angband-version.h
#1743 の実装案ですが、これを実行するとセーブデータが破損します
具体的には以下の流れを踏みます：
1. セーブデータの書き込みは正常に完了するように見える (save.cpp)
2. セーブデータの読み込みに関して、バリアント部は正常に読み込めている (load.cpp)
3. しかし、rd\_version\_info() でw\_ptr->sf\_systemを読み込む辺りでXORのローテーションが壊れている (sf\_savesはセーブした回数なので、デバッグ用のセーブデータだと精々数回のはずだが、1000を超えた値で読み込まれる)
4. その手前、load\_xor\_byte = w\_ptr->sf\_extra; は、developブランチだと右辺と左辺が同値なので行が存在している意味がないのだが、このfeatureブランチだと異なる値になっている
どこがおかしそうか、お手数ですが確認頂けると助かります
> バリアント名をセーブデータに含めた

- src/main-gcu.cpp
- src/main.cpp
- src/term/z-term.cpp
Implement bigscreen for curses and use it as the default behaviour. The old behaviour is still avilable using -o as a subopt for -mgcu. Also implements a new syntax for user-controlled subwindow layouts (from poschengband), documented within code comments.
> GCU版の機能拡張: bigscreen / color / layout customize / cursor flicker fix

- src/load/angband-version-comparer.cpp
- src/system/angband-version.h
現状だとバリアントを切ってバージョンの数字を書き換えるとセーブファイルを読み込む際にバグるが、そのためにバリアントを切る度この関数による条件分岐全てを消すのは面倒なので、姑息な対処だがとりあえずバリアント名を書き換えたらh_older_thanは常にfalseを返すようにした
バージョンによる互換性の確保を全て別ファイルに分けるなどして処理自体を消しやすくした方がいいため、それについては別途Issueを作成する
> 変愚蛮怒以外ではh_older_thanによる互換性確保は作動しないように

- src/load/old/item-loader-savefile50.cpp
- src/load/old/load-v1-5-0.cpp
- src/object/object-stack.cpp
- src/save/item-writer.cpp
- src/store/store-util.cpp
- src/system/object-type-definition.h
- src/wizard/wizard-item-modifier.cpp
掲題の通りです
もう使われていないフィールドにつき、ほとんど読み捨てる形で\*抹殺\*しました
ご確認下さい
なおxtra1で全文grepするとまだ何箇所か引っかかりますが、これは昔耐性を被ダメ時と画面表示時で別々に計算していた頃の名残っぽいです
本件とは無関係なので暫定で残してあります
> object_type::xtra1を消した

- src/spell-realm/spells-chaos.cpp
> [Fix] vanish_dungeon()が通常のダンジョンで効かなくなっていた不具合を修正。

- lib/pref/pref-key.prf
Resolve #1509
誰も必要としていないであろう Ctrl+C と Ctrl+K による自殺コマンド('Q')へのキーマップ
アサインを削除する。
> fix: 不要な自殺コマンドへのキーマップアサインを削除

- src/core/player-processor.cpp
- src/core/speed-table.cpp
- src/core/speed-table.h
- src/lore/lore-util.h
- src/monster/monster-damage.cpp
- src/monster/monster-list.cpp
- src/monster/monster-list.h
- src/monster/monster-processor-util.cpp
- src/monster/monster-processor-util.h
- src/monster/monster-processor.cpp
- src/monster/monster-status.cpp
- src/player-status/player-speed.cpp
- src/player/digestion-processor.cpp
- src/spell-kind/spells-sight.cpp
- src/system/h-type.h
- src/system/monster-race-definition.h
- src/system/monster-type-definition.h
掲題の通りです
速度定義がbyteなのでそれに統一しています
一部、PlayerSpeedがint16\_tを返していますがインターフェースを噛ましていて他との兼ね合いがありそうだったのでそこは手つかずとしました
ご確認下さい
> SPEED の型エイリアスを廃止した

- .github/scripts/check-bom.sh
- .github/workflows/buildtest-on-linux.yml
新しく追加したソースファイルへの BOM 付け忘れや修正したソースファイルからの BOM 消失
防止のため、GitHub Actions のビルドテストでビルド実行前にすべてのソースフィアルに
BOM が付いているかどうかのチェックを行うようにする。
> [Feature] ビルドテストの Workflow に BOM チェックを追加

- src/wizard/wizard-spells.cpp
デバッグコマンドの wiz_kill_target() を実行した時に EffectID の入力で番号を調べる
のが面倒なので属性一覧とその番号を表示する。
表示する属性の名称は gf_desc で定義されている名称から "GF_" の部分を取り除いたもので、
表示スペースの問題から先頭10文字までを表示する。
> [Feature] wiz_kill_target() で指定できる属性一覧を表示する

- src/effect/effect-characteristics.h
- src/effect/effect-processor.cpp
- src/mspell/mspell-checker.cpp
Resolve #2252 
PROJECT_BREATHの定数が16ビットを超えているが、実際にこの定義を使用している変数はどれも32ビットであり、16ビットのものは見つからなかったため問題ないと判断し、追加した
> ブレスのルールを変更した

- src/load/lore-loader.cpp
> 思い出フラグがモンスター情報の変更に対応できてないバグを修正

- src/action/activation-execution.cpp
- src/artifact/artifact-info.cpp
- src/autopick/autopick-entry.cpp
- src/flavor/flavor-util.cpp
- src/flavor/named-item-describer.cpp
- src/floor/floor-events.cpp
- src/info-reader/ego-reader.cpp
- src/load/old/load-v1-5-0.cpp
- src/main/info-initializer.cpp
- src/object-enchant/object-ego.cpp
- src/object-enchant/object-ego.h
- src/object-enchant/weapon/apply-magic-weapon.cpp
- src/object/object-flags.cpp
- src/object/object-value-calc.cpp
- src/object/object-value.cpp
- src/racial/racial-android.cpp
- src/wizard/wizard-item-modifier.cpp
Resolve #2250 
本質は parse_e_info をちょこっと修正しただけなので、他の *_info を map にする必要がでてきた場合も参考にできるかと思います。
> [Refactor] エゴアイテムの情報を格納する e_info を std::map にする

- src/cmd-io/cmd-menu-content-table.cpp
- src/cmd-io/cmd-menu-content-table.h
- src/io/input-key-requester.cpp
- src/io/input-key-requester.h
special\_menu\_contentという構造体がありました
optionalが無かったことを差し引いても「プレイヤーのクラス (enum)」と「荒野にいるかフィールドにいるか (bool)」を同一の変数で扱うというxtra4もびっくりのマルキ設計があったので修正しました
変数名もローマ字で本物のゴミだったのでそれも修正しました
ご確認下さい
> クラスまたは荒野に依存する判定の設計を修正した

- src/effect/effect-monster-resist-hurt.cpp
Fixed #2172 
#2173 から分離
例えば減速が効いて朦朧が効いてないと「効果がなかった」ってなったり、逆でも「効果がなかった」となる
これは最終的にobviousをリターンする関数である```affect_monster()```の
```
* @return 何か一つでも効力があればTRUEを返す / TRUE if any "effects" of the projection were observed, else FALSE
```
という仕様に反するため修正した
> 重力属性のobviousの挙動を修正

- .github/workflows/buildtest-on-linux.yml
GitHub Actions でキャッシュストレージを使用できるらしいので、ccache でビルドテスト
を高速化する。
リポジトリごとに 10GB まで使用できるらしいが、とりあえず ccache のキャッシュサイズ
設定を 8.0GB として様子を見る。
> [Feature] ビルドテストに ccache を使用する

- .github/workflows/create-cache-for-ccache.yml
Pull Request Status Check で行われるビルドテスト時に ccache によるコンパイル
キャッシュが初めから利用できるようにしやすくするため、develop ブランチにマージされた
時にビルドテストと同じビルドを実行してキャッシュを予め生成しておくようにする。
> [Feature] ccache のためにキャッシュを生成するワークフロー

- src/system/angband-exceptions.h
Resolve #2314 
継承元の例外クラス (std::runtime_error等) のコンストラクタをすべて使えるようにする
ため、自作のコンストラクタではなく継承コンストラクタを使用する。
> [Refactor] 独自定義例外に継承コンストラクタを使用する

- src/combat/slaying.cpp
Resolve #2323 
ゲームバランス面で致命的なので優先度は緊急にしておきます
参考(置き換える前のコード):
```cpp
if (flgs.has_not(p->slay_flag) || !(atoffset(BIT_FLAGS, r_ptr, p->flag_offset) & p->affect_race_flag))
continue;
```
> スレイの対象が逆転してしまっているバグを修正した

- src/player-status/player-speed.cpp
改めてメソッド名、変数名、ブランチ名をbonusに変えてみました
ご確認下さい
> 速度補正が正しく機能していない不具合を解消した

- src/object-enchant/others/apply-magic-others.cpp
掲題の通りです
ご確認下さい
(ポインタではなく)参照の上書きをしたのでおかしなことになったようです
> 自分のキャラ表示が @ ではなく別の文字に変わってしまう事象を解決した

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/knowledge/knowledge-monsters.cpp
- src/load/load-zangband.cpp
- src/load/player-info-loader.cpp
- src/market/bounty-type-definition.h
- src/market/bounty.cpp
- src/market/bounty.h
- src/monster/monster-damage.cpp
- src/object-hook/hook-quest.cpp
- src/save/player-writer.cpp
- src/system/angband-version.h
- src/window/display-sub-windows.cpp
- src/world/world.h
Resolve #2338 
賞金首周りの奇っ怪なコードをリファクタリングしました。
内容についてはコミットログをご参照ください。
⚠️ セーブデータバージョンが15→16に上がります。
> [Refactor] 賞金首情報の処理コードのリファクタリング

- src/melee/monster-attack-monster.cpp
Resolves #2348 
HP回復効果が有効かどうかのチェックで monster_living() 関数を呼んでいるが、この時本
来は「攻撃目標のモンスターの種族ID」を渡すべきところ、誤って「攻撃主のモンスターの現マ
ップに存在するモンスターリスト上の要素番号」を渡しておりダブルで間違っている。
正しいものを渡すように修正する。
> [Fix] モンスター間の生命力吸収攻撃の挙動がおかしい

- src/effect/effect-processor.cpp
- src/spell-kind/spells-launcher.cpp
Resolve #2345 
一つ一つの変更は小さいが、かなり大幅にスコープを狭めているものもあるため注意してご確認いただきたい
ちなみにビット計算の件だが、pythonスクリプトで置き換えれば可能であるため使っても問題ないと判断し、今回からnone_bits()などに置き換える
> project() 内の一部変数のスコープを処理内容に合わせた + ブレスのエンバグ修正

- src/effect/effect-player-resist-hurt.cpp
Resolves #2368 
暗黒属性の攻撃を受けた時に、盲目効果を防げるかの判定で暗黒耐性のみを見ており暗黒免疫は
見ていないため、暗黒耐性がなく免疫のみを所持している時は盲目になってしまう。
暗黒免疫を持っているかどうかも判定に加えるようにする。
> [Fix] 暗黒免疫があるにも関わらず暗黒属性の攻撃で盲目になる

- src/effect/effect-player-resist-hurt.cpp
「気分がよくなった」と「気分が良くなった」が両方表示されてたので後者に合わせた
> 地獄免疫の回復メッセージがひらがなと漢字で２度表示されるバグを修正

- src/main-win/main-win-music.cpp
- src/monster-race/monster-race.h
monster_key_at() がintとenum classの比較をしていたため
なお当該関数はコールバックとして使われており引数の型を変えられなかったので、MonsterRaceIdを返り値とする関数の方にenum2i() を噛ませた。本質的にはもう型がintとenum classで異なるのでコールバックせず素直に関数を分離した方が良さそうである
以上、ご確認下さい
> MSVCにおけるコンパイルエラー/警告を解消した

- src/monster/monster-update.cpp
- src/mspell/high-resistance-checker.cpp
Resolves #2371
そもそも既存のコードで暗黒免疫が学習対象になっていない。全く学習しないのはおかしいので、
とりあえず暗黒耐性と同様の学習を行うようにする。
また、免疫持ちの場合100%暗黒ブレス・ボールの使用がキャンセルされるが、この時種族の特性
フラグしか対象としていない。現状装備では暗黒免疫が付与される事はないが、幽体化による一
時的な暗黒免疫が存在するので、has_immune_dark() に置き換えて全ての暗黒免疫を対象に
する。
> [Fix] モンスターが暗黒免疫を学習しない

- src/gcc-wrap
gcc-wrap に渡されたソースファイルに対応するオブジェクトファイルのパス文字列を作る時に、
ソースファイルの拡張子が .cpp である事を前提としているため、MacOS への移植 Fork に
あるソースファイルの拡張子 .mm (Objective C++ 用の拡張子らしい) が渡された場合にオ
ブジェクトファイルのパス文字列が正しく生成されず MacOS でビルドエラーとなっている。
sed により拡張子を決め打ちせずに .o に置換することで MacOS でも正常にビルドできるよ
うにする。
> [Fix] gcc-wrap を .cpp 以外の拡張子にも対応する

- src/birth/game-play-initializer.cpp
- src/knowledge/knowledge-monsters.cpp
- src/load/world-loader.cpp
- src/market/bounty.cpp
- src/market/bounty.h
- src/monster-race/monster-race.cpp
- src/monster-race/monster-race.h
- src/monster/monster-damage.cpp
- src/object-hook/hook-quest.cpp
- src/save/player-writer.cpp
- src/system/player-type-definition.h
- src/window/display-sub-windows.cpp
is_bounty() を MonsterRace のメンバにする。
また、 PlayerType::today_mon は日替わり賞金首を確認済みかだけの情報があればよい
（実際のモンスター種族IDは world_type::today_mon を見ればわかる）ので、bool 型に
変更し、メンバ名を knows_daily_bounty に変更する。
同じ MonsterRace クラスを変更する関係上、 #2377 のブランチから分岐しているため #2377 の差分も含まれます。後でリベースしますが、このPR単体の修正範囲を確認するには、 9f4a6e8b976d23f5b9b3539bd5ad40746541e4df を見てもらえば良いです。
> [Refactor] 賞金首関連のコードの整理

- src/cmd-visual/cmd-visuals.cpp
- src/knowledge/knowledge-monsters.cpp
グループに含まれるモンスター種族IDのリストの終了に番兵を使うのをやめ、std::vectorの
サイズ情報を使用するようにする。
また、関連してモンスターの文字/色の変更でIDの切り替えが正常にできていない問題があった
ので合わせて修正する。
MonsterRaceId::PLAYER の使用と MonsterRaceId と整数間の必要以上のキャストを削減するリファクタリングの一環です。
> [Refactor] do_cmd_knowledge_monsters() のコード整理

- src/cmd-action/cmd-hissatsu.cpp
- src/cmd-action/cmd-mane.cpp
- src/cmd-action/cmd-pet.cpp
- src/cmd-action/cmd-spell.cpp
- src/cmd-item/cmd-magiceat.cpp
- src/mind/mind-elementalist.cpp
- src/mind/mind-power-getter.cpp
- src/mind/mind-power-getter.h
- src/mind/mind-sniper.cpp
- src/mind/mind-weaponsmith.cpp
掲題の通りです
これらのUI操作は似たりよったりのコピペなので、ひとまず剣術家で動いてヨシ！ したのでPRとして提出します
ご確認下さい
なお、元々以下のようなメッセージが出ていました
冷静に考えるとa～hの範囲しか取り得ないので数値が正常値扱いされるのは違和感があります
> (必殺剣 a-5, '*'で一覧, ESC) どの必殺剣を使いますか？
メニューを使ってカーソルを選んでも、取りうる値の範囲が2、4、6、8及びそれらのローグキー配置なのと、カーソル移動のためのキー入力を敢えて正常値としてユーザに示すのは変なので、全体として整合性が取れていません
本件は別途対応します
> 小文字しか入力範囲のないコマンドで大文字を入力した際の確認機能を削除した

- src/action/movement-execution.cpp
- src/birth/game-play-initializer.cpp
- src/floor/floor-leaver.cpp
- src/market/arena-info-table.cpp
- src/monster-floor/monster-generator.cpp
- src/monster-floor/monster-summon.cpp
- src/monster-floor/one-monster-placer.cpp
- src/monster-floor/special-death-switcher.cpp
- src/monster-race/monster-race-hook.cpp
- src/monster-race/monster-race.cpp
- src/monster-race/monster-race.h
- src/monster-race/race-indice-types.h
- src/monster/monster-damage.cpp
- src/monster/monster-damage.h
- src/monster/monster-list.cpp
- src/monster/monster-processor.cpp
- src/object-enchant/others/apply-magic-others.cpp
- src/room/rooms-pit-nest.cpp
MonsterRaceId への不要なキャストを減らせるようにリファクタリングする。
ObjectType::pval を MonsterRaceId にキャストするコードは数が多いので別途対応する。
MonsterRaceId::PLAYER という値はほとんどの場合、どのモンスターでもないという意味で
使用されているので、その場合 MonsterRaceId::empty_id() の戻り値を使用する。
（念の為、実際の値は MonsterRaceId::PLAYER のままとしてある。）
真にプレイヤーを意味する場合のみに MonsterRaceId::PLAYER を使用する。
関連して MSVC の警告をなくすためのリファクタリングも含まれます。
> [Refactor] 必要以上のMonsterRaceIdのキャストとMonsterRaceId::PLAYERの使用を避ける

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/effect/effect-feature.cpp
- src/effect/effect-processor.cpp
- src/floor/floor-leaver.cpp
- src/grid/grid.cpp
- src/grid/grid.h
- src/mind/mind-mirror-master.cpp
- src/mind/mind-mirror-master.h
- src/racial/racial-switcher.cpp
- src/spell-class/spells-mirror-master.cpp
- src/spell-class/spells-mirror-master.h
掲題の通りです
以下の4つは移していません
* シーカーレイ：project() に繰り込まれていて分離困難 (飛竜さん作業予定)
* スーパーレイ：同上
* 封魔結界：長過ぎるので保留
* 幻惑の光：混沌の戦士も使えるので現時点では混ぜたくない
現時点では、シーカーレイ/スーパーレイ の処理を移植させる準備としてクラスを作るのが目的なので特に大きな変更はありません
ご確認下さい
> SpellsMirrorMaster クラスを作成して鏡魔法の効果処理を大部分移した

- src/autopick/autopick-inserter-killer.cpp
- src/cmd-io/cmd-macro.cpp
- src/io/input-key-acceptor.cpp
- src/io/interpret-pref-file.cpp
- src/util/string-processor.cpp
- src/util/string-processor.h
【バグ】 マクロを保存しようとするとゲームが落ちる https://github.com/hengband/hengband/issues/2337 の原因。
ascii_to_text()がバッファサイズを越える書き込みを禁止していないため範囲外アクセスが発生している。
バッファ長を引数に取り、範囲外アクセスを禁止する。
また、対になるtext_to_ascii()も同様に修正する。
> [Fix] ascii_to_textのバッファオーバーランを修正

- Hengband/Hengband/Hengband.vcxproj
- Hengband/Hengband/Hengband.vcxproj.filters
- src/Makefile.am
- src/object-enchant/apply-magic.cpp
- src/object-enchant/protector/apply-magic-armor.cpp
- src/object-enchant/protector/apply-magic-armor.h
- src/object-enchant/protector/apply-magic-boots.h
- src/object-enchant/protector/apply-magic-cloak.h
- src/object-enchant/protector/apply-magic-crown.h
- src/object-enchant/protector/apply-magic-dragon-armor.cpp
- src/object-enchant/protector/apply-magic-dragon-armor.h
- src/object-enchant/protector/apply-magic-gloves.h
- src/object-enchant/protector/apply-magic-hard-armor.cpp
- src/object-enchant/protector/apply-magic-hard-armor.h
- src/object-enchant/protector/apply-magic-helm.h
- src/object-enchant/protector/apply-magic-shield.h
- src/object-enchant/protector/apply-magic-soft-armor.cpp
- src/object-enchant/protector/apply-magic-soft-armor.h
#2404 の後続作業です
ドラゴン・スケイルメイルは行数的にかなり寂しいですが、分岐はファクトリに閉じ込めた方が分かりやすくなるのでこのままとします
ご確認下さい
> ArmorEnchanter を鎧種別ごとに分離した
